### ISSUE TITLE
support for exact match searching

### ISSUE THREAD

**Issue by javamonkey79** [amundsen-io/amundsen#100]
- given, there is a full text string in a table description, and part of the  full text strong in another table description
- when queried from elastic search for the full text string
- then other entries are returned from elastic search
example:

![image](https://user-images.githubusercontent.com/1403289/65083825-72f01280-d95e-11e9-90aa-8a37b15e19b3.png)

I would expect, that an exact string search would be the only result returned.

**Comment by feng-tao** [comment]
it does support with the advanced search view.
