### ISSUE TITLE
bug: neo4j 4.x support in databuilder

### ISSUE THREAD

**Issue by dorianj** [amundsen-io/amundsen#1008]
neo4j 4.x isn't supported in databuilder.

Prior work has been done on this in https://github.com/amundsen-io/amundsendatabuilder/pull/447.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by akiratwang** [comment]
+1 to this issue. The Neo4j version 3.2.56 results in some issues with packages such as APOC.

**Comment by dwwhitlock** [comment]
I will likely take a stab at this. As Neo4j driver 3.5 is nearing end of life support our firm is concerned about onboarding an already deprecated neo4j instance

**Comment by allisonsuarez** [comment]
I am working on moving us to neo4j-driver 4.4.5 since the support for 1.7 is now very limited, will put a PR up for this soon @dorianj

**Comment by allisonsuarez** [comment]
#1938
