### ISSUE TITLE
How to display column stats in front end page

### ISSUE THREAD

**Issue by leandro-rouberte** [amundsen-io/amundsen#1050]
Hi everyone. 
I would like to know how can I display the column stats info in my Amundsen frontend page:
![image](https://user-images.githubusercontent.com/37634317/117232119-ed50fd00-adf6-11eb-81ac-a32f03830899.png)

I'm currently using amundsen-databuilder==4.2.2 and using the hive dag extractor example:
https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/dags/hive_sample_dag.py

My amundsen images are:
- amundsendev/amundsen-metadata:3.5.0
- amundsendev/amundsen-frontend:3.7.0
- amundsendev/amundsen-search:2.5.1

The table in question has stats:
```scala
scala> spark.sql("describe extended test2000 id").show(false)
+--------------+----------+
|info_name     |info_value|
+--------------+----------+
|col_name      |id        |
|data_type     |bigint    |
|comment       |NULL      |
|min           |0         |
|max           |999       |
|num_nulls     |0         |
|distinct_count|1000      |
|avg_col_len   |8         |
|max_col_len   |8         |
|histogram     |NULL      |
+--------------+----------+
```

But looking in Amundsen there's no stats information for column id:
![image](https://user-images.githubusercontent.com/37634317/117233287-399d3c80-adf9-11eb-8d6e-16b56af41cc5.png)

Can you help me figure out what I'm doing wrong here, please. Thanks.

**Comment by dorianj** [comment]
you're computng and sending the stats in databuilder?

you'll need to add this to your frontend config, under `[ResourceType.table]:`
```
      stats: {
        uniqueValueTypeName: "unique_values",
      }
```

**Comment by leandro-rouberte** [comment]
Thanks for the reply, @dorianj . The Hive example fo metadata export does not seems to reference column stats in the export query. Do we have any documentation showing how this frontend property maps to data in neo4j and even export queries. For example, if I add to my export query a column with the name "unique_values", it will be assigned to this field?

Thanks.

**Comment by mgorsk1** [comment]
I don't think hive extractor touches spark and column stats at all. It uses direct connection to hive metastore db. Amundsen documentation only suggests using hive stats but there is no extractor for them. 

You could use https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/pandas_profiling_column_stats_extractor.py to get column stats to neo4j. It's the only official extractor for column stats afaik.
