### ISSUE TITLE
Bug Report: Manually added tag is not searchable

### ISSUE THREAD

**Issue by jsnowacki** [amundsen-io/amundsen#1069]
## Expected Behavior
If I have `table1` in Amundsen and add `tag1` to it, the search result by `tag1` returns `table1`.

## Current Behavior
The manual tag addition of `tag1` saves the data in metadata service correctly (tag is visible in table details), but the search result by `tag1` doesn't return `table1`; to do that we need to manually trigger external metadata service backend copy to search service (likely ES directly), e.g. via databuilder.  

## Possible Solution
Trigger search service update via metadata service; possibly frontend can trigger update in both metadata and search services (PUT `/document_table`?).

## Steps to Reproduce
In frontend:
1. Open `table1` (or other datasource) details.
2. Add unique tag name, e.g. `tag1`.
3. Use advanced search to search for your unique tag, eg. `tag1`
4. See the results; `table1` or your other table should be there.

## Screenshots (if appropriate)
NA.

## Context
After tag is added manually it is visible to the user in table details metadata, but it is not searchable until the metadata service backend will be indexed again using databuilder. There is also no good solution apart from periodically updating index in ES using databuilder.

## Your Environment
* Amunsen version used: `amundsendev/amundsen-search:2.4.0`, `amundsendev/amundsen-metadata:3.5.0`, `amundsendev/amundsen-frontend:2.3.0`.
* Data warehouse stores: AWS Neptune and Elasticsearch Helm 1.32.0  from https://charts.helm.sh/stable/ (as in documentation)
* Deployment (k8s or native): k8s (cdk8s based on official Helm)
* Link to your fork or repository: NA

**Comment by NiravLangaliya** [comment]
similar changes added here, Could you please check it? https://github.com/amundsen-io/amundsenfrontendlibrary/pull/883
