### ISSUE TITLE
Installation issue - Python 3.7 error

### ISSUE THREAD

**Issue by anonymesh** [amundsen-io/amundsen#1075]
I was trying to install Amundsen with the docker-compose command. 
However, While every container was up and running, I saw the 0.0.0.0/5000 frontend where nothing loads. And in the logs, it says some connectionPool error. I have attached screenshot with the same.

## Here is the screenshot attached
https://imgur.com/a/nJHYB4J

**Comment by dorianj** [comment]
Hey, are you attempting to use Atlas intentionally? It looks like you've configured it that way, but Atlas isn't running..
