### ISSUE TITLE
Need help to set up column and table lineage in UI

### ISSUE THREAD

**Issue by srikanthanbalagan** [amundsen-io/amundsen#1077]
Hi,

I noticed some changes were made to Amundsen front regarding table and column lineage.

https://github.com/amundsen-io/amundsenfrontendlibrary/commit/df9532a89fa09f6cfe1059f4d6a300c54f277020

I have pushed the column lineage data to neo4j and metadata service and frontend api is working well and I can see the data in network calls.

But I cannot see any difference in UI. I mean when I expand the column a network call is made to fetch the column lineage data but no changes in UI.

Do we need to add some config to enable lineage in UI?

**Comment by verdan** [comment]
@srikanthanbalagan I responded to a similar question here: https://github.com/amundsen-io/amundsen/issues/1099#issuecomment-841730817

a few things to check: 
- make sure to build the frontend after changing the config on the frontend. 
- try to clear the browser cache, as sometimes it does not refresh the JS files immediately.
