### ISSUE TITLE
bug: auto-release is broken

### ISSUE THREAD

**Issue by dorianj** [amundsen-io/amundsen#1078]
This is a tracking issue for the issue of auto-releases not working since we moved to the mono-repo. 

At core the challenging thing here is that python-semantic-release operates entirely on commit messages. Thus it has no way of knowing which commits correspond to which submodules. This could be resolved in a number of ways:
    - Adding another GH action to modify the PR description to include which modules it modifies, then providing semantic-release a custom Python reader which would then extract that info
    - Requiring pull-requestors to annotate which modules their PR affects, which seems error-prone and undesirable
    - Not doing auto-releases (not a good option)
    - [Wait on the upstream library to do something](https://github.com/relekang/python-semantic-release/issues/168) (not a good option)
- Publish Release: The problem here is a bit more banal: we just don't have a super easy way to get this to execute only for the modified files (if the on filter in the action includes all )

A corollary problem is that the old auto-release mechanism wasn't correctly segmenting README files: e.g. if you look at https://github.com/amundsen-io/amundsendatabuilder/releases/tag/4.3.1, it contains items for all of the releases that have ever happened (since we implemented auto-release), not just new changes for that particular release. You can see this reflected in https://github.com/amundsen-io/amundsendatabuilder/blob/master/CHANGELOG.md, which doesn't have subsections for particular releases.

**Comment by dorianj** [comment]
first step: https://github.com/amundsen-io/amundsen/pull/1079 -- this will at least allow us to release manually, and will be the final step of the automated process

**Comment by Golodhros** [comment]
Build and publish docker image still not working
