### ISSUE TITLE
build: common should be installed from-source for CI tests

### ISSUE THREAD

**Issue by dorianj** [amundsen-io/amundsen#1086]
Now that we have a mono-repo, it is ideal to put all changes to a logical concept in one PR. However, because `common` and `databuilder` are installed as packages, they need to be updated separately (and published to pypi) before the other tests will work.

To fix this, we should install `common` from the source tree when testing in CI, rather than going out to pypi.

cc @allisonsuarez and @verdan

**Comment by verdan** [comment]
this is also an issue for the feature itself too, as the PR will be pending until the common is published. 
I'd want to propose to use the 'common` source in requirements.txt files in each package. so common is always pulled in from the current source within repo for all packages.

**Comment by dorianj** [comment]
> this is also an issue for the feature itself too, as the PR will be pending until the common is published.

This is a real issue, that we've been bitten by recently... I don't think it's new to the monorepo, do you know of any good solutions here?

> I'd want to propose to use the 'common` source in requirements.txt files in each package. so common is always pulled in from the current source within repo for all packages.

This seems reasonable. 2 questions:
* how exactly will that approach work when the package is published to pypi?
* when people install locally, will it be installed with `--dev` meaning they can edit common? (is it possible to get that behavior automatically?)



---

unrelated, one change to fix this was landed in https://github.com/amundsen-io/amundsen/commit/dc9a1f9aa0df7637319c0f9bcad5ab670ab12d5c#diff-efd92be0f0364c0686ff36259d9bdb3c6e63fda680e9d6f5606305b567332355

**Comment by mgorsk1** [comment]
I think we should not solve this on requirements level but ci level. After migrating to monorepo in ING we just uninstall common (version from requirements) and install directly from common folder. Anything else might hurt pypi installations.
