### ISSUE TITLE
PrestoViewMetadataExtractor Backquoted error

### ISSUE THREAD

**Issue by telmofranciscmultivision** [amundsen-io/amundsen#1090]
Hi,

I was trying to use PrestoViewMetadataExtractor and I'm having this issue:

(type=USER_ERROR, name=SYNTAX_ERROR, message="line 2:32: backquoted identifiers are not supported; use double quotes to quote identifiers", query_id=20210513_103645_00086_itrg5

MyJob:

    tmp_folder = '/var/tmp/amundsen/table_metadata'
    node_files_folder = f'{tmp_folder}/nodes/'  
    relationship_files_folder = f'{tmp_folder}/relationships/'
  
    config = ConfigFactory.from_dict({
        f'extractor.presto_view_metadata.extractor.sqlalchemy.{SQLAlchemyExtractor.CONN_STRING}': 'trino://presto_service:@172.22.119.75:8080/catalog/hivemetastore',
        f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.NODE_DIR_PATH}': node_files_folder,
        f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.RELATION_DIR_PATH}': relationship_files_folder,
    })
    job = DefaultJob(conf=config,
                     task=DefaultTask(extractor=PrestoViewMetadataExtractor(), loader=FsNeo4jCSVLoader()),
                     publisher=Neo4jCsvPublisher())

**Comment by tooptoop4** [comment]
@telmofranciscmultivision  how did u solve? i thought conn_string should be mysql port
