### ISSUE TITLE
Delta Lake extractor problems and clarity

### ISSUE THREAD

**Issue by dan-origami** [amundsen-io/amundsen#1096]
I have tried getting Amundsen to properly ingest our Delta Lake schemas and am hitting some issues.

The documentation is not particularly clear on how it fits together, so I will explain our setup and it would be great if someone could chime in. I couldn't find really anything out there about this on the web, so if anyone has a working setup of this it would also be cool to see.

Our Delta Lake is on s3, and I have created the hive metastore tables of our delta tables and they are working correctly inside hive. 
In terms of the delta lake extractor, which it says needs to be linked to the hive containing the delta metadata, which I do as part of the spark submit which will be shown a bit lower. 

What are the cluster_key and database required as part of the delta_lake_config in the extractor example? https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/scripts/sample_deltalake_metadata.py 

```
cluster_key = ''
database = ''
```

These aren't mysql or hive terms so tried a few things relating to the table name in hive and such but not getting anywhere.

Our spark-submit of this extractor script completes and does make a connection to neo4j but no data seems to be scraped or ingested.

This is our spark-submit, containing the hive warehouse with all the metadata of our deltalake tables in

```
spark-submit  --conf spark.hadoop.hive.metastore.warehouse.dir=/tmp/hive/deltalake test-delta.py
```

Our hive is configured in hive-site.xml with

```
<property>
  <name>spark.sql.warehouse.dir</name>
  <value>/tmp/hive/deltalake</value>
</property>
```

Any pointers with delta lake and amundsen would be really great.

**Comment by feng-tao** [comment]
It may need some addition efforts if you run the extractor outside of a Databricks cluster.

**Comment by dan-origami** [comment]
@feng-tao that would make sense, databricks was only mentioned in passing in comments in the code without a hard dependency/reliance though. 
Have you got any idea what we might need to dive into here or is it not feasible?

**Comment by gamberooni** [comment]
@dan-origami are you using hive for `spark.sql.catalogImplementation`? Spark needs to use Hive as a metastore. I personally setup Spark with remote Hive metastore via Thrift protocol. For the `cluster_key`, the value does not matter. I kept it the same as the default value (my_delta_environment) in the sample script. For `database`, assuming you create a table in the database in the example below:
```
spark.sql('CREATE DATABASE testdb')
spark.sql("CREATE TABLE testdb.testtable ( \
    date STRING, \
    eventId STRING, \
    eventType STRING, \
    data STRING) \
USING delta \
LOCATION 's3a://test/testtable'")
```
Then your `database` value will be **testdb**. After doing `spark.sql('CREATE DATABASE testdb')`, you can verify if Hive metastore syncs with Spark by doing `spark.sql('show databases')`. 

Hope this helps.
