### ISSUE TITLE
Feature Proposal: Implement Airflow lineage provider

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#1097]
Airflow supported the provider package feature (https://airflow.apache.org/docs/apache-airflow-providers/). Given now we have lineage API and backend supports, we should support Airflow lineage provider (https://airflow.apache.org/docs/apache-airflow/stable/lineage.html) for Amundsen. Given lineage backend is experimental, it should be a separate repo instead of within mono-repo. 

This ticket is free for grab. For those who interested in contributing to Amundsen, here is a good ticket to get to know Airflow and Amundsen. Please file a RFC for the detail proposal .

**Comment by Arun-kc** [comment]
Can I help? @feng-tao
