### ISSUE TITLE
Popular tables without atlas

### ISSUE THREAD

**Issue by telmofranciscmultivision** [amundsen-io/amundsen#1111]
Hi, 
There is anyway of getting popular tables for amundsen without atlas integration?

Best Regards
Telmo Francisco

**Comment by dorianj** [comment]
Yes, there is! If you're using Mode, it will extract usage info automatically.

There's unfortunately not great support for this out-of-box with most other datastores, but you can look at `databuilder/databuilder/extractor/bigquery_usage_extractor.py` for an example of usage extraction from BQ

**Comment by dorianj** [comment]
Please write back or join #troubleshooting on slack if you need more help
