### ISSUE TITLE
Feature Proposal: Frontend configuration using a file

### ISSUE THREAD

**Issue by jsnowacki** [amundsen-io/amundsen#1121]
Currently to change the default configuration in the React frontend, you need to edit file `frontend/amundsen_application/static/js/config/config-custom.ts`, which requires recompilation of the application, and, thus, if someone wants to have different settings in the frontend, one needs to create their own image file for the deployment.

## Expected Behavior or Use Case
The application should attempt to read configuration JSON file, which path can be given via environment variable, e.g. `FRONTEND_APP_CONFIG_JSON_FILE`, which can default to something like `./config-custom.json`, and just ignore it if the file is missing. Further overlay of the configuration values over defaults can be done similar as for `config-custom.ts`, so only the defined keys and values would be changed. 

## Service or Ingestion ETL
`amundsen-frontend` service; possibly both React and Flask API.

## Possible Implementation
I'm not React expert but I'm not sure if it'd be possible to inject the file to React served as static content by Flask, thus, maybe extra config endpoint in flask serving the config file content would be a solution, and reading it on the application start.

## Context
This would allow to have a general image that can be used in various setup, including Kubernetes, in which the configuration can be given e.g. via volume mount or [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/).

**Comment by dorianj** [comment]
This would be a nice win for us. We have to manage the FE substantially differently due to the need to build the FE with custom files (rather than injecting/overwriting files)

**Comment by mgorsk1** [comment]
Agree, this would be a real productivity booster.

**Comment by Golodhros** [comment]
We currently have JavaScript functions in our configuration objects, so the format couldn't be .json.

We are open to change the way it loads, but the file type should still be javascript.
