### ISSUE TITLE
Feature Proposal: Search service ElasticSearch AWS (and potentially other) authentication support

### ISSUE THREAD

**Issue by jsnowacki** [amundsen-io/amundsen#1135]
Currently ES Proxy in Search service allows for simple user-password pair, non SSL setup. Whereas, in our usage we would like to use [AWS Elasticsearch Service](https://aws.amazon.com/elasticsearch-service/) which requires [specific ES client ](https://elasticsearch-py.readthedocs.io/en/v7.12.1/#running-on-aws-with-iam) initialisation, which currently requires code modification and injection of another `Elasticsearch` client.

## Expected Behavior or Use Case
User can setup in config using env variables:
```bash
PROXY_CLIENT=ELASTICSEARCH_AWS
CREDENTIALS_PROXY_USER=aws_access_key
CREDENTIALS_PROXY_PASSWORD=aws_secret_key
```

## Service or Ingestion ETL
`amundsen-search` service.

## Possible Implementation
The change would be mostly to the initialisation of ES Proxy, eg.
```python
# Current ES Proxy would require ES client, without any other changes to the class business logic
class ElasticsearchProxy(BaseProxy):
    """
    ElasticSearch connection handler
    """

    def __init__(self, *,
                 client: Elasticsearch = None,
                 page_size: int = 10
                 ) -> None:
        """
        Constructs Elasticsearch client for interactions with the cluster.
        Allows caller to pass a fully constructed Elasticsearch client, {elasticsearch_client}.

        :param elasticsearch_client: Elasticsearch client to use, if provided
        :param  page_size: Number of search results to return per request
        """
        self.elasticsearch = client

        self.page_size = page_size
...

# Old implementation would only be for creating simple ES client but most of the logic is still in ElasticsearchProxy; 
# can be setup as before by env variable PROXY_CLIENT=ELASTICSEARCH
class SimpleElasticsearchProxy(ElasticsearchProxy):
    """
    ElasticSearch connection handler
    """

    def __init__(self, *,
                 host: str = None,
                 user: str = '',
                 password: str = '',
                 page_size: int = 10
                 ) -> None:
        """
        Constructs simple Elasticsearch client from the parameters provided.

        :param host: Elasticsearch host we should connect to
        :param user: user name to use for authentication
        :param password: user password to use for authentication
        :param  page_size: Number of search results to return per request
        """
        http_auth = (user, password) if user else None
        client = Elasticsearch(host, http_auth=http_auth)

        super().__init__(client=client, page_size=page_size)

# AWS ES Proxy connector can be setup via env variable PROXY_CLIENT=ELASTICSEARCH_AWS
class AwsElasticsearchProxy(ElasticsearchProxy):
    """
    ElasticSearch connection handler
    """

    def __init__(self, *,
                 host: str = None,
                 user: str = '',
                 password: str = '',
                 page_size: int = 10
                 ) -> None:
        """
        Constructs simple Elasticsearch client from the parameters provided.

        :param host: Elasticsearch host we should connect to
        :param user: AWS access key
        :param password: AWS secret key
        :param  page_size: Number of search results to return per request
        """
        region = os.environ.get('AWS_REGION')
        awsauth = AWS4Auth(user, password, region, 'es')

        client = Elasticsearch(
            hosts=[{'host': host, 'port': 443}],
            http_auth=awsauth,
            use_ssl=True,
            verify_certs=True,
            connection_class=RequestsHttpConnection
        )

        super().__init__(client=client, page_size=page_size)
```

## Context
This would allow to have different implementation of ES and other proxy client, which can be selected via configuration and would not require witting new code and manual docker image building.

**Comment by piotr-kalanski** [comment]
I like this proposition :)

I would consider using environment variables to get AWS credentials (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY).
Additionally, it would be good also to support session token which is generated when using AWS temporary credentials.
Here is example from AWS doc:
```python
service = 'es'
credentials = boto3.Session().get_credentials()
awsauth = AWS4Auth(credentials.access_key, credentials.secret_key, region, service, session_token=credentials.token)
```
source:  https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html#es-request-signing-python

**Comment by mgorsk1** [comment]
Thanks for raising this @jsnowacki Have you tried adding `PROXY_CLIENT_KEY` config option to your Config class? It can receive custom Elasticsearch client which is used instead of `basic_auth` one:

https://github.com/amundsen-io/amundsen/blob/main/search/search_service/proxy/__init__.py#L43 and subsequently:
https://github.com/amundsen-io/amundsen/blob/main/search/search_service/proxy/elasticsearch.py#L69-L89

**Comment by feng-tao** [comment]
@mgorsk1 do you know if the github bot which does pr labelling work for issue as well?

**Comment by mgorsk1** [comment]
afaik no, we could use it to validate the title (instead of using title lint) but auto tagging would require extending its functionality

**Comment by jsnowacki** [comment]
@mgorsk1 thanks a lot for the suggestion. Indeed, it is a sort of solution. The problem is with the AWS credentials as @piotr-kalanski pointed out; i.e. using this approach we would need to pass the credentials as env variables, which is not a good practice indeed. Also, we as many other EKS users use [Service Account approach](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)  to pass the credentials to pods, which require `boto3` to get them, which is not currently in requirements. Also, `requests-aws4auth` is required to setup the client for AWS ES. Hence, it is a bit more cumbersome to setup ES with AWS credentials, than just having custom config. Therefore, I would add the additional `AwsElasticsearchProxy` even just for sake of the above requirements.

Following @piotr-kalanski suggestion the class constructor should look as follows:
```python
...
import boto3
from requests_aws4auth import AWS4Auth
...

class AwsElasticsearchProxy(ElasticsearchProxy):
    """
    ElasticSearch connection handler
    """

    def __init__(self, *,
                 host: str = None,
                 page_size: int = 10
                 ) -> None:
        """
        Constructs simple Elasticsearch client from the parameters provided.

        :param host: Elasticsearch host we should connect to
        :param  page_size: Number of search results to return per request
        """
        region = os.environ.get('AWS_REGION')
        service = 'es'
        credentials = boto3.Session().get_credentials()
        awsauth = AWS4Auth(credentials.access_key, credentials.secret_key, region, service, session_token=credentials.token)

        client = Elasticsearch(
            hosts=[{'host': host, 'port': 443}],
            http_auth=awsauth,
            use_ssl=True,
            verify_certs=True,
            connection_class=RequestsHttpConnection
        )

        super().__init__(client=client, page_size=page_size)
```

**Comment by mgorsk1** [comment]
I see your point. I still think that this can be achieved without modyfing proxy class, simply by:

1. custom config
```
class AwsSearchConfig(Config):
    import boto3
    from requests_aws4auth import AWS4Auth
    
    service = 'es'

    host = os.environ.get('ES_HOST')
    port = os.environ.get('ES_PORT')
    use_ssl = True
    verify_certs = True
    region = os.environ.get('AWS_REGION')
    credentials = boto3.Session().get_credentials()

    aws_auth = AWS4Auth(credentials.access_key, credentials.secret_key, region, service, session_token=credentials.token)

    client = Elasticsearch(
        hosts=[{'host': host, 'port': port}],
        http_auth=aws_auth,
        use_ssl=use_ssl,
        verify_certs=verify_certs,
        connection_class=RequestsHttpConnection
    )

    PROXY_CLIENT_KEY = client
```
2. adding optional aws requirements (extras_require) in setup.py

the change in that form could easily be upstreamed for users convenience

**Comment by mgorsk1** [comment]
btw. out of curiosity (as I am not that familiar with es on aws) - are those credentials valid for some period of time and if so - will AW4Auth refresh `session_token` once it's expired? I am asking cause Proxy object is a singleton so it won't be recreated unless service has been restarted

**Comment by jsnowacki** [comment]
@mgorsk1 thanks for the suggestion.

As for the `session_token` and in general `AWS4Auth` as [STS Temporary Credentials](https://github.com/tedder/requests-aws4auth#sts-temporary-credentials), indeed, looking at the above documentation link, they should be occasionally refreshed as they can expire. In this, case probably again we'd need a special class that recreates `AWS4Auth` and `Elasticsearch` client once the token expires, e.g once the client fails. So while the config class is a good idea, we'd need a custom implementation I think.

**Comment by jsnowacki** [comment]
I've created initial PR #1141 . The tests for new `AwsElasticsearchProxy` pass file, but I need to figure out how to unit test retry correctly and also do some manual integration tests, hence, there may be some additions to it. Also, it is better to discuss the issue with real code IMO.

**Comment by feng-tao** [comment]
yeah, +1 on @mgorsk1 's suggestion, I wonder whether we need another proxy class if we could solve it through config.

**Comment by mgorsk1** [comment]
@jsnowacki i think the section just below the one you have pointed out will fulfill your use case by relying on custom config only:

'''
Dynamic STS Credentials using botocore RefreshableCredentials
>>> from requests_aws4auth import AWS4Auth
>>> from botocore.session import Session
>>> credentials = Session().get_credentials()
>>> auth = AWS4Auth(region='eu-west-1', service='es',
                    refreshable_credentials=credentials)
...
This example shows how to construct an AWS4Auth instance with automatically refreshing credentials, suitable for long-running applications using AWS IAM assume-role. The RefreshableCredentials instance is used to generate valid static credentials per-request, eliminating the need to recreate the AWS4Auth instance when temporary credentials expire.
'''

**Comment by jsnowacki** [comment]
@mgorsk1 Good point! Not sure how I missed that. Nonetheless, I give it a go next week and see if indeed the credentials refresh correctly, before deleting the code. Moreover, I assume that if the config works, the PR should have at least the necessary requirements i.e. `boto3` and  `requests_aws4auth`, right?

**Comment by mgorsk1** [comment]
I think you could upstream the config and aws dependencies as optional ones through `extras_require=dict(aws=['botocore' ,'requests-aws4auth'])` in `setup.py`

**Comment by jsnowacki** [comment]
@mgorsk1 I've tried the config approach and when I set `SEARCH_SVC_CONFIG_MODULE_CLASS=search_aws_config.AwsSearchConfig`
```bash
ModuleNotFoundError: No module named 'search_aws_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "search_service/search_wsgi.py", line 15, in <module>
application = create_app(config_module_class=config_module_class)
File "/usr/local/lib/python3.7/site-packages/amundsen_search-2.5.1-py3.7.egg/search_service/__init__.py", line 73, in create_app
app.config.from_object(config_module_class)
File "/usr/local/lib/python3.7/site-packages/flask/config.py", line 170, in from_object
obj = import_string(obj)
File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 564, in import_string
ImportStringError, ImportStringError(import_name, e), sys.exc_info()[2]
File "/usr/local/lib/python3.7/site-packages/werkzeug/_compat.py", line 147, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 555, in import_string
module = __import__(module_name, globals(), locals(), [obj_name])
werkzeug.utils.ImportStringError: import_string() failed for 'search_aws_config.AwsSearchConfig'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'search_aws_config' not found.

Original exception:

ModuleNotFoundError: No module named 'search_aws_config'
```

The file content is:
```python
import os

import boto3
from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

from search_service.config import Config


class AwsSearchConfig(Config):
    service = 'es'

    host = os.environ.get('PROXY_ENDPOINT')
    port = 443
    use_ssl = True
    verify_certs = True
    region = os.environ.get('AWS_REGION')
    credentials = boto3.Session().get_credentials()

    aws_auth = AWS4Auth(region=region, service=service, refreshable_credentials=credentials)

    client = Elasticsearch(
        hosts=[{'host': host, 'port': port}],
        http_auth=aws_auth,
        use_ssl=use_ssl,
        verify_certs=verify_certs,
        connection_class=RequestsHttpConnection
    )

    PROXY_CLIENT_KEY = client
```

The file is passed in k8s as a part of ConfigMap and mounted as a single file: `/app/search_aws_config.py`. The file is mounted correctly; if I comment out the env variable everything goes through OK and the file with its content is present as `/app/search_aws_config.py`:

```bash
# ls -al
total 156
drwxr-xr-x 1 root root    34 May 24 15:20 .
drwxr-xr-x 1 root root    39 May 24 15:20 ..
-rw-r--r-- 1 root root 94208 May 21 15:59 .coverage
-rw-r--r-- 1 root root     5 May 21 10:43 .dockerignore
-rw-r--r-- 1 root root    12 May 21 10:43 .gitattributes
drwxr-xr-x 3 root root    50 May 24 09:19 .pytest_cache
-rw-r--r-- 1 root root  1442 May 21 10:43 CHANGELOG.md
-rw-r--r-- 1 root root 11341 May 21 10:43 LICENSE
-rw-r--r-- 1 root root   117 May 21 10:43 MANIFEST.in
-rw-r--r-- 1 root root  1001 May 21 10:43 Makefile
-rw-r--r-- 1 root root   107 May 21 10:43 NOTICE
-rw-r--r-- 1 root root  7992 May 21 10:43 README.md
drwxr-xr-x 2 root root   130 May 24 09:19 amundsen_search.egg-info
drwxr-xr-x 1 root root    43 May 24 09:19 build
drwxr-xr-x 2 root root    45 May 24 09:19 dist
drwxr-xr-x 2 root root    29 May 24 09:19 docs
-rw-r--r-- 1 root root   236 May 21 10:43 public.Dockerfile
-rw-r--r-- 1 root root   561 May 24 08:43 requirements.txt
-rw-r--r-- 1 root root   760 May 24 15:20 search_aws_config.py
drwxr-xr-x 6 root root   141 May 24 09:19 search_service
-rw-r--r-- 1 root root  1172 May 21 17:29 setup.cfg
-rw-r--r-- 1 root root   821 May 21 10:43 setup.py
drwxr-xr-x 4 root root    56 May 24 09:19 tests
```

FYI I also tried places like `/app/search_service/search_aws_config.py` without much luck.

**Comment by jsnowacki** [comment]
> I think you could upstream the config and aws dependencies as optional ones through `extras_require=dict(aws=['botocore' ,'requests-aws4auth'])` in `setup.py`

In general, this is not a bad idea, but the problem is that currently docker install the requirements using the below commands:

```dockerfile
...
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app
RUN python3 setup.py install
...
```

I.e. `python3 setup.py install` will only install the requirements, without extras. Hence, either the AWS requirements should be in `requirements.txt` file or the command for the installation of the `amundsen-search` should be something like `pip install .[aws]`. I think the first one makes a bit more sense as currently there is no distiction between types of requirements, e.g. `pytest` is installed within the file `requirements.txt`.

**Comment by mgorsk1** [comment]
as for first comment, you will also need to:
- have empty `__init__.py` file in `/app` folder
- add `/app` to `PYTHONPATH` env variable 
otherwise python cannot import `search_aws_config.py` as `search_aws_config` module.

as for the second comment - agree, currently it might be overkill to use extras_require, adding it to `requirements.txt` could be enough (I think it's already the case for metadata).

**Comment by jsnowacki** [comment]
Hmmm usually the files/modules correctly added under Docker's `WORKDIR` should be resolved by Python correctly; this may be some oddity of how the class is resolved by `werkzeug`. Nonetheless, adding `PYTHONPATH=/app` to the container works (via k8s container env definition), but it is not particularly elegant, as it may destroy some other `PYTHONPATH`, which is already there and I don't think adding `PYTHONPATH=$PYTHONPATH...` would fix it. Maybe `ENV PYTHONPATH=$PYTHONPATH:/app` should be added to Dockerfile as well.

**Comment by mgorsk1** [comment]
In general, the best approach for customizing IMO would be to add any custom classes to `/custom` directory, append this directory to `PYTHONPATH` and there you go.

**Comment by jsnowacki** [comment]
> @jsnowacki as for first comment, you will need to:
> 
> * mount the file in `/app/search_service` not in `/app` (this I think you tried)
> * set `SEARCH_SVC_CONFIG_MODULE_CLASS=search_service.search_aws_config.AwsSearchConfig`
> 
> as for the second comment - agree, currently it might be overkill to use extras_require, adding it to `requirements.txt` could be enough (I think it's already the case for metadata).

As I written previously, this doesn't work as well, as, in general, the `search_service` module is resolved by `werkzeug` from Pythons `site-packages` and gives the same result with module resolution problem. 

> In general, the best approach for customizing would be IMO to add any custom modules to /custom directory (along with 
empty __init__.py file), append this directory to PYTHONPATH in dockerfile (like you said) and there you go. They need to be reachable through PYTHONPATH (or installed through pip3). The approach with appending /app to PYTHONPATH is just a workaround.

Adding `custom` folder with init or, in fact, other folder will have the same result, as `werkzeug` doesn't seem to have any other folder in its `PYTHONPATH`, than Python `site-packages`. 

Indeed, making config into module and installing it would probably work, but we cannot do it from k8s or any other docker image orchestration software. Hence,  we are again reaching shooting spider with a shotgun situation, as we cannot correctly configure search service with AWS without fork, custom patch, rebuild docker image approach, I try to avoid with this proposal. 

We should either: 

1. Use the extra proxy I proposed; probably simple as PR should take into account `AWS4Auth` with `reshable_credentials`
2. Make the docker accept the custom AWS config in the `/app` folder, i.e.: 
    * add the requirements to `requirements.txt`
    * add  `ENV PYTHONPATH=$PYTHONPATH:/app` to `public.Dockerfile`
    * improve the documentation for `SEARCH_SVC_CONFIG_MODULE_CLASS` showing how to do it correctly (extracted from the above struggle)

**Comment by jsnowacki** [comment]
BTW I'm happy to alter the PR with the agreed changes, though, we need to reach a common agreement I think :)

**Comment by jsnowacki** [comment]
In addition, it is safer to inherit from `LocalConfig` as below, as `search_service/proxy/__init__.py`, requires some `PROXY_*` config keys: 
```python
...
           obj = current_app.config[config.PROXY_CLIENT_KEY]

            # Gather all the configuration to create a Proxy Client
            host = current_app.config[config.PROXY_ENDPOINT]
            user = current_app.config[config.PROXY_USER]
            password = current_app.config[config.PROXY_PASSWORD]
            client = import_string(current_app.config[config.PROXY_CLIENT])
...
```

The custom config class:

```python
import os

import boto3
from elasticsearch import Elasticsearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

from search_service.config import LocalConfig


class AwsSearchConfig(LocalConfig):
    service = 'es'

    host = os.environ.get('PROXY_ENDPOINT')
    port = 443
    use_ssl = True
    verify_certs = True
    region = os.environ.get('AWS_REGION')
    credentials = boto3.Session().get_credentials()

    aws_auth = AWS4Auth(region=region, service=service, refreshable_credentials=credentials)

    client = Elasticsearch(
        hosts=[{'host': host, 'port': port}],
        http_auth=aws_auth,
        use_ssl=use_ssl,
        verify_certs=verify_certs,
        connection_class=RequestsHttpConnection
    )

    PROXY_CLIENT_KEY = client
```

**Comment by mgorsk1** [comment]
Yes, `/app/search_service` won't work for the reasons you said - I realised this after posting but didn't want to edit as you already replied :D 

I think for adding the AwsSearchConfig you have just tested succesfuly I think something much simpler can be done:
1. extend `requirements.txt` with aws4auth and boto3
2. add below code directly to `search_service/config.py`
```
class AwsSearchConfig(LocalConfig):
    import boto3
    from elasticsearch import Elasticsearch, RequestsHttpConnection
    from requests_aws4auth import AWS4Auth

    service = 'es'

    host = os.environ.get('PROXY_ENDPOINT')
    port = 443
    use_ssl = True
    verify_certs = True
    region = os.environ.get('AWS_REGION')
    credentials = boto3.Session().get_credentials()

    aws_auth = AWS4Auth(region=region, service=service, refreshable_credentials=credentials)

    client = Elasticsearch(
        hosts=[{'host': host, 'port': port}],
        http_auth=aws_auth,
        use_ssl=use_ssl,
        verify_certs=verify_certs,
        connection_class=RequestsHttpConnection
    )

    PROXY_CLIENT_KEY = client
```
3. Document possibility of using AwsSearchConfig (and explain how it relies on iam session tokens)

**Comment by jsnowacki** [comment]
Sorry it took a bit longer but I wanted to confirm it works on real system; and it does.

I've updated #1141 with changes to config and requirements; note I used older `boto3` as there were `urllib` issue with ES Python library, but it works fine.

As for the documentation, where is the best place to put information about the new feature?

**Comment by mgorsk1** [comment]
thanks @jsnowacki for filing this and your PR!
