### ISSUE TITLE
The current Helm chart is buggy (500 errors) and out of date

### ISSUE THREAD

**Issue by mickours** [amundsen-io/amundsen#1137]
The current helm chart located in  `amundsen-kube-helm/templates/helm` is not working out of the box (lots of 500 errors on the frontend) because it is out of date.

Thanks to `dave hartley` on the #kube-helm slack channel :+1:  for reporting this.

## Expected Behavior
The Frontend should work out of the box and the chart should be updated with the latest version of amundsen services

## Current Behavior
The Frontend is not working out of the box after a helm install

## Possible Solution
Images should be udated to:
- amundsendev/amundsen-frontend:3.7.0
- amundsendev/amundsen-metadata:3.5.0
- amundsendev/amundsen-search:2.5.1

## Steps to Reproduce
1. Install the current helm chart with:
```sh
cd amundsen-kube-helm/templates/helm
helm dependency update 
helm install amundsen .
```
2. Get access to the frontend:
```sh
kubectl port-forward service/amundsen-frontend 5000:5000
```
3. access to http://localhost:5000 and you'll get 500 errors

## Your Environment

* Amunsen version used: current master (0cb9098)
* Data warehouse stores: ES
* Deployment (k8s or native): k8s EKS

**Comment by armandleopold** [comment]
+1

**Comment by mgorsk1** [comment]
I wonder if there is a way to automatically bump image version in helm chart on release/docker push @dorianj , having to remmber about this seems mundane

**Comment by feng-tao** [comment]
the service imageTags of the helm have been updated. Please check it out and see if the issue persists. Feel free to reopen the issue if that's not the case.
