### ISSUE TITLE
Exception: 'NoneType' object has no attribute 'create_issue'Bug Report

### ISSUE THREAD

**Issue by HenrryVargas** [amundsen-io/amundsen#1149]
When a try to do a new issue show error
## Expected Behavior

   Report issue to a dataset
## Current Behavior

amundsenfrontend    | 20_callback.logging_action
ActionLogParams(command=ch_ms=1621848013399, end@example.org', host_nameargs_json='{"url": "httpst_schema/test_table1/da "test dashboard", "prod": "test dashboard descr48095587, user='roald.amundsen@example.org', host_name='d500de7944ee', pos_args_json='[]', keyword_args_json='{"command": "click", "target_id": "report-table-issue-form", "target_type": "form", "label": "Title\\nDescription\\nSubmit", "location": "/table_detail/gold/hive/test_schema/test_table1", "value": null}', output='null', error=None)
amundsenfrontend    | 2021-05-24T09:21:35+0000.589 [ERROR] issue.post:78 (9:MainThread) - Encountered exception: 'NoneType' object has no attribute 'create_issue'
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/app/amundsen_application/api/issue/issue.py", line 67, in post
amundsenfrontend    |     response = self.client.create_issue(description=args['description'],
amundsenfrontend    | AttributeError: 'NoneType' object has no attribute 'create_issue'

## Steps to Reproduce

1. Select  a dataset
2. click report am issue
3. Input totile
4. Input description
5.  summit

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by dorianj** [comment]
Can you share your issue configuration?
