### ISSUE TITLE
Bug Report: Errors using front end to edit some values in Neptune backend.

### ISSUE THREAD

**Issue by zjph90** [amundsen-io/amundsen#1151]
## Metadata service errors when I use the frontend to add owner or bookmark to Neptune backend

I currently have our Amundsen system running against an AWS Neptune back end. Databuilder ingestion seems to work ok. I can use the front end to make edits to things like column descriptions but when I try to use the front end to add a dataset owner I get the following from the metadata service:

> 2021-05-19T18:10:08+0000.667 [INFO] shared.retrying:63 (132:Thread-5) - exception  is not retryable
> 2021-05-19T18:10:08+0000.668 [WARNING] gremlin_proxy.__call__:229 (132:Thread-5) - got exception executing query=[['V', 'User:owner@test.com']], get=<bound method FromResultSet.getOnly of <class 'metadata_service.proxy.gremlin_proxy.FromResultSet'>>, bindings=None
> Traceback (most recent call last):
>   File "/app/amundsenmetadatalibrary/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 227, in __call__
>     return retrying(callable, is_retryable=self.is_retryable)
>   File "/app/amundsenmetadatalibrary/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/shared.py", line 58, in retrying
>     return callable()
>   File "/app/amundsenmetadatalibrary/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 225, in callable
>     return ClientQueryExecutor.__call__(self, query, get, bindings=bindings)
>   File "/app/amundsenmetadatalibrary/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 205, in __call__
>     return get(result_set)
>   File "/app/amundsenmetadatalibrary/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 162, in getOnly
>     value = next(i)
> StopIteration
> 

The added owner ID does not subsequently show up in the front end

I also get similar behaviour when trying to bookmark a dataset:

> 2021-05-24T18:01:36+0000.773 [INFO] shared.retrying:63 (27:Thread-11) - exception  is not retryable
> 2021-05-24T18:01:36+0000.773 [WARNING] gremlin_proxy.__call__:231 (27:Thread-11) - got exception executing query=[['V', 'User:test_user_id']], get=<bound method FromResultSet.getOnly of <class 'metadata_service.proxy.gremlin_proxy.FromResultSet'>>, bindings=None
> Traceback (most recent call last):
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 229, in __call__
>     return retrying(callable, is_retryable=self.is_retryable)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/shared.py", line 58, in retrying
>     return callable()
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 227, in callable
>     return ClientQueryExecutor.__call__(self, query, get, bindings=bindings)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 207, in __call__
>     return get(result_set)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 164, in getOnly
>     value = next(i)
> StopIteration
> 2021-05-24T18:01:36+0000.774 [ERROR] user.put:154 (27:Thread-11) - UserFollowAPI PUT Failed
> Traceback (most recent call last):
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/api/user.py", line 147, in put
>     resource_type=to_resource_type(label=resource_type))
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/statsd_utilities.py", line 38, in wrapper
>     return f(*args, **kwargs)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 1575, in add_resource_relation_by_user
>     vertex2_label=vertex_type, vertex2_key=id)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 584, in _link
>     executor(query=g.V(vertex1_id), get=FromResultSet.getOnly)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 229, in __call__
>     return retrying(callable, is_retryable=self.is_retryable)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/shared.py", line 58, in retrying
>     return callable()
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 227, in callable
>     return ClientQueryExecutor.__call__(self, query, get, bindings=bindings)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 207, in __call__
>     return get(result_set)
>   File "/app/amundsen/metadata/venv/lib/python3.7/site-packages/amundsen_metadata-3.5.0-py3.7.egg/metadata_service/proxy/gremlin_proxy.py", line 164, in getOnly
>     value = next(i)
> StopIteration
> 2021-05-24T18:01:36+0000.775 [INFO] _internal._log:122 (27:Thread-11) - 172.23.0.4 - - [24/May/2021 18:01:36] "PUT /user/test_user_id/follow/table/Table:oracle://t01edw.bi_edw/wc_trading_activity_summary HTTP/1.1" 500 -
> 

## Steps to Reproduce
1. Establish Amundsen with Neptune back-end
2. Populate with test data using the sample data
3. Attempt to add/modify the owner of an existing dataset using the frontend

## Your Environment

We are using the 3.3.0 front end but the latest (3.7.0?) version of the metadata service.
Neptune instance on AWS - latest version on db.t3.medium
Elasticsearch running on AWS also - version 6.7
Amundsen microservices running on docker containers on WSL2

**Comment by zjph90** [comment]
I did some further investigation here and it would appear that the proxy in its current state will only add the ownership relationship if the user to be added already exists as a vertex in the database. 

Comparing with the [Neo4j proxy](https://github.com/amundsen-io/amundsen/blob/0e600dea3127569169093aabe0c5a2280a7d2cda/metadata/metadata_service/proxy/neo4j_proxy.py#L549-L571) this does a pre-emptive MERGE so that, if the user does not already exist, one is created. No such checking or handling is done in the gremlin proxy.

From my limited research there does not appear to be an equivalent to MERGE in Gremlin. There seems to be a preferred workaround (described here: https://stackoverflow.com/questions/49758417/cosmosdb-graph-upsert-query-pattern). We could maybe incorporate this with something like: 

```
g.V().has('User','key','fred@cmc.com').
fold().
coalesce(unfold(),
       addV('User').
       property(id, 'User:fred@cmc.com').
       property('key','fred@cmc.com').
       property('email','fred@cmc.com')
)
```

Obviously replacing the literal email with the supplied string. I've tested this in a Gremlin console and it appears to work.

**Comment by zjph90** [comment]
Further to this - I noticed, from the way Tags are handled, that there is an **_upsert** method that can do what we want. 
I modified the **_add_owner** method as follows:

```python
def _add_owner(self, *, table_uri: str, owner: str, executor: ExecuteQuery) -> None:
        _upsert(executor=executor, g=self.g, label=VertexTypes.User, key=owner,
         key_property_name=self.key_property_name, email=owner, is_active="true")
        _link(executor=executor, g=self.g, edge_label=EdgeTypes.Owner, key_property_name=self.key_property_name,
              vertex1_label=VertexTypes.Table, vertex1_key=table_uri,
              vertex2_label=VertexTypes.User, vertex2_key=owner)
```
Note there is now a call to **_upsert**.

This has the desired effect of creating the User node if it does not exist. The method proceeds to add the relationship. 

However - there is a slight glitch in the way the front end works here and the owner field is not visible immediately. Instead we get "There was a problem with the request, please reload the page". I can see from chrome tools that we are getting an error:

> POST http://localhost:5000/api/mail/v0/notification 501 (NOT IMPLEMENTED)

This happens even if the user already exists beforehand. The error does go away when the page is refreshed and the new owner is displayed.

Some other concerns I have are:
- Are there other properties we should be setting here?
- The relationship appears to be only created in one direction (same as for Tags). They are bi-directional when loaded with databuilder.

**Comment by zjph90** [comment]
This is still unresolved

**Comment by zjph90** [comment]
This is still unresolved, thanks

**Comment by amommendes** [comment]
This is still unresolved, thanks
