### ISSUE TITLE
Move databuilder requirements from within setup.py to separate files

### ISSUE THREAD

**Issue by sewardgw** [amundsen-io/amundsen#1161]
Requirements are currently defined directly in the setup.py file which means that even the smallest change that is made to a databuilder script and placed into a docker container requires a long time to rebuild the image. A select few of the extra_requires requirements create prohibitively-long build times on the order of 10+ minutes. 

For example, a docker file that includes the databuilder + any script to execute it may look like:

```Dockerfile
...
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /app

RUN pip install /app[all]

CMD [ "python3", "databuilder/my_scripts/run_databuilder.py" ]
```

Where `all` could be any of the sets of extra requirements. Since the local data builder needs to be pip installed to pick up on any changes made under `./databuilder` and all of the requirements are defined in-line, we cannot take advantage of Docker caching which could enable us to pip install the requirements prior copying the local databuilder code and installing it. 

## Expected Behavior or Use Case

Databuilder should enable implementers to package a local version into a docker container without having to reinstall requirements.

## Service or Ingestion ETL
Databuilder

## Possible Implementation
Replicate a similar structure for what [Faust has built](https://github.com/robinhood/faust).

Place the requirements into their own directory with the file name corresponding to the requirement type currently defined such that the current values:
```python
requirements = [
    "neo4j-driver>=1.7.2,<4.0",
    "pytz>=2018.4",
   ...
    "pandas>=0.21.0,<1.2.0",
    "amundsen-rds>=0.0.4"
]

kafka = ['confluent-kafka==1.0.0']

cassandra = ['cassandra-driver==3.20.1']

glue = ['boto3==1.10.1']

snowflake = [
    'snowflake-connector-python',
    'snowflake-sqlalchemy'
]

athena = ['PyAthena[SQLAlchemy]>=1.0.0, <2.0.0']
```
Would turn into 

```text
-requirements
  |-requirements.txt
  |-kafka.txt
  |-cassandra.txt
  |-glue.txt
...
```
The contentst of `kafka.txt`, for example, would contain:
```text
confluent-kafka==1.0.0
```

The `setup.py` file would then read these values from the file and build them into the exact same `extra_requires` object that we have today. This would mean that there is 100% compatibility with the existing processes.

This supports the docker builds process because the requirements can be copied over and installed like:

```Dockerfile
COPY requirements/kafka.txt /app/requirements/kafka.txt
RUN pip3 install -r /app/requirements/kafka.txt

COPY requirements/cassandra.txt /app/requirements/cassandra.txt
RUN pip3 install -r /app/requirements/cassandra.txt

COPY . /app

RUN pip install /app
```
Taking advantage of docker cachine.

## Context
See above

**Comment by mgorsk1** [comment]
I think it makes sense, could be done as a part of https://github.com/amundsen-io/rfcs/pull/38 as I was planning to do the same for requirements.txt and requirements-dev.txt for every subproject. One nit: I'd still have `requirements` in the name of the file (so `requirements-kafka.txt` over `kafka.txt`)

**Comment by mgorsk1** [comment]
Thanks for replying. My second question was mostly towards how using external requirements files solves the issue better than selective pip install (pip install .[kafka] && pip install .[cassandra] instead of pip install .[all]). 

As we don't really provide docker image for databuilder it sounds like the major benefit would be for developer who builds databuilder images to test his changes in dockerized env (is this a common pattern? why not use venv?). For users relying on end product it doesn't change much I think.

**Comment by sewardgw** [comment]
I completely agree with all of your points. For context, I am running databuilder inside of Kubernetes (not scheduled by Airflow).

In regards to how the external requirements file is better than a selective pip - it actually only provides benefit for the pip install portion that is installing the base requirements (e.g. neo4j, pytz, pandas, etc). As seen in the comment above, it is possible to install and cache the "extra" dependencies. If there was a separate requirements file that had these base requirements something like this could be done:

```Dockerfile
COPY requirements/base_requirements.txt /app
RUN pip install -r /app/base_requirements.txt 

COPY . /app
RUN pip install /app
```

Now, when the `RUN pip install /app` command runs, the pip within this docker container has already installed the base requirements and it would not need to pull and install these reqs again , making this step much faster every time I make a change to databuilder and rebuild the image.  This base requirements file would be different than the existing `requirement.txt` in that it also would not have the testing resources (flake 8, etc).

Let me know if this helps to clarify
