### ISSUE TITLE
Bug Report: Amundsen Keycloak SSO

### ISSUE THREAD

**Issue by iamtodor** [amundsen-io/amundsen#1170]
As our discussion has started in slack from the message https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1622027515072500

@OElesin and I couldn't manage to run Amundsen services along with Keycloak SSO:
We were able to get the login to work but we keep getting the error message:
```json
{"msg":"Encountered exception: 'dict' object has no attribute 'user_id'"}
```
The error comes from: https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/amundsen_application/api/v0.py#L46

After that @verdan and I had a private conversation about how to debug or log it. Due to we are running containers on AWS Fargate, we don't have direct access to the container. 
So I started to build and reproduce it locally. A new issue raised - `OSError: [Errno 99] Cannot assign requested address `. 
To make it simple I created a repo with explicit steps to reproduce: https://github.com/iamtodor/amundsen-sso-keycloak-reproduce-repo

@verdan could you please take a look and figure out what went wrong in my setup?

CC @HenrryVargas @markgrover

**Comment by mgorsk1** [comment]
hey @iamtodor there are couple of things you'll need to fix in your repo so the sso works. Apply this diff file on your repo and it should work like a charm (it has for me)

```
diff --git a/README.md b/README.md
index c3f1236..3333a93 100644
--- a/README.md
+++ b/README.md
@@ -1,7 +1,7 @@
 # HOWTO
 
 To reproduce the issue:
-1. Run `docker run --hostname host -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:13.0.1`
+1. Run `docker run --hostname amundsen-keycloak -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:13.0.1`
 2. login to `http://localhost:8080/auth/admin` with admin/admin
 3. Setup authentication as it described here https://nirav-langaliya.medium.com/setup-oidc-authentication-with-lyft-amundsen-via-okta-eb0b89d724d3
 with keycloak integration:
diff --git a/cloak/keycloak.json b/cloak/keycloak.json
index b432c17..b4edfda 100644
--- a/cloak/keycloak.json
+++ b/cloak/keycloak.json
@@ -4,7 +4,7 @@
     "issuer_admin": "http://localhost:8080/auth/admin/realms/master",
     "auth_uri": "http://localhost:8080/auth/realms/master/protocol/openid-connect/auth",
     "client_id": "amundsen-frontend",
-    "client_secret": "2c789fcb-0b6a-4c56-b571-3cb0cc342b0a",
+    "client_secret": "f061f360-ac42-4f5e-9b58-97275b3502b8",
     "userinfo_uri": "http://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo",
     "token_uri": "http://localhost:8080/auth/realms/master/protocol/openid-connect/token",
     "token_introspection_uri": "http://localhost:8080/auth/realms/master/protocol/openid-connect/token/introspect",
@@ -15,4 +15,4 @@
       "http://0.0.0.0:5000/oidc_callback"
     ]
   }
-}
\ No newline at end of file
+}
diff --git a/docker-compose.yml b/docker-compose.yml
index c0b0a15..ecf7ddf 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -9,23 +9,18 @@ services:
       nofile:
         soft: 40000
         hard: 40000
-    ports:
-      - 7474:7474
-      - 7687:7687
     volumes:
       - ./example/docker/neo4j/conf:/var/lib/neo4j/conf
       - ./.local/neo4j/data:/data
   #      networks:
   #        - amundsennet
-  #      network_mode: host
+    network_mode: host
   elasticsearch:
     image: elasticsearch:6.7.0
     container_name: es_amundsen
-    ports:
-      - 9200:9200
     #      networks:
     #        - amundsennet
-    #      network_mode: host
+    network_mode: host
     ulimits:
       nofile:
         soft: 65536
@@ -35,13 +30,11 @@ services:
   amundsensearch:
     image: amundsendev/amundsen-search:latest
     container_name: amundsensearch
-    ports:
-      - 5001:5001
     depends_on:
       - elasticsearch
     #      networks:
     #        - amundsennet
-    #      network_mode: host
+    network_mode: host
     environment:
       - PROXY_ENDPOINT=es_amundsen
   amundsenmetadata:
@@ -51,11 +44,9 @@ services:
     container_name: amundsenmetadata
     depends_on:
       - neo4j
-    ports:
-      - 5002:5002
     #      networks:
     #        - amundsennet
-    #      network_mode: host
+    network_mode: host
     environment:
       - PROXY_HOST=bolt://neo4j_amundsen
       - FLASK_APP_MODULE_NAME=flaskoidc
@@ -73,11 +64,9 @@ services:
     depends_on:
       - amundsenmetadata
       - amundsensearch
-    ports:
-      - 5000:5000
     #      networks:
     #        - amundsennet
-    #      network_mode: host
+    network_mode: host
     environment:
       - SEARCHSERVICE_BASE=http://amundsensearch:5001
       - METADATASERVICE_BASE=http://amundsenmetadata:5002
@@ -90,10 +79,10 @@ services:
       - SESSION_TYPE=sqlalchemy
       - FLASK_OIDC_LOG_DATE_FORMAT=%Y-%m-%dT%H:%M:%S%z
       - FLASK_OIDC_LOG_LEVEL=DEBUG
-      - OIDC_CLOCK_SKEW=560 # https://stackoverflow.com/questions/53477760/flask-oidc-with-keycloak-oidc-callback-default-callback-not-working
+      # - OIDC_CLOCK_SKEW="560" # https://stackoverflow.com/questions/53477760/flask-oidc-with-keycloak-oidc-callback-default-callback-not-working
 
 #networks:
 #  amundsennet:
 #  default:
 #    external: true
-#    name: my_amundsen
\ No newline at end of file
+#    name: my_amundsen
diff --git a/frontend.Dockerfile b/frontend.Dockerfile
index a56380a..3483095 100644
--- a/frontend.Dockerfile
+++ b/frontend.Dockerfile
@@ -18,10 +18,10 @@ ENV SQLALCHEMY_DATABASE_URI 'sqlite:///sessions.db'
 
 ENV SESSION_TYPE 'sqlalchemy'
 
-ENV FLASK_OIDC_SECRET_KEY 'fe4843b4-5abe-4122-83d4-309235b03625'
+ENV FLASK_OIDC_SECRET_KEY = 'f061f360-ac42-4f5e-9b58-97275b3502b8' 
 
 ENV FLASK_OIDC_WHITELISTED_ENDPOINTS "status,healthcheck,health"
 ENV FLASK_OIDC_LOG_DATE_FORMAT '%Y-%m-%dT%H:%M:%S%z'
 ENV FLASK_OIDC_LOG_LEVEL 'INFO'
 
-ENV OIDC_CLIENT_SECRETS '/cloak/keycloak.json'
\ No newline at end of file
+ENV OIDC_CLIENT_SECRETS '/cloak/keycloak.json'

```

**Comment by iamtodor** [comment]
@mgorsk1 according to my mailbox I believe you've left the comment and then delete it? I updated [HOWTO section](https://github.com/iamtodor/amundsen-sso-keycloak-reproduce-repo/blob/master/README.md#howto) and provided `keycloak-config.json` with that you can easily setup keycloak client.
If I missed something, please feel free to reach me out

**Comment by verdan** [comment]
@iamtodor, I will get back to you by the end of this week.

**Comment by iamtodor** [comment]
@verdan Awesome, thank you for the feedback :)

**Comment by HenrryVargas** [comment]
@iamtodor I am struggling yet with connect Amundsen with keycloak.
 My issue: https://github.com/amundsen-io/amundsen/issues/1132

**Comment by verdan** [comment]
@iamtodor my understanding is that the issue that you are facing locally has nothing to do with the Amundsen. This is the way Docker works with flask and keycloak. 
I followed this answer: https://stackoverflow.com/questions/53613866/flask-oidc-gives-errno-99-cannot-assign-requested-address-when-run-in-docker-c

**Comment by verdan** [comment]
Also, I am working on moving away from `flask-oidc`, and use Auth0 instead, as the `flask-oidc` is not being maintained anymore and has a lot of security issues. This will take a few days before I actually release a new version of `flaskoidc` package, which is backed by Auth0. I will keep you posted on the progress.

**Comment by verdan** [comment]
@iamtodor I have released a new version of flaskoidc on TestPyPi. Would you be able to give it a try quickly and see if this works for you? 

https://test.pypi.org/project/flaskoidc/0.3.0/

Just follow the Readme, and Please note that this is testpypi, so you may need to add --extra-index-url if you specify this in your requirements.txt. 

And then you'll also need to modify your oidc_config.py file as well. 

'''python

# Copyright Contributors to the Amundsen project.
# SPDX-License-Identifier: Apache-2.0
import json

from typing import Dict, Optional
from flask import Flask, session
from amundsen_application.config import LocalConfig
from amundsen_application.models.user import load_user, User


def get_access_headers(app: Flask) -> Optional[Dict]:
    """
    Function to retrieve and format the Authorization Headers
    that can be passed to various microservices who are expecting that.
    :param oidc: OIDC object having authorization information
    :return: A formatted dictionary containing access token
    as Authorization header.
    """
    try:
        # noinspection PyUnresolvedReferences
        access_token = json.dumps(app.auth_client.token)
        return {'Authorization': 'Bearer {}'.format(access_token)}
    except Exception:
        pass


def get_auth_user(app: Flask) -> User:
    """
    Retrieves the user information from oidc token, and then makes
    a dictionary 'UserInfo' from the token information dictionary.
    We need to convert it to a class in order to use the information
    in the rest of the Amundsen application.
    :param app: The instance of the current app.
    :return: A class UserInfo (Note, there isn't a UserInfo class, so we use Any)
    """
    user_info = load_user(session.get("user"))
    return user_info


class OidcConfig(LocalConfig):
    AUTH_USER_METHOD = get_auth_user
    REQUEST_HEADERS_METHOD = get_access_headers

'''

**Comment by iamtodor** [comment]
stale bot, we will have some activity in nearest future, no need to close it :D

**Comment by iamtodor** [comment]
don't stale it

**Comment by iamtodor** [comment]
Hello @verdan!
I've tried following your new FlaskOIDC new version and instruction.
I'm a bit stuck at the point while set uping Request Headers: https://www.amundsen.io/amundsen/authentication/oidc/#setting-up-request-headers
Since I'm using docker containers I don't quite understand how should I define the following function in config.py
```python
from flask import Flask
def get_access_headers(app: Flask) -> Optional[Dict]:
    try:
        # noinspection PyUnresolvedReferences
        access_token = json.dumps(app.auth_client.token)
        return {'Authorization': 'Bearer {}'.format(access_token)}
    except Exception:
        pass 
```
[1] If I got everything right I need to build my own docker image for the frontend right from the source https://github.com/amundsen-io/amundsen/tree/main/frontend. Is it correct?
[2] On the page https://www.amundsen.io/amundsen/authentication/oidc there are no mentions for Metadata and Search containers. However, I noticed your comment and screens here https://github.com/amundsen-io/amundsen/pull/1248 What should I follow in order to set up SSO? Cause currently, I'm confused :)

**Comment by verdan** [comment]
Are you using this docker image? https://hub.docker.com/r/amundsendev/amundsen-frontend-oidc
Then you do not need to set this function as it will do this automatically for you. 

For metadata and Search, if you'd simply specify the required environment variables (https://github.com/verdan/flaskoidc#configurations) it will work just fine. 

No need to change the code in there if you already have the users in your database.
