### ISSUE TITLE
Table/Column Description gets overwritten after Re-Extraction, if data source has Table/Column Comment 

### ISSUE THREAD

**Issue by zaheeruddinfaiz** [amundsen-io/amundsen#1171]
## Expected Behavior
I have a Postgres DB and I have made comment on Table and columns in the DB. After Importing the metadata for first time. I can change the table/column description in Amundsen. However, if I import my Postgres DB again. The description that I wrote in Amundesn should not be overwritten by the comment I have made in the DB. 
## Current Behavior
The description gets overwritten by the comment on Table/Column. 
## Possible Solution
I have not looked in detail in databuilder code. I think we might need to make changes in the Cypher queries. 
## Steps to Reproduce
1. Create a Test DB (Postgres) and add comment on Table and Column
2.Import the metadata from the DB. You will see the comment you made on Table/Column as Table/Column description in Amundsen 
3.Change the Table/Column description in Amundsen 
4.Run the extraction again, the Table/Column description will be overwritten by the Table/Column Comment in the Db

## Screenshots
I made comment on Table in DB
![image](https://user-images.githubusercontent.com/50898382/120094299-efc61e80-c138-11eb-8a04-ddaac84030ff.png)
After importing the metadata for the first time
![image](https://user-images.githubusercontent.com/50898382/120094327-28fe8e80-c139-11eb-9d64-f9e67bfd7d7f.png)
Changed Description in Amundsen.
![image](https://user-images.githubusercontent.com/50898382/120094366-62cf9500-c139-11eb-8725-5a0e2374365c.png)
After running the extraction again, The description I wrote in Amundsen gets overwritten
![image](https://user-images.githubusercontent.com/50898382/120094413-9b6f6e80-c139-11eb-8f77-aa040e365564.png)

## Context
I consider this behaviour as bug, because, this fails the purpose of using Amundsen. I don't want to worry about keeping the description in Sync with my original data source and Amundsen. 
## Your Environment
Default Amundsen version, with local setup

**Comment by zjph90** [comment]
Hi Zaheer,

I think you can partially address your requirement by using Programmatic Descriptions ([here](https://technology.edmunds.com/2020/05/27/Adding-Data-Quality-into-Amundsen-with-Programmatic-Descriptions/) is a good page about this). 

Unfortunately Programmatic Descriptions are not yet implemented for Columns. I have raised an issue requesting this (https://github.com/amundsen-io/amundsen/issues/1093)
