### ISSUE TITLE
Marshmallow validation error: common_joins

### ISSUE THREAD

**Issue by madison-ookla** [amundsen-io/amundsen#1191]
I've recently upgraded from pre-monorepo days to now `common-0.13.0-fix2`, and I'm getting a Marshmallow validation error on all table metadata pages.

## Expected Behavior

When I visit a table page, I should see the data as typically prevented.

## Current Behavior

The page says `Something went wrong...` and the frontend logs show the following:

```
amundsenfrontend    | 2021-06-03T22:50:49+0000.609 [ERROR] v0._get_table_metadata:155 (9:MainThread) - Encountered exception: {'common_joins': ['Unknown field.'], 'common_filters': ['Unknown field.']}
amundsenfrontend    | Traceback (most recent call last):
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/amundsen_application/api/metadata/v0.py", line 149, in _get_table_metadata
amundsenfrontend    |     results_dict['tableData'] = marshall_table_full(table_data_raw)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/amundsen_application/api/utils/metadata_utils.py", line 109, in marshall_table_full
amundsenfrontend    |     table: Table = schema.load(table_dict)
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
amundsenfrontend    |     data, many=many, partial=partial, unknown=unknown, postprocess=True
amundsenfrontend    |   File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
amundsenfrontend    |     raise exc
amundsenfrontend    | marshmallow.exceptions.ValidationError: {'common_joins': ['Unknown field.'], 'common_filters': ['Unknown field.']}
```

I believe this has to do with #1155.

## Steps to Reproduce

1. Build the containers with `common-0.13.0-fix2`
2. Ingest some data
3. Visit a table page

## Your Environment

* Amunsen version used: `common-0.13.0-fix2`
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by HenrryVargas** [comment]
Hi
Few days ago, I have this issue, the solution was change set common version to 0.13 in frontend,databuilder,metadadata and search, into the requeriments.txt for each one and after deploy the dockers.

requeriments.txt in search: amundsen-common>=0.13.0,<1.0
requeriments.txt in metadata: amundsen-common>=0.13.0
requeriments.txt in frontend: amundsen-common==0.13.0
requeriments.txt in frontend: amundsen-common>=0.13.0

**Comment by mgorsk1** [comment]
Thanks for filing this, indeed common must be the same for each services. There is open PR to unify this this moving forward.

**Comment by madison-ookla** [comment]
Got it, thank you both! I'll give that a shot

**Comment by madison-ookla** [comment]
For future reference, on `common-0.13.0-fix2`, I was able to resolve this by pinning the metadata and search repos to `amundsen_common==0.11.0`. This prevented a version conflict with the base libraries.
