### ISSUE TITLE
databuilder 4.5.0 is missing an install_requires dependency to amundsen-common 0.13.0

### ISSUE THREAD

**Issue by ecerulm** [amundsen-io/amundsen#1203]
## Expected Behavior

importing `databuilder.models.dashboard.dashboard_metadata` should NOT raise any ModuleNotFoundError

   

## Current Behavior

 
    python -c 'import databuilder.models.dashboard.dashboard_metadata'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/rubelagu/tmp/venv/lib/python3.8/site-packages/databuilder/models/dashboard/dashboard_metadata.py", line 8, in <module>
        from amundsen_common.utils.atlas import AtlasCommonParams, AtlasDashboardTypes
    ModuleNotFoundError: No module named 'amundsen_common'

We get that `ModuleNotFoundError` on `amundsen_common` because `amundsen-common==0.13.0` was not installed when I installed `amundsen-databuilder==4.5.0'. 

## Possible Solution

I guess the this can be solved by declaring an `install_requires` dependency on `amundsen-common` in setup.cfg or setup.py

## Steps to Reproduce

   pyenv shell 3.8.2
    python -m venv venv
    source venv/bin/activate
    pip install amundsen-databuilder==4.5.0
    python -c 'import databuilder.models.dashboard.dashboard_metadata' # raises a ModuleNotFoundError

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by dorianj** [comment]
This is fixed by https://github.com/amundsen-io/amundsen/pull/1163 

I'm not actually sure how this was working properly before -- there have been no major changes AFAICT to setup.py since last release

**Comment by mgorsk1** [comment]
common was just introduced in databuilder and I see it's in requirements.txt but not in setup.py. PR mentioned by @dorianj  fixes this indeed.

**Comment by mgorsk1** [comment]
@ecerulm unification of dependencies solved this issue. Feel free to reopen if something new comes up.
