### ISSUE TITLE
Elastic Search Failing

### ISSUE THREAD

**Issue by dhavalmohandas** [amundsen-io/amundsen#1205]
## Expected Behavior

I'm following the user guide and I'm on step 6 of the installation. After running sample_data_loader.py, I'm getting an exception. Currently using Neo4j backend. I should be able to see some result after searching "test"
## Current Behavior

Getting:
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [table : {properties={schema={analyzer=simple, type=text, fields={raw={type=keyword}}}, cluster={analyzer=simple, type=text, fields={raw={type=keyword}}}, description={analyzer=simple, type=text}, display_name={type=keyword}, column_descriptions={analyzer=simple, type=text}, programmatic_descriptions={analyzer=simple, type=text}, tags={type=keyword}, badges={type=keyword}, database={analyzer=simple, type=text, fields={raw={type=keyword}}}, total_usage={type=long}, name={analyzer=simple, type=text, fields={raw={type=keyword}}}, last_updated_timestamp={format=epoch_second, type=date}, unique_usage={type=long}, column_names={analyzer=simple, type=text, fields={raw={type=keyword}}}, key={type=keyword}}}]'
## Possible Solution

I have used this: https://github.com/docker/for-win/issues/1825#issuecomment-444766883 
for getting docker up. 

## Steps to Reproduce

1.
2.
3.
4.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/14835820/121293577-d865fe80-c8b9-11eb-9757-3611d32ab9b3.png)

## Context

I'm using my work laptop without admin rights. Have launched docker using powershell in admin mode.

## Your Environment

* Amunsen version used: 
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by BartoszJanota** [comment]
Hi @dhavalmohandas, did you get it solved? If so, how?
