### ISSUE TITLE
Jira Issue Tracker integration - create issue incompatibility

### ISSUE THREAD

**Issue by bbsbb** [amundsen-io/amundsen#1206]
The current integration with the Jira rest API does not match an evolution implemented by Atlassian over GDPR.

The 'reporter' field currently passed by the JiraClient relies on the name field, the field is now obsolete and accountId should be used instead.

https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/proxy/issue_tracker_clients/jira_client.py#L96

The changes in question are described here: 
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

## Expected Behavior

Creating an issue to a new Atlassian Cloud jira project succeeds and the issue is visible in the Amundsen UI.

## Current Behavior

Attempts to create an issue over the Amundsen UI results in an error.
The logs indicate a status code 400 with an error message 'text: Reporter is required'.

## Possible Solution

Using accountId with matching accountId solves the issue.

The Jira API allows to resolve emails to accountIds. Introducing an additional request to achieve that is trivial, I'm up for PR-ing if it's an acceptable solution.

## Steps to Reproduce
1. Enable issue tracking with jira cloud instance.
2. Attempt to create an issue from the amundsen interface
3. Observe failure in logs.

## Screenshots (if appropriate)

N/A

## Context

N/A

## Your Environment

Amundsen head of main branch ( 8d87e7cd442ab03f4382d85ee93be42506c86ac2 ) , Atlassian cloud.

**Comment by dorianj** [comment]
Thanks for fixing this!
