### ISSUE TITLE
Support for PrestoDB Integration

### ISSUE THREAD

**Issue by rohanpednekar** [amundsen-io/amundsen#1243]
Could you guys please add support for [PrestoDB](https://prestodb.io/) Integration as well? 

Presto Community would love to collaborate, please feel free to @ me if you guys need any help from us. 

Thanks for this great project. 🙏

**Comment by feng-tao** [comment]
it has a presto (or trino) view extractor.

**Comment by feng-tao** [comment]
https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/presto_view_metadata_extractor.py

**Comment by rohanpednekar** [comment]
Thanks, @feng-tao, Do you think it will work for PrestoDB as well since Trino has diverged a lot from Presto? Do you know What Presto version it got tested for?

**Comment by rohanpednekar** [comment]
CC @aweisberg

**Comment by feng-tao** [comment]
I actually don't know as the extractor has been contributed long time ago back at Lyft. The implementation doesn't have to do with presto but issue a metadata query to hive metastore to fetch all the presto view information.

**Comment by feng-tao** [comment]
if you use the extractor and found any issues, feel free to report/upstream any fix.

**Comment by rohanpednekar** [comment]
Sure, meanwhile could you please add  [PrestoDB](https://prestodb.io/) as well in your list of [connectors](https://www.amundsen.io/amundsen/#table-connectors) since you support its other forks.

**Comment by feng-tao** [comment]
Could you create a Pr for that? Happy to review and ship it. Thanks.

**Comment by rohanpednekar** [comment]
Thanks, please review https://github.com/amundsen-io/amundsen/pull/1244
