### ISSUE TITLE
Bug Report: Some links not working in https://www.amundsen.io/amundsen/

### ISSUE THREAD

**Issue by robalvsan** [amundsen-io/amundsen#1261]
These are the broken links:

- Please visit the Amundsen installation documentation for a [quick start](https://www.amundsen.io/amundsen/docs/installation.md) to bootstrap a default version of Amundsen with dummy data.

- Please visit [Architecture](https://www.amundsen.io/amundsen/docs/architecture.md) for Amundsen architecture overview.

- Please visit [Installation guideline](https://www.amundsen.io/amundsen/docs/installation.md) on how to install Amundsen.

- Please visit [Roadmap](https://www.amundsen.io/amundsen/docs/roadmap.md) if you are interested in Amundsen upcoming roadmap items.

## Expected Behavior
Go to webpages with more info.

## Current Behavior
404 - Not found

## Possible Solution
Check the links.

**Comment by feng-tao** [comment]
thanks for reporting. Let me know if you have the chance to fix it as it is related to relative path change after mono report happens.

**Comment by rbrishabh** [comment]
I can help with this!

**Comment by robalvsan** [comment]
Thanks for the changes @rbrishabh!
