### ISSUE TITLE
Feature Proposal: Make Popular Dashboard's logic pluggable

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#1279]
For now, we are using the same logic for dashboards that we have popular tables. Based on Tao's comment here: https://github.com/amundsen-io/amundsen/pull/1271#issuecomment-868874435 this can be a pluggable implementation.

**Comment by Golodhros** [comment]
It is already pluggable, you can extend the metadata method to be whatever you want it to be and use a custom metadata class.
