### ISSUE TITLE
Have some doubts regarding Amundsen integration with ATLAS

### ISSUE THREAD

**Issue by vthorwat** [amundsen-io/amundsen#1302]
Hello Guys,

We were planning to explore Amundsen in our environment. 

Currently, we have Hortoworks Cluster (HDP Cluster) where below are the Services that we want to integrate.

Atlas Version --  0.8.0
Hive Verison -- 1.2.1000

Can you please confirm, above versions are compatible with Amundsen?

If yes, then I would like to integrate Amundsen into our environment and explore its functionalities. 

After looking at the installation steps given below in the docs, I observed that Amundsen is spawning an Atlas Container internally.  

```
URL: https://github.com/amundsen-io/amundsen/blob/main/docs/installation.md
```
![image](https://user-images.githubusercontent.com/14247410/124084552-b7359f80-da6c-11eb-9a0f-e9ff6082c49e.png)

But we want Amundsen to integrate with our Atlas which will help us to run perform some data discovery on Hive Schemas. 

Please let us know if it possible, 

Also please correct me, If I am missing something regarding Amundsen architecture. 

Thanks,
Vinod

**Comment by mgorsk1** [comment]
Hi @vthorwat! Unfortunately Atlas 0.8 is not compatible with Amundsen. The main reason is we have introduced a number of improvements over last years to Atla so it plays nicely with Amundsen. There might be a few things not working as expected when using version 0.8 that's why we recommend using version 2.1.0 as it contains all the submitted patches.

**Comment by vthorwat** [comment]
Thank you @mgorsk1 for your quick response..!

So if we spawn up Amundsen with Atlas as specified in the Installation Steps will it be able to integrate with external Hive Services?

if yes then we would love Amundsen to connect to our cluster's Hive Service (1.0.1000) version. Please let me know if it's possible.

Thanks in advance..!

**Comment by vthorwat** [comment]
Hey @mgorsk1, can you please tell me whether Amundsen will support the **1.0.1000** version of **Apache Hive**?

Thanks in advance..!

**Comment by mgorsk1** [comment]
I've responded here @vthorwat https://github.com/amundsen-io/amundsen/issues/1310
