### ISSUE TITLE
Does Amundsen supports Apache Hive 1.2.1000 version ??

### ISSUE THREAD

**Issue by vthorwat** [amundsen-io/amundsen#1310]
Hello Guys,

We were planning to explore Amundsen in our environment.

Currently, we have Hortoworks Cluster (HDP Cluster) where below are the Services that we want to integrate.

Hive Verison -- 1.2.1000

Can you please confirm, above versions are compatible with Amundsen?

If yes, then I would like to integrate Amundsen into our environment and explore its functionalities.

Thanks,
Vinod

**Comment by mgorsk1** [comment]
Hi,

It should work with 1.2.1 according to Atlas documentation: https://atlas.apache.org/1.2.0/Hook-Hive.html

**Comment by feng-tao** [comment]
are you using databuilder or atlas for backend?

**Comment by vthorwat** [comment]
@feng-tao - We want to try with Atlas as backend but as described by @mgorsk1 our atlas is on 0.8 version which is not compatible with Amundsen, So we were trying to use Hive version - 1.2.1000  

But still not figured it how to work with the current Amundsen version

Please suggest if there is some other way for this
