### ISSUE TITLE
The helm repo stable/elasticsearch is deprecated

### ISSUE THREAD

**Issue by dingobar** [amundsen-io/amundsen#1325]
The helm repository that the amundsen helm chart depends on for elasticsearch is officially deprecated and moved, see https://github.com/helm/charts/pull/21955. Using the supported one is probably easy as I assume the api hasn't changed much. I'm willing to contribute down the line but for now I'm just filing this issue as a heads up.

**Comment by feng-tao** [comment]
yes, would be great if you could contribute the change
