### ISSUE TITLE
how to point presto_view_metadata_extractor.py at the underlying db? will it capture column lineage between views?

### ISSUE THREAD

**Issue by rsaw4** [amundsen-io/amundsen#1327]
I am brand new user evaluating Amundsen. My goal is to harvest lineage from Presto views. ie viewA select from viewB which selects from viewC, including column transformations between them.

2 Qs:
1. does presto_view_metadata_extractor.py facilitate this lineage?
2. what steps to run to try it? not sure where db host/credentials are to be inputted

**Comment by tooptoop4** [comment]
cc @sewardgw @feng-tao

**Comment by feng-tao** [comment]
presto_view_metadata_extractor is mainly used to extract the metadata of presto views from hive metastore. Getting lineage will be a separate process (e.g doing sql parsing using tool like https://github.com/uber/queryparser on your presto query log)

**Comment by tooptoop4** [comment]
@feng-tao why do I need query log? I want the lineage on the views (ie viewA selects from tables and tableY) that presto_view_metadata_extractor pushed to Amundsen

**Comment by feng-tao** [comment]
> @feng-tao why do I need query log? I want the lineage on the views (ie viewA selects from tables and tableY) that presto_view_metadata_extractor pushed to Amundsen

I guess I was talking about general lineage extraction. But in your case, in theory, we could extract the view to table lineage from the view ddl. But that requires some efforts.

**Comment by tooptoop4** [comment]
maybe https://github.com/wzy816/sql-lineage-analyser or https://github.com/pinterest/querybook/blob/b33e390725f5d7ecfb93071b226c495ae4272f73/querybook/server/lib/query_analysis/lineage.py can help

**Comment by tooptoop4** [comment]
https://github.com/tooptoop4/presto_sql_lineage
