### ISSUE TITLE
new docker release of 'metadata' 

### ISSUE THREAD

**Issue by tooptoop4** [amundsen-io/amundsen#1339]
when will be new docker release of 'metadata' ?
want this change: https://github.com/amundsen-io/amundsen/pull/1103

**Comment by feng-tao** [comment]
cc @mgorsk1

**Comment by mgorsk1** [comment]
I am on it, will get back to you once the release is done.

**Comment by mgorsk1** [comment]
I've just released metadata `3.8.1` and pushed it to docker hub. feel free to use it @tooptoop4
