### ISSUE TITLE
DEFAULT_LINEAGE_URL ? is there a column lineage graph?

### ISSUE THREAD

**Issue by tooptoop4** [amundsen-io/amundsen#1340]
1. what should DEFAULT_LINEAGE_URL be set to in config-default.ts?
2.  is there a column lineage graph? i only found link for table lineage in the ui

**Comment by feng-tao** [comment]
that's the old lineage implementation which supports linking lineage UI from external (e.g dbt lineage, vendor lineage). Not sure if we still need that. cc @danwom @allisonsuarez @Golodhros
