### ISSUE TITLE
Bug: Atlas proxy sometimes returns `-1` for `results_count` in `_atlas_basic_search` which breaks the frontend

### ISSUE THREAD

**Issue by lmk-coles** [amundsen-io/amundsen#1343]
I have noticed that sometimes Atlas will return `-1` as an approximate count of results along with results entities.

However, the search service returns this value to the front end service, which ends up breaking the search results display (ie: no results shown, when there actually results returned from Atlas).

## Expected Behavior
The search service should return a value which allows the front end to display the results.

## Current Behavior
The front end will not show any results if `-1` is returned as `results_count`. (Despite there being results returned in the response data as well).

## Possible Solution
```
    if results_count == -1:
        results_count = len(search_results.entities)
```

## Steps to Reproduce

1. **Note:** This is somewhat data deterministic, I am unsure of how Atlas decides `approximateResults`
2. Perform a search using the Amundsen user interface
3. There may be no results shown in the interface
4. However, the search service has actually found some results from atlas but is also returning `results_count` as `-1`

## Context
Search does not work correctly.

## Your Environment
* Amunsen version used: git (`cb9fcdc339a994c7e427f80cc20903198e974d72`)
* Data warehouse stores: Apache Atlas (using `hbase` and `solr`)

**Comment by feng-tao** [comment]
cc @mgorsk1

**Comment by mgorsk1** [comment]
HI @lmk-coles, could you give me little more info on two things:
- which version of Atlas are you using @lmk-coles ? I think at some point we've fixed the search results count in Atlas codebase.
- is this happening for basic or advanced search ?

If you are using older version of Atlas and suffer from this issue then I encourage you to submit a PR to resolve this. It should be pretty easy to do something like `results_count = max(0, len(search_results.entities)` to be on a safe-side.

**Comment by lmk-coles** [comment]
Hi @mgorsk1 sorry I haven't had the chance to work on this, however I will try and get back to you with the Atlas git version we are using...
