### ISSUE TITLE
Would like an example on how to use TableColumnStats model to get column stats integrated during loading metadata

### ISSUE THREAD

**Issue by raajpackt** [amundsen-io/amundsen#1350]
There are several examples of loaders in the databuilder/example folder. It would be good if there was a sample code for getting TableColumnStats from a database.
For example an example postgres loader fetching max/min/null values for columns in all tables.

**Comment by mgorsk1** [comment]
that's a nice idea, feel free to submit a PR!

**Comment by raajpackt** [comment]
can this issue stay open as a feature request?

**Comment by chonyy** [comment]
+1 Having the same request here.
