### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by benrifkind** [amundsen-io/amundsen#1352]
## Expected Behavior or Use Case

A SalesForceExtractor that pulls the SalesForce object Metadata into ~~Hive~~ Amundsen.  This would populate the `databuilder.models.table_metadata.TableMetadata` object.

## Service or Ingestion ETL

databuilder

## Possible Implementation

Could use the [simple-salesforce](https://github.com/simple-salesforce/simple-salesforce) Python library to fetch the SalesForce object metadata. And then it would be a simple matter of extracting the necessary fields. There would be a configuration that would allow the user to specify which SalesForce objects they wanted to fetch since from my experimentation there are a lot of SalesForce objects (200+) that I don't care about.

The client returns a JSON blob from requesting information about a SalesForce object and you can extract ColumnMetaData like so:

```python
# sort the fields by name because Amundsen requires a sort order for the columns and I did
# not see one in the response
fields = sorted(data["fields"], key=lambda x: x["name"])
columns = [
    ColumnMetadata(
        name=f["name"],
        description=f["inlineHelpText"],
        col_type=f["type"],
        sort_order=i,
    )
    for i, f in enumerate(fields)
]

```

## Context

This is to help me in auto-documentation. We copy the SalesForce data daily into Hive tables. These are what are used for analytics and other ETL jobs. Getting the SalesForce objects into Amundsen gives me an easy way to propagate the SalesForce object comments into the Hive tables which are the objects that are actually used at my company and which would now be better documented.

**Comment by sewardgw** [comment]
Hey @benrifkind really like the idea of expanding databuilder to support bringing in Salesforce data. Could you elaborate on what you mean with this statement, in particular around how Hive plays in here?

> A SalesForceExtractor that pulls the SalesForce object Metadata into Hive.

**Comment by benrifkind** [comment]
@sewardgw That was a typo on my part. I fixed it.

**Comment by benrifkind** [comment]
I can take this on. Working branch is here: https://github.com/benrifkind/amundsen/tree/salesforce-extractor

**Comment by benrifkind** [comment]
This feature was merged
