### ISSUE TITLE
Feature Proposal - Oracle Extractor

### ISSUE THREAD

**Issue by savioteles** [amundsen-io/amundsen#1354]
## Expected Behavior or Use Case
An extractor that load Oracle database metadata into Amundsen. 

## Service or Ingestion ETL
Ingestion ETL (databuilder module)

## Possible Implementation
I have developed the code to make easy the Oracle database integration with Amundsen following the Amundsen code pattern. It is attached below in the zip file. There are two files with the extractor code and one file with a sample example.

[oracle-amundsen.zip](https://github.com/amundsen-io/amundsen/files/6834799/oracle-amundsen.zip)

## Context
It is important to have a standard extractor for Oracle to facilitate the integration of metadata from Oracle tables into Amundsen. Oracle is one of the world's leading databases.

**Comment by mgorsk1** [comment]
Thanks for opening issue and taking an action! Would you mind submitting PR with this code? It would be easier to review it and eventually merge to main. Thanks!

**Comment by savioteles** [comment]
Done! https://github.com/amundsen-io/amundsen/pull/1357

Tks, @mgorsk1
