### ISSUE TITLE
Bug: Slack access link isn't working 

### ISSUE THREAD

**Issue by supratim-mukh** [amundsen-io/amundsen#1366]
Hey There! 
I am trying to access the slack channel of Amundsen but it says the link doesn't exist and to contact the owner of the channel. I tried to join it via the website and Git link.  

## Expected Behavior
It should have instead asked me to signup for the workspace. 

## Current Behavior
Link is no longer active.  

## Possible Solution
Creating a new link

## Steps to Reproduce
1. Go to Amundsen website
2. Click on join slack
3. Link is no longer active page appears

**Comment by feng-tao** [comment]
thanks for reporting. I will update the link.

**Comment by feng-tao** [comment]
@supratim-mukh could you try with the link shown in  https://github.com/amundsen-io/amundsen/pull/1367 and let me know if it works?

**Comment by feng-tao** [comment]
@supratim-mukh feel free to reopen the issue if it is still the case.
