### ISSUE TITLE
Hierarchical 'data catalogue' navigation within the frontend

### ISSUE THREAD

**Issue by cpnat** [amundsen-io/amundsen#138]
I believe it would be useful to offer alternative navigation options within the Amundsen frontend (as many users will naturally understand data in the way which is structured within the database).

In it's simplest form this would be a hierarchical view (under the 'Browse' page), exposing the existing nodes/relations persisted in Neo4J (Database -> Cluster -> Schema -> Table). This could be extended by allowing a user to return to the hierarchical view from within the page for a given table_detail entity.

This has been discussed in further detail within the Slack thread here:- https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1571252882070700

**Comment by jornh** [comment]
Related issue https://github.com/lyft/amundsen/issues/275

**Comment by IslamAzab** [comment]
@cpnat How can I access this Slack link to follow up on the discussion?

**Comment by feng-tao** [comment]
@IslamAzab you could join slack in https://github.com/lyft/amundsen

**Comment by Golodhros** [comment]
In Lyft's team opinion, we think that a good faceted search would cover this use case partially. That's the direction we will try to follow, but we are not closed to anybody else in the community to take over this and ship it.
