### ISSUE TITLE
Bug Report:  FAQ On Capturing all GA Outdated

### ISSUE THREAD

**Issue by cooper6581** [amundsen-io/amundsen#1381]
## Expected Behavior
When going to https://www.amundsen.io/amundsen/faq/#how-to-capture-all-google-analytics it shouldn't point to a dead link, and it shouldn't embed `<script async src="https://my-proxy-domain/MASKEDGOOGLETAGAMANAGERURL"></script>` in the HTML

## Current Behavior
NA

## Possible Solution
Update FAQ with current instructions on how to capture all GA data

## Steps to Reproduce
NA

## Screenshots (if appropriate)
NA

## Context
It hasn't, just noticed it while reading the docs.

## Your Environment
NA

**Comment by feng-tao** [comment]
do you want to upstream the fix?
