### ISSUE TITLE
Question: databuilder atlas elasticsearch sync

### ISSUE THREAD

**Issue by tomassatka** [amundsen-io/amundsen#1419]
Hi all, trying to install helm chart with metadata fetched from apache atlas and search connected to elasticsearch as suggested here: [https://www.amundsen.io/amundsen/search/docs/atlas-search](https://www.amundsen.io/amundsen/search/docs/atlas-search) 

Mainly section 'We suggest using Elasticsearch as backend for Atlas janusgraph (it’s possible with latest Atlas version) and additionally sync data with databuilder to have indices compatible with Amundsen Elasticsearch Search Proxy.' 

So if i understand it correctly, apache atlas uses own elasticsearch as graph index search engine and then amundsen is configured to use own elasticsearch for search service and between is expected to setup a databuilder to sync the data running in cronjob. 

Can you please share where such databuilder config/image/or simply more information can be found on how to set it up?

**Comment by mgorsk1** [comment]
Hi @tomassatka! Let me answer those questions:
1. amundsen helm-chart currently does not support Atlas deployment, you'd need to deploy amundsen configured to use Atlas and deploy Atlas with underlying dbs separately
2. indeed the suggested approach is to configure Atlas to use ES as janusgraph backend and then sync data to another ES index (which is Amundsen specific). The example script can be found here: https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/scripts/sample_atlas_search_extractor.py

**Comment by tomassatka** [comment]
@mgorsk1 **thank you**
1. yes that is exactly what i did
2. i am relatively new to python and by first look i thought i see script connecting to atlas rest api and then syncing it to amundsen elastic search. 
```python
# atlas config
atlas_url = 'localhost'
atlas_port = 21000
atlas_protocol = 'http'
atlas_verify_ssl = False
atlas_username = 'admin'
atlas_password = 'admin'
atlas_search_chunk_size = 200
atlas_details_chunk_size = 10
```
honestly i expected endpoints of 2 elasticsearch services therefore the atlas config confuses me here. 

What does the script do in principle? And can it be leveraged as single point of data load into amundsen search/metadata service?

**Comment by mgorsk1** [comment]
Hi, so in the nutshell this scripts hits atlas rest api, pulls metadata and loads in to ES Index (Amundsen specific one). Janusgraph indices are not accessed directly - every bit of communication (push/pull) with Atlas goes through API.

Lastly, in theory (and in real life) both janusgraph and Amundsen specific indices can be created within the same ES instance, nothing limits you from such approach (at the end of a day there is no specific reason nor requirement to have separate ES instances for each). That's how we in ING deployed Atlas and Amundsen.

**Comment by tomassatka** [comment]
@mgorsk1 awesome explanation. 
Is there any requirement to use elasticsearch as index search backend in atlas? If the communication goes over atlas api could atlas use solr? 

As first try i started atlas with external cassandra and external solr. 
Because of bug: https://issues.apache.org/jira/browse/ATLAS-3993 i switched from cassandra to embedded hbase and replace solr with elasticsearch for better connection to amundsen. But if the connection goes to by rest api is that switch necessary?

Thx again for all info

**Comment by mgorsk1** [comment]
There is no requirement to use es over solr. We do because we didn't want to maintain two different services.

As for Cassandra we have both Atlas and Cassandra running as separate deployments on k8s. I think @dechoma might remember something about the issue you mention which I think is only related to audit (switching off audit would have to be required for Atlas to work with Cassandra).

I don't recommend using anything embedded for prod use case.

**Comment by tomassatka** [comment]
@mgorsk1 can you please help me with creation of python docker image?

I am trying to setup Dockerfile but i think i miss some steps

```
FROM python:3
WORKDIR /databuilder
COPY . .
RUN pip3 install -r requirements.txt
ENTRYPOINT ["python3"]
CMD ["./example/scripts/sample_atlas_search_extractor.py"]
```

when i jump afterwards to container i setup `export PYTHONPATH=$PYTHONPATH:/databuilder`
however i am getting:

```
root@a8d5ec4476cc:/databuilder# python3 -S example/scripts/sample_atlas_search_extractor.py 
Traceback (most recent call last):
  File "/databuilder/example/scripts/sample_atlas_search_extractor.py", line 10, in <module>
    from databuilder.extractor.atlas_search_data_extractor import AtlasSearchDataExtractor
  File "/databuilder/databuilder/extractor/atlas_search_data_extractor.py", line 14, in <module>
    from atlasclient.client import Atlas
ModuleNotFoundError: No module named 'atlasclient'

```

what do i miss? is it something related to setup.py? even if i run setup.py build & setup.py install i am getting the same...

**Comment by mgorsk1** [comment]
you'll also need to install atlas specific deps.

try

```RUN pip3 install -e ".[atlas]" ```

instead of 

```
RUN pip3 install -r requirements.txt
```

**Comment by tomassatka** [comment]
@mgorsk1 build looks good.. have to try the cronjob

@dechoma any idea what is wrong with cassandra connection?

with atlas 2.1.0 i tried to bind:
  - name: cassandra
    version: 7.6.5
    repository: https://charts.bitnami.com/bitnami

```
  atlas-application.properties: |
    atlas.graph.storage.backend=cql
    atlas.graph.storage.hostname={{ .Release.Name }}-cassandra
    atlas.graph.storage.cassandra.keyspace=JanusGraph
    atlas.graph.storage.username=cassandra
    atlas.graph.storage.password=cassandra
    atlas.graph.storage.clustername={{ .Values.config_parameter.cassandra_clustername  }}
    atlas.graph.storage.port={{ .Values.config_parameter.cassandra_storage_port  }}

    atlas.EntityAuditRepository.impl=org.apache.atlas.repository.audit.CassandraBasedAuditRepository
    atlas.EntityAuditRepository.keyspace=atlas_audit
    atlas.EntityAuditRepository.replicationFactor=1
```

but getting:
```
Caused by: java.lang.RuntimeException: org.apache.atlas.AtlasException: com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host atlas-cassandra/10.217.4.3:9042: Host atlas-cassandra/10.217.4.3:9042 requires authentication, but no authenticator found in Cluster configuration
        at org.apache.atlas.service.Services.start(Services.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by tomassatka** [comment]
databuilder looks good. Tried on openshift 4 cluster. Have to add data to verify though..
$>oc logs amundsen-1628507220-hvbkj
WARNING:databuilder.publisher.elasticsearch_publisher:received no data to upload to Elasticsearch!

**Comment by dechoma** [comment]
@tomassatka 
it looks like the CassandraBasedAuditRepository implementation currently does not support cassandra authentication

https://github.com/apache/atlas/blob/master/repository/src/main/java/org/apache/atlas/repository/audit/CassandraBasedAuditRepository.java#L221

you can try to disable audit by using `atlas.EntityAuditRepository.impl=org.apache.atlas.repository.audit.NoopEntityAuditRepository`

**Comment by tomassatka** [comment]
@dechoma thanks. that did the trick and i was able to start atlas with cassandra

**Comment by tomassatka** [comment]
Hi @mgorsk1 
Just to be sure. To which version of apache atlas is this extractor dedicated: https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/scripts/sample_atlas_search_extractor.py

apache atlas 1.x
apache atlas 2.x

or will work for both?

Thx

**Comment by mgorsk1** [comment]
It should work with Atlas 2.x starting with rev 21b15842fd74bc91910b2d8901dbea57769065d0 (Atlas has very weird and rare release model)
