### ISSUE TITLE
Support for loading views from schemas in addition to tables

### ISSUE THREAD

**Issue by raajpackt** [amundsen-io/amundsen#1420]
Current databuilder can be used to load table information from sources into amundsen.
Request a feature or workaround to load view information as well. 
Please let me know if there is an existing implementation already.

**Comment by mgorsk1** [comment]
You can add views as well. There is dedicated Table property 'is_view' to distinguish them from regular tables in ui. You can check sample data CSV files cause there are some view entities defined there.

**Comment by feng-tao** [comment]
+1 on @mgorsk1 . going to close this ticket now assuming the question has been answered.

**Comment by raajpackt** [comment]
@mgorsk1 
https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/dags/postgres_sample_dag.py

I was trying out this dag to load views.
What changes do i need to make in the dag to load views?
I can see it loads only the tables in the given schemas by default and not the views.

**Comment by raajpackt** [comment]
Can we get some replies in this thread?
@feng-tao  I  do not think the answer by @mgorsk1 answered the question. The example only shows you to load views from the csv. I think generally an user would expect an example of how to load views from a database connection right? 
Maybe a dag or script dataloader example?
If we want more people to use amundsen we could well start with more examples. I will be having to understand a lot of internal underlying code to figure out how the view loading works and would appreciate some abstraction from you! :)

**Comment by feng-tao** [comment]
@raajpackt you could take a look at https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/hive_table_metadata_extractor.py#L40 as an example which the hive extractor exacts view as well.
