### ISSUE TITLE
wrong path to Values.yaml

### ISSUE THREAD

**Issue by lotnikov** [amundsen-io/amundsen#1423]
Hello, 
here https://github.com/amundsen-io/amundsen/tree/main/amundsen-kube-helm/README.md 
a command to install helm chart is specified
helm install my-amundsen ./templates/helm --values impl/helm/dev/values.yaml

but the path impl/helm/dev/ doesn't exist

## Expected Behavior
helm chart installation

## Current Behavior
values.eml not exists

## Possible Solution
I used --values ./templates/helm/values.yaml but I am not sure if this is correct

## Steps to Reproduce
git clone <amundsen project>
cd amundsen-kube-helm/
helm install my-amundsen ./templates/helm --values impl/helm/dev/values.yaml

## Your Environment
windows 10, minikube latest, kubectl latest, helm latest

**Comment by cbcoutinho** [comment]
I have the same issue - can we reopen this issue?
