### ISSUE TITLE
Oracle databuilder sample loader refer to missing extractor config  OracleMetadataExtractor.USE_CATALOG_AS_CLUSTER_NAME

### ISSUE THREAD

**Issue by ak93-ak93** [amundsen-io/amundsen#1425]
## Expected Behavior

Remove
        f'extractor.oracle_metadata.{OracleMetadataExtractor.USE_CATALOG_AS_CLUSTER_NAME}': True,

## Current Behavior

Fail saying that there is no property in the extractor that supports
OracleMetadataExtractor.USE_CATALOG_AS_CLUSTER_NAME
## Possible Solution

1) Remove from sample
2 ) add property  OracleMetadataExtractor.USE_CATALOG_AS_CLUSTER_NAME to config of oracle extractor
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by mgorsk1** [comment]
cc @savioteles
