### ISSUE TITLE
Installation instrctions - 404 page not found

### ISSUE THREAD

**Issue by lotnikov** [amundsen-io/amundsen#1434]
Hello, 
When you try to read the documentaion, "getting started" or "installation guideline" https://www.amundsen.io/amundsen/docs/installation.md
you get 404

## Expected Behavior
installation instructions should apper

## Current Behavior
404 page not found

## Steps to Reproduce
follow https://www.amundsen.io/amundsen/docs/installation.md

**Comment by lotnikov** [comment]
the same is for
https://www.amundsen.io/amundsen/docs/architecture.md

**Comment by delwaterman** [comment]
https://www.amundsen.io/amundsen/installation/
https://www.amundsen.io/amundsen/architecture/

Look like the correct URLs

**Comment by delwaterman** [comment]
This is still an issue
