### ISSUE TITLE
"Advanced search" returning "Page index out of bounds for available matches" error

### ISSUE THREAD

**Issue by corridordigital** [amundsen-io/amundsen#1439]
I'm using Amundsen with neo4j and ES, with a standard docker-compose installation.
The data is ingested in neo4j (visible through browser) & Elasticsearch (visible through API calls), and I can find it and diplay it using the homepage searchbar.

## Expected Behavior

Advanced Search must work and return results when there are assets that match the search keywords. This actually used to work with older versions (the one on the `master` branch, for example).

Using "*" as a keyword in the Source bar should return every asset.

## Current Behavior

I get a `Page index out of bounds for available matches` error everytime.

## Possible Solution

The error is raised by the frontend service ([here](https://github.com/amundsen-io/amundsen/blob/f085dbe0cbf32cff5971ee1ca6afd057008b33f2/frontend/amundsen_application/static/js/pages/SearchPage/index.tsx#L145)).

## Steps to Reproduce

1. Standard docker installation
2. Data ingestion from a PostgreSQL database 
3. Using the search bar on the homepage works well  
4. Doing an "Advanced Search" returns the error 

### Homepage search : 

![Capture d’écran du 2021-08-12 15-13-18](https://user-images.githubusercontent.com/5432086/129203688-6067e63f-66a4-476f-ad9e-8012a4e0112c.jpg)

### Advanced search : 

![image](https://user-images.githubusercontent.com/5432086/129202739-d4539e1e-3198-4b22-a032-039e6853e654.png)

## Context

Issue appeared with newer versions of Amundsen. It happens evey single time.

## Your Environment

* Amunsen version used: newest (`main` branch)
* Data warehouse stores:
* Deployment (k8s or native): native (docker-compose on ubuntu)

**Comment by corridordigital** [comment]
Reproduced the issue on Debian 10.
I am using `miniconda3` for the Python environment.

**Comment by corridordigital** [comment]
I've been comparing amundsenfrontend DEBUG logs between the newest version (defective), and an older fully functioning version (3.6.0). 
I've been focusing on the logs generated by Advanced Search queries, and more specifically on the data received by the frontend service for displaying. The data is stored in JSON strings, and the `keyword_args_json` looks like this : 

```json
{
    "filters": {
        "database": [
            "*"
        ]
    },
    "search_term": "",
    "page_index": 0,
    "search_type": "update_filter"
}', output='{
    "search_term": "",
    "msg": "Success",
    "tables": {
        "page_index": 0,
        "results": [
            {
               <METADATA ABOUT MY DB>
        ],
        "total_results": null
    },
    "status_code": 200
}
```
I've noticed something very suprising in this data : `total_results": null`, which is **wrong**in my case, as I can see in the results JSON. In y older version, this has a non-null value, equal to the number of search hits. 

`total_results `happens to be used to raise the `Page index out of bounds for available matches` error, in[ here](https://github.com/amundsen-io/amundsen/blob/f085dbe0cbf32cff5971ee1ca6afd057008b33f2/frontend/amundsen_application/static/js/pages/SearchPage/index.tsx#L145) : 

 ```js
if (page_index < 0 || startIndex > total_results) {
      return (
        <div className="search-list-container">
          <div className="search-error body-placeholder">
            {PAGE_INDEX_ERROR_MESSAGE}
          </div>
        </div>
      );
    }
```

**Comment by mgorsk1** [comment]
which version of ES and Amundsen you are using? Might be some mismatch after introducing support for ES7

cc @verdan

**Comment by corridordigital** [comment]
It's a fresh install, all versions are the latest.

**Comment by corridordigital** [comment]
> which version of ES and Amundsen you are using? Might be some mismatch after introducing support for ES7
> 
> cc @verdan

Hi, 
It's a fresh install, with the lastest versions : 
* elasticsearch:7.13.3
* Amundsen : 
  * frontend :  3.12
  * search : 2.10
  * metadata : 3.9
  * builder : 6.0.2
  * common : 0.19.0
  * gremlin : 0.0.12 
  * rds : 0.0.5

**Comment by corridordigital** [comment]
@mgorsk1 I can't identify the exact origin of the problem, but I can provide logs & evidence.

**Comment by corridordigital** [comment]
I tried using older (6) and newer versions of ES through changing my `docker-amundsen.yml` file. They don't seem to be compatible with the other services.

**Comment by dewes** [comment]
Also having same problem, fresh git clone, using sample_data_loader.py. (After facing same problem on  #1442).

Data is on Neo4j and in Elasticsearch as results shows up on direct query:

> curl -X GET "http://localhost:5001/search?query_term=test"
{"results": [{"key": "hive://gold.test_schema/test_table1", "database": "hive", "display_name": "test_schema.test_table1", "total_usage": 1330, "name": "test_table1", "badges": [{"tag_name": "beta"}], "schema": "test_schema", "column_names": ["col1", "col2", "col3", "col4", "col5"], "column_descriptions": [], "description": "1st test table", "programmatic_descriptions": ["### Quality Report:\n--- \nIpsus enom. Ipsus enom ipsus lorenum.\n---\n[![Build Status](https://api.travis-ci.com/amundsen-io/amundsendatabuilder.svg?branch=master)](https://travis-ci.com/amundsen-io/amundsendatabuilder)", "**Size**: 50T\n\n**Monthly Cost**: $5000"], "cluster": "gold", "schema_description": "test schema description", "tags": [{"tag_name": "tag1"}, {"tag_name": "tag2"}, {"tag_name": "low_quality"}, {"tag_name": "expensive"}], "last_updated_timestamp": 1570230473}, {"key": "dynamo://gold.test_schema/test_table2", "database": "dynamo", "display_name": "test_schema.test_table2", "total_usage": 520, "name": "test_table2", "badges": [{"tag_name": "npi"}, {"tag_name": "json"}], "schema": "test_schema", "column_names": ["col4", "col3", "col2", "col1"], "column_descriptions": [], "description": "2nd test table", "programmatic_descriptions": ["**Size**: 1T\n\n**Monthly Cost**: $50"], "cluster": "gold", "schema_description": null, "tags": [{"tag_name": "cheap"}, {"tag_name": "recommended"}], "last_updated_timestamp": 1070230473}, {"key": "hive://gold.test_schema/test_table3", "database": "hive", "display_name": "test_schema.test_table3", "total_usage": 0, "name": "test_table3", "badges": [], "schema": "test_schema", "column_names": ["col1"], "column_descriptions": [], "description": "3rd test", "programmatic_descriptions": [], "cluster": "gold", "schema_description": "test schema description", "tags": [{"tag_name": "needs_documentation"}], "last_updated_timestamp": null}, {"key": "hive://gold.test_schema/test_view1", "database": "hive", "display_name": "test_schema.test_view1", "total_usage": 0, "name": "test_view1", "badges": [], "schema": "test_schema", "column_names": ["col1"], "column_descriptions": [], "description": "1st test view", "programmatic_descriptions": [], "cluster": "gold", "schema_description": "test schema description", "tags": [{"tag_name": "tag1"}], "last_updated_timestamp": null}, {"key": "delta://gold.test_schema/delta_test_table", "database": "delta", "display_name": "test_schema.delta_test_table", "total_usage": 0, "name": "delta_test_table", "badges": [], "schema": "test_schema", "column_names": ["col2", "col1"], "column_descriptions": [], "description": "test table for delta", "programmatic_descriptions": [], "cluster": "gold", "schema_description": null, "tags": [{"tag_name": "delta"}], "last_updated_timestamp": null}, {"key": "hive://gold.test_schema/test's_table4", "database": "hive", "display_name": "test_schema.test's_table4", "total_usage": 0, "name": "test's_table4", "badges": [], "schema": "test_schema", "column_names": [], "column_descriptions": [], "description": "4th test", "programmatic_descriptions": [], "cluster": "gold", "schema_description": "test schema description", "tags": [{"tag_name": "needs_documentation"}], "last_updated_timestamp": null}]}

And on Neo4j:

![image](https://user-images.githubusercontent.com/649884/129825025-450e15af-dd43-4618-926e-71d473ffaa4e.png)


On frontend it shows up while writing search terms, like:

![image](https://user-images.githubusercontent.com/649884/129825184-4ba0fd9f-093d-4f8a-a3ed-be80fec67bab.png)

But nothing on results search page, just "Page index out of bounds for available matches"

![image](https://user-images.githubusercontent.com/649884/129825244-b74cc41b-6a07-462f-8e9b-32848f5849f5.png)

**Comment by tmihordea-gpsw** [comment]
I am also getting the same error as https://github.com/amundsen-io/amundsen/pull/1386#issuecomment-890064706 
It looks related to this breaking change in elasticsearch 7: https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

**Comment by dfall-gh** [comment]
Hi everyone,

@corridordigital  : same issue for me with same version of Amundsen (Tried on Firefox and Chrome).

Indeed, I noticed that the error was raised  [here](https://github.com/amundsen-io/amundsen/blob/f085dbe0cbf32cff5971ee1ca6afd057008b33f2/frontend/amundsen_application/static/js/pages/SearchPage/index.tsx#L145):

```
if (page_index < 0 || startIndex > total_results) {
     return (
       <div className="search-list-container">
         <div className="search-error body-placeholder">
           {PAGE_INDEX_ERROR_MESSAGE}
         </div>
       </div>
     );
   }

```

In the Amundsen logs (docker compose lauch in debug mode), I saw results for my advanced search.

From the browser Debug Console I got :
- **total_results** : null (despite the fact we can see results in the JSON)
- **page_index** : 0
- **startIndex** : 1

So 
```if (page_index < 0 || startIndex > total_results)``` is **TRUE**.

So this bug seems to appear because of **total_results** with **NULL value.**

Thank everyone for your help on this.

**Comment by verdan** [comment]
I believe this is because of the older version of Amundsen search. have you guys tried this using local docker-compose?, as I can see the version on the search package on docker hub is a couple of months older. 

In any way, I will release a new version of the search, that should fix this problem for you all.

**Comment by verdan** [comment]
https://github.com/amundsen-io/amundsen/pull/1445

**Comment by corridordigital** [comment]
Hi @verdan :wave: 
I tested your last commit from the `vm-versions-upgrade` branch, and the search works great ! 
Can't wait to see it merged on `main`.
Thanks a lot,

**Comment by verdan** [comment]
sweet! merged....

**Comment by dewes** [comment]
Also confirm it's working now! Thanks for the very fast patch!

![image](https://user-images.githubusercontent.com/649884/129935373-fd7c52f9-240b-49e0-be85-f92e356aa05f.png)

**Comment by dfall-gh** [comment]
Works also fine for me !

Thank your for the fix , really appreciated.
