### ISSUE TITLE
Bug Report: Issue with sample data loader

### ISSUE THREAD

**Issue by mroovaz** [amundsen-io/amundsen#1442]
I have run into an issue while deploying sample data for amundsen as described in the guide: https://www.amundsen.io/amundsen/installation/

## Expected Behavior
Sample data should be loaded without issues.

## Current Behavior
While running cmd: `\amundsen\databuilder>py example/scripts/sample_data_loader.py`
Sample data loader fails in run_csv_job with 'example/sample_data/sample_application.csv' file.
Following error message may be searched by other users: 
`TypeError:_ __init__() got an unexpected keyword argument 'exec_date'`

## Possible Solution
It looks like csv_extractor is trying to read header row from the csv file. As a quick workaround to load sample data, I removed header row from sample_application.csv file.

**Comment by a-cid** [comment]
This is the commit that removed the exec_date parameter: 
https://github.com/amundsen-io/amundsen/commit/1a75a2f16648e73698b8b6b21641ed8d2e4c5c0e

A temporary workaround is to run `pip install amundsen-databuilder==6.0.1` instead of `python3 setup.py install`
