### ISSUE TITLE
Bug Report - Lineage does not look good when there are lots of upstream and downstream

### ISSUE THREAD

**Issue by apalmercari** [amundsen-io/amundsen#1443]
Lineage does not look good when there are lots of upstream and downstream

https://amundsenworkspace.slack.com/archives/C01A87A5EUU/p1627859139002600
https://amundsenworkspace.slack.com/archives/C01A87A5EUU/p1627859139002600

## Current Behavior
Lineage shows cluttered view
<img width="1124" alt="Screen Shot 2021-08-02 at 8 15 21" src="https://user-images.githubusercontent.com/62978713/129429794-e3684472-49b8-4548-8c3c-d9097a635220.png">

## Steps to Reproduce
1. Create lineage data with lots of tables (100+) either downstream or upstream
2.
3.
4.

## Your Environment

* Amunsen version used: 
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by feng-tao** [comment]
cc @danwom 
Have you tried the table list for lineage as well?

**Comment by feng-tao** [comment]
also cc @Golodhros

**Comment by apalmercari** [comment]
Table list works ok.

**Comment by apalmercari** [comment]
Hi Team, any updates on this

**Comment by markgrover** [comment]
Hi @apalmercari we are aware of this - the lineage UI is pretty alpha. It's on our roadmap, but can't share a timeline just yet. In the meantime, I'd recommend using the list view. Thanks for filing the bug report.

**Comment by brunsgaard** [comment]
@markgrover maybe you can give another update on this issue?

**Comment by markgrover** [comment]
Hi @brunsgaard, no update. We did make an internal update to the UI at stemma.ai but haven't thought about contribution at the moment. We used React Flow for the new version but I am not sure if that's helpful to you.

**Comment by ozandogrultan** [comment]
Hi @markgrover, any plans on contributing React Flow implementation to the open-source? We are facing this issue as well and would be great to see it fixed!

**Comment by markgrover** [comment]
No updates, unfortunately. My recommendation is to use the list view in the meantime. Patches greatly welcome here.

**Comment by ozandogrultan** [comment]
@markgrover Can you please share the documentation/link on how to enable "list view"? We were not aware of this option.

**Comment by markgrover** [comment]
More details in this thread:
https://amundsenworkspace.slack.com/archives/C01A87A5EUU/p1631302036018100

**Comment by paularmand** [comment]
@markgrover maybe better post the details here, since Amundsen's slack plan currently does not retain history for messages and files longer than 90 days.

**Comment by ozandogrultan** [comment]
Hi @Golodhros, this issue still remains open for us actually. Is there any plan to fix it in the near future?
