### ISSUE TITLE
Feature Proposal: add create/update users method

### ISSUE THREAD

**Issue by amommendes** [amundsen-io/amundsen#1479]
Currently, we do not have implemented in the Gremlin and Neptune proxy the method to create or update Amundsen users, which turns difficult to use features related to users, as ownership, popular table, and so on.

## Expected Behavior or Use Case

Create users programmatically, for example, as implemented [here](https://www.stemma.ai/blog/how-to-setup-oidc-authentication-in-amundsen)

## Example Screenshots (if appropriate):
[Method](https://github.com/amundsen-io/amundsen/blob/45d96dd8cfa0a92c06b0b84b791150a5603dbeee/metadata/metadata_service/proxy/gremlin_proxy.py#L1017) to be implemented 
![image](https://user-images.githubusercontent.com/11285563/131925570-5a64760a-510b-47d1-94ee-62bad0c20b09.png)

**Comment by feng-tao** [comment]
Make sense, feel free to upstream the change. Thanks!

**Comment by amommendes** [comment]
keep fresh
