### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by ChristalJohn** [amundsen-io/amundsen#1497]
Hello Amundsen Community Team,

Im trying to implement OKTA Authentication on Metadata API.
The API page crashes with below error after the OKTA authentication is done

Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server.

I do see in the logs that callback request is made multiple time, and each time the URL length keeps growing.

Below are the configs which we are using for starting up Metadata:

export FLASK_APP_MODULE_NAME=flaskoidc
export FLASK_APP_CLASS_NAME=FlaskOIDC
export SQLALCHEMY_DATABASE_URI='sqlite:///sessions.db'
export FLASK_OIDC_SQLALCHEMY_DATABASE_URI='sqlite:///sessions.db'
export FLASK_OIDC_WHITELISTED_ENDPOINTS="status,healthcheck,health"
export OIDC_CLIENT_SECRETS='/home/...../metadata_client_secrets.json'
export FLASK_OIDC_SECRET_KEY='base-flask-oidc-secret-key'
export FLASK_OIDC_CLIENT_SECRETS='/home/...../metadata_client_secrets.json'
export OVERWRITE_REDIRECT_URI='http://<metadata_alb>/apidocs/authorization-code/callback'
export OIDC_CALLBACK_ROUTE='/authorization-code/callback'
export OIDC_DEBUG=True
export FLASK_OIDC_WHITELISTED_ENDPOINTS='api.healthcheck'

We added below Redirect URL s in OKTA config as well:
http://<metadata-alb>/apidocs/ 
http://<metadata-alb>/apidocs/authorization-code/callback

Redirect URL is updated in the client.json as well along with token details:

  "redirect_uris": ["http://<metadata-alb>/apidocs/authorization-code/callback"]
}}

Any pointers to fix this issue will be very helpful.

Thanks!

**Comment by verdan** [comment]
@ChristalJohn what version of `flaskoidc` are you using? 
here is the tutorial on how to enable OIDC in Amundsen. Please let me know if you face the same issue again. 
https://medium.com/stemma/how-to-setup-oidc-authentication-in-amundsen-47f704345c1

The config/env variables you are using are outdated. 
More details about the configs here: https://github.com/verdan/flaskoidc#readme

**Comment by ChristalJohn** [comment]
@verdan 
Thank you for picking this up.

Below flask versions are installed in the env.:
flask-oidc               1.4.0
flaskoidc                0.2.3

I will go through the URLs shared and revert here.

**Comment by verdan** [comment]
yes, please make sure to use the newer version of `flaskoidc` i.e., 1.0.2 and follow the how-to steps.

**Comment by ChristalJohn** [comment]
@verdan 

I implemented new configs suggested in below URLs also updated flaskoidc version 1.0.2 across frontend, search and metadata:
https://medium.com/stemma/how-to-setup-oidc-authentication-in-amundsen-47f704345c1
https://github.com/verdan/flaskoidc#readme

For frontend, I was able to get to the OKTA Login page, below are configs used:

export FRONTEND_SVC_CONFIG_MODULE_CLASS='amundsen_application.oidc_config.OidcConfig'
export OIDC_CLIENT_SECRETS='/home/../client_secrets.json'
export FLASK_APP_MODULE_NAME='flaskoidc'
export FLASK_APP_CLASS_NAME='FlaskOIDC'
export FLASK_OIDC_PROVIDER_NAME='okta'
export FLASK_OIDC_SCOPES='openid email profile offline_access'
export FLASK_OIDC_CLIENT_ID='0xxx7'
export FLASK_OIDC_CLIENT_SECRET='WxxN'
export FLASK_OIDC_REDIRECT_URI='/auth/'
export FLASK_OIDC_CONFIG_URL='https://.../.well-known/openid-configuration'


client_secrets.json for frontend :

{"web": {
  "issuer": "https://..7",
  "auth_uri": "https://..e",
  "client_id": "0..7",
  "client_secret": "W..N",
  "token_uri": "https://..n",
  "token_introspection_uri": "https://..t",
  "userinfo_uri": "https://...o",
  "redirect_uris": ["http://../authorization-code/callback"]
}}


But Metadata API page keeps crashing before it gets to the okta login page:

400 Error
Identity Provider: Unknown
Error Code: invalid_request
Description: The 'redirect_uri' parameter must be a Login redirect URI in the client app settings: https://...oktapreview.com/admin/app/oidc_client/instance/0...7#tab-general

Config used:
export OIDC_CLIENT_SECRETS='/home/..../metadata_client_secrets.json'
export FLASK_APP_MODULE_NAME='flaskoidc'
export FLASK_APP_CLASS_NAME='FlaskOIDC'
export FLASK_OIDC_PROVIDER_NAME='okta'
export FLASK_OIDC_SCOPES='openid email profile offline_access'
export FLASK_OIDC_CLIENT_ID='0...7'
export FLASK_OIDC_CLIENT_SECRET='W...N'
export FLASK_OIDC_REDIRECT_URI='/auth/'
export FLASK_OIDC_CONFIG_URL='https://...oktapreview.com/oauth2/a..7/.well-known/openid-configuration'

metadata_client_secrets.json had below

{"web": {
  "issuer": "https://..7",
  "auth_uri": "https://e..e",
  "client_id": "0..7",
  "client_secret": "W..N",
  "token_uri": "https://../v1/token",
  "token_introspection_uri": "https://../v1/introspect",
  "userinfo_uri": "https://../v1/userinfo",
  "redirect_uris": ["http://../apidocs/authorization-code/callback"]
}}


In OKTA, in Login Sign-in redirect URIs below are the entries, frontend and metadata API urls respectively:

http://e....d/auth/ 
http://m....d/apidocs/auth/

Please let me know, if any of the above configs are incorrectly set, since I'm getting redirect URI error.

**Comment by verdan** [comment]
@ChristalJohn a few things:
- `OIDC_CLIENT_SECRETS` is deprecated and not being used anymore. Please remove the env variables along with the .json files. 
- `FLASK_OIDC_REDIRECT_URI` must match the one you specified within the OKTA. In case of metadata the `FLASK_OIDC_REDIRECT_URI` should be `/apidocs/auth/`, so the metadata configs should look like: 
```
export FLASK_APP_MODULE_NAME='flaskoidc'
export FLASK_APP_CLASS_NAME='FlaskOIDC'
export FLASK_OIDC_PROVIDER_NAME='okta'
export FLASK_OIDC_SCOPES='openid email profile offline_access'
export FLASK_OIDC_CLIENT_ID='0...7'
export FLASK_OIDC_CLIENT_SECRET='W...N'
export FLASK_OIDC_REDIRECT_URI='/apidocs/auth/'
export FLASK_OIDC_CONFIG_URL='https://...oktapreview.com/oauth2/a..7/.well-known/openid-configuration'
```

**Comment by ChristalJohn** [comment]
@verdan 

Thanks for the pointers, its very helpful.
I was able to get through the OKTA login page for metadata API.

However, once the login is complete, i encounter 400 URL not found error,  on the URL tab I can see the API URL without /apidocs/ appended to it, if I add apidocs the API page loads fine.

![image](https://user-images.githubusercontent.com/91137301/134661563-a17d1771-e12b-4e4f-bf05-2a2ad864df74.png)



Thanks!

**Comment by ChristalJohn** [comment]
@verdan 

Configs used for metadata:

export FLASK_APP_MODULE_NAME='flaskoidc'
export FLASK_APP_CLASS_NAME='FlaskOIDC'
export FLASK_OIDC_PROVIDER_NAME='okta'
export FLASK_OIDC_SCOPES='openid email profile offline_access'
export FLASK_OIDC_CLIENT_ID='0...7'
export FLASK_OIDC_CLIENT_SECRET='W...N'
export FLASK_OIDC_REDIRECT_URI='apidocs/auth/'
export FLASK_OIDC_CONFIG_URL='https://...oktapreview.com/oauth2/a..7/.well-known/openid-configuration'

In OKTA, Login Sign-in redirect URIs below are the entries

http://e....d/auth/     (Frontend URL)
http://m....d/apidocs/auth/           (Metadata URL)

Thanks!

**Comment by verdan** [comment]
@ChristalJohn after successful login, `flaskoidc` simply redirects you to the `/` instead of `/apidocs` which is the endpoint of your metadata. and you don't have `/` endpoint available, this is why it is returning 404. 
I will update the `flaskoidc` package to give an option to overwrite redirect uri after login today, and release a new version. Give me a few hours to add this support.

**Comment by verdan** [comment]
@ChristalJohn can you please update your `flaskoidc` to the latest version i.e., 1.0.4
https://pypi.org/project/flaskoidc/1.0.4/

and then use the [FLASK_OIDC_OVERWRITE_REDIRECT_URI](https://github.com/verdan/flaskoidc#flask_oidc_overwrite_redirect_uri) in your metadata configuration to match with your endpoint.

**Comment by verdan** [comment]
this issue was fixed. 
https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1632287479054200
