### ISSUE TITLE
Popular Resources not being populated after searching

### ISSUE THREAD

**Issue by ssmails** [amundsen-io/amundsen#1516]
1. Install Amundsen with docker installation, with Neo4j backend, using instructions at https://github.com/amundsen-io/amundsen/blob/main/docs/installation.md
2. Search at localhost:5000 for test
3. Search successful, select one of the tables Eg: test
_schema.test_table1
4. Add new tag to this table and query it multiple times using the Advanced search (query by tag option) or main Search. 
5. Go to localhost:5000, Check the Popular resources. It is not populated with this table name, but still empty. Expectation would be to have this populated with the frequently searched table, as mentioned in docs

Add tag "bookmark" to table and search
<img width="1397" alt="Screen Shot 2021-10-04 at 1 06 28 PM" src="https://user-images.githubusercontent.com/43550938/135917601-494d115d-f953-49c6-b573-f5c9e274dea3.png">
.

Popular resources not populated with table searched.
<img width="614" alt="Screen Shot 2021-10-04 at 12 59 41 PM" src="https://user-images.githubusercontent.com/43550938/135917654-698522a4-b8ab-4cf3-9c52-017668743346.png">

**Comment by feng-tao** [comment]
You need to ingest usage into the metadata store.

**Comment by ssmails** [comment]
@feng-tao I believe this is being done already as part of amundsen/databuilder/example/scripts/sample_data_loader.py
    run_csv_job('example/sample_data/sample_column_usage.csv', 'test_usage_metadata',
                'databuilder.models.table_column_usage.ColumnReader')

Please confirm. Thanks

**Comment by kenny-shopback** [comment]
@ssmails, there are some configs control it.
```
POPULAR_RESOURCES_PERSONALIZATION = False
POPULAR_RESOURCES_COUNT = 10  # top resources
```
Using `Advanced search` is not right way to identify populated resource. You should query by: "SELECT .. FROM table..", or sth like that. Then push table query usage count to neo4j.

**Comment by ssmails** [comment]
@kenny-shopback Thanks for the explanation, Is there a REST API for <Then push table query usage count (model ColumnReader) to neo4j.> ? @feng-tao Assuming we would need to do this externally to Amundsen, each time that we reference a tables column for which we have metadata ingested into Amundsen.

**Comment by kenny-shopback** [comment]
@ssmails , you can check example in `sample_column_usage.csv`

**Comment by ssmails** [comment]
@feng-tao @kenny-shopback 

So, I added some additional logs to check that the configs are ok. Although the configs seem ok, I am unable to see the table in the Popular tables.
This was also tried with the official image amundsendev/amundsen-frontend:3.12.0, prior to modifying on my local setup.

Steps followed -
1. Start all containers with docker-amundsen.yml using neo4j backend (When running locally replace frontend image in this file)
2. Start Airflow DAG to run an ETL with script sample_data_loader.py, ensure new values are populated in neo4j. Attached snapshot for neo4j values.
3. Check the Popular Resources section to see if table is populated.

frontend logs - 

2021-10-06T23:03:55+0000.599 [INFO] __init__.create_app:68 (10:MainThread) - Created app with config name amundsen_application.config.TestConfig
2021-10-06T23:03:55+0000.599 [INFO] __init__.create_app:69 (10:MainThread) POPULAR_RESOURCES_PERSONALIZATION True
2021-10-06T23:03:55+0000.600 [INFO] __init__.create_app:70 (10:MainThread) - POPULAR_RESOURCES_COUNT 4
2021-10-06T23:03:55+0000.600 [INFO] __init__.create_app:71 (10:MainThread) - Using metadata service at http://amundsenmetadata:5000
2021-10-06T23:03:55+0000.601 [INFO] __init__.create_app:72 (10:MainThread) - Using search service at http://amundsensearch:5000

API response when getting the popular_resources.
2021-10-06T23:12:54+0000.490 [DEBUG] connectionpool._make_request:461 (9:MainThread) - http://amundsenmetadata:5000 "GET /popular_resources/test_user_id?limit=4&types=table HTTP/1.1" 200 41

sample_column_usage.csv

database,cluster,schema,table,column,user_email,read_count
dynamo,gold,test_schema,test_table2,col1,soald9@example.org,8
dynamo,gold,test_schema,test_table2,col1,toald9@example.org,18
dynamo,gold,test_schema,test_table2,col1,chrisc@example.org,508

noe4j populated with updated read count values

<img width="1324" alt="Screen Shot 2021-10-06 at 4 59 16 PM" src="https://user-images.githubusercontent.com/43550938/136299897-31a51488-af94-404d-937d-df900a2f2c84.png">
