### ISSUE TITLE
Table view not rendering after changes to column list

### ISSUE THREAD

**Issue by mgorsk1** [amundsen-io/amundsen#1517]
After latest changes to column list in table view it doesn't render properly. The assumption about the cause was confirmed by building amundsen from hash 527fda4b87415a0b9343f53b51f783fa42481f95 (last commit on main before changes to column list).

## Expected Behavior
Table view renders correctly

## Current Behavior
Table view shows blank screen

## Steps to Reproduce
1. Build frontend locally from main and run local deployment of whole amundsen stack
2. populate sample data
3. try to view any table details in ui

## Screenshots (if appropriate)
Errors in console:

![image](https://user-images.githubusercontent.com/5680655/136074320-b3bbd564-8a98-4c5d-94b0-507c1cfdb45a.png)

![image](https://user-images.githubusercontent.com/5680655/136074475-4a60e755-f58b-4e6f-ad83-445f4c8c4f68.png)

## Context
n/a

## Your Environment
- discovered when developing amundsen locally

**Comment by mgorsk1** [comment]
cc @danwom @Golodhros @allisonsuarez

**Comment by mgorsk1** [comment]
indeed the fix you've mentioned did not work, issue was found on latest main

**Comment by danwom** [comment]
This is kind of silly but I think we need to add a concept of `column_index` so we can refer back to the original column in order since `sort_order` is apparently an unreliable field. Either that or cancel the whole passing of indexes and instead use the column name as an identifier instead.

**Comment by zjph90** [comment]
Has this issue been resolved?
