### ISSUE TITLE
Can't enable OIDC using Helm installation

### ISSUE THREAD

**Issue by raman-nbg** [amundsen-io/amundsen#1521]
I want to enable OIDC using the Helm Chart. After some search in the issues here, [I found that amundsen is providing special oidc images](https://github.com/amundsen-io/amundsen/issues/813). But there is no image for `amundsen-search` image. I also verified this on [docker hub](https://hub.docker.com/u/amundsendev).

So, I tried to use the image `amundsendev/amundsen-search:2.11.1`. But with this image I get the following error during startup.

```
Traceback (most recent call last):
  File "search_service/search_wsgi.py", line 15, in <module>
    application = create_app(config_module_class=config_module_class)
  File "/app/search_service/__init__.py", line 55, in create_app
    importlib.import_module(FLASK_APP_MODULE_NAME),
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flaskoidc'
```

This is the configuration that I'm using:
```yaml
frontEnd:
  image: amundsendev/amundsen-frontend-oidc
  imageTag: 3.12.0
metadata:
  image: amundsendev/amundsen-metadata-oidc
  imageTag: 3.9.0
search:
  image: amundsendev/amundsen-search
  imageTag: 2.11.1

oidc:
  enabled: true
  configs:
    FLASK_OIDC_PROVIDER_NAME: auth0
    FLASK_OIDC_CLIENT_ID: "..."
    FLASK_OIDC_CLIENT_SECRET: "..."
    FLASK_OIDC_CONFIG_URL: "https://my-domain.auth0.com/.well-known/openid-configuration"
```

## Expected Behavior
I would expect that there is oidc-image for the search component.

## Current Behavior
search service can not start with oidc enabled due to the error described above.

## Steps to Reproduce
1. clone the amundsen repository containing the helm chart
2. override the values in `values.yaml` with the values from above
3. run `helm install amundsen 

## Context
I want to use Amundsen on GKE with OIDC. Currently, this is not possible.

## Your Environment
* Amundsen version used: See yaml configuration
* Deployment (k8s or native): K8s

**Comment by raman-nbg** [comment]
> Even I am facing the same issue. Have you found the fix ?

No, couldn't find any solution. It looks like that Amundsen is not really interested to run on kubernetes.

**Comment by raman-nbg** [comment]
Why isn't there an official docker image of the search component that includes oidc? At least, this is available for metadata and Frontend. Why not for search?

**Comment by benrifkind** [comment]
I am also curious why is oidc necessary for the metadata/search services? I would have thought that we only require oidc for the frontend which is the service that handles requests from users.

**Comment by verdan** [comment]
@raman-nbg the reason there is no search oidc image is that no one implemented this. 🤷  Happy to review your PR if you like to give it a go, and implement the same logic for search. 

@benrifkind the reason some organizations require the OIDC for search/metadata is that they want to expose the metadata and search endpoints to be used in other applications, hence securing those endpoints.
