### ISSUE TITLE
BigQuery Last Updated fields extractor ( Databuilder)

### ISSUE THREAD

**Issue by Javier162380** [amundsen-io/amundsen#1551]
## Expected Behavior or Use Case
Create a Bigquery last update extractor similar to the one built for Hive. I have already built this extractor for the company I am working for and I will like to add this extractor to Amundsen so the community could use it in the future.

## Service or Ingestion ETL
Databuilder

**Comment by Javier162380** [comment]
Thanks! I create this PR with the extractor code https://github.com/amundsen-io/amundsen/pull/1558. Although now I am having issues to create the tests, I need some help on how to mock the BQ Client, as the package I am using it is different from the package, other BigQuery extractor uses

**Comment by sagar-raythatha** [comment]
@Javier162380 
I have also implemented for my company, but using different approach. I have done below changes for the same:

file: bigquery_metadata_extractor
change: added below line in function  _retrieve_tables along with other metadata items.
`last_updated_timestamp=table.get('lastModifiedTime', '')`


file: table_metadata
change: added  class TimestampMetadata and referenced it in a TableMetadata like we do for any other object.

would like to see which one would be the better approach?

**Comment by Javier162380** [comment]
Hey @sagar-raythatha!

Nice suggestion, I create a separate BigQueryInterface, following the approach that the project follows with the BigqueryUsage and BigQueryWatermark interfaces.

Here is the PR, as you mention, maybe your approach is better than mine as it requires fewer lines of code change.

What about discussing this topic in this PR https://github.com/amundsen-io/amundsen/pull/1558
