### ISSUE TITLE
Advanced search column bug

### ISSUE THREAD

**Issue by sagar-raythatha** [amundsen-io/amundsen#1566]
This issue is exactly same as https://github.com/amundsen-io/amundsen/issues/863 which is closed.  However even after using the latest version repo I am facing the same issue, can anyone please help here?

**Expected Behavior**
On advanced search column when searching for revenue or revenue* it should return all tables with Revenue, RevenueUSD, etc.

**Comment by sagar-raythatha** [comment]
Can anyone guide, how to resolve it?

**Comment by sagar-raythatha** [comment]
Hi All,

I could resolve this issue by removing `.raw` from the `TABLE_MAPPING` object. I understand that .raw is the type of keyword and simple analyzer haven't applied on that.


https://github.com/amundsen-io/amundsen/blob/main/search/search_service/proxy/elasticsearch.py#L45

**Comment by feng-tao** [comment]
CC @allisonsuarez

**Comment by sagar-raythatha** [comment]
@feng-tao Do you think this should be applied to global repo? As of now I have done this change in my implementation.
