### ISSUE TITLE
What [AWS] ElasticSearch version(s) are supported Amundsen Search Service?

### ISSUE THREAD

**Issue by ecc256** [amundsen-io/amundsen#1584]
Could somebody clarify, please?

[Amundsen Search Service](https://github.com/amundsen-io/amundsen/blob/main/search/README.md) from Jun 23, 2021 says:
**Requirements**
Python >= 3.6
elasticsearch **6.x** (currently it **doesn't support 7.x**)

[Feature Proposal: Search service ElasticSearch AWS (and potentially other) authentication support](https://github.com/amundsen-io/amundsen/issues/1135) from May 20, 2021
goes over AWS ElasticSearch related configuration, but didn't specify Elasticsearch version...

**Is it still elasticsearch 6.x only?**

**Comment by NiravLangaliya** [comment]
it supports elasticsearch  7.x as well

**Comment by ecc256** [comment]
> it supports elasticsearch 7.x as well

Does it support both 
**elasticsearch 7.x from elasticsearch**
and
**Amazon OpenSearch Service (successor to Amazon Elasticsearch Service) running elasticsearch 7.x**
?

The reason I ask:
Newer elasticsearch python client versions detect AWS elasticsearch 7.x and refuse to work with it...

**Comment by NiravLangaliya** [comment]
We have ES Version : Elasticsearch 7.10  on AWS.
