### ISSUE TITLE
Provide a Amundsen demo playground environment

### ISSUE THREAD

**Issue by chonyy** [amundsen-io/amundsen#1607]
As I was evaluating the pros and cons between Amundsen and DataHub. I found out that there's a [demo environment](https://demo.datahubproject.io/) provided by [DataHub](https://datahubproject.io/docs/demo). It could really help the users quickly explore the features without building their own environment following the quick start guide.

I think it would be nice if Amundsen could also provide one!

## Expected Behavior or Use Case
Provide a simple demo environment in the documentation site for users to explore.

## Service or Ingestion ETL
Demo playground

## Possible Implementation
Host a simple demo with the data ingested by [sample data loader](https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/scripts/sample_data_loader.py)

**Comment by mgorsk1** [comment]
That's very good idea, do you have proposition of any free hosting that would handle this? It'd be easy to get free ES from bonsai.io but not sure about the rest of components.

**Comment by chonyy** [comment]
Hi @mgorsk1 , I actually know nothing about the free resources 😅
I'm just thinking that it would be nice to have one such demo environment.
Maybe the community could help host one with Docker compose or Kubernetes?
