### ISSUE TITLE
sample_dbt_loader is failing with KeyError 

### ISSUE THREAD

**Issue by IrinaSel** [amundsen-io/amundsen#1615]
## Expected Behavior
Load dbt metadata

## Current Behavior
Failing with KeyError

## Possible Solution
manifest file changes its version/schema and it could be that the original solution was build for v1, but not v4 is available.

## Steps to Reproduce
$ python3 example/scripts/sample_dbt_loader.py

## Screenshots (if appropriate)
![Screenshot 2021-12-08 at 17 57 58](https://user-images.githubusercontent.com/9607710/145250491-cde32c20-3b81-471d-a1c9-f009810cd2c5.png)

## Context
dbt loader is not working

## Your Environment
* Amunsen version used: databuilder 6.4.1
* Data warehouse stores: redshift 
* Deployment (k8s or native): local
* Link to your fork or repository:

**Comment by vinicius-ch** [comment]
Any update on this matter?
I'm facing the same problem.

**Comment by teoria** [comment]
hi 
can you try with this pr ?
https://github.com/amundsen-io/amundsen/pull/1653

**Comment by falkzeh** [comment]
The solution @teoria provided fixed the issue for me!

**Comment by teoria** [comment]
@feng-tao
