### ISSUE TITLE
[Security] Workflow search_pull_request.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Ale0x78** [amundsen-io/amundsen#1627]
The workflow search_pull_request.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by feng-tao** [comment]
@Ale0x78 do you have an example on how to change https://github.com/amundsen-io/amundsen/blob/main/.github/workflows/search_pull_request.yml#L16 to use the latest one that has CVE fix?
