### ISSUE TITLE
Watermarks for Hive table views not available

### ISSUE THREAD

**Issue by lkrishnan-cn** [amundsen-io/amundsen#1628]
## Expected Behavior
I have ingested Hive source, but we would like the feature to see how old/new our data is.

## Current Behavior
Here is what the view looks like now:
<img width="557" alt="Screenshot 2021-12-20 at 5 06 50 PM" src="https://user-images.githubusercontent.com/88760743/146761936-9f7b056d-1704-4c10-b7e0-377f1d19e3f6.png">

## Steps to Reproduce

1.Ingest any Hive source from amundsen hive ingestion library.

## Your Environment

* Amunsen version used: 3.9
* Data warehouse stores: Hive
* Deployment (k8s or native):  k8s
* Link to your fork or repository:

**Comment by chonyy** [comment]
Not sure if the date range is the feature that you are expecting. It's actually about the data itself, which is the date of the partition if you partition the data by date.
![image](https://user-images.githubusercontent.com/44046550/147181525-f3e655e8-c77b-4cdf-953e-d4346182ee63.png)
[Link to the Slack thread](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1638384540157300)
