### ISSUE TITLE
Bug Report - Error from "docker-compose -f docker-amundsen-atlas.yml up"

### ISSUE THREAD

**Issue by cheji02** [amundsen-io/amundsen#1650]
Env: Docker running on Windows 10

Steps: 
1. Download Amundsen on 12/15/2021 and successfully installed/deployed Amundsen with Neo4j;
2. Stop Amundsen;
3. Download Amundsen into another folder to install/deploy Amundsen with Atlas;
4. From the new Amundsen folder run "docker-compose -f docker-amundsen-atlas.yml up"
5. Result with the following error:

 => ERROR [stage-1 7/7] RUN pip3 install -e .                                                                      5.6s
------
 > [stage-1 7/7] RUN pip3 install -e .:
#21 1.703 Obtaining file:///app
#21 5.292     ERROR: Command errored out with exit status 1:
#21 5.292      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/app/setup.py'"'"'; __file__='"'"'/app/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qhcfveei
#21 5.292          cwd: /app/
#21 5.292     Complete output (10 lines):
#21 5.292     /bin/sh: 1: npm: not found
#21 5.292     ERROR:root:npm must be available
#21 5.292     /bin/sh: 1: npm: not found
#21 5.292     /app/setup.py:30: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
#21 5.292       logging.warn('Installation of npm dependencies failed')
#21 5.292     WARNING:root:Installation of npm dependencies failed
#21 5.292     /app/setup.py:31: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
#21 5.292       logging.warn(str(e))
#21 5.292     WARNING:root:Command '['npm install']' returned non-zero exit status 127.
#21 5.292     error in amundsen-frontend setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
#21 5.292     ----------------------------------------
#21 5.292 WARNING: Discarding file:///app. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#21 5.293 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#21 5.482 WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
#21 5.482 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip3 install -e .]: exit code: 1
ERROR: Service 'amundsenfrontend' failed to build : Build failed

![image](https://user-images.githubusercontent.com/3838324/148233905-9ebf015a-5cfb-4c59-9beb-237e2f1fd410.png)

**Comment by feng-tao** [comment]
cc @mgorsk1 any idea

**Comment by cheji02** [comment]
able to run "docker-compose -f docker-amundsen.yml up" in the same environment without any error.  
I wonder if the Amundsen docker containers created from the previous "docker-compose ..." run need to be removed first before running "docker-compose -f docker-amundsen-atlas.yml up" on that same host.

**Comment by mgorsk1** [comment]
you could always try by doing `docker-compose -f docker-amundsen-atlas.yml build --no-cache` to test it

**Comment by cheji02** [comment]
Just tested that "... build --no-cache" option as suggested and received the exact same error

**Comment by matwalk** [comment]
This looks like the same error message here: https://github.com/amundsen-io/amundsen/issues/1317
Seems to be related to the setup.py of frontend and Windows.

I have the same error when running this: docker-compose -f docker-amundsen-local.yml build

**Comment by cheji02** [comment]
Confirmed "docker-compose -f docker-amundsen-local.yml build" had same error.

But "docker-compose -f docker-amundsen.yml up/build" worked without error.

**Comment by matwalk** [comment]
Yes, I think it's because docker-amundsen.yml use an image
![image](https://user-images.githubusercontent.com/46995425/149640486-edd3a8b6-b865-408d-afea-4ba3e6085788.png)


Contrary to docker-amundsen-atlas.yml and docker-amundsen.yml which has to build it :
![image](https://user-images.githubusercontent.com/46995425/149640543-daeac1c0-d1fd-4ce0-8759-156727b4d92d.png)

**Comment by matwalk** [comment]
The last comment of fforever14, to change "FROM python:3.7-slim" to "FROM nikolaik/python-nodejs:python3.7-nodejs12-slim" in the Dockerfile.frontend.local file seems to resolve the error of npm.

But I still have the error: "error in amundsen-frontend setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers."

**Comment by esperancaleonardo** [comment]
Same here
