### ISSUE TITLE
Search broken after introducing latest changes

### ISSUE THREAD

**Issue by mgorsk1** [amundsen-io/amundsen#1652]
## Expected Behavior
Deploying Amundsen locally from latest main is broken - search service is not compatible with frontend service.

## Current Behavior
While searching 405 error is returned.

![image](https://user-images.githubusercontent.com/5680655/148556309-c8f9b816-a404-4f0d-8903-0baf755116a9.png)

## Steps to Reproduce

1. docker-compose -f docker-compose-local.yml build --no-cache
2. docker-compose -f docker-compose-local.yml up -d
3. load sample data (sample_data_loader for neo4j)
4. go to incognito mode
5. search in UI

## Your Environment

* Amunsen version used: latest main
* Data warehouse stores:
* Deployment (k8s or native): local
* Link to your fork or repository:

**Comment by mgorsk1** [comment]
cc @allisonsuarez @dkunitsk

**Comment by allisonsuarez** [comment]
Latest version of FE is compatible with the new search, this is the latest release for FE that works with the latest search https://github.com/amundsen-io/amundsen/releases/tag/frontend-4.0.0

**Comment by Rohan1-23** [comment]
Hi @mgorsk1 @allisonsuarez 

I tried with frontend image - 4.0.0 and search image 3.0.0. And searching is broke. I think it's compatibility issue.

**Comment by zjph90** [comment]
I am having this issue also. I have built frontend and search images from the same (latest) distribution.  I am getting the following error from the frontend:

> [DEBUG] connectionpool._make_request:465 (9:MainThread) - http://amundsensearch:5000 "POST /v2/search HTTP/1.1" 200 3
> [INFO] v1._search_resources:132 (9:MainThread) - {}
> [ERROR] v1._search_resources:155 (9:MainThread) - Encountered exception: {'status_code': ['Missing data for required field.'], 'page_index': ['Missing data for required field.'], 'msg': ['Missing data for required field.'], 'results_per_page': ['Missing data for required field.'], 'results': ['Missing data for required field.']}

It looks like the request to the Search service comes back successfully (code 200) but the results payload is empty.

**Comment by mgorsk1** [comment]
for me no, what helped was cloning Amundsen repo again

**Comment by zjph90** [comment]
Well it looks like I may not have the same issue that Mariusz was having. I tried re-cloning the repo and I still get the same behaviour. I've rebuilt from various releases and can see my problem is introduced exactly at the frontend-4.0.0/search-3.0.0 release. Before that it works fine. Afterwards I get the issue.
I'm thinking it may be related to the elasticsearch service we are using - OpenSearch on AWS. If I run with the docker-compose-local.yml (using elasticsearch:7.13.3) and load the sample data then everything seems to work fine. But when I point it at our datastore - nope.

The only things that are different are the elasticsearch version and our actual data.

**Comment by allisonsuarez** [comment]
@zjph90 are you also getting a 405?

**Comment by allisonsuarez** [comment]
oh hold up, "missing data for required field" is a marshmallow issue, do you also have the latest version of amundsen-common?

**Comment by allisonsuarez** [comment]
Do you have any configuration that is setting the ES client to be something other than `ELASTICSEARCH_V2`? https://github.com/amundsen-io/amundsen/blob/main/search/search_service/config.py#L18

**Comment by allisonsuarez** [comment]
Also what happens if you hit search with a request directly?

**Comment by zjph90** [comment]
Hi @allisonsuarez  - apologies for this. My bad. I did indeed have custom config which did not have the correct proxy client. We had implemented our own AWS connection and I see we now have _AwsSearchConfig_. I was able to point to this and now search works fine. Thanks for your time.
