### ISSUE TITLE
Bug Report -- elasticsearch on AKS deployment error - bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

### ISSUE THREAD

**Issue by rajendra-tamboli** [amundsen-io/amundsen#1668]
Ran the following commands before installing Amundsen on AKS - 
helm repo add elasticsearch https://helm.elastic.co
helm dependency update

We are getting the following error and pods are continuously giving CrashLoopbackoff error due to below reason - 
bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

Is there a way to fix this for Kubernetes deployment via helm ?

While checking the value.yaml file for sysctlVmMaxMapCount value under the following --- 
amundsen-kube-helm\templates\helm\charts\elasticsearch-7.13.4\elasticsearch

sysctlVmMaxMapCount: 262144

Is there anything needs to be done to fix this issue?

**Comment by rajendra-t** [comment]
hi Team, has anyone faced issues deploying the Elasticsearch pods on K8's? can you please suggest?
