### ISSUE TITLE
ColumnStatistics Info Text

### ISSUE THREAD

**Issue by AykCanDem** [amundsen-io/amundsen#1686]
## Expected Behavior or Use Case
Currently, there are 3 types for ColumnStatistics Info text.
1) If you give same start and end time, (Ex: Sep 11, 2019)
info text is `"Stats reflect data collected on Sep 11, 2019 only. (daily partition)"`
2) If you give different start and end time
info text is `Stats reflect data collected between Sep 11, 2019 and Oct 21, 2019.`
3) If you dont provide start or end time
info text is `Stats reflect data collected over a recent period of time.`

I would suggest to have 4th option here which is like
**4)** When you only provide end time
info text is `Stats reflect data collected until Sep 11, 2019`

check: https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/utils/index.spec.ts
lines 678-704

## Possible Implementation
check: https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/utils/index.spec.ts
lines 678-704

## Example Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/15074091/151782629-938d7d3f-09ba-4095-937b-9ee804576f1b.png)

## Context
This feature is needed for the scenario like below.
* You are running databuilder daily for updating columns and tables in amundsen. And the time of execution can be found in amundsen last updated date.
* But, you want to run your column statistics databuilder in different frequency then the above one. (like ones a week). With this feature, you will be able to see when the column statistics run happened.

**Comment by Golodhros** [comment]
What do you think @allisonsuarez?

**Comment by AykCanDem** [comment]
please check: https://github.com/amundsen-io/amundsen/pull/1696

**Comment by mgorsk1** [comment]
Closing as #1696 was merged. Thanks
