### ISSUE TITLE
Update application model

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#169]
Currently the application model(https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/models/application.py) is too tight with:
1. assume Airflow as application
2. assume task_id is hive.schema.table

We should extend it.

**Comment by jornh** [comment]
Great @feng-tao that you already did the the generalizations mentioned above in https://github.com/lyft/amundsendatabuilder/pull/166

One thing the current Neo4j models does not support is describing the relationship of data going *into* an application. That would be useful/needed to build full lineage involving the transformations happening between tables/datasets.

There are multiple ways this could be implemented. A simple option, with what we have got now, might be to add a `direction` in/out parameter on the application table relationships. For backwards compatibility “out” could be default.
