### ISSUE TITLE
RUN sample_deltalake_metadata.py errors out with an AWS S3 exception

### ISSUE THREAD

**Issue by joe-manjiyil** [amundsen-io/amundsen#1701]
I am running the python3 example/scripts/sample_deltalake_metadata.py script to extract information from the databricks cluster. The job shows up on the databricks cluster but after a while throws error. Error is attached below
[Amundsen_error.txt](https://github.com/amundsen-io/amundsen/files/7996495/Amundsen_error.txt)

## Expected Behavior
The local instance of Amundsen dashboard should show the extracted metadata information

## Current Behavior
Currently the job starts running and throws error

## Possible Solution
Not sure about workaround

## Steps to Reproduce
Follow the steps in the link https://github.com/amundsen-io/amundsen/blob/main/docs/installation.md#troubleshooting
## Context
Unable to use Amundsen to create data dictionary

`cluster_key = 'clusterid'
#database = 'delta'
database='default'
# Or set to empty to do all
#schema_list = ['schema1', 'schema2']
schema_list = []`

What should be the clusterid provided in the script.I have provided the ClusterId from the Tags section of databricks cluster

* Deployment (k8s or native): local mac book
* Link to your fork or repository:

**Comment by feng-tao** [comment]
do you run on a databricks spark cluster ?

**Comment by joe-manjiyil** [comment]
> do you run on a databricks spark cluster ?

I am running the amundsen on a local machine with dockers. I connect to databricks cluster hosted on aws using databricks-connect and run the job on the cluster. Data_loader python script runs on the mac book and triggers a job on the databricks cluster.
