### ISSUE TITLE
Elasticsearch 7 documented to not work, but docker-amundsen.yml uses it

### ISSUE THREAD

**Issue by razzius** [amundsen-io/amundsen#1702]
## Expected Behavior
If elasticsearch 7 is supported, which it appears to be as it is used in the [docker compose file here](https://github.com/amundsen-io/amundsen/blob/main/docker-amundsen.yml#L23), the docs should not require Elasticsearch 6.

## Current Behavior
Pages such as https://www.amundsen.io/amundsen/databuilder/ say:

> Requirements
> * Python >= 3.6.x
> * elasticsearch 6.x (currently it doesn’t support 7.x)

which conflicts with the docker-amundsen.yml, which seems to work.

## Possible Solution

Update supported elasticsearch versions to include 7.x, if it is indeed supported. If [Opensearch](https://www.opensearch.org/) is supported as well that would be good to know.

## Screenshots (if appropriate)
<img width="697" alt="image" src="https://user-images.githubusercontent.com/2244895/152444282-6286adca-11fb-48fa-ae2c-7929a0599493.png">

**Comment by mgorsk1** [comment]
Thanks for pointing that out @razzius! Indeed the docs would need update, are you willing to submit PR?

**Comment by mgorsk1** [comment]
docs are up to date now
