### ISSUE TITLE
Bug Report: OIDC module absent

### ISSUE THREAD

**Issue by korjavin** [amundsen-io/amundsen#1724]
After enabling OIDC pod is failing

## Expected Behavior

OIDC auth will be allowed

## Current Behavior
Pod restarts with ERROR:

```ModuleNotFoundError: No module named 'flaskoidc'```

## Possible Solution
Install the module to the docker image

## Steps to Reproduce
1. Enable OIDC
2. Deploy to k8s
3. look at frontend pod status

## Your Environment

* Amunsen version used:  amundsendev/amundsen-frontend:latest 
* Deployment (k8s or native): k8s

**Comment by DantasB** [comment]
Same problem here!

**Comment by korjavin** [comment]
still a problem

**Comment by sambhav8695** [comment]
Hi, I am also facing the same problem
