### ISSUE TITLE
Bootstrap a default version of Amundsen using Docker

### ISSUE THREAD

**Issue by oscarfuquen** [amundsen-io/amundsen#1726]
I follow all steps mentioned on the quick start page https://www.amundsen.io/amundsen/installation/ for the Bootstrap a default version of Amundsen using Docker.

I can see the data was uploaded.

<img width="1330" alt="Screen Shot 2022-02-23 at 1 23 41 pm" src="https://user-images.githubusercontent.com/4535310/155256851-2e945dd9-a6a9-4387-b0c0-d765821c6c1b.png">

All the containers are running.

<img width="635" alt="Screen Shot 2022-02-23 at 1 24 24 pm" src="https://user-images.githubusercontent.com/4535310/155256902-2aaa3cff-9e36-4d75-8333-60652d96f85a.png">

I am trying to execute the step 7 `View UI at http://localhost:5000/ and try to search test, it should return some result.` but I am not getting anything.

<img width="1437" alt="Screen Shot 2022-02-23 at 1 29 04 pm" src="https://user-images.githubusercontent.com/4535310/155257246-65fcc7d7-7228-40b4-8be8-77f25283731b.png">

However, I can see that are two API calls failing.

Request: `GET http://localhost:5000/api/auth_user 500 (INTERNAL SERVER ERROR)`
Response: `{"msg":"Encountered exception: 'NoneType' object has no attribute 'get'"}`

Request: `GET http://localhost:5000/api/metadata/v0/get_last_indexed 500 (INTERNAL SERVER ERROR)`
Response: `{"msg":"Encountered exception: HTTPConnectionPool(host='amundsenmetadata', port=5002): Read timed out. (read timeout=3)","timestamp":null}`

I have request the same API's from the terminal using CURL:

auth_user API
`curl -X GET "http://localhost:5000/api/auth_user"
{"msg":"Encountered exception: 'NoneType' object has no attribute 'get'"}`

get_last_indexed
`curl -X GET "http://localhost:5000/api/metadata/v0/get_last_indexed "
{"msg":"Success","timestamp":0}`

The latter request is returning data but the former it has the same issue.

I found that the issue is in amundsenfrontend trying to request link => this http://amundsenmetadata:5002/user/test_user_id

* Amunsen version used: https://github.com/amundsen-io/amundsen.git
* Local environment

**Comment by esperancaleonardo** [comment]
same here, still trying to understand how to make users work in frontend.

indexed users from sample_data_loader.py in ES seems ok... but get same error in logged test user

![image](https://user-images.githubusercontent.com/26230577/155773501-05e2bf2c-02e9-4e1d-9d91-7e1313615d46.png)

![image](https://user-images.githubusercontent.com/26230577/155773548-cf58a1cc-6a90-4d67-81c2-497c6e29374d.png)
![image](https://user-images.githubusercontent.com/26230577/155773637-646abfa5-1b93-440b-9008-8215a03880c4.png)

**Comment by rylativity** [comment]
@oscarfuquen I am seeing the same issue and can suggest a temporary workaround.  

I haven't dug into it that deeply, but it looks like the frontend is looking for a user with an email value of "test_user_id".  If you look in databuilder/example/sample_data/sample_user.csv, it shows the users that get added when you run sample_data_loader.py.  You can search for all occurrences of one of those email addresses (e.g. "roald.amundsen@example.org") and replace all occurrences of that email with "test_user_id" **prior to running sample_data_loader.py.**

I recommend doing a "docker-compose -f docker-amundsen.yml down -v" to remove the existing volumes with the user data before you rerun the setup steps and sample_data_loader.py.
