### ISSUE TITLE
Bug Report cannot import name 'CypherError' from 'neo4j.exceptions'

### ISSUE THREAD

**Issue by pongpanot0** [amundsen-io/amundsen#1729]
in the sample dataBuilding for neo4js backend 
inthe terminal 
cannot import name 'CypherError' from 'neo4j.exceptions'
![amudsen](https://user-images.githubusercontent.com/61924591/155452966-1ae65c22-132b-4d2e-8006-ef6bfda676e5.jpg)
ThankYou

**Comment by sp31071973** [comment]
Any resolution in this thread?

**Comment by hituhe2** [comment]
Any resolution on this? In many places amundsen refer to it like this,
_from neo4j.exceptions import CypherError_

But in neo4j (4.4.2) , /home/ec2-user/.local/lib/python3.7/site-packages/neo4j/exceptions.py , there is **CypherSyntaxError** and **CypherTypeError**
