### ISSUE TITLE
Bug Report - Schema Descriptions no longer appear in the frontend

### ISSUE THREAD

**Issue by zjph90** [amundsen-io/amundsen#1759]
## Expected Behavior

Have built the latest version (databuilder.6.7.1) using docker-amundsen-local.yml 
Loaded this with sample data (sample_data_loader.py)
Entered "test" into the search box
In the results list  the "test_schema" name in the hive://gold.test_schema results should be underlined and upon hovering show a tooltip with the schema description ("test schema description")

## Current Behavior

The schema names are not underlined. No tooltips are visible.

## Possible Solution

Not a solution but possibly a pointer to the issue - I can see from the frontend output that the search results don't look right
```
         {
            "type":"table",
            "key":"delta://gold.test_schema/delta_test_table",
            "name":"delta_test_table",
            "cluster":"gold",
            "description":"test table for delta",
            "database":"delta",
            "schema":"test_schema",    
            "schema_description":null,  // <- Should not be null  
            "badges":[               
            ],
            "last_updated_timestamp":null
         },
```

## Steps to Reproduce

1. Build recent release locally 
2. Load with sample data
3. Search for "test"
4. Observer lack of tooltip in results list

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/31225/157401975-226a5041-37f3-460e-8e5f-fa468d06f0fb.png)
![image](https://user-images.githubusercontent.com/31225/157402408-3d0934a3-5771-4bf7-a62f-8c747bd33f48.png)

## Context

Our current prod build (common-0.24.1) functions correctly in this regard. This is stopping us from upgrading.

## Your Environment

* Amunsen version used: databuilder-6.7.1 
* Data warehouse stores: sample data
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by feng-tao** [comment]
cc @kristenarmes @allisonsuarez @Golodhros

**Comment by zjph90** [comment]
As far as I know this is still an issue

**Comment by akiratwang** [comment]
Bad bot >:(
