### ISSUE TITLE
User info missing upon login with flaskoidc

### ISSUE THREAD

**Issue by denispoperechny** [amundsen-io/amundsen#1761]
User is not Created automatically upon login with flaskoidc.

The node "User" is not created in database when user gets logged in; "/auth_user" call to backend fails; profile picture (top right corner on UI) stays blank. 
It fixes itself when user marks something as Favorite - at this time both the User node and Follow relation are getting created in database and all issues above are getting fixed.

## Expected Behavior
Profile picture (top right corner on UI) displays user information for newly joined users.

## Current Behavior
- profile picture (top right corner on UI) stays blank
- "/auth_user" call to backend fails
- The node "User" is not created in database when user gets logged in

## Possible Solution
Create the node "User" in database for newly logged in users

## Steps to Reproduce
1. Let new user login to Amundsen with flaskoidc
2. Observe missing user info in top right corner on UI

## Context
If not fixed - we will need to train users to 1. login; 2. mark something as favorite; 3. refresh the page; to get their user profile initiated. 

## Your Environment
- Kubernetes deployment
- Amundsen 3.12.0 + flaskoidc
- Azure AD

**Comment by MehdiSfr** [comment]
Anyone got a fix on this?
