### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by codera21** [amundsen-io/amundsen#1763]
Ability to inject via pandas data frame/
## Expected Behavior or Use Case

Just like we are injecting via CSV files as done in examples we can inject via data frame on the fly.
## Service or Ingestion ETL

Injection ETL
## Context

I think this feature would add more flexibility to Amundsen, especially while we're building a prototype or check the behavior with more fine control and ease.

**Comment by mgorsk1** [comment]
Hey Atul, thanks for this proposal. Can you elaborate on how loading from pandas directly would bring much value over loading from csv generated by pandas to_csv method?

**Comment by codera21** [comment]
It would not bring much value, it would just remove one extra step of to_csv as you have mentioned.
