### ISSUE TITLE
Amundsen frontend fails to open Glue datasets because of session token as CLUSTER_KEY 

### ISSUE THREAD

**Issue by shalseban** [amundsen-io/amundsen#1779]
## Expected Behavior
On the Amundsen frontend when you click on a Dataset of source - Glue, it takes you the table_metadata page of the dataset.

## Current Behavior
Possibly related to this #1383
 
On the Amundsen frontend when you click on a Dataset of source - Glue, it redirects you to the main page. I believe it might have to do with the size or format of the `CLUSTER_KEY`. The `CLUSTER_KEY` for glue dataset is the `session-token`, which might not be url friendly.      

## Possible Solution
Allow `GlueExtractor` to take in another parameter - `AWS_SESSION_TOKEN` and let the `CLUSTER_KEY` be the name of the cluster defined by the user.  

## Steps to Reproduce
1. [ECS Deployment](https://www.amundsen.io/amundsen/installation-aws-ecs/aws-ecs-deployment/)
2. Run [Sample Glue loader](https://github.com/amundsen-io/amundsen/blob/main/databuilder/example/scripts/sample_glue_loader.py)
3. Navigate to the Glue dataset on the amundsen-frontend

**Comment by feng-tao** [comment]
@[shalseban](https://github.com/shalseban) I didn't work with glue, but feel free to post your finding or even pr if you find the fix.
