### ISSUE TITLE
bug: Links in the Announcement html content don't work properly in homepage

### ISSUE THREAD

**Issue by ozandogrultan** [amundsen-io/amundsen#1875]
## Expected Behavior
Links in the Announcement html contents should not be overridden by the Announcement list page navigation

## Current Behavior
When there are links in the Announcement html content, they are overridden by the navigation of the Card component and when they are clicked, announcement list page is shown instead of the link itself.

## Possible Solution
N/A

## Steps to Reproduce

1. Have an Announcement with link in the html content
2. In the homepage, click the link
3. Announcement list page opens up, instead of the link itself

## Screenshots (if appropriate)
N/A

## Context

This causes poor UX for all users.

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by sagar-raythatha** [comment]
+1

**Comment by ozandogrultan** [comment]
This issue still persists, so it is not stale

**Comment by ozandogrultan** [comment]
This issue still persists, so it is not stale

**Comment by ozandogrultan** [comment]
https://github.com/amundsen-io/amundsen/pull/1934 is created for the fix
