### ISSUE TITLE
[databuilder] Typo in new SearchMetadatatoElasticasearchTask 

### ISSUE THREAD

**Issue by akaul** [amundsen-io/amundsen#1889]
## Expected Behavior

While migrating to [New Amundsen Search](https://github.com/amundsen-io/amundsen/blob/main/docs/tutorials/search-v2_1.md), I observed a typo in the class name for [SearchMetadatatoElasticasearchTask](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/task/search/search_metadata_to_elasticsearch_task.py#L28). 

## Current Behavior

The current behavior doesn't impact any end-to-end databuilder behavior at the moment. 

## Possible Solution

Without the typo, the task name should be `SearchMetadatatoElasticsearchTask` or alternatively `SearchMetadataToElasticsearchTask`.

## Steps to Reproduce

https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/task/search/search_metadata_to_elasticsearch_task.py#L28 has a reference to the classname.

## Context

As the task name is used in configuration keys, this could break end users using the library with a lot of name changes further down the line adoption of new Amundsen search grows. 

```
 $ git grep 'SearchMetadatatoElasticasearchTask' | wc -l
      15
```

Publishing a new release with the typo fixed and instructions in the [README](https://github.com/amundsen-io/amundsen/blob/main/docs/tutorials/search-v2_1.md) updated might alleviate this.

## Your Environment

* Amunsen version used: amundsen-databuilder 6.8.0
* Data warehouse stores: N/A
* Deployment (k8s or native): N/A
* Link to your fork or repository: N/A

**Comment by akaul** [comment]
Happy to open up a PR with the changes to fix the typo, but I wanted to report the issue first after going through the Contribution Guidelines.

**Comment by dkunitsk** [comment]
Is there any impact besides that the name contains a typo? A fix for this typo would be backwards incompatible.
