### ISSUE TITLE
Feature Proposal: Implement `create_update_user` function for Metadata Service `gremlin_proxy`

### ISSUE THREAD

**Issue by lucasvieirasilva** [amundsen-io/amundsen#1971]
## Expected Behavior or Use Case

Currently, the function [gremlin_proxy.py#create_update_user](https://github.com/amundsen-io/amundsen/blob/main/metadata/metadata_service/proxy/gremlin_proxy.py#L1022-L1023) is not implemented as it is implemented for [neo4j](https://github.com/amundsen-io/amundsen/blob/main/metadata/metadata_service/proxy/neo4j_proxy.py#L1407-L1444)

This implementation is required when the OIDC with `indexUsers` is configured, in order to create the user details.

## References

Documentation reference: https://www.amundsen.io/amundsen/metadata/docs/configurations/#user_detail_method-optional

Article reference: https://www.stemma.ai/blog-post/how-to-setup-oidc-authentication-in-amundsen topic `Optional: Ingest Users in metadata proxy`

**Comment by hansadriaans** [comment]
There is a lot of functionality not implemented for gremlin that is implemented in Neo4j. We are currently looking into using openCypher for Neptune not using Gremlin anymore

**Comment by lucasvieirasilva** [comment]
> There is a lot of functionality not implemented for gremlin that is implemented in Neo4j. We are currently looking into using openCypher for Neptune not using Gremlin anymore

That will be great, however, I'm afraid the migration process won't be easy, considering the Amazon Neptune openCypher limitations.

https://docs.aws.amazon.com/neptune/latest/userguide/feature-opencypher-compliance.html

**Comment by hansadriaans** [comment]
Turns out there are two main issues:
1. Neptune doesn't support None types (it puts in string 'null')
2. the current package neptune 1.4.0.1 somehow doesn't support nested structure in the order by. So `order by item.row_id doesn't work and `item.row_id as item_row_id order by item_row_id` does work. 

We are working on some small changes here
