### ISSUE TITLE
BigQuery usage extractor in databuilder should not remove fixed date length in date sharded tables

### ISSUE THREAD

**Issue by sahithi03** [amundsen-io/amundsen#1979]
The bigquery usage extractor in amundsen is using a fixed date length to fetch table name from a date-sharded table. 
https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/bigquery_usage_extractor.py#L125

However the bigquery metadata extractor is removing the entire suffix while storing table name from a date-sharded table:
https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/extractor/bigquery_metadata_extractor.py#L51

This can cause problems when we have tables with date suffix length != 8 and if we use bigquery metadata extractor followed by bigquery usage extractor with relational db (mysql) as the metadata store. This results in foreign key violation as the table names with date suffix removed differ in bq_metadata_extractor.py and bq_usage_extractor.py.

## Expected Behavior
Table_id names after date suffix removal should be the same for bq_usage_extractor.py and bq_metadata_extractor.py

## Current Behavior

For example: table name: *foo2022030302*
Table name after removing date suffix in bq_metadata_extractor.py is *foo*
Table name after removing date suffix in bq_usage_extractor.py is *foo20*

## Possible Solution

bq_usage_extractor.py should use similar method of trimming the date suffix as bq_metadata_extractor.py i.e remove the whole date suffix instead of fixed length, since table names can sometimes have hour/minute also included in the suffix.
## Context

We have a few tables with date suffix with length greater than 8 resulting in foreign key violation when using  bq_usage_extractor.py followed by bq_metadata_extractor.py with mysql as the backend metadata store
## Your Environment

* Amundsen version used: Databuilder version 6.8.0
* Data warehouse stores: BigQuery
* Metadata store: Mysql

**Comment by feng-tao** [comment]
thanks, pr merged now

**Comment by sahithi03** [comment]
Hi @feng-tao, When can we expect this change to be included in the next release of databuilder? Thanks!

**Comment by feng-tao** [comment]
@sahithi03 could you create a pr and update databuilder minor version? i could help release it.

**Comment by sahithi03** [comment]
@feng-tao I believe databuilder 7.3.0 was just released https://github.com/amundsen-io/amundsen/releases/tag/databuilder-7.3.0. Could you please help publish this version to pypi as well. Thanks!
