### ISSUE TITLE
Feature: Commonly Joined Against Tables

### ISSUE THREAD

**Issue by nikshepsvn** [amundsen-io/amundsen#199]
The high-level objective of this feature is to provide visibility into which tables are commonly joined against each other. 

My current mental approach for implementing this (for SQL based databases at-least) is as follows:

1. Obtain SQL Query log for DB in question. ex: For Redshift we can query `STL_QUERY_LOG`, Postgres Logs can be enabled by setting `log_statement` to true and then ingested

2. Use a SQL parsing library like `moz-sql-parser` (https://github.com/mozilla/moz-sql-parser) to parse queries into a more usable form. For example:

**Query**
```
SELECT Orders.OrderID, Customers.CustomerName, Orders.OrderDate
FROM Orders
INNER JOIN Customers ON Orders.CustomerID=Customers.CustomerID;
```

**Parsed Output:**
```
{"select": [{"value": "Orders.OrderID"}, {"value": "Customers.CustomerName"}, {"value": "Orders.OrderDate"}], "from": ["Orders", {"inner join": "Customers", "on": {"eq": ["Orders.CustomerID", "Customers.CustomerID"]}}]}
```
3. Analyze parsed output -- We can then check the parsed data for joins Ex: Iterate and check the "from" clauses, look for any join clauses, update metadata
 
This could potentially be extended to pull more insights from queries, like most commonly queried column etc.

Note: All of this is just off the top of my head. Thoughts and ideas are welcome -- would love to get working on this and merge it upstream :)

**Comment by markgrover** [comment]
Love it. It'd be good to get this validated with a few users, I can do this at Lyft. I think it'd be good to:
1. List tables in descending order of how often they were joined
2. Cap the number of tables shown to 5.

What do you think?

**Comment by nikshepsvn** [comment]
Thanks a bunch! I appreciate it. I agree with both those points, sorting and capping it will definitely make the data more digestible for the user.

I was also thinking of maybe allowing users to preview those top 5 queries in the UI, to get a better idea of how the data is being used -- but that can come later maybe, after we have a base version of this functional.

**Comment by markgrover** [comment]
Agreed queries will be helpful and that they can come later.

**Comment by nikshepsvn** [comment]
Hey @markgrover, wondering if you have any updates on this. Would love to get started on this as soon as I can :)

**Comment by markgrover** [comment]
Sorry didn't realize you were waiting on me. Your plan looks great to me,
this would be a great contribution. Just let's sort them based on join
frequency and cap it to 5. Let me know if there's anything else I can help
with.
