### ISSUE TITLE
Fix HiveTableMetadataExtractor col_sort_order when table has multiple partitions

### ISSUE THREAD

**Issue by jakemongaya** [amundsen-io/amundsen#200]
When table is having multiple partitions(year,month,day), the col_sort_order is having the same rank. 
By introducing a PARTITION_OFFSET_INDEX, the sorting will show partitions in the top rows followed by the column rows.

**Comment by feng-tao** [comment]
cc @jinhyukchang

**Comment by jinhyukchang** [comment]
@jakero12 Sounds good to me!

**Comment by jakero12** [comment]
@jinhyukchang cool! I will work and test this hopefully by end of this week.

**Comment by jornh** [comment]
@jakemongaya how did this go? - is it still an open issue or was something merged into the Databuilder repo?

**Comment by jakemongaya** [comment]
Hi @johrn! I have the code in my repo and will work on the PR as soon as possible.

**Comment by jornh** [comment]
Great, thanks for getting back👍 

No worries - now we have a visible status  which is always a good Thing

**Comment by Golodhros** [comment]
Hi @jornh, was this solved?

**Comment by feng-tao** [comment]
I don't think it is fixed yet.
