### ISSUE TITLE
Lineage Graph - Add links to table name text for easy navigation

### ISSUE THREAD

**Issue by dbittenbender** [amundsen-io/amundsen#2008]
When on the Lineage Page, it would be great if you could navigate to an up/downstream table directly from the graph instead of having to go back to the up/downstream pages.

## Expected Behavior or Use Case
While exploring the lineage graph, you find a table that you are interested in learning about.  You click the table name and it navigates you to the table details page for that table.

## Service or Ingestion ETL
frontend

## Possible Implementation
I have code in a fork we are using to extend Amundsen. I can PR it to this repo.  

There is already a getLink() function in frontend/amundsen_application/static/js/components/ResourceListItem/TableListItem which is used, among other places, in the lineage up/downstream pages.  This code generates the link from a LineageItem so simply using it in frontend/amundsen_application/static/js/components/Lineage/Graph/chart.js in an href element does the trick.

We also would need to move the onclick event that expands/contracts the graph to the circle +/- instead of the entire node.

## Example Screenshots (if appropriate):
The screen looks the same except now the label is a link.

## Context
As we, and our clients, have been using Amundsen, they get frustrated with having to navigate out of the Lineage graph to the up/downstream pages to see table details for  dependent tables.

**Comment by jsnb-devoted** [comment]
Just chiming in that this would also be useful for our deployment 👋
