### ISSUE TITLE
Bug Report: Problem met when installing [npm:not found] .

### ISSUE THREAD

**Issue by fireragnarous** [amundsen-io/amundsen#2009]
## Expected Behavior
According to your installing instructions, I git clone the project and try to install amundsen with command: 
C.

## Current Behavior
![7](https://user-images.githubusercontent.com/55270059/195529075-1bb43157-a1b0-4b61-b45b-970b6f8d86bb.PNG)

## Steps to Reproduce

1.Download the github project
2.run "docker-compose -f docker-amundsen-local.yml build"

## Screenshots (if appropriate)
![8](https://user-images.githubusercontent.com/55270059/195529417-91307ad3-f2a2-4a9f-882a-55b99a1e8835.PNG)
![7](https://user-images.githubusercontent.com/55270059/195529463-dcabf591-8414-4086-858c-2e2f1d10cbf2.PNG)

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native): Centos 7
* Link to your fork or repository:

**Comment by e-mense** [comment]
I do get the same output using win10 when running the `docker-compose -f docker-amundsen-atlas.yml up` command. Is there a simple solution?
`PS C:\Users\b156\Documents\amundsen> docker-compose -f docker-amundsen-atlas.yml up
[+] Building 7.4s (21/21) FINISHED
 => [internal] load build definition from Dockerfile.frontend.local                                                0.0s
 => => transferring dockerfile: 47B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/python:3.7-slim                                                 1.7s
 => [internal] load metadata for docker.io/library/node:12-slim                                                    1.7s
 => [node-stage 1/9] FROM docker.io/library/node:12-slim@sha256:c28ca4124ac84ff1e72ee68abfe70aa4cc86f499c1ef20408  0.0s
 => [stage-1 1/7] FROM docker.io/library/python:3.7-slim@sha256:47bad4fb65c0194bddff388ce44b19a21f6e40869bb968065  0.0s
 => [internal] load build context                                                                                  0.2s
 => => transferring context: 99.05kB                                                                               0.2s
 => CACHED [stage-1 2/7] WORKDIR /app                                                                              0.0s
 => CACHED [stage-1 3/7] COPY ./frontend /app                                                                      0.0s
 => CACHED [stage-1 4/7] COPY requirements-dev.txt /app/requirements-dev.txt                                       0.0s
 => CACHED [stage-1 5/7] COPY requirements-common.txt /app/requirements-common.txt                                 0.0s
 => CACHED [node-stage 2/9] WORKDIR /app/amundsen_application/static                                               0.0s
 => CACHED [node-stage 3/9] COPY ./frontend/amundsen_application/static/package.json /app/amundsen_application/st  0.0s
 => CACHED [node-stage 4/9] COPY ./frontend/amundsen_application/static/package-lock.json /app/amundsen_applicati  0.0s
 => CACHED [node-stage 5/9] RUN npm install                                                                        0.0s
 => CACHED [node-stage 6/9] COPY ./frontend/amundsen_application/static/ /app/amundsen_application/static/         0.0s
 => CACHED [node-stage 7/9] RUN npm rebuild node-sass                                                              0.0s
 => CACHED [node-stage 8/9] RUN npm run dev-build                                                                  0.0s
 => CACHED [node-stage 9/9] COPY ./frontend /app                                                                   0.0s
 => CACHED [stage-1 6/7] COPY --from=node-stage /app /app                                                          0.0s
 => ERROR [stage-1 7/7] RUN pip3 install -e .                                                                      5.5s
------
 > [stage-1 7/7] RUN pip3 install -e .:
#0 1.930 Obtaining file:///app
#0 1.931   Preparing metadata (setup.py): started
#0 4.991   Preparing metadata (setup.py): finished with status 'error'
#0 5.003   error: subprocess-exited-with-error
#0 5.003
#0 5.003   × python setup.py egg_info did not run successfully.
#0 5.003   │ exit code: 1
#0 5.003   ╰─> [10 lines of output]
#0 5.003       /bin/sh: 1: npm: not found
#0 5.003       ERROR:root:npm must be available
#0 5.003       /bin/sh: 1: npm: not found
#0 5.003       /app/setup.py:30: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
#0 5.003         logging.warn('Installation of npm dependencies failed')
#0 5.003       WARNING:root:Installation of npm dependencies failed
#0 5.003       /app/setup.py:31: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
#0 5.003         logging.warn(str(e))
#0 5.003       WARNING:root:Command '['npm install']' returned non-zero exit status 127.
#0 5.003       error in amundsen-frontend setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
#0 5.003       [end of output]
#0 5.003
#0 5.003   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 5.006 error: metadata-generation-failed
#0 5.006
#0 5.006 × Encountered error while generating package metadata.
#0 5.006 ╰─> See above for output.
#0 5.006
#0 5.006 note: This is an issue with the package mentioned above, not pip.
#0 5.006 hint: See above for details.
#0 5.328 WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
#0 5.328 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
failed to solve: executor failed running [/bin/sh -c pip3 install -e .]: exit code: 1
PS C:\Users\b156\Documents\amundsen>`
