### ISSUE TITLE
Bug Report: NeptuneConfig import failing - Flask

### ISSUE THREAD

**Issue by roboverall** [amundsen-io/amundsen#2013]
## Expected Behavior
The metadata service (using Neptune) to start successfully.

## Current Behavior
Flask application startup fails due to an import error - `ImportError: module 'metadata_service.config' has no attribute 'NeptuneConfig'`

## Possible Solution
Make the NeptuneConfig discoverable by the service.

## Steps to Reproduce
1. Deploy a container based on the amundsen-metadata image (latest)
2. Follow this [guide](https://github.com/amundsen-io/amundsen/blob/08839140b774acb50018813511db17cb0056500c/docs/tutorials/how-to-use-amundsen-with-aws-neptune.md) to set up the service to use Neptune i.e. configure env vars
3. Start container and the app is unable to start

## Screenshots (if appropriate)
![Screenshot 2022-10-18 at 18 31 04](https://user-images.githubusercontent.com/36985452/196503029-9ff2c833-e54f-4be0-a79e-80cfae510fed.png)

## Context
I cannot start an ECS task based on this image and therefore can't connect to the Neptune cluster.

**Comment by sangram23** [comment]
Any solution for this?

**Comment by roboverall** [comment]
> Any solution for this?

The error message was a bit of a red herring. The actual problem was amundsen-gremlin isn't installed as part of the base image creation `amundsendev/amundsen-metadata`.

Solution 1 - add the package to the requirements files and rebuild your own Amundsen image

Solution 2 - build on the base image and add a `RUN pip install amundsen-gremlin` to your bespoke dockerfile. For my use case I've gone with the latter.
