### ISSUE TITLE
Unable to use Amundsen search API in another Web App

### ISSUE THREAD

**Issue by sonawanekaran** [amundsen-io/amundsen#2044]
I’m working on exposing those Amundsen APIs as graphQL endpoint so that we can use those search endpoints at other web apps. It always returns:

```
"status": 500,
          "statusText": "INTERNAL SERVER ERROR",
          "body": "<!doctype html>\n<html lang=en>\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n"
```

And stucks at auth(). 
We are using Okta authentication and FlaskbasedOIDC.

Any help with this is appreciated.

**Comment by Golodhros** [comment]
In theory, you should be able to authenticate and do this.
Maybe you could give us more context or ask in the Slack community.

**Comment by karansdd** [comment]
> In theory, you should be able to authenticate and do this. Maybe you could give us more context or ask in the Slack community.

https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1670576394475169
added question in the slack

**Comment by sonawanekaran** [comment]
> In theory, you should be able to authenticate and do this. Maybe you could give us more context or ask in the Slack community.

https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1670576394475169
added question in the slack
