### ISSUE TITLE
UI crashes on "search page" if we add multiple filters with the same category

### ISSUE THREAD

**Issue by mikaalanwar** [amundsen-io/amundsen#2053]
UI crashes on Search Page if we add multiple filters to the same category.

## Expected Behaviour
There can be scenarios where having multiple search filters for the same category can be useful, e.g. maybe we could have a checkbox to include or exclude items that have a certain badge (e.g. PII). Having such a checkbox can be more user friendly if we're trying to build a complex search query as many analysts might not be able to follow proper search syntax, as is expected in the search filter field.

## Current Behaviour
If we add multiple search filters having the same "categoryId", the search page breaks upon switching back and forth between resource types.

## Possible Solution
Perhaps, this is happening because "category Ids" get passed further as "html ids" which are supposed to be unique. Maybe a better support to specify html id in the config or handling of this edge case in code to accommodate duplicate category ids is needed.

## Steps to Reproduce
1. Add two filters having the same categoryId in the [config-default.ts](https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/config/config-default.ts) or [config-custom.ts](https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/config/config-custom.ts) file.

2. After building and running, navigate to the "Search" page and upon switching back and forth between different resource types (e.g. Tables and Dashboards etc.), you will notice that the search filter with the duplicate "categoryId" keeps on getting duplicated in FilterSection (sidebar) e.g. if we switch 3 times, there will be 3 extra filters displayed (one added per transition). 

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/22380077/206613857-638c8aec-47cf-4120-99ee-30f74a5d9d22.png)

## Context
This affects a very useful and highly requested feature of ours.  Would be great if it can be fixed.

## Your Environment
* Amundsen version used: common-0.30.0 (e0373e17a03b833f4a5c6097b12b8d7f6446d2f1)
* Data warehouse stores: BigQuery
* Deployment (k8s or native): k8s
* Link to your fork or repository:https://github.com/deliveryhero/amundsen

**Comment by ozandogrultan** [comment]
@Golodhros @kristenarmes @allisonsuarez can you please take a look and help with this issue if possible?

**Comment by mikaalanwar** [comment]
Closing this, as it has been fixed by [this PR](https://github.com/amundsen-io/amundsen/pull/2057).
