### ISSUE TITLE
Feature Proposal: add table/column lineage for mysql backend

### ISSUE THREAD

**Issue by xuan616** [amundsen-io/amundsen#2072]
The request is going to add table/column lineage in amundsen-rds and all the corresponding functions in databuilder/metadata-service to enrich the metadata mysql backend can support.

## Expected Behavior or Use Case
It would work similarly to the current lineage feature which has been running in graph db backend for a long time. With the new lineage models in amundsen-rds, lineage data would be ingested into mysql and api in metadata service would be responsible for lineage extraction.

## Service or Ingestion ETL
Components impacted:
- [amundsen-rds](https://github.com/amundsen-io/amundsenrds)
- [databuilder](https://github.com/amundsen-io/amundsen/tree/main/databuilder)
- [metadata-service](https://github.com/amundsen-io/amundsen/tree/main/metadata)
## Possible Implementation
- amundsen-rds: add two new models(table_lineage, column_lineage) and the corresponding schema migration script
- databuilder: add iterators for table/column lineage with rds serializable in [table_lineage](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/models/table_lineage.py) model
- metadata-service: implement an api endpoint to get lineage results in [mysql_proxy](https://github.com/amundsen-io/amundsen/blob/main/metadata/metadata_service/proxy/mysql_proxy.py)
## Context
As a fundamental feature for data tracking, lineage is still missing in mysql backend. Implementing this feature would be helpful for analyzing data pipeline and aligning with graph db features for mysql backend users. Thanks.

cc @feng-tao

**Comment by feng-tao** [comment]
Cool!
