### ISSUE TITLE
Feature Proposal: Load Data Preview when the button is clicked instead of page load

### ISSUE THREAD

**Issue by ozandogrultan** [amundsen-io/amundsen#2074]
## Expected Behavior or Use Case
As discussed [here](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1665439749124809), there seems to be a collective interest on changing when the Data Preview request is done on the frontend. The proposal is to trigger the Data Preview request only when the button is clicked, instead of page mount so that the compute resources are used more efficiently and potentially some cloud cost is saved.

## Service or Ingestion ETL
Frontend

## Possible Implementation
React code will need to be updated to trigger Data Preview request only on button click instead of page mount

## Example Screenshots (if appropriate):
N/A

## Context
The reason for this proposal is since the Data Preview request can be compute-intensive depending on the backend, it is more efficient to load it only when it is needed, instead of loading every time a table detail page is visited. This can potentially save some cloud cost for the hosts as well.

**Comment by Golodhros** [comment]
Let's make this configurable though, so people that always want it don't have to wait extra.
