### ISSUE TITLE
Customize search results metadata: visible columns, results ordering, and filter options

### ISSUE THREAD

**Issue by eschranz** [amundsen-io/amundsen#2084]
## Expected Behavior or Use Case
It would be nice to have control over the search results view, including the visible columns and results ordering. Furthermore, maybe being able to select different filter fields dynamically and setting filters would be useful.

## Service or Ingestion ETL
Frontend

## Possible Implementation
I think seeing dropdown options for sort order (alphabetical, popularity, etc) and another for check boxes that would show the visible columns on the search page. Also providing a quasi query language for filtering could be nice. I would use Jira as a good example for all these features.

## Example Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/98729458/214394577-ffbdd2c4-cacb-4458-b535-d26e351d59e0.png)

## Context
For our instance, we don't use badges, so having that be a default column in the search view isn't very useful. Our users have indicated that seeing tags instead (which are more used) would help when searching for resources.

Generally, the search page could have more features that make it more flexible to users to display the things they want to help in searching. There are filter fields (e.g. badges) that are filterable, but not shown in the default view. Having control of this from the UI (or from the backend) would provide much needed customizability.

**Comment by Golodhros** [comment]
Thanks for creating this @eschranz!
