### ISSUE TITLE
Frontend npm install problems (lyft repository dependencies)

### ISSUE THREAD

**Issue by wuttem** [amundsen-io/amundsen#2141]
I was trying to build the static part of the amundsen frontend like outlined in the documentation

```
cd static
npm install
npm run build
```

This leads to a E401 errors from npm.

## Current Behavior
Some of the dependencies in `package-lock.json` are resolved to a repository hosted by lyft.
This leads to problems building because it seems this is not open for public.

Example:
`react-switch` is resolved to `https://artifactory-npm.lyft.net/artifactory/api/npm/virtual-npm-lyft/react-switch/-/react-switch-6.0.0.tgz` which requires some kind of login to access.

Not sure what the reason for this is, but it seems like all of these dependencies could also be resolved by a public repository.

For Example
`react-switch` could be resolved from `https://registry.npmjs.org/react-switch/-/react-switch-6.0.0.tgz`

## Possible Solution
It is of course possible to delete `package-lock.json` and rebuild it however this makes it much more complicated to get a working configuration. Manually changing the file for just a couple of dependencies is also not a great solution.

My proposal would be to change `package-lock.json` to only resolved dependencies to public available repositories.

**Comment by mikaalanwar** [comment]
I came across this issue once as well and saw some occurrences of people facing this in the amundsen slack channel too ...

**Comment by wuttem** [comment]
This might be a nitpick, but to me, the "stale bot" does not seem to make a lot of sense. It just makes it obvious that replies are taking some time... Which I am totally ok with, by the way. Why shouldn't it be ok if there is no reply to an issue for 2 weeks ? Does not seem like auto closing issues helps with anything.

**Comment by rjalan01** [comment]
It is still happening, it is connecting to https://artifactory-npm.lyft.net/artifactory/api/npm/virtual-npm-lyft/tree-changes/-/t
ree-changes-0.7.1.tgz which need lyft credential. please prioritise it

**Comment by Golodhros** [comment]
Definitely a bug.
I will prioritize this, thanks for your patience!

**Comment by Golodhros** [comment]
Check https://github.com/amundsen-io/amundsen/pull/2174 for a fix

**Comment by rjalan01** [comment]
Thank you for the fix
