### ISSUE TITLE
GPL-licensed dependency `unidecode`

### ISSUE THREAD

**Issue by hehao98** [amundsen-io/amundsen#2148]
(I think this is not a bug or a feature request, so I am opening an issue without a template)

Hello,

We are a group of researchers developing tools to monitor and remediate open-source license incompatibilities in the PyPI ecosystem.

We find that your `amundsen-databuilder` package has a **GPL-2.0-or-later** licensed dependency `unidecode`. This could be problematic because GPL-licensed software requires any of its derivative work to be also licensed under GPL, but `amundsen-databuilder` is licensed under Apache 2.0. 

To remove this license incompatibility, the following possible remediations may be considered:

* Relicense `amundsen-databuilder` under GPL 3.0 or AGPL 3.0
* Migrate `unidecode` to `text-unidecode`
* Change `unidecode` version to 0.04.6
* Remove `unidecode`

Note that the above remediations are generated by an automated tool that is still under test, may be incorrect, and does not represent legal advice. We welcome any suggestions and feedback!

**Comment by kristenarmes** [comment]
Hi @hehao98, thanks for bringing this to our attention, I have opened a PR to address this issue
