### ISSUE TITLE
Quickstart: Add hint to EOL for neo4j.conf for windows users

### ISSUE THREAD

**Issue by makatony** [amundsen-io/amundsen#217]
For the quickstart installation.md I suggest to add a hint like "windows users: make sure the neo4j.conf file has EOL set to unix style LF, not windows style CRLF. Read more here on how to automatically checkout correctly: https://www.edwardthomson.com/blog/git_for_windows_line_endings.html"

otherwise During the quickstart using "docker-compose -f docker-amundsen.yml up" the neo4j container exits with the error: Unrecognized VM option 'UseG1GC

The error and solution is described here: https://stackoverflow.com/questions/45209737/neo4j-docker-unable-to-create-jvm

Thank you

**Comment by feng-tao** [comment]
Feel free to reopen if the issue still valid
