### ISSUE TITLE
Proposal: documentation of possible queries for data generated from `action_logging callback`

### ISSUE THREAD

**Issue by worldwise001** [amundsen-io/amundsen#22]
As per chat, if folks are able to get data out of `action_logging callback` in amundsenfrontendlibrary into a single table, it would be great to see how some sample queries could be structured using this data, to build Looker dashboards and the like.

**Comment by jinhyukchang** [comment]
Not the query but for a starter here's what we have in Lyft:
- WAU
- DAU
- Top 50 active user
- Top search term
- Top popular tables
- Search click index
- Metadata edits
- Metadata edit leaders
- Amundsen user per role (by joining with employee data)

**Comment by ttannis** [comment]
Issue can be summarized as essentially documenting what commands and parameters we log.
