### ISSUE TITLE
Document the OIDC docker images

### ISSUE THREAD

**Issue by jornh** [amundsen-io/amundsen#224]
Document that Docker images exist (as part of the OIDC doc page?) which includes OIDC config for authentication 

A follow up to https://github.com/lyft/amundsenfrontendlibrary/pull/352 and the similar PR in the amundsenmetadata repo

This is - also - a `good first issue` for someone who successfully managed to spin up Amundsen using these images.

**Comment by samshuster** [comment]
not sure if the readme added here covers this story?
https://github.com/lyft/amundsen/issues/260

**Comment by jornh** [comment]
@samshuster apologies for the late reply.

Well, it does, partially, and it’s certainly a huge step towards better documentation of it. Thanks!

I do have a few thoughts I’d like input on:

* Ideally I’d like documentation of how to use it with docker compose - for those not able to run K8s, though the bar for that certainly gets lowered with eg Docker Desktop evolution - even on a local windows box.

* I think the page structure could be improved on. My preference would be top to bottom - like : 
 -   K8s (hopefully soon with d, 
 - docker images (we can start adding a placeholder heading asking for PRs), 
 - manually aka @verdan’s original description

Context for suggestions above in this slack thread: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1582228133384300?thread_ts=1582148962.353900&channel=CGFBVT23V&message_ts=1582228133.384300

Thoughts?
