### ISSUE TITLE
Support for Unity Catalog

### ISSUE THREAD

**Issue by xpaulnim** [amundsen-io/amundsen#2253]
## Expected Behavior or Use Case

It would be nice for Amundsen to have a data extractor for Databricks Unity catalog

## Service or Ingestion ETL

Metadata extractor

## Possible Implementation

An`databuilder.extractor.base_extractor.Extractor` specific to the databricks Unity Catalog

## Context

I would like to make it possible for Amundsen to support Databricks unity catalog.

**Comment by feng-tao** [comment]
@xpaulnim feel free to contribute and happy to review and support

**Comment by kristenarmes** [comment]
closing this since it has been triaged - will track by status label
