### ISSUE TITLE
Feature Proposal: In Memory loader

### ISSUE THREAD

**Issue by HaoXuAI** [amundsen-io/amundsen#2257]
The current supported loaders are all loading data from file systems(csv/json) into the destination. Instead it can be a simple loader take in Record in memory and load it directly.

## Service or Ingestion ETL

[Data builder](https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/loader/generic_loader.py)

**Comment by kristenarmes** [comment]
closing this since it has been triaged - will track by status label
