### ISSUE TITLE
fetch_table_search_results don't have wildcard enabled

### ISSUE THREAD

**Issue by sandeshvijayraj** [amundsen-io/amundsen#244]
fetch_table_search_results don't have a wildcard enabled as fetch_table_search_results_with_field has can this be enabled so that both search api behaves in a similar way

**Comment by jornh** [comment]
Sorry @ttannis to bother with another maybe related to recent search improvements. Perhaps this issues is now irrelevant as well?

From #243 conversation etc. I’m sure you're in the know!

**Comment by ttannis** [comment]
> Sorry @ttannis to bother with another maybe related to recent search improvements. Perhaps this issues is now irrelevant as well?
> 
> From #243 conversation etc. I’m sure you're in the know!

This might not be, `fetch_table_search_results` ins't deprecated, it's now just the logic that is used when there are no filters passed. We could still look into this
