### ISSUE TITLE
AWS: Amundsen Frontend not reaching Neo4j

### ISSUE THREAD

**Issue by lordravo** [amundsen-io/amundsen#257]
I just followed the [aws-ecs-deployment guide](https://github.com/lyft/amundsen/blob/master/docs/installation-aws-ecs/aws-ecs-deployment.md), and successfully launched the frontend, elasticsearch and neo4j endpoints.

After executing a dag with a BigQueryMetadataExtractor, I was also able to send metadata to Neo4j. As you can see:
![image](https://user-images.githubusercontent.com/58708386/73385139-5fa96800-42ab-11ea-8306-3ac5dc0fbcf0.png)

But, for some reason, nothing is reachable through the amundsen frontend. Just a blank page:
![image](https://user-images.githubusercontent.com/58708386/73385232-8d8eac80-42ab-11ea-879b-b5807b6c3dbf.png)

Looking into the developer console there is a failed request:
/api/search/v0/table?query=events&page_index=0
![image](https://user-images.githubusercontent.com/58708386/73389150-54a60600-42b2-11ea-9b4f-f181cd70c3a9.png)
> {"msg":"Encountered exception: HTTPConnectionPool(host='amundsensearch', port=5000): Max retries exceeded with url: /search?query_term=events&page_index=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3bf88fd470>: Failed to establish a new connection: [Errno -2] Name or service not known'))","search_term":"events","tables":{"page_index":0,"results":[],"total_results":0}}

I am not sure if it is related, but the elasticsearch endpoint returns the following:

> {
  "name" : "-ZjL23y",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "yekS4uxBS76ULwUj4yp57A",
  "version" : {
    "number" : "6.7.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "8453f77",
    "build_date" : "2019-03-21T15:32:29.844721Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

Any ideas why? Am I missing something?

**Comment by jornh** [comment]
It could be the “classic gotcha” that you also need to ingest data into Elasticsearch through the databuilder.

Here’s a sample of doing that: https://github.com/lyft/amundsendatabuilder/blob/v1.5.1/example/scripts/sample_data_loader.py#L590

**Comment by jornh** [comment]
The architecture diagram and the **Search** and **Databuilder** sections in https://github.com/lyft/amundsen/blob/master/docs/architecture.md gives a good high level overview.

**Comment by lordravo** [comment]
Hi @jornh, thanks for the help..

I added a `create_es_publisher_sample_job` to the DAG, but even so all requests on Amunsen Frontend ends up with status 500.. It seems a configuration issue perhaps?

Event the `/api/auth_user` endpoints returns: 
> {"msg":"Encountered exception: AUTH_USER_METHOD is not configured"}

And `api/metadata/v0/get_last_indexed`:
> {"msg":"Encountered exception: HTTPConnectionPool(host='amundsenmetadata', port=5000): Max retries exceeded with url: /latest_updated_ts (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3bf88ac080>: Failed to establish a new connection: [Errno -2] Name or service not known'))","timestamp":null}

I am attaching my code anyways...
[sample_amundsen_v2.zip](https://github.com/lyft/amundsen/files/4134969/sample_amundsen_v2.zip)

The `amundsen_databuilder_table_metadata_job` task works properly, adding the metadata to Neo4J

The `es_table_job` task endsup with success, bit I'm not sure how to check any effects other than trying to query on Amundsen Frontend.

Any idea?

**Comment by lordravo** [comment]
I'm pretty sure it is ECS related... I just launched Amundsen on a CenOS Instance, on GoogleCloud. Exact same yml (without the aws logs), and everything is working so far.

**Comment by andrey-oreshko** [comment]
@lordravo hey i'm experiencing the same issue
Did you come up with some solution except using CentOS?

**Comment by iamtodor** [comment]
Hi guys
Step #3 from https://www.amundsen.io/amundsen/installation-aws-ecs/aws-ecs-deployment/ is not valid.
$ ecs-cli up --keypair JoaoCorreia --extra-user-data userData.sh --capability-iam --size 1 --instance-type t2.large --cluster-config amundsen --verbose --force --aws-profile $AWS_PROFILE
>>> FATA[0002] Error executing 'up': open userData.sh: no such file or directory
What to do with it?
I've seen some comment: in ~/<your-path-to-cloned-repo>/amundsenfrontendlibrary/docs/instalation-aws-ecs but there is no such dir `instalation-aws-ecs`

**Comment by iamtodor** [comment]
Same issue to step #4 from https://www.amundsen.io/amundsen/installation-aws-ecs/aws-ecs-deployment/
`ecs-cli compose --cluster-config amundsen --file docker-ecs-amundsen.yml up --create-log-groups`
No such file. I searched over two repos https://github.com/amundsen-io/amundsen and https://github.com/amundsen-io/amundsenfrontendlibrary
I haven't found such files. What am I missing?

**Comment by iamtodor** [comment]
While walking thought the issues I found a proper location of the needed files: https://github.com/amundsen-io/amundsen/tree/master/docs/installation-aws-ecs

**Comment by hkuchibhotla** [comment]
running into the same issue, any luck with getting this to work on ECS?
