### ISSUE TITLE
Frontend Resources: Querying over Tables and Clusters

### ISSUE THREAD

**Issue by lordravo** [amundsen-io/amundsen#273]
Currently, I have Amundsen set on a Container-Optimized OS from Google Cloud, and, so far, it is working pretty nice for BigQuery. Tables, Columns and Stats, are being published through Dags on Airflow, successfully logging all metadata and relations.

Yet, just a small issue is making a little confusing; 

We currently have a lot of projects (for different products) on BigQuery, and some of them have schemes (datasets) with the same name. Since Amundsen results are returned as datasets, there is duplicity of results, since the project is not given:

![image](https://user-images.githubusercontent.com/58708386/73847153-78160700-4804-11ea-8b8f-0ef58ed103fe.png)

Is there any way to show the project also? Or even give the option to select other resources other than Dataset on the left panel?

![image](https://user-images.githubusercontent.com/58708386/73847334-cdeaaf00-4804-11ea-9c99-bbbdab0f42b6.png)

Besides that, is there a way to add other dataset categories; Or query on different resources (tables, clusters, descriptions..)

> Search within a category using the pattern with wildcard support 'category:*searchTerm*', e.g. 'schema:*core*'. Current categories are 'column', 'database', 'schema', 'table', and 'tag'.

![image](https://user-images.githubusercontent.com/58708386/73846479-608a4e80-4803-11ea-8ce8-273b944d7a27.png)
![image](https://user-images.githubusercontent.com/58708386/73846613-8fa0c000-4803-11ea-89a8-9bbdf8b07241.png)
![image](https://user-images.githubusercontent.com/58708386/73847443-0ee2c380-4805-11ea-99a8-20dd55339b79.png)

**Comment by feng-tao** [comment]
hey @lordravo , glad that you get it working. And please take a look at @ttannis 's proposal for search filter(https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1581029636194200) which should solve your issues.

**Comment by feng-tao** [comment]
Feel free to comment on the proposal(https://docs.google.com/document/d/1pruajPdiqMjG0qWbx6O5kbChxh_O7ZfMZm3N8i0CcPw/edit)
