### ISSUE TITLE
Support case insensitive/sensitive search where applicable

### ISSUE THREAD

**Issue by ttannis** [amundsen-io/amundsen#283]
Context: https://github.com/lyft/amundsensearchlibrary/pull/70/files#r376499915

For some search parameters it is desirable to support case insensitive matches, for example the search term. However for other parameters like tags where specific acronyms are used, we may want that to remain case sensitive.

This issue is for evaluating which parameters should be case sensitive/insensitive and adding that support.

**Comment by dorianj** [comment]
I suspect that case-insensitive is probably user expectation in most cases? IMO should be the default -- if operators or options were added, then add then?

**Comment by bruno-nirello** [comment]
i agree with @dorianj, in my company case this is crucial.
