### ISSUE TITLE
feature request - sample queries for tables

### ISSUE THREAD

**Issue by javamonkey79** [amundsen-io/amundsen#31]
It would be useful, to provide a sample queries field in the table view, such that users can get a jump start, on how to use a table and it's columns.

**Comment by jornh** [comment]
Could be seen as related to https://github.com/lyft/amundsen/blob/master/docs/roadmap.md#index-dashboards 

Notice there’s a “queries” tab in the design proposal:

![FC6E3D5C-CFF1-495C-9B7D-4E11BFFD1BD8](https://user-images.githubusercontent.com/766423/64082914-e1a25e80-cd16-11e9-8cee-dd06804e6ed1.jpeg)

**Comment by dorianj** [comment]
This could be implemented via https://github.com/amundsen-io/rfcs/pull/27
