### ISSUE TITLE
Clicking on Badges pulls up a tag:{badge_name} search like for tags

### ISSUE THREAD

**Issue by samshuster** [amundsen-io/amundsen#318]
# Overview

Users would like to click on badges like they do for tags to see all tables that have that particular badge.

# AC
- upon clicking on a badge, a query page is pulled up tag:{badge_name} just like for tags.

**Comment by feng-tao** [comment]
cc @ttannis @danwom I am wonder whether you two have discussed with UI/UX designer about this. Potentially we could update the browse page to show badge as well.

We have an engineer enhancing the functionality of badge(non editable whitelist tag) which allows user to search, surface in search FE as well. Stay tuned.

**Comment by samshuster** [comment]
ok sounds good @feng-tao based on what you are saying, sounds like this issue will be handled with those changes, so I will not work on this.

**Comment by ttannis** [comment]
Such a feature would become available when we implement filtering support for badges. Which could be worked on after @csteez completes the work Tao mentioned. I can't speak on how soon Lyft would be able to implement this, but I had previously scoped out some of the work we can provide guidance on how to complete it.

In terms of the browse page suggestion, I'd separate that as its own issue for discussion if anyone feels strongly about it.

**Comment by csteez** [comment]
I'm not sure about the implementation details of how filtering is done for tags, but I think after the work I've done for badges it should be relatively trivial to add (as that filter query is valid after my changes) to amundsensearch/databuilder.

**Comment by ttannis** [comment]
Note for community: Feature is dependent on implementing badge filtering support.

**Comment by ttannis** [comment]
Addressed in https://github.com/amundsen-io/amundsenfrontendlibrary/pull/519.

**Comment by NiravLangaliya** [comment]
I have added multiple badges to the table  ,  as we are grouping tables with badge level hierarchy.

**Comment by ttannis** [comment]
> We have added multiple badges to the table, as we are grouping tables with badge level hierarchy.
> 
> For example, the table has three badges
> 
> 1. product type
> 2. geo_location
> 3. product
> 
> and in UI, we are able to see that three badges are assigned to the table.
> 
> but when we try to click badge ( example clicked on geo_location) and to search all tables with the same geo_location badge irrespective of product type or product. The search is not working. what we have noticed is search will only work for a badge that appears first in UI.
> 
> so consider that in UI it display like this
> 
> table_a product type geo_location product
> 
> then we can click all badges but the search will work only for product type not for the rest of the badges.

Can you file a separate issue so that we can better address this new concern?
