### ISSUE TITLE
Amundsen + CKAN connections 

### ISSUE THREAD

**Issue by rufuspollock** [amundsen-io/amundsen#330]
Amundsen looks great and just started looking through the code and design and I wanted to see if there were any productive connections even if at the conceptual level between it and CKAN another python-based open source data management / metadata management platform (which I've help create) https://github.com/ckan/ckan - https://ckan.org/

**Comment by jornh** [comment]
Hey @rufuspollock thanks for reaching out across fellow Python based metadata projects! 

 One question that has come up a few times recently in the Amundsen community are people asking about how Amundsen can help with data discovery of data in object stores like S3, minio, Azure Data Lake, HDFS, Googles similar offerings etc. Is this an area where CKAN has solutions in place for “foreign data” that isn’t managed/uploaded directly through CKAN itself? I’m thinking crawlers etc.

Any immediate productive connections you stumbled upon after spelunking through Amundsen? - also if you want to discuss further I’d encourage you to join the Amundsen Slack. There are just over 500 people interested in metadata and data discovery there now.
