### ISSUE TITLE
Build a bot to archive OSS slack discussion into issue  

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#347]
Amundsen has a open source slack channel which currently runs out of its free msg quota. It would be good to archive the discussions as an issue like stackoverflow to keep track.

**Comment by jornh** [comment]
Why build when you can adopt existing  OSS? 😝


https://github.com/docmarionum1/slack-archive-bot 
- seems to have recent commits 
- it’s 🐍 Python

Seems to require a box to run on though

Haven’t tried it, so can’t say more just came up on a quick search

**Comment by feng-tao** [comment]
yeah, the ticket is more about find out a solution :) thanks for the pointer. Will take a look.
