### ISSUE TITLE
Make a connection to Active Directory to get user details

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#35]
In order to get details of user from Active Directory (and not from Neo4j), we need a connection and configurations of the AD. At the moment the user details is highly coupled with Neo4j proxy.

**Comment by amitasthana** [comment]
I have to work on LDAP integration in Amundsen, can someone suggest how do I proceed, like a rough idea what all ingredients I need to setup LDAP with Amundsen, so that in an organisation different sets of permission and permission groups can be set and roles can be assigned to the users who log in and view the categorised data in Amundsen and access the data only authorised to them.

**Comment by verdan** [comment]
@amitasthana we are not using LDAP for Access Control at the moment, and will use Apache Ranger for that. 
However, I have implemented the LDAP connection to get the user details from AD. You can simply use that way to inject user groups etc in the user detail and then can use that groups/policies to fine tune the access. Still a lot of work in this domain I'd say. 

This is the method I imeplemented to get details from LDAP. 
https://github.com/lyft/amundsenmetadatalibrary/blob/master/docs/configurations.md#user_detail_method-optional

**Comment by ibnipun10** [comment]
@feng-tao : Ideally user information is kept in a different dbs to support single sign-on. My company have users in office 365 and would lobe to have oauth enabled in amundsen for users to signin using there office 365 account. This way, if any user leaves the org, he may not be able to login to the catalog as well

**Comment by tiago-cruz-movile** [comment]
Do you have some example about how to configure the ldap authentication in config.py?

I mean, after set the `USER_DETAIL_METHOD = get_user_details`, where I should put the string connection, user, port and etc?

**Comment by verdan** [comment]
@tiago-cruz-movile the way I did was to define all these things in get_user_details method. 

So my config.py was something like this:
```python

def get_user_details(user_id):
    import ldap
    ldap_user = os.environ.get('LDAP_USER')
    ldap_password = os.environ.get('LDAP_PASSWORD')
    
    connection = ldap. initialize...
    .....

class Config:
    USER_DETAIL_METHOD = get_user_details
```

**Comment by Agustin1913** [comment]
Hi guys, do we have any updates about AD or AAD integration?

We are currently working on a ubuntu machine where Amundsen is deployed using Docker. The ubuntu server is joined in the domain (AD in windows server 2019). Do you know how we can integrate it?
