### ISSUE TITLE
Possible to intergrate with other tool to implement lineage features?

### ISSUE THREAD

**Issue by fBedecarrats** [amundsen-io/amundsen#356]
(Don't know if this fits here or in Slack).
For Amundsen instances running on Neo4J, I can think of 3 directions to implement lineage with the current version of Amundsen.

1. Integrating with [ArcadeAnalytics](https://github.com/ArcadeData/arcadeanalytics) which provides a ready to use facility to visualize (with embedable widgets-iframes) and edit graph data. Graph widgets are triggered by cypher queries so one can filter for tables and their lineage relationships. This already works out of the box and you can launch AA docker image and connect it to your Neo4J Amundsen graph database to navigate and edit it. Being able to edit the Neo4J Graph in an ergonomic ways makes it doable to manually document lineage relathonships.
2. Using the [Neo4J ETL tool](https://github.com/neo4j-contrib/neo4j-etl) to extract source schema that reflects the lineage between tables inside a RDBMS.
3. Including in the Gobblin-Like scripts the corresponding ones to parse and ingest the ETL jobs that move the data from a system to another.

I tried 1, which works quite fine in Neo4J, but one needs to publish the changes to Elasticsearch frequently and I can't think of an easy way to do it. 
Sorry in advance if this seems too much out of the scope you imagined for Amundsen. If so, please feel free to delete this issue.

**Comment by feng-tao** [comment]
Thanks for bringing this up. There are some previous discussions in https://github.com/lyft/amundsen/issues/163. I think it is a good topic to discuss in the slack.

**Comment by anheiser1997** [comment]
@fBedecarrats @feng-tao Hi, I had a query. If we were to use one of the three options above, and also considering using DBT as another option, would the URL for the page we built for lineage be given as a third party URL as mentioned here: https://github.com/amundsen-io/amundsen/issues/69
