### ISSUE TITLE
Get Table Description in Neo4j proxy is not leveraging the graph db functionalities

### ISSUE THREAD

**Issue by PaschalisDim** [amundsen-io/amundsen#361]
Insights on how the description of a table is being called in Amundsen
In our case, we are using  the /table endpoint from the AmundsenMeta repository which does not use the relations defined in Neo4j. The current implemention is searching for a specific key in nodes of type table and description. (repo). That's how it retrieves a table and its description, by searching for the specified unique key that holds each node. That means the graph functionality is not being leveraged.

What would be the "right" implementation to leverage the functionality of Neo4j?
In this case when a user would call the /table endpoint the Neo4j query would get the table with the right key. Afterwards, it would retrieve the description type of objects that are linked to it with relations of type "DESCRIPTION_OF" in order to retrieve the linked description.

**Comment by Golodhros** [comment]
@feng-tao which project would fit this issue?

**Comment by feng-tao** [comment]
metadata

**Comment by jinhyukchang** [comment]
Hi @PaschalisDim ,

Do you think you can elaborate this? Code snippet would be great as well.
> In our case, we are using  the /table endpoint from the AmundsenMeta repository which does not use the relations defined in Neo4j.

I am assuming this is not `amundsen-metadata` for it uses [relation](https://github.com/lyft/amundsenmetadatalibrary/blob/master/metadata_service/proxy/neo4j_proxy.py#L179) to Description AFAIK.
