### ISSUE TITLE
Unnecessary code - proxy/elasticsearch.py vs api/table.py

### ISSUE THREAD

**Issue by jhettler** [amundsen-io/amundsen#37]
Hi,
in my opinion, the code below can't be reached and the default value is set from different places.

https://github.com/lyft/amundsensearchlibrary/blob/ab13456f29f1effbe7360e300af7c469fe9fe320/search_service/proxy/elasticsearch.py#L219-L220

elasticsearch.py is called from table.py below, but there is a default value set in table.py and if I set the default value in table.py as a param of add_argument, it will never reach else condition in elasticsearch.py

https://github.com/lyft/amundsensearchlibrary/blob/ea46e71de6e9e345a4b0207f364d2e9afc110cc6/search_service/api/table.py#L28

https://github.com/lyft/amundsensearchlibrary/blob/ea46e71de6e9e345a4b0207f364d2e9afc110cc6/search_service/api/table.py#L43

I am I right and should it be fixed or is it on purpose and I can't see the reason?
I would prefer to leave the default value just in config and remove it from `add_argument` from table.py.

Thanks

**Comment by feng-tao** [comment]
we move the code to common which the issue should be fixed now.
