### ISSUE TITLE
Is the amundsen helm chart publicly available?

### ISSUE THREAD

**Issue by Jwan622** [amundsen-io/amundsen#382]
What's your url for the amundsen helm chart? I tried installing/adding it but the only way I could get it work was to git clone the whole repo. Is the chart hostly remotely? IF so, what's the command to add and install the helm chart?

I think you can add the helm charts to a repo:
https://helm.sh/docs/topics/chart_repository/#google-cloud-storage

Right now when I run this, I find no repo:

```
 helm search repo amundsen
No results found
helm search hub amundsen
No results found
```

**Comment by jornh** [comment]
It’s currently only available through a `git clone` or similar like GitHub zip download.

Contributions towards an _automated publishing_ are welcome. If you’re interested it’s an excellent `good first issue` as it doesn’t require a lot of Amundsen insight.

**Comment by jacobhjkim** [comment]
Is there any plan on adding Amundsen to the incubator or any other helm repository?

**Comment by jornh** [comment]
@jacobhjkim the incubator will be delisted on Helm hub by August, see https://github.com/helm/charts#status-of-the-project. The new preferred way with publishing  seem to be self-hosting, then submitting for Helm Hub. The hosting can for example be made on GitHub pages and managed by a GitHub workflow. 

This feature request is marked as “good first issue”, so feel free to take a stab at automating this.

**Comment by joshthoward** [comment]
I went and created a sample charts repo [here](https://github.com/joshthoward/charts). 

If someone on the core team can create a fork within the amundsen-io organization, I can reference it from Artifact Hub.

**Comment by raman-nbg** [comment]
One year later: Is there any progress?

Or in other words: Is a Kubernetes deployment really a recommended deployment option for Amundsen?

**Comment by mattssll** [comment]
I tried deploying it and could not - sometimes the metadata service fails, then in another the elastic search service never starts
