### ISSUE TITLE
Frontend rebuilding (hot reload ?)

### ISSUE THREAD

**Issue by andrew-oreshko** [amundsen-io/amundsen#392]
Hey everyone

Guys, is there a way to rebuild frontend WITHOUT executing setup.py of frontend microservice ? 
Documentation tells that npm run build is sufficient to see changes, but actually static that is used is which lies within venv i believe. So every time when i wanna rebuild frontend i have to execute python3 setup.py. Is there a way to avoid this ?

**Comment by feng-tao** [comment]
I recall we have a pr to do that @ttannis @danwom ? or that pr never make it to the end?

**Comment by andrew-oreshko** [comment]
@feng-tao could you please point me to that PR ?

**Comment by feng-tao** [comment]
@andrew-oreshko I believe this one https://github.com/lyft/amundsenfrontendlibrary/pull/248 (cc @danwom  @ttannis in case you are around to confirm and maybe we could revisit that pr and get it to finish line?)

**Comment by tusharsadhwani** [comment]
Any updates on this?
What's the fastest way to iterate on the react part of the application without having to rebuild the whole frontend project as of now?

**Comment by dorianj** [comment]
https://github.com/lyft/amundsenfrontendlibrary/pull/534 doesn't implement full hot reload, but does remove need to rebuild the server.
