### ISSUE TITLE
The terms `schema` and `db` can have multiple meanings and confusing

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#41]
The terminology used for Amundsen table URI is a bit confusing and people can interpret that in multiple ways. We should make them consistent as what is being used normally. 

As per @feng-tao [here](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1553547523009800): I think the `schema` term at Amundsen is same as database (e.g `create database`) while `database` is used to define the system(`hive`, `redshift` etc). 

And Amundsen is using these terms to generate table URN `{db}://{cluster}.{schema}/{table}`

In my opinion both terms are overloaded somehow, schema means table columns and in Amundsen we are using as database `<this thing>.table`, while database means physical database, and also `<this thing>.table`. I think we need to have a 3rd term here. 

I propose to use a different term for the system itself, and use `db` instead of `schema`.
Something like this: `{system|type|db_type}://{cluster}.{db}/{table}`

@feng-tao @jinhyukchang

**Comment by feng-tao** [comment]
I don't think it is an issue given we have use the term for more than 2 years now.
