### ISSUE TITLE
Design lineage UI

### ISSUE THREAD

**Issue by bolkedebruin** [amundsen-io/amundsen#42]
Lineage information should be displayed in the UI. Atlas shows the following

<img width="464" alt="Screenshot 2019-04-28 at 18 02 21" src="https://user-images.githubusercontent.com/4282712/56869858-a01b4300-6a06-11e9-9637-cfd388da5722.png">

Which should be more "Amundsen" like

**Comment by feng-tao** [comment]
with lineage RFC, I think we could close this issue now.
