### ISSUE TITLE
Setup PyUp to automatically update the python dependencies

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#44]
Free for open source projects, automatically creates Pull Request to update python dependencies.

https://pyup.io/

We are using this in python atlas client. 
ref PRs: https://github.com/jpoullet2000/atlasclient/pulls?q=is%3Apr+is%3Aclosed+author%3Apyup-bot

**Comment by dorianj** [comment]
We're using dependabot for this, so I think this is fulfilled.
