### ISSUE TITLE
Markdown in column descriptions renders as raw text when collapsed

### ISSUE THREAD

**Issue by jdavidheiser** [amundsen-io/amundsen#441]
When showing the single-line preview for Markdown descriptions, Markdown content like links is rendered as the raw text.  When expanded, the text renders as Markdown as expected.

This may be tricky to solve elegantly, because ideally you'd want to render the first line, but ignore things like multiline code blocks or bulleted lists.

![expanded](https://user-images.githubusercontent.com/3308182/81862311-612b3300-951e-11ea-9a4e-c182723cd861.png)
![collapsed](https://user-images.githubusercontent.com/3308182/81862320-62f4f680-951e-11ea-8606-f764343e229a.png)

**Comment by ttannis** [comment]
@jdavidheiser I tried to reproduce and it looks like the issue is currently fix on master. Please reopen if you are somehow able to still reproduce with the latest code.

**Comment by mparaz** [comment]
Hi, I'm seeing this issue with the current `master` - `9d558af458c3545249daafb5b44c48fbf3746a6a` 

This is using the sample data loader.

Collapsed:
![amundsen-markdown1](https://user-images.githubusercontent.com/838336/105627694-74074d00-5e8c-11eb-8ac1-1bb5e9e463ea.png)

Expanded:
![amundsen-markdown2](https://user-images.githubusercontent.com/838336/105627572-d3189200-5e8b-11eb-9f18-8715f6514bbb.png)
