### ISSUE TITLE
Support versioning of Tables in amundsen

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#45]
To explore the historical metadata, we should support the versioning of tables in Amundsen to understand what changed in each version of Table. 
There would be a detail page for each version of a table, including the column information of that particular version. 

Apache Atlas provides this information in the form of "Deleted" Table and Columns entities, and can be filtered out using the `entityStatus` attribute.

**Comment by jornh** [comment]
## Roadmap link

https://github.com/lyft/amundsen/blob/master/docs/roadmap.md#versioning-system
