### ISSUE TITLE
Enable --strictNullChecks

### ISSUE THREAD

**Issue by ttannis** [amundsen-io/amundsen#47]
Enabling `--strictNullChecks` helps us better leverage TypeScript to ensure that if we write code that attempts to access a property of a null or undefined variable, the error will be caught. Expect that many of our type definitions will have to be updated as well.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html

Right now, we are using betterer to keep track of regressions on this side. This ticket will be done once we are ready to remove our betterer check.

**Comment by Golodhros** [comment]
We integrated betterer for checking for strict Null infractions on https://github.com/amundsen-io/amundsenfrontendlibrary/pull/598

There are a lot of warnings now, so this is still an issue.

**Comment by Golodhros** [comment]
Finished on https://github.com/amundsen-io/amundsenfrontendlibrary/pull/758
