### ISSUE TITLE
Failed search for one resource (e.g., user or dashboard) causes no results to show for any resource

### ISSUE THREAD

**Issue by jonhehir** [amundsen-io/amundsen#473]
Right now, if any one of the search requests returns a non-200 status, it causes any search from the search bar to return no results. This can happen, for example, by simply enabling `indexUsers` or `indexDashboards` before importing any data for those resources. In this case, searching for any table will return no results (unless you explicitly search for only tables via the sidebar of the search page).

## Expected Behavior

If the search results succeed on the backend for a given resource (e.g., table), it should show on the frontend.

## Current Behavior

This currently only happens if the search request succeeds for all search types (e.g., table, user, dashboard).

## Possible Solutions

- Modify the frontend to display search results from any successful search rather than requiring all searches to succeed. (In the case of any single failure, the frontend merely shows "no results" for all resource types.)
- Modify the search service to more gracefully handle the case when a search index does not yet exist.

## Steps to Reproduce

1. Follow the instructions for [bootstrapping an Amundsen install in Docker](https://github.com/lyft/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker), including the loading of sample data via `sample_data_loader.py`.
2. Search for `test`. Test tables should appear in the search results.
3. Enable `indexUsers` and `indexDashboards` in `config-custom.ts`.
4. Search for `test` again. No results will appear.

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/745011/83307916-b2504d80-a1d3-11ea-8f55-61aa2afd94ef.png)

![image](https://user-images.githubusercontent.com/745011/83308083-fe02f700-a1d3-11ea-8bee-4479dac01c89.png)

## Your Environment

Recent checkout of Amundsen repo running through packaged `docker-amundsen.yml`.

**Comment by feng-tao** [comment]
@ttannis do you know what happens ?

**Comment by jonhehir** [comment]
I believe the front-end behavior stems from the `all()` effect used to combine the three searches here: https://github.com/lyft/amundsenfrontendlibrary/blob/6b324c8b3ed26263ae44a17cb13789af729b2a8a/amundsen_application/static/js/ducks/search/sagas.ts#L216. I didn't see an easy way to modify this behavior, so I opened this issue instead. 😄

**Comment by ttannis** [comment]
> @ttannis do you know what happens ?

@jonhehir is correct. I'm aware of the issue but haven't gotten around to it yet.

**Comment by feng-tao** [comment]
Ah i see, so if we enable user/dashboard entity, we assume there are data return...

**Comment by feng-tao** [comment]
cc @allisonsuarez
