### ISSUE TITLE
Column aliases (column clean names)

### ISSUE THREAD

**Issue by andrey-oreshko** [amundsen-io/amundsen#481]
Hi there! We as LavaMap (lavamap.com) are going to actively use this software. Thanks all of you who worked hard to create such an amazing product! However, we suggest to add some feature, called "clean names". The goal of it is to provide aliases for the column and table names. On our side data structures are created by engineers and often not understood by non-technical stakeholders, so we would like to add the ability to create a human readable name. We have already made this feature in our fork and would like to share this with you. Mostly it's pretty similar to the column/table description but it is also searchable. I'm also aware of the "programmatic descriptions" concept but i'm not really sure this fits here well as we want to make aliases editable, which i think programmatic descriptions don't allow to do. 

We are glad to hear any thoughts, concerns, suggestions from you, guys. Thanks for attention!

## Expected Behavior or Use Case
1. Ability to add clean name for column same way as description.
2. Ability to add clean name for table same way as description.
3. Clean names are supposed to be searchable and editable.

## Service or Ingestion ETL
Affects each of 5 repos

## Possible Implementation
In our fork we used same approach as for the column/table descriptions

## Example Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/65236498/83418033-9941d980-a42b-11ea-9b90-d6bfe50b6914.png)

**Comment by feng-tao** [comment]
cc @markgrover @danwom PM for fYI

**Comment by feng-tao** [comment]
hey @andrey-oreshko , thanks for the info. And glad to hear that your team is using Amundsen. Do you think we could add your company to https://github.com/lyft/amundsen#who-uses-amundsen ? Thanks.

**Comment by markgrover** [comment]
Thanks Andrey! Appreciate you contributing. I think this could warrant a good discussion. Right now, it seems like clean name is very similar to a description.

Can you share an benign example of this? What's the column name? What's the clean name? What's the description? 

Also, I'd be curious if the column name and clean name apply across tables? For example, if column name is "app_id", clean name is "application ID based on v3 of the LavaMap app". Does that mean that app_id in other tables also should have a clean name?

cc @kbaekgit as fyi

**Comment by andrey-oreshko** [comment]
@markgrover thanks for the response!

For the moment it is not necessary for us to share clean names across tables.

And the one clear example of why we need clean names: as many DB's are case-sensitive(because of that our fields are mostly lowercased) and don't allow you to add spaces it's sometimes become a problem to read them easily because of all lowercased letters and underscores. If we are looking through our data catalog we would like to easily see the field names. We could easily run the field names through some regex and create clean titles btw. We would like the description to be reserved for details about the field like where the data comes from or how the field works when the title itself is not clear.

**Comment by markgrover** [comment]
Thanks Andrey. @feng-tao thoughts on this? This seems similar to having a programmatic description for a column and a human curated description for a column. And, I am supportive of such a construct. I am not sure if I like the name "clean name" per se, but the underlying construct seems usable. What do you think, Tao?
