### ISSUE TITLE
Transient Docker pull timeout from Travis.

### ISSUE THREAD

**Issue by jinhyukchang** [amundsen-io/amundsen#49]
This is known issue from Travis
https://github.com/travis-ci/travis-ci/issues/9127

One action item from Amundsen:
- Research if there's a way to get a notification of failure

**Comment by jornh** [comment]
@jinhyukchang is this still relevant?

I guess with the recent wave of 2.0.0 builds (thanks! good work btw) you have the knowledge on if it’s working flawlessly or not.

**Comment by jornh** [comment]
As per https://github.com/amundsen-io/amundsen/issues/537#issuecomment-675760763 builds are now on GitHub workflow instead of Travis. 

Guess this also means #49 isn’t relevant any more?

**Comment by feng-tao** [comment]
thanks @jornh for the heads up!
