### ISSUE TITLE
Notification icon for Announcements

### ISSUE THREAD

**Issue by mgorsk1** [amundsen-io/amundsen#499]
Currently Announcements feature in Amundsen Frontend doesn't provide any information to the user that there is a new announcement to read. Because of that, user have to consciously visit Announcements page to notice it.

## Expected Behavior or Use Case
When there is a new announcement that user didn't see, frontend displays icon with number of unread announcements near **Announcements** link in top bar.

## Service or Ingestion ETL
Frontend

## Possible Implementation
Notification icon like in mobile apps - notification indicator with counter.

Simpler version: Indicator displayed for every announcement which is up to X days old (configuration option) 

Complex version: Indicator is `user aware` and shows counter with announcements unread by user.

## Example Screenshots (if appropriate):
Indicator for unread emails:

![image](https://user-images.githubusercontent.com/5680655/84129329-209dd700-aa42-11ea-8f7e-838b4cebc18b.png)

## Context
We are considering using Announcements as a hub for all notifications around our data. For that, we need a solution that will be used by users and encourage them to read new announcements. UI part is quite significant in this regard as in it's current shape it's easy to miss out on announcements.

**Comment by feng-tao** [comment]
cc @ttannis @Golodhros 
interesting idea as we just talked about the announcement is easy missed out for our users as well.

**Comment by Golodhros** [comment]
Looks like a useful feature indeed. A bit far from the main use of the application, but useful nonetheless.

I guess we would use a client-side only persistence mechanism to mark the unread notifications, right?

**Comment by jornh** [comment]
With https://github.com/amundsen-io/amundsenfrontendlibrary/pull/591 has this feature request been fulfilled?

What got implemented is not just an “unread indicator” but a feed on the front page: https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/application_config.md#announcements-config

**Comment by Golodhros** [comment]
> With [amundsen-io/amundsenfrontendlibrary#591](https://github.com/amundsen-io/amundsenfrontendlibrary/pull/591) has this feature request been fulfilled?
Nope, it didn't include a badge, but the Announcements block got a lot more visibility.
