### ISSUE TITLE
Adopt Airbnb-Typescript Code Guidelines on the Frontend library

### ISSUE THREAD

**Issue by Golodhros** [amundsen-io/amundsen#502]
We have setup code linting with ESLint and added some basic rules like the 'react/recommended' to our project.

To make sure we use best practices, reduce our code review effort and provide the best developer experience for our contributors, I suggest to extend the linting rules with the Airbnb rules for Typescript.

## Possible Implementation
This rules are already added on the system, but they trigger warnings at the moment. The work on this ticket would entail removing the warnings so they become errors and one by one, fix those issues.

## Context
Following strict coding rules for our code benefits Amundsen as:

- We spend less time on code reviews
- We provide a great developer experience to our contributors, increasing the chances of obtaining more help and reducing churn
- We signal that we are a serious project that care about code quality and good practices
- We make subsequent changes easier

**Comment by feng-tao** [comment]
cc @ttannis , I think we need to apply the keep fresh label as well, or we remove the stalebot in this repo.

**Comment by ttannis** [comment]
> cc @ttannis , I think we need to apply the keep fresh label as well, or we remove the stalebot in this repo.

I wouldn't remind removing it if we can
