### ISSUE TITLE
Use 'raise_for_status' in python API calls

### ISSUE THREAD

**Issue by danwom** [amundsen-io/amundsen#51]
> If the response is not a success message, this would not go in the Exception block, and will raise exception when try to proceed normal try block.
> I think you should call raise_for_status() method of response, to properly raise the exception.
> 
> Also, the whole try except block is repetitive, how about make this a decorator?

https://github.com/lyft/amundsenfrontendlibrary/pull/156/files/11ead489d7a46d12f986aa0d673c313d74cbb81b#r287533106

**Comment by sourvad** [comment]
Can I work on this?

**Comment by dorianj** [comment]
@sourvad yes, we'd gladly accept patches for this!

**Comment by sourvad** [comment]
Thank you!
