### ISSUE TITLE
Updating Tags does not update Elastic Indexes

### ISSUE THREAD

**Issue by rjindal02** [amundsen-io/amundsen#52]
When updating "Tags" from frontend, it does update backend Neo4j but does not update Elastic indexes. Hence, once tags are updated, they are not searchable.

**Comment by jornh** [comment]
I’d say a PR towards ticking the last box in https://github.com/lyft/amundsen/issues/52#issuecomment-500339360 after the search service now has got the API endpoint needed (as added in https://github.com/lyft/amundsensearchlibrary/pull/40) would be most welcome!

If anyone wants to have a go at this and need a bit of guidance just give a shout 😄

**Comment by jornh** [comment]
PR to fix this issue: https://github.com/lyft/amundsenmetadatalibrary/pull/76

**Comment by alran** [comment]
Still looking for review on this PR! https://github.com/lyft/amundsenmetadatalibrary/pull/76

**Comment by markgrover** [comment]
Keeping this issue up-to-date, another solution being proposed at https://github.com/amundsen-io/amundsenfrontendlibrary/pull/883

**Comment by feng-tao** [comment]
the fix is merged now.
