### ISSUE TITLE
feat: Gracefully hide missing fields in front-end (e.g., Dashboard fields that cannot be populated)

### ISSUE THREAD

**Issue by jonhehir** [amundsen-io/amundsen#544]
As mentioned in today's community meeting, when ingesting Redash dashboards into Amundsen, there are some dashboard-related fields that we are not able to populate, due to discrepancies in the data models between Redash and Amundsen. I expect this problem to be more general than this specific case, since in general, not every data product will have matching schemas.

## Expected Behavior or Use Case

When a field is completely missing, it would be nice to hide it rather than display it with an empty value. I will admit that this is not necessarily a trivial problem, since this ultimately gets at whether the missingness of the data is expected. There may be some cases where missing data is a case we want to display in the UI, while in other cases, it is expected, and the cleanest solution for the user is to hide the field entirely.

## Service or Ingestion ETL

Front-end

## Possible Implementation

The simplest solution here is to hide fields like dashboard timestamps and view counts when the fields are completely missing. This would probably come with the drawback that, for example, a dashboard with a recent view count of 0 is likely to have no `DashboardUsage` stored rather than a `DashboardUsage` record with a view count of 0, causing the view counter to disappear in this case. This would require explicitly inserting zeroes in such cases.

I imagine there are other ways this could be dealt with as well, e.g., allowing for some configuration of when to show/hide certain fields. Some of these options could likely get messy.

**Comment by ttannis** [comment]
One concept that I want to make sure we keep in mind with this is the difference between data not being supported, and data being supported but having no value. The frontend deals with the second concept by either not showing it OR showing a special "empty state" UI. In terms of the first concept, my perspective is that if the data is not supported we should address it at the source and it should not be sent to the frontend in the first place.

**Comment by feng-tao** [comment]
with https://github.com/amundsen-io/amundsenfrontendlibrary/pull/814, we could close this issue now.
