### ISSUE TITLE
feat: Support uneditable descriptions in dashboards

### ISSUE THREAD

**Issue by jonhehir** [amundsen-io/amundsen#545]
https://github.com/lyft/amundsenfrontendlibrary/pull/497 provides a way to make descriptions uneditable for tables and columns. It would be nice to support this for dashboards as well.

Note: Dashboard descriptions in general do not seem to be a very mature feature. Even editing descriptions more generally is likely going to need to evolve. For now, though, being able to disable whatever sort of editing feature/link exists would be nice.

## Service

Front-end

## Context

Redash dashboards do not have descriptions. Currently, the Amundsen front-end displays an edit link back to Redash in the description field for a Redash dashboard. It would be nice to suppress this.

**Comment by feng-tao** [comment]
cc @ttannis @dikshathakur3119
