### ISSUE TITLE
feat: Store relationships between queries and tables

### ISSUE THREAD

**Issue by jonhehir** [amundsen-io/amundsen#547]
As mentioned in today's community meeting, the current method of associating dashboards to tables is through a relationship between dashboards and tables. There is no relationship stored between _queries_ and tables. It seems to me that storing a relationship between queries and tables would be an easy add that would allow for greater flexibility in terms of how we use the data.

## Service or Ingestion ETL

Metadata

## Possible Implementation

- Option 1: Store the relationship between queries and tables _instead of_ between dashboards and tables. Dashboard--table relationships would only exist through intermediate query nodes.
- Option 2: Store the relationship between queries and tables _in addition to_ the relationship between dashboards and tables. This would require no immediate changes but would store additional relationships for potential use.

## Context

I have no real immediate use-case for this, but this would potentially be useful for displaying example queries directly on tables (rather than showing relevant dashboards and making the user find the query) or even example queries that join some set of tables.

**Comment by feng-tao** [comment]
thanks @jonhehir for putting lots of great details on improving the project!

**Comment by feng-tao** [comment]
also I wonder whether it is now a good time to put asana as one of Amundsen users in https://github.com/lyft/amundsen#who-uses-amundsen given all the great work you and your team is doing ? also cc @jdavidheiser

**Comment by dorianj** [comment]
RFC for this https://github.com/amundsen-io/rfcs/pull/27, would love your thoughts @jonhehir

**Comment by jdavidheiser** [comment]
Jon may not be available (his internship where he worked on this ended a while ago), but I have some context on what he was doing, so will take a look.

**Comment by jonhehir** [comment]
Hey, folks! Sorry for the delayed response. As @jdavidheiser mentioned,  I'm out of the internship and back on the grad school grind, so this isn't something I'm focused on currently. I'll leave a few comments in the RFC, though. Thanks!
