### ISSUE TITLE
Feature request - knowledge posts/repository

### ISSUE THREAD

**Issue by tpcarrier** [amundsen-io/amundsen#55]
As a 'data discovery' platform, I should aim to empower users across my organization to make better decisions - based on data. I should allow new users to onboard quicker to the organization and learn about the business, help users answer (most of) their own 'data' questions through past analysis, and reduce the barriers of access to analyze data on questions that have yet to be answered.

Once analysis has been done on a 'data' questions, the results are often saved or archived in the form of a wiki or knowledge post. For Airbnb + Lyft...Knowledge Repo + Stache Overflow.

https://github.com/airbnb/knowledge-repo
https://stackoverflow.com/teams

Although this is not a concrete implementation plan - the story should be the same = **within amundsen, I should be able to search past analysis or knowledge posts (created and connected to users on the platform), ranked by popularity, has owners, followers, etc.**

**Comment by jdavidheiser** [comment]
We no longer use Knowledge Repo, but have been tossing around an idea about indexing notebooks served on our internal Jupyter nbviewer.  I think this is a great idea!

**Comment by tpcarrier** [comment]
Interesting @jdavidheiser - main inspiration would be like stackoverflow for code but for data 'stories'. Would solve the problem data users of "hey do we have analysis on _______" and ultimately would be an evolution of 'data artifacts' from an amundsen-like tool.
