### ISSUE TITLE
databuilder: clean up py2 references in the repo

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#560]
## Expected Behavior
Remove all the py2 related codes.
- remove six
- remove py2 CI
- (bonus) change typing from py2 to mypy py3 

## Current Behavior
databuilder supports both py2 and py3 and we should remove py2 for now as py2 is already EOL.

**Comment by dorianj** [comment]
Started on this in https://github.com/lyft/amundsendatabuilder/pull/310, will follow-up with typing changes once that lands
