### ISSUE TITLE
chore: apply license headers to all the files for all the repos of Amundsen projects

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#562]
## Expected Behavior or Use Case
Apply the following headers:
```
# Copyright Contributors to the Amundsen project.
# SPDX-License-Identifier: Apache-2.0

```
to all the source files

**Comment by morrme** [comment]
@feng-tao  I've previously done this for a different project using https://github.com/google/addlicense .

**Comment by dorianj** [comment]
AFAIK this is done -- please re-open if not
