### ISSUE TITLE
Feature request for improve browsing、searching and description management for column.

### ISSUE THREAD

**Issue by damon09273** [amundsen-io/amundsen#579]
I have applied Amundsen to our company since 3 months ago, my colleagues become favorite user of Amundsen (one hundred people).

Here are some feedbacks from daily usage of them, hope it’s helpful for reference of feature updating.

## Expected Behavior or Use Case

- All table browsing：Hoping some where can browse all tables.
- Browsing by tag level or multiple tag searching：Hoping there’s feature like tag level or multiple tag searching.
- A Column description can be used for multiple table and editing synchronize.

## Service or Ingestion ETL
- Frontend
- Elasticsearch

### All table browsing
Add a button in navigation, maybe call it _Browsing_, and show all table with schema by list.

### Browsing by tag level 
For example, feature Follow can be using follow against 3 object：
Forum > Follow > Post
Forum > Follow > User
Forum > Follow > Topic

###  Multiple tag searching
Follow + Post + DailySnapshot(Grain of data)
Follow + Post + RawData(Grain of data) 

### Common column with editing synchronize
User can create a common column description by Web UI.
A common column description can be added to multiple table.

### All table browsing
Because there’s no keyword in mind of some user, especially for new co-worker .

###  Browsing by tag level
It's an efficiency way for information browsing.

###  Multiple tag searching
Get more specific result by input multiple Tag.

### Common column with editing synchronize
Some column had a lot of attributes, appears in multiple table, updating frequently, and generated by non-technical guys.

**Comment by jerryzhu2007** [comment]
It will be good to have All table browsing

**Comment by ArthurEgide** [comment]
All table browsing it's awesome! I'm needing this feature.
The others features that u said it's very good too

**Comment by Golodhros** [comment]
For the all table browsing, this issue is related: https://github.com/amundsen-io/amundsen/issues/138

**Comment by Golodhros** [comment]
There is multiple tag searching since we added comma separated filtering in the search page
