### ISSUE TITLE
Frontend changes aren't getting reflected even after npm run dev-build

### ISSUE THREAD

**Issue by sarthak3097** [amundsen-io/amundsen#585]
### **General summary** 
I was trying to make UI changes (text present on the the frontend) like the Footer, the Title of the page, etc. through the following files-
amundsen/amundsenfrontendlibrary/amundsen_application/static/js/components/Footer/index.tcs

For all the small changes, I tried to change the constants.ts and index.tcs files in - 
amundsen/amundsenfrontendlibrary/amundsen_application/static/js/components/

I tried hard coding the changes and running the following build commands - 
-- In ~/<your-path-to-cloned-repo>/amundsenfrontendlibrary/amundsen_application
$ cd static
$ npm install --only=dev
-- In ~/<your-path-to-cloned-repo>/amundsenfrontendlibrary/amundsen_application
$ cd static
$ npm run dev-build # builds the development bundle

### **Existing open and closed issues  -->**
Tried the following to make the UI changes
Developer guide - https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md

https://github.com/EarnestResearch/hackethon-remote-2020-amundsen/issues/4
https://app.slack.com/client/TGFR0CZM3/CGFBVT23V/thread/CGFBVT23V-1584468280.274800

### **Expected Behavior**
The changes in the footer, title of page and all related changes should be reflected in the UI

### **Current Behavior**
Even though the build is successful, there are no changes being reflected in the UI.

**Comment by feng-tao** [comment]
cc @ttannis @dikshathakur3119 @allisonsuarez

**Comment by ttannis** [comment]
This will be better for our #troubleshooting channel as it is an issue of helping with your process and/or environment vs. a bug with code, but to start:
1. Can you do a hard reload of your page to ensure your browser is not keeping a cached version of the previous build?
2. Is there any difference when running `npm run build`?

**Comment by sarthak3097** [comment]
1. I did try a hard refresh, no success.
2. I just tried that as well and got a similar result.

I also tried to see if there is a change in the frontend docker container after I executed  `npm run build ` , but there wasn't. I feel that is where the change should get reflected.

**Comment by sarthak3097** [comment]
I'm trying to run all the services together on a docker, not using standalone services.

**Comment by jornh** [comment]
How are you building the docker frontend container? Are you following https://github.com/lyft/amundsen/blob/master/docs/developer_guide.md? - otherwise please share your exact steps.

As I tried to express in https://github.com/lyft/amundsen/issues/190 I fear the two build methods (with/without docker) interfere with each other. 

I didn't get to the bottom of figuring out how to introduce this properly - but try adding **this** to https://github.com/lyft/amundsenfrontendlibrary/blob/master/.dockerignore and see if it fixes the issue for you:

``` 
amundsen_application/static/node_modules/
amundsen_application/static/dist/
```

If that doesn't resolve the issue try adding these as well:
```
venv/
amundsen_frontend.egg-info/
```

**Comment by jornh** [comment]
@sarthak3097 did you have a chance to test if the suggested `.gitignore` changes above helped?

**Comment by sarthak3097** [comment]
Hi jornh, 
Sorry for the late response. Was trying few things. 

https://github.com/lyft/amundsen/blob/master/docs/developer_guide.md?  
This did help to quite a large extent. 

But I had to configure few changes in the docker file. 
So basically, this document is to make changes to the docker-amundsen-local.yml 
So to make changes in the actual frontend, I tried to replicate the same code in the docker-amundsen.yml and had to change a few things like : 

I commented out this statement in the docker-amundsen.yml  in the frontend container becuase there were error occurring in bringing the frontend container up - 
command: gunicorn -w 2 --bind :5000 amundsen_application.wsgi

After this I was able to make all changes in the frontend, changing logo, footer, title, etc.

But I wasn't sure if it is a stable solution and wanted to ask the same.

**Comment by sarthak3097** [comment]
Didn't get the chance to check this - `.gitignore`
Will check it by today and get back to you.

Thank you for the suggestions though, they were pretty helpful.

**Comment by jornh** [comment]
Surprised Gunicorn gave you an error. It’s been working in the official builds so far. What error/stack trace did you get?

Would appreciate if you could try the gitignore suggestions.

**Comment by dorianj** [comment]
Are you still seeing this @sarthak3097 ?

**Comment by sunanda3055** [comment]
I am also unable to see the React/Scss changes reflecting in the browser after 'npm run build'.

To see my changes, I have to again install the resources and then again start the server with the command 'python3 amundsen_application/wsgi.py'

Please let me know another way to reflect my changes immediately on the browser without, again installing the python resources every time/

**Comment by dorianj** [comment]
@sunanda3055  can you try running `npm run watch`?

**Comment by dorianj** [comment]
@sunanda3055 Please comment if this still isn't working :)

**Comment by mateusmtm** [comment]
@sarthak3097 did you manage to solve this problem?
