### ISSUE TITLE
Feature request: Looker dashboard extractor

### ISSUE THREAD

**Issue by minsuo** [amundsen-io/amundsen#586]
## Expected Behavior or Use Case
Looker dashboard extractor, similar to other dashboard extractors for populating dashboard metadata.

## Service or Ingestion ETL
Dashboard extractor for amundsendatabuilder, which can either leverage Looker API or an org's looker code repo as a source for metadata.

## Possible Implementation
Currently have a coworker developing an implementation utilizing the API, though we might leverage repo code as well.

## Context
Aside from working directly with tables, dashboards are a popular medium in how we consume data.  We currently use Looker and it would be great to have an extractor following the same direction as other dashboard extractors for leveraging any future developments like data lineage between tables and dashboard objects.

**Comment by feng-tao** [comment]
thanks @minsuo , also could we add Brex to the Amundsen user list(https://github.com/lyft/amundsen#who-uses-amundsen) ? Thanks.

**Comment by feng-tao** [comment]
Also linked the previous discussion from slack (https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1594809182111500?thread_ts=1594219120.056200&cid=CGFBVT23V) about looker extractor support. 

References:
- https://medium.com/google-cloud/google-cloud-data-catalog-and-looker-integration-4ebefdef6a34
- https://github.com/GoogleCloudPlatform/datacatalog-connectors

**Comment by markgrover** [comment]
Also, another related thread: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1597970165017500

**Comment by markgrover** [comment]
Another related thread: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1597970165017500
