### ISSUE TITLE
TTransport.TTransportException: TSocket read 0 byte for Thrift Hive metastore

### ISSUE THREAD

**Issue by vikalpmullick** [amundsen-io/amundsen#591]
**Objective**: Extract metadata from Hive Tables

**Connection Script**:  amundsendatabuilder/example/dags/hive_sample_dag.py
**Hive Connection String** : "hive://10.x.x.x:9083"
SUPPORTED_HIVE_SCHEMAS =['default']

**HIVE Version** 
Cloudera CDH-6.1.1-1
hive-common-2.1.1-cdh6.1.1.jar

Python 3.7 

**hive-site.xml**
hive.server2.authentication = NONE
hive.metastore.uris = thrift://10.x.x.x:9083
hive.server2.transport.mode = binary

## Expected Behavior
Read metadata from Hive and ingest in Neo4j and Elastic search

## Current Behavior
**Error**: thrift.transport.TTransport.TTransportException: TSocket read 0 byte
![image](https://user-images.githubusercontent.com/68067507/89184059-d0607280-d5b5-11ea-8199-01b4f1d878d5.png)
(Pls excuse for bad image)

I have taken latest version of amundsen code.

**Comment by Alagappan** [comment]
@vikalpmullick Please post on #troubleshoot slack channel. Might be good to post exception trace as text there.

**Comment by feng-tao** [comment]
the connection string should be the sqlchemy string for the hive metastore.

**Comment by jornh** [comment]
@feng-tao sounds like a doc or example clarification might help. Seems several have stumbled on it.

**Comment by vikalpmullick** [comment]
@feng-tao @jornh Could you pls give me an example for it, or let me know wht am i missing on here?

**Comment by jornh** [comment]
I’m not using Hive myself. So found a previous thread on Slack.

Source: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1567015023009900?thread_ts=1565830431.396400&channel=CGFBVT23V&message_ts=1567015023.009900

So I guess for Derby you’d have to use a Sqlalchemy connection string starting with `derby://...` not `hive://...` as you said you’re currently trying to use.

Not sure if there are any other differences for Derby. Recently some issues in this repo and PRs in the databuilder repo have been going around.

**Comment by jornh** [comment]
Also to repeat my own comment from that old Slack thread:

> Thanks also @Jin (Lyft) but the README use example only explains how to call the Extractors API, not which driver it is using, neither does the example DAG really reveal it: https://github.com/lyft/amundsendatabuilder/blob/v1.4.0/example/dags/sample_dag.py#L58-L60

Let alone that either the README or the sample code could give sample connection strings. But I’ll leave that to you as I *could* add stuff there but I think it’s better to have it contributed by someone who has actually tested it out themselves. 🙂

**Comment by vikalpmullick** [comment]
@Alagappan @jornh i am not able to access the above slack channel? Pls let me know hoe to check it. Is it an invite based channel? (vikalpmullick@gmail.com)

**Comment by jornh** [comment]
No it's in the public #amundsen channel. But it's a 11-12 month old thread now.

Find icon link to join Amundsen Slack in the README.md in this repo.

And ... main message for you to try first is probably:
> So I guess for Derby you’d have to use a Sqlalchemy connection string starting with derby://... not hive://... as you said you’re currently trying to use.

as I said above.

**Comment by jornh** [comment]
Related PR: https://github.com/lyft/amundsendatabuilder/pull/312 
Related issue: #552

**Comment by jornh** [comment]
@vikalpmullick any news on your end here? The PR #552 got merged and should be part of databuilder 3.0.0.

**Comment by feng-tao** [comment]
close it now. Feel free to reopen if the issue persists.
