### ISSUE TITLE
Bug: Neo4j Node key format is confused It is necessary to decide whether to allow uppercase.

### ISSUE THREAD

**Issue by bogo96** [amundsen-io/amundsen#596]
## Structure
The Extractor returns some model class implemented in databuilder/models.
In each model class, there are functions like ```get_table_key```, ```get_col_key``` which makes ```key``` of neo4j. node.

## Problem
We use ```TableColumnStats``` class (databuilder/models/table_stats.py) for extracting column statistics.
The ```__init__``` function of ```TableColumnStats``` convert table_name, schema, col_name to lower case like below.
```
self.table = table_name.lower()
```
But, ```TableMetadata``` class doesn't. It allows capital letter.

Then, when publisher send query to neo4j with csv file which made by extractor, statistic node cannot find column node.
statistic node try to find column nodes which has ```'postgres://cluster.schema/tablename/columnname'``` key but the column node's key is ```'postgres://cluster.schema/TableName/columnName'``` 

I think this issue should be decided. 
Some model convert every name(db, schema, stat_name, table etc..) to lower case, but others not.

## Suggestion
In my opinion, converting name to lower case isn't good because some DBs allow capital letters in table name.
If user register their dataset, I think it's correct to display the original name instead of the lowercase name on the web page.

I'm wondering Amundsen's policy on this.

**Comment by feng-tao** [comment]
will take a look

**Comment by zer0pool** [comment]
@feng-tao Any review on this issue?

**Comment by joshthoward** [comment]
@bogo96 We should be able to close this issue now. See the PR above.
