### ISSUE TITLE
Column based search is unimplemented in Atlas?

### ISSUE THREAD

**Issue by pPanda-beta** [amundsen-io/amundsen#597]
On amundsen advanced search, use a query term for column, and the xhr fails (that too silently without informing user)

## Expected Behavior
Should list down all the column entries and/or all the tables with that column

## Current Behavior
No results showup, api returns 500
Amundsen Search logs
```
    tables, approx_count = self._atlas_basic_search(query_params)
UnboundLocalError: local variable 'query_params' referenced before assignment
```

## Possible Solution

Reason: 
Looking at those lines it seems team had no intension to build the feature. If that is the case then please document the known limitations. In that case we would not have chosen amundsen if known beforehand . 

https://github.com/lyft/amundsensearchlibrary/blob/17c673903e2db3b1145af69fb31659d7be185eb4/search_service/proxy/atlas.py#L237-L240

Suggested solution (in case you change your mind to implement it): 
Use atlas basic search api 
`POST /api/atlas/v2/search/basic`
with this payload
```json
{
	"excludeDeletedEntities": true,
	"includeSubClassifications": true,
	"includeSubTypes": true,
	"includeClassificationAttributes": true,
	"entityFilters": null,
	"tagFilters": null,
	"attributes": [],
	"query": "😀 😀 Your fancy query string <3 ",
	"limit": 25,
	"offset": 0,
	"typeName": "Column",
	"classification": null,
	"termName": null
}
```

## Steps to Reproduce
1. Open the advanced search page
2. Choose a query string form column field
3. Click on apply
4. Or just visit `/search?resource=table&index=0&filters=%7B"column"%3A"your_fancy_query"%7D`

## Context
A simple explorer software like apache superset or metabase supports searching tables with free test. No one will use a new software if it only reinvents the same feature. Column searching could be at least some feature to take a stand for amundsen. 

## Your Environment
Amunsen version used:
dockerimages :
amundsendev/amundsen-search:2.4.0
amundsendev/amundsen-metadata:2.5.4
amundsendev/amundsen-frontend-oidc:2.2.2

Deployment: k8s behind ingress

**Comment by pPanda-beta** [comment]
# Same goes for schema as well :( 

when search_request = `{'type': 'AND', 'filters': {'schema': ['datasets']}}`
Rest of the flow is same as above...

**Comment by feng-tao** [comment]
cc @verdan or @mgorsk1

**Comment by mgorsk1** [comment]
Hey @pPanda-beta that's correct, when implementing first version of advanced-search with Atlas we only took into account following attributes: **database, table, cluster and tag (classification)**. This is because enabling advanced search by any other attribute mentioned by you (column name, schema) entails more complexity in implementation.

However, there was no `decision` not to support additional search filters, atlas proxy in amundsensearchlibrary can be extended with this support and we welcome any suggestion on how to approach this. Column search would, indeed, be very helpful. Using basic search for that'd require solving issue of deduplication and accurate total_count rendering (if using basic search for this).

@feng-tao not sure if bug or actually a feature request ?

**Comment by feng-tao** [comment]
I think it falls into the feature request category.

**Comment by pPanda-beta** [comment]
@feng-tao At least update the documentation / known limitations notes.

**Comment by pPanda-beta** [comment]
@mgorsk1 @feng-tao 
I've added this small chunk to start name based column searching on atlas. This solution is not perfect. It creates two rest calls for the search. Second call is only required to fetch table descriptions.

```python3
        column_filter_value = _filters.get('column')
        if column_filter_value:
            from collections import namedtuple
            query_body = self._prepare_basic_search_query(
                self.page_size, page_index, filters=[("name", "CONTAINS", column_filter_value[0])],
                entity_type="Column")
            search_results = self.atlas.search_basic.create(data={**query_body, "attributes": ["table"], "sortBy": None})
            columns = search_results.entities.to_dict()
            table_headers = [col["attributes"]["table"] for col in columns]
            unique_table_headers = {th["guid"]: th for th in table_headers}.values() # <<<<<< How to make it easy?
            table_proxy_entities = [namedtuple("Entity", th)(**th) for th in unique_table_headers]
            tables = self._prepare_tables(table_proxy_entities, enhance_metadata=True)
            return SearchTableResult(total_results=len(unique_table_headers), results=tables)

```

**Comment by mgorsk1** [comment]
With current atlas limitations in regard to search there is nothing more to be done on Amundsen side to improve this. If extended search capabilities are required from Atlas then the most efficient course of action is to bring it up with Atlas community directly. 

Alternatively, you might want to try out atlas search extractor from databuilder to sync Atlas with ES. This solution will give you search capabilities on both column names and descriptions.
