### ISSUE TITLE
Feature Proposal: Add support for displaying Primary Key/Partition column in table details page

### ISSUE THREAD

**Issue by Alagappan** [amundsen-io/amundsen#599]
## Expected Behavior or Use Case
Table details page should display which column(s) are Primary key and partition keys for the table. Please note not all databases support primary key so this needs to be enabled only for once that support it, for e.g., Snowflake

## Service or Ingestion ETL
All 3 amundsen services (`amundsenfrontend`, `amundsensearch` and `amundsenmetadata`) and `amundsendatabuilder` needs to be modified.

## Possible Implementation
We had a light discussion on #amundsen slack channel (see [thread](https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1596231043296100)). One way would be to add attributes to [ColumnMetadata](https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/models/table_metadata.py#L143) model to indicate if this column is primary key or partition key or both. Another implementation would be ( as mentioned in the thread) to do this via column level badges. 

We need to modify `amundsenfrontend`, `amundsenmetadata` and `amundsendatabuilder` just to highlight the column in table details. We can update the `amundsensearch` service if we would like to support advance search on primary and partition columns.

## Context
Displaying Primary and Partition key has been a top requested feature by analysts and data scientists. It helps them identify which column they need to use in their SQL filter by condition.

**Comment by Alagappan** [comment]
cc @feng-tao @markgrover @danwom

**Comment by feng-tao** [comment]
thanks @Alagappan

**Comment by Alagappan** [comment]
@feng-tao please let me know if I can help with anything on this feature (PR, design reviews, docs or code reviews)
