### ISSUE TITLE
Feature Proposal: Stored relationships/foreign keys between table columns

### ISSUE THREAD

**Issue by jfhbrook** [amundsen-io/amundsen#601]
## Expected Behavior or Use Case

I'm looking into adopting Amundsen at my workplace, and one feature request that's come up in this project which I don't see is support for encoding relationships between columns in various tables.

What I'm looking for is an extra thing in the column metadata panel that shows which other columns in other tables are related to each other. The obvious case here is foreign keys within a particular database, but I also have use cases for adding this metadata for data stores that don't support this directly, as well as for data stores that aren't technically joinable but for which the columns have the same semantics and definition anyway.

## Service or Ingestion ETL

This feature could be directly supported by any data source that supports foreign keys - that means the mysql, mssql, postgres, DBAPI and sqlalchemy extractors could all support it, and probably other extractors I'm not familiar with as well. In addition, a way to add this metadata "manually" would be great. I *think* this is a low lift for something like the CSV extractor.

## Possible Implementation

My feeling is that this would require extending the Column model to have a new Column -> Column relationship in neo4j named something like "ForeignKey", adding support for extracting the foreign key to the mysql, postgres, mssql and sqlalchemy extractors (try to keep the scope narrow), making sure this can also be done for more bespoke use cases, and finally add a field and link in the column metadata in the UI.

## Example Screenshots (if appropriate):

I'd like to see a widget show up here:

![image](https://user-images.githubusercontent.com/57536/89686226-fe9ec480-d8cb-11ea-9650-a5c435582e65.png)

I tried to quickly hack up something in the DOM but I don't know the classes and structure well enough to pants it in a way that's useful, but my thinking is that it would show up as a section similar to column statistics but expose an UL of relationships instead of key/value tables.

## Context

I work for an ads measurement company, and as you might imagine we generate a lot of data. That data lives in a bunch of different places and is touched by many different teams. We're getting big enough that finding the right datasets and understanding their context can be a challenge! Pretty typical situation for a growing company, I figure.

As with most people, the datasets I work with tend to form star schemas, with fact tables and dimension tables, and different columns in various tables will encode the same concept and be intended to be joined with each other. For an example: If I have a table of site metrics, it might have an ID that corresponds to a particular website, and I might have a dimension table about the content of that website which has a joinable key. It would be really slick if I could go to the page in Amundsen for the impressions table and discover the relevant dimension table and join columns by clicking.

We have data in databases that don't directly support foreign key constraints, such as Vertica, but for which we still generally join certain columns anyway (as in the fact/dim example). We also have datasets in other data stores, such as Hive and BigQuery, which wouldn't be joined directly but for which the semantics of the column are the same. Knowing that two datasets in different stores are related this way is still useful, since if two datasets are semantically joinable but don't live next to each other that can be fixed, and if two datasets are similar then that work might already be done.

**Comment by feng-tao** [comment]
We plan to add the support to surface PK/FK as column level badge in Q3/Q4. Let me tag @ttannis and share the mock and see if it fits the need.

**Comment by feng-tao** [comment]
also similar to https://github.com/lyft/amundsen/issues/599

The reason we think column badge is better is that we could decouple different column level metadata with the column model. This way makes it easier to extend to cover other column level use case as well.

**Comment by jfhbrook** [comment]
Nice! I don't have strong opinions (yet) about what the UI aspects would look like. I'm pretty new to Amundsen! I just wanted to try and be useful and follow the template. Definitely down to check out your mock-up and be an early user!
