### ISSUE TITLE
Add Extractors for Delta Lake Format

### ISSUE THREAD

**Issue by samshuster** [amundsen-io/amundsen#608]
This will add delta-lake table metadata and last updated extractors.
https://github.com/delta-io

## Expected Behavior or Use Case
Will fetch delta-lake metadata and ingest it into amundsen using databuilder extractors.

## Service or Ingestion ETL
databuilder

## Possible Implementation
It will require that the extractor is run on a spark cluster as my understanding is that is the only way to get at delta-lake metadata.

Due to performance reasons, it should incorporate a two phase pull. The first phase would actually loop through all tables and fetch the metadata which is then dumped into some sort of persistence layer. The second phase would then be different extractors that extracts the different pieces of metadata to send out to amundsen. The reason why this is important is that the scraping phase can take a very long time, but it returns lots of useful metadata, for example both last updated and column/table information. Because of this, it seems that we will want to persist the intermediate raw results.

## Context
Delta-lake has been a file format that various companies want to ingest into amundsen

**Comment by samshuster** [comment]
Just pointing out that I am making slow progress on this. My hope is to have a WIP MR out by early next week.

**Comment by samshuster** [comment]
Ok here is the WIP extractor here: https://github.com/amundsen-io/amundsendatabuilder/pull/351/files

I will try to tag some disney folks to take a look too as I know they do something similar.

Once approach is deemed ok, then I will circle back and think about how to add unit tests, clean up code (add type annotations), make it more configurable where possible and also add documentation

**Comment by jornh** [comment]
> It will require that the extractor is run on a spark cluster as my understanding is that is the only way to get at delta-lake metadata.

FYI just noticed there’s now a standalone connector not depending on Spark: https://github.com/delta-io/connectors/releases/tag/v0.2.0

**Comment by feng-tao** [comment]
the issue could be closed now as the code is merged and it works great!

**Comment by samshuster** [comment]
> > It will require that the extractor is run on a spark cluster as my understanding is that is the only way to get at delta-lake metadata.
> 
> FYI just noticed there’s now a standalone connector not depending on Spark: https://github.com/delta-io/connectors/releases/tag/v0.2.0

Ah nice find @jornh. I am sure this will be a path to simplify the current amundsen extractor (most importantly allowing it to run like other extractors do) in the future for anybody who wants to look into it. Looks like most important pieces of metadata can be obtained this way.
