### ISSUE TITLE
Add Storybook to the Frontend library

### ISSUE THREAD

**Issue by Golodhros** [amundsen-io/amundsen#611]
All projects create frontend components for their user interfaces. Amundsen has been creating some of these, and reusing others. However, it is not easy to understand what we have created before, the different styles we apply to them and if we have duplicates.

A storybook implementation will help us gather together our *presentational components*, making it easy to share, develop and evolve our UI, as well as keeping it consistent.

## Expected Behavior or Use Case
We will have a storybook page with examples of our components.

## Service or Ingestion ETL
Frontend Library

## Possible Implementation
Storybook for React

**Comment by dorianj** [comment]
I'm looking into this

**Comment by dorianj** [comment]
This is done

**Comment by Golodhros** [comment]
Thanks @dorianj !
