### ISSUE TITLE
[DOCS] Update references to github.com/lyft to be github.com/amundsen-io

### ISSUE THREAD

**Issue by markgrover** [amundsen-io/amundsen#615]
## Expected Behavior
Update the github references to be correct (i.e. under github.com/amundsen-io)

## Current Behavior
There's a bunch of places in docs, etc. where there are references to github.com/lyft.

**Comment by markgrover** [comment]
Also, btw, PRs will need to wait before we fix the Travis/PyPi setup to ensure tests are running.

**Comment by dorianj** [comment]
databuilder: https://github.com/amundsen-io/amundsendatabuilder/pull/323

**Comment by markgrover** [comment]
Thanks for picking this up, Dorian! Marking it here so I don't forget.
Repositories include all github.com/amundsen-io/amundsen* repositories (including github.com/amundsen-io/amundsen-io.github.io)

Regex'es that I can think of:
github.com/lyft/amundsen* -> github.com/amundsen-io/amundsen*
lyft.github.io/amundsen -> amundsen.io/amundsen

cc @Golodhros @feng-tao

**Comment by jornh** [comment]
I took a stab at the `amundsen` repo: https://github.com/amundsen-io/amundsen/pull/619

**Comment by dorianj** [comment]
common: https://github.com/amundsen-io/amundsencommon/pull/51

**Comment by dorianj** [comment]
mdl: https://github.com/amundsen-io/amundsenmetadatalibrary/pull/174

**Comment by dorianj** [comment]
sl: https://github.com/amundsen-io/amundsensearchlibrary/pull/133
