### ISSUE TITLE
Feature Proposal: Use github action instead travis for CI / CD

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#617]
## Expected Behavior or Use Case
Github action is easy to setup and maintained. We should use github action for all CI / CD in the long run instead of travis. Here is an example workflow(https://github.com/amundsen-io/amundsencommon/pull/47).

**Comment by feng-tao** [comment]
I will take a look next week once back.
cc @ttannis @Golodhros

**Comment by dorianj** [comment]
I haven't used GH actions much but I've worked a ton with circleci, I think I could make good progress on this without too much help -- can I pick this up?

**Comment by feng-tao** [comment]
Thanks @dorianj , but I think this one requires to access some passwords / token for the project in order to test it end 2 end (e.g upload pypi). I would still prefer to do it myself if it is ok to you.

**Comment by feng-tao** [comment]
all the prs are merged and we are 100% on github action now.
