### ISSUE TITLE
Bug Report: Clicking the link of Amundsen Logo on documentation site redirects to 404

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#630]
Clicking the Amundsen logo on the documentation site https://www.amundsen.io/amundsen/ navigates to 404. 

## Expected Behavior
Clicking the Amundsen logo should redirect users to the home page of the amundsen documentation. 

## Current Behavior
Clicking redirects to 404 page. i.e., `https://lyft.github.io/amundsen/`

## Possible Solution
href should be `https://www.amundsen.io/`

## Steps to Reproduce
1. Navigate to `https://www.amundsen.io/amundsen/`
2. Click the Amundsen logo on the top left corner
3. Clicking will redirect to `https://lyft.github.io/amundsen/`

## Your Environment
* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by feng-tao** [comment]
the issue should be fixed now. thanks for raising it.
