### ISSUE TITLE
Data Preview Fails for Selected Tables

### ISSUE THREAD

**Issue by debbielee1996** [amundsen-io/amundsen#631]
## Expected Behavior

Data preview should show all tables in the same database without problems.

## Current Behavior

Table not loading for this particular table.
![image](https://user-images.githubusercontent.com/62943444/90202816-5af46d80-de11-11ea-8bd7-c270cf6a06f0.png)

**Error message in debug mode:**
Triggering query_id: 6
INFO:superset.views.core:Triggering query_id: 6
timeout can't be used in the current context
WARNING:superset.utils.core:timeout can't be used in the current context
signal only works in main thread
Traceback (most recent call last):
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/superset/utils/core.py", line 584, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:superset.utils.core:signal only works in main thread
Traceback (most recent call last):
  File "/amundsen/amundsen/amundsendatabuilder/venv/lib/python3.6/site-packages/superset/utils/core.py", line 584, in __enter__
    signal.signal(signal.SIGALRM, self.handle_timeout)
  File "/usr/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Query 6: Executing 1 statement(s)
INFO:superset.sql_lab:Query 6: Executing 1 statement(s)
Query 6: Set query to 'running'
INFO:superset.sql_lab:Query 6: Set query to 'running'
Query 6: Running statement 1 out of 1
INFO:superset.sql_lab:Query 6: Running statement 1 out of 1
Query 6: <class 'pyodbc.ProgrammingError'>
ERROR:superset.sql_lab:Query 6: <class 'pyodbc.ProgrammingError'>
INFO:werkzeug:172.22.0.6 - - [14/Aug/2020 09:15:10] "POST /superset/sql_json/ HTTP/1.1" 500 -

## Steps to Reproduce

1. start docker-compose
2. start superset
3. navigate to tables under localhost:5000
4. certain tables will be able to allow users to preview, some others will fail... (I'm not sure but I'm guessing it might have to do with the data types of the tables?)

## Your Environment

* Amunsen version used: latest version I believe
* Ubuntu 18.04 LTS
* Firefox v79

Any help will be very much appreciated, thank you!

**Comment by feng-tao** [comment]
most likely due to superset auth instead of Amundsen as it uses FAB for security management. I would suggest you reach out superset community.

**Comment by feng-tao** [comment]
^^ @debbielee1996 let us know if you got any answered from the superset community.

**Comment by debbielee1996** [comment]
![image](https://user-images.githubusercontent.com/62943444/92556730-3c14ba00-f29d-11ea-98bd-c04cf2899be8.png)

Hi feng-tao, I am having this issue when I try to preview the datatables. The username and password for superset login is correct, do you have any idea what went wrong?
