### ISSUE TITLE
Frontend repo - broken docs link

### ISSUE THREAD

**Issue by jornh** [amundsen-io/amundsen#633]
Link to docs on frontend repo still points to Lyft org.

## Expected Behavior

https://www.amundsen.io/amundsen (or maybe even `/frontend` ?)

## Current Behavior

![8305097C-A881-4A3B-BC53-BFEE06272084](https://user-images.githubusercontent.com/766423/90293296-0b9b5500-de84-11ea-8944-d01f902a1598.jpeg)

**Comment by ttannis** [comment]
Fixed the link!
