### ISSUE TITLE
Feature Proposal: add github action to check license header

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#639]
## Expected Behavior or Use Case
We add license headers for all the code files(py, ts, css). We should add a github action to make sure license header is added for new files

**Comment by jornh** [comment]
Duplicate of https://github.com/amundsen-io/amundsen/issues/563 ?

**Comment by feng-tao** [comment]
yeap, just close that one.

**Comment by pratikSethi** [comment]
Hi @feng-tao, @Golodhros I would like to give this a try over the weekend. Can I take this up?

**Comment by Golodhros** [comment]
Yes please, we would love your contribution!

**Comment by feng-tao** [comment]
thanks @pratikSethi for the interest, but i think we have already implemented this github action (https://github.com/amundsen-io/amundsendatabuilder/blob/master/.github/workflows/license.yml). Sorry about forgetting to update the issue status.

**Comment by pratikSethi** [comment]
Thanks @feng-tao for letting me know :)
