### ISSUE TITLE
Redshift spectrum metadata extraction is not supported by postgres extractor

### ISSUE THREAD

**Issue by p5k6** [amundsen-io/amundsen#65]
Figured this out yesterday while working on some spectrum tables; the current query in lyft/amundsendatabuilder#63 works for native redshift tables (which is what I tested with earlier), but does not work with spectrum tables (as spectrum metadata is stored outside sql standard INFORMATION_SCHEMA). `svv_external_columns` should provide access to the equivalent external tables metadata.

If/when I have some time I'll add a PR, or if anyone else wants to tackle in the meantime - have at it 😉.

**Comment by jornh** [comment]
With the resolution of https://github.com/amundsen-io/amundsen/issues/672 which got solved by introducing Redshift and Postgres variants of base implementation introducing late-bindings this issue may have become a more low hanging fruit low. 

@p5k6 if you’re still interested maybe worth looking into?

**Comment by feng-tao** [comment]
I think the issue could be closed now. Feel free to reopen if that's not the case.
