### ISSUE TITLE
R u kidding me? 2.5.5 pushed to 2.5.4 tag :stonned: 

### ISSUE THREAD

**Issue by pPanda-beta** [amundsen-io/amundsen#658]
Famous mammoth commit https://github.com/amundsen-io/amundsenmetadatalibrary/commit/48b4c71054f7b34bca8a8f148e8b7499dfb986fc got pushed to dockerhub for tag `amundsendev/amundsen-metadata:2.5.4` 6 days ago from today, which broke the existing integration with atlas.
 
## Expected Behavior
Amundsen metadata (v2.5.4) `GET /table/` should work in the same env where it used to work 7 days before today. 

## Current Behavior
A simple rest call to amundsen-metadata `GET /table/hive_table://primary.apps/some_simple_beautiful_table` breaks with 500. 

```

   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
     resp = meth(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/flasgger/utils.py", line 249, in wrapper
     return function(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/amundsen_metadata-2.5.4-py3.7.egg/metadata_service/api/table.py", line 32, in get
     table = self.client.get_table(table_uri=table_uri)
   File "/usr/local/lib/python3.7/site-packages/amundsen_metadata-2.5.4-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 445, in get_table
     owners=self._get_owners(table_details[self.REL_ATTRS_KEY].get('ownedBy'), attrs.get('owner')),
   File "/usr/local/lib/python3.7/site-packages/amundsen_metadata-2.5.4-py3.7.egg/metadata_service/proxy/atlas_proxy.py", line 385, in _get_owners
     data_owners)
 TypeError: 'NoneType' object is not iterable
```

## Possible Solution
I'm not even looking into the actual problem. **EXPECTATION IS WHEN I PULL IMAGE TAG 2.5.4 I GET CODE OF GIT BRANCH/TAG 2.5.4**.

As a quick fix : Using sha of old image (**hopefully I didn't pull the image on my laptop for several days which saved my job**)
`amundsendev/amundsen-metadata@sha256:098afdc15444b212c30202f729b1a30772625e304499fc1f602773d7457938cc`

Long term fix: 
Stop trusting amundsendev, their CI/CD, till they use rewrite-able docker tags. Once confidence is gained, pull the images and save them on a pendrive or your own container registry. 

## Steps to Reproduce (Proof of my claim)
1. `docker run -it --rm amundsendev/amundsen-metadata:2.5.4 bash -c 'head -n 395 /usr/local/lib/python3.7/site-packages/amundsen_metadata-2.5.4-py3.7.egg/metadata_service/proxy/atlas_proxy.py | tail -20'`
Or simply
`docker run -it --rm amundsendev/amundsen-metadata:2.5.4 bash -c 'cat /usr/local/lib/python3.7/site-packages/amundsen_metadata-2.5.4-py3.7.egg/metadata_service/proxy/atlas_proxy.py | wc -l'`
2.  Now verify the code against https://github.com/amundsen-io/amundsenmetadatalibrary/blob/v2.5.4/metadata_service/proxy/atlas_proxy.py
3. Expected 672 lines but found 873 lines! (🤔 ) 
4. 

## Screenshots (if appropriate)

I can attach a pic of my manager's angry face at 2AM 

## Context
I wasted 3 hours of my life debugging the issue. I was working on a feature to do full access control using apache ranger on both amundsen and atlas.  i thought this is a problem of the ranger integration code. 
It broke our production environment as we thought amundsendev will never mutate release tags of stable docker images. 

## Your Environment
* Amunsen version used: Does it really matter now?

Amunsen version used:
dockerimages :
amundsendev/amundsen-search:2.4.0 
amundsendev/amundsen-metadata:2.5.4 (cough cough)
amundsendev/amundsen-frontend-oidc:2.2.2

Deployment: k8s behind ingress

**Comment by pPanda-beta** [comment]
@verdan  - looks like you are involved, anyways, things are stable now, I'm using sha256 everywhere and will soon make clone of those docker images.

**Comment by feng-tao** [comment]
@pPanda-beta sorry to heard that, I think our docker CI/CD incorrectly mutate the version when doing a push.

**Comment by pPanda-beta** [comment]
@feng-tao Thanks for the quickest action.
Can you check the other images as well? Although I've hardcoded all sha256 for safety.

**Comment by verdan** [comment]
@pPanda-beta indeed the issue is with out CI/CD as @feng-tao mentioned. anyways, if you want to use the latest master branch in the future, please make sure to use the latest version of https://github.com/dwarszawski/amundsen-atlas-types as well. 
This change was recently introduced in the metadata and requires new entity definitions, which is also released. 

We usually announce these changes every time there is a breaking change in the release in the documentation (is applicable) and also on community Slack.

**Comment by pPanda-beta** [comment]
@verdan Thanks for the update.
Since amundsen-atlas-types, doesn’t have integration tests within it, I've to do manual testing before upgrading. And we are already live on production with amundsen and atlas. 
So need to test the following before migration : 
1. Existing entities and relationships are not harmed
2. All basic user journeys of amundsen are working fine. (Will write some taiko/selenium scripts for it) (Right now, tags, advanced search, user, bookmark are not working)
3. we can revert back easily if anything goes wrong.

**Comment by feng-tao** [comment]
@pPanda-beta if your company is using Amundsen in production, could we add your company as Amundsen user in https://github.com/amundsen-io/amundsen#who-uses-amundsen ?

**Comment by pPanda-beta** [comment]
Sure, we can make PR.

@learningyoda what say?

**Comment by feng-tao** [comment]
thanks

**Comment by feng-tao** [comment]
@pPanda-beta ping

**Comment by pPanda-beta** [comment]
@feng-tao 
We have released it for a limited audience.
Soon, we release it for the entire organisation and get the first round of user feedback, I'll raise the PR. 
Till that time, we have to wait.
