### ISSUE TITLE
Coverage reports are gone after migrating to github actions

### ISSUE THREAD

**Issue by verdan** [amundsen-io/amundsen#663]
With the migration from travis to Github Actions, somewhere we lost the coverage reports that used to be there for each PR. Can we try to get them back?

## Expected Behavior
As soon as you open a PR, there should be a coverage reports explaining what is the difference in coverage with this PR. 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by Golodhros** [comment]
To be honest, that was just noise for me. Maybe I am too much of an extremist, but either we decide they really matter and break builds when they go down, or we better remove them.

My 2 cents :)

**Comment by verdan** [comment]
That is something really useful in my opinion and give you the idea what you are trying to merge in master. 
I am also happy to break the build when they go down certain percentage.
