### ISSUE TITLE
PostgresMetadataExtractor doesn't discover Redshift late binding views

### ISSUE THREAD

**Issue by nathanlawrence-asana** [amundsen-io/amundsen#672]
## Expected Behavior
We're heavy users of late binding views in Redshift (e.g. [`with no schema binding`](https://looker.com/blog/how-to-use-late-binding-views-with-amazon-redshift-and-looker)).  I believe that those views _should_ show up in Amundsen (non-late binding views seem to show up just fine), but are not currently showing up in Amundsen.

## Possible Solution
The root issue is that views don't actually show up in `pg_tables` or in the `information_schema` tables.

The correct way to pull the metadata for these tables is by running the built-in function `PG_GET_LATE_BINDING_VIEW_COLS()` or by querying against `svv_columns` (note that unfortunately, neither of these seem to include description metadata).

See https://github.com/amundsen-io/amundsendatabuilder/pull/356 as a possible solution.

## Steps to Reproduce
1. Create a Redshift late binding view
2. Ingest the Redshift database using the `PostgresMetadataExtractor`
3. Verify that the late binding view wasn't ingested

## Context
A number of our late-binding views are very heavily used and so it's important that analysts and data scientists who are using Amundsen can use the tool to look up the table structure.

## Your Environment
* Amunsen version used: 
* Data warehouse stores: Redshift
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by jornh** [comment]
@nathanlawrence-asana I guess with https://github.com/amundsen-io/amundsendatabuilder/pull/356 merged this issue is resolved, so you can close it?

**Comment by nathanlawrence-asana** [comment]
Yep!  Thank you.

**Comment by nathanlawrence-asana** [comment]
@jornh or @feng-tao , do we need to update the Status: label as well? (I don't think I have permissions there).

**Comment by feng-tao** [comment]
thanks @nathanlawrence-asana @jornh , label is updated as well.
