### ISSUE TITLE
Newlines in sample data are not rendered properly on the front end

### ISSUE THREAD

**Issue by madison-ookla** [amundsen-io/amundsen#674]
## Expected Behavior

I've just run the docker compose images and run the steps for the sample data loader as defined in the [quick start guide](https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker).

When viewing the data in the Amundsen UI, I would expect these newline characters to be rendered on separate lines rather than retaining the newline character (it appears that newline character exists in the data source CSV itself). 

## Current Behavior

The newline characters `\n` are being displayed explicitly in certain fields

## Possible Solution

It looks like the bold annotations within the source CSV are being rendered into markdown correctly, I'm not sure why the newline characters are being missed.

## Steps to Reproduce

1. Run the docker compose setup for a local instance with Neo4j
2. Run the steps for ingesting the sample data via `sample_data_loader.py`
3. View the Hive dataset `test_schema.test_table1`

## Screenshots (if appropriate)
![Screen Shot 2020-09-02 at 1 36 19 PM](https://user-images.githubusercontent.com/52679885/92033944-5e4c8c00-ed21-11ea-9fcd-842cd1b6dc5c.png)

## Context

Since those characters are in the example data, my assumption would be that the UI would load them correctly.

## Your Environment

* Amunsen version used: 0a71beb

**Comment by feng-tao** [comment]
cc @ttannis

**Comment by ttannis** [comment]
Laying out next steps:

1. We should first have to update the quick start, then see if the issue still occurs.Programmatic descriptions have had recent changes so we first have to check if this occurs on the recent code.
2. If it does, programmatic descriptions are rendered using `ReactMarkdown` which is a 3rd party component. We will have to see if there are options we have to set to that things are displayed correctly. https://github.com/rexxars/react-markdown#options
3. If not, we will have to file an issue for support on `ReactMarkdown`

**Comment by madison-ookla** [comment]
Thank you both for the immediate feedback!

**Comment by madison-ookla** [comment]
Investigating this a little further, it seems like it might actually be a data loading issue. When the data is loaded into the models, it seems that the `\n` is being escaped:
```
(Pdb) results
[TableMetadata('hive', 'gold', 'test_schema', 'test_table1' DescriptionMetadata('s3_crawler', '**Size**: 50T\\n\\n**Monthly Cost**: $5000'), [], False, ['expensive']), TableMetadata('dynamo', 'gold', 'test_schema', 'test_table2' DescriptionMetadata('s3_crawler', '**Size**: 1T\\n\\n**Monthly Cost**: $50'), [], False, ['cheap']), TableMetadata('hive', 'gold', 'test_schema', 'test_table1' DescriptionMetadata('quality_service', '### Quality Report:\\n --- \\n Ipsus enom. Ipsus enom ipsus lorenum.\\n ---\\n[![Build Status](https://api.travis-ci.com/amundsen-io/amundsendatabuilder.svg?branch=master)](https://travis-ci.com/amundsen-io/amundsendatabuilder)'), [], False, ['low_quality'])]
```

The `ReactMarkdown` component is probably receiving the escaped text already and thus rendering it appropriately. 

I was able to confirm this by replacing the two characters `\n` in the original CSV with a literal newline, and Amundsen rendered the data correctly:
![Screen Shot 2020-09-15 at 11 47 38 AM](https://user-images.githubusercontent.com/52679885/93251700-5f31e480-f749-11ea-8721-ef71d032c475.png)

**Comment by madison-ookla** [comment]
I'll submit a PR for the amundsen data builder to adjust this 🙂
