### ISSUE TITLE
Add instructions for BigQuery Extractor

### ISSUE THREAD

**Issue by Alagappan** [amundsen-io/amundsen#68]
Could we please add some setup instructions for BigQuery metadata extractor and usage extractor? Instructions could include IAM roles and permissions that are needed for extractor access and extract metadata and usage information. An example response from Bigquery for metadata and usage would be ideal.

**Comment by oliveratutexas** [comment]
I think the instructions should also include necessary key values that might be inherited and unique.

**Comment by feng-tao** [comment]
with https://github.com/amundsen-io/amundsendatabuilder/pull/222, I think we could close this issue now.
