### ISSUE TITLE
Unable to load the data into postgres tables

### ISSUE THREAD

**Issue by vilasmamidyala-icf** [amundsen-io/amundsen#688]
Hi Team,

I am using the sample_postgres_loader.py to load the data into the Postgres table, it is not working for me. it doesn't throw any error and it just ran. I don't see any changes in the database.

It works well when I just try to ingest data into the neo4j issue is only with Postgres. can someone help me with this issue?

**Comment by feng-tao** [comment]
is it with the latest master?

**Comment by vilasmamidyala-icf** [comment]
I didn't use the latest one from the master. I have used the one which I downloaded a couple of days ago.

**Comment by feng-tao** [comment]
feel free to reopen with error log once you rerun with master version.

**Comment by vilasmamidyala-icf** [comment]
Hello, 
I had run into the same issue after using the latest build. N data is loaded. I had the properties set as attached in the screenshot. while running the data load for the first time i got the error saying the password issue, i then kept the password as you see in the attachment. Later when i run the job it ran like the second screenshot shown and it then did nothing. I dont see anything loaded to postgresql.
![connprop](https://user-images.githubusercontent.com/53584082/93027295-efe9b280-f5d9-11ea-9a8b-373b8af0d15d.JPG)
![image](https://user-images.githubusercontent.com/53584082/93027338-11e33500-f5da-11ea-9f57-9fcf0a25c77b.png)
