### ISSUE TITLE
Reagarding neo4j License

### ISSUE THREAD

**Issue by ShambhuT** [amundsen-io/amundsen#689]
I could see that neo4j that is used here, is neo4j Community edition. The neo4j Community edition is having GPL v3 license. So I have a following question, Pls check and help me in clarifying this,

Query : In our organization , if we want to use Amundsen as base for building our Data Catalog solution (of course accessible only to our Data Platform team with in our organization, not customer facing). Then in this case, do our organization need to open up all our custom libraries/software that will be linked to this Data Catalog ( because the neo4j is under GPL v3 license ) ?

**Comment by feng-tao** [comment]
Amundsen doesn't change any neo4j source code but just leverage and run neo4j binary to host the metadata. I don't think you need to open up the lib. If you have real concern, I would suggest you to clarify with neo4j community.
