### ISSUE TITLE
Add examples for Action Logging

### ISSUE THREAD

**Issue by ajbosco** [amundsen-io/amundsen#691]
## Context
It would be useful to have examples for how people can use `action_logging` to record data about Amundsen usage. 
https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1599768689098500

**Comment by jornh** [comment]
Related (duplicate issue?): #22 which in a comment mention some metrics

**Comment by feng-tao** [comment]
I think it is related, I did a spot check which the only thing is not open source from Lyft side is the IDL event schema for user action. We could take some time to write a doc / tutorial on our user tracking dashboard as well as IDL schema...

**Comment by jornh** [comment]
With #692 merged I guess this issue and possibly #22 as well can be closed

**Comment by jornh** [comment]
Does additions merged  in https://github.com/amundsen-io/amundsen/pull/774/files#diff-cd0c22a29d9cd7247dfa67a88a65cb3c0b4d7e2e7563aff42fc2b26d7d74a039R40 Resolve this?

**Comment by feng-tao** [comment]
thanks! should be close now
