### ISSUE TITLE
Bug Report: unable to data into load postgrses

### ISSUE THREAD

**Issue by vilasmamidyala-icf** [amundsen-io/amundsen#693]
Hello,
I had run into the same issue after using the latest build. N data is loaded. I had the properties set as attached in the screenshot. while running the data load for the first time i got the error saying the password issue, i then kept the password as you see in the attachment. Later when i run the job it ran like the second screenshot shown and it then did nothing. I dont see anything loaded to postgresql.

Also could you please let me know how i can connect to existing database tables to get the metadata.
![image](https://user-images.githubusercontent.com/53584082/93027390-769e8f80-f5da-11ea-8d8d-1ce4458cd5a4.png)
![image](https://user-images.githubusercontent.com/53584082/93027393-7ef6ca80-f5da-11ea-8749-4aac5850b484.png)

**Comment by feng-tao** [comment]
are you on windows?

**Comment by vilasmamidyala-icf** [comment]
Yes I am on windows

**Comment by dorianj** [comment]
Were you able to resolve this? It might be worth trying an updated databuilder -- if you're still seeing this, please re-open
