### ISSUE TITLE
Hard time loading data to amundsen using apache atlas

### ISSUE THREAD

**Issue by liviasilvasantos** [amundsen-io/amundsen#698]
Hi all, 

I've seen some examples to load data into amundsen using Neo4j (amundsendatabuilder/example/scripts/) but how can I load data using Apache Atlas? Is there any sample too? Should I use Atlas Rest API? Atlas client?

I'm finding it dificult to find examples. And quite confusing. 

Thanks.

**Comment by feng-tao** [comment]
cc @verdan @mgorsk1 
hey Verdan, Mariusz, I wonder whether it will be possible to have some guide or doc on how to boostrap Amundsen with Atlas. I don't have much experience with Atlas, so will leave it to you to decide :)

**Comment by dorianj** [comment]
Since Amundsen in this context is displaying data present in Atlas, I'd suggest reading the Atlas guides for loading data, and/or hitting up their support community. If you get the data loaded but the display isn't as expected in Amundsen, we're happy to help debug that.
