### ISSUE TITLE
Implement git repo extractor

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#70]
https://github.com/gitpython-developers/GitPython

**Comment by jornh** [comment]
It looks like this should be able to populate the “GitHub Table source link” on the table detail pages:  

https://github.com/lyft/amundsenfrontendlibrary/blob/1.0.7/amundsen_application/static/js/components/TableDetail/index.tsx#L178-L193

The Metadata schema for the optional `Source` attribute on the Table entity is defined as: 

https://github.com/lyft/amundsenmetadatalibrary/blob/02ccae36fbc24ca9fdf245632bd76c1261a80b45/metadata_service/entity/table_detail.py#L102-L104

**Comment by jornh** [comment]
This could update:
* TableOwner as shown in #139 (with owner based on latest committer for each source file)
* Source as shown in #130 (if configured with git root path for SQL source files)

@feng-tao is this what you hand in mind as specification?

Illustration from #139:

![](https://user-images.githubusercontent.com/2134660/67091296-55ac9f00-f1bd-11e9-9f20-7d21e6a0351b.png)
  
  
Illustration from #130:

![](https://user-images.githubusercontent.com/1403289/66419900-c089f900-e9b9-11e9-8244-d065b97e6646.png)
