### ISSUE TITLE
Announcement xhr from frontend is broken - 2.3.0

### ISSUE THREAD

**Issue by pPanda-beta** [amundsen-io/amundsen#702]
No announcement api call is initiating from frontend. 

## Expected Behavior
A get call to `/api/announcements/v0/` on component did mount.

## Current Behavior
No backend call is going

## Possible Solution
Don't have correct source maps in docker image, so cant debug.

## Steps to Reproduce
1. Load home page.
2. Announcement section is missing.

## Context
we have created our own announcement client. But if no call goes to metadata-service then the feature is not useful anymore. 

## Your Environment

Amunsen version used:
dockerimages :
amundsendev/amundsen-search:2.4.0
amundsendev/amundsen-metadata-oidc@sha256:166ac204f774088f792a2811504d7aaaabe9beb6cbfe8514142f862b2608d4b4  (once 2.5.5)
amundsendev/amundsen-frontend-oidc@sha256:17d5f316c3990c1cce557b9240c1175d231ced4c963f9549a8326fff1001f524 (once 2.3.0)

Deployment: k8s behind ingress

**Comment by feng-tao** [comment]
announcement never goes to metadata. You need to build a custom client in FE to do that. We just disable the client by default. Also I think we fix the docker image tag issue (https://hub.docker.com/r/amundsendev/amundsen-frontend/tags) which the version shouldn't get overridden.

**Comment by feng-tao** [comment]
yeah, latest tag override makes sense as it should match the latest master. If you want stable one, I would suggest to use the stable tag which matches the version.

**Comment by pPanda-beta** [comment]
Proof of tag overriding 

docker pull amundsendev/amundsen-frontend-oidc@sha256:17d5f316c3990c1cce557b9240c1175d231ced4c963f9549a8326fff1001f524

docker pull amundsendev/amundsen-frontend-oidc@sha256:f5e7ce16853e2b6d26054b96ae9d1caa862d9161fad0a1ba6b3ed971882ca26d


Both belongs to 2.3.0

**Comment by pPanda-beta** [comment]
@feng-tao I always avoid pulling "latest" tag, since that is supposed to be the only mutable tag.

But here until a version bump up happens, the check in tag is getting overridden again and again by the pipeline. 
I'm planning to create a pipeline to save backups of good, stable images on my organization's own container registry. 
To verify the features, I will create end-to-end functional tests using taiko. 

Considering last tag, well to be honest, there is huge difference in 2.3.0 and 2.2.0. Only things left for exploring are the release-cut tags.

Out of curiosity, is there any plan for amundsen to start following SemVar 2.0?

**Comment by dorianj** [comment]
@pPanda-beta Palash, are you still seeing this? Please re-open if so. 

Generally, we do try to adhere to semver -- please feel encouraged to open a ticket if you see a place where it's violated.
