### ISSUE TITLE
Cannot access the amundsenmetadata and amundsensearch

### ISSUE THREAD

**Issue by GiovannaR** [amundsen-io/amundsen#704]
Hi all,

When I try to access the amundsenmetadata or amundsensearch in the Browser using the ports 5002 and 5001 respectively, I get this message:

![NotFound](https://user-images.githubusercontent.com/19623850/93477212-1c027d80-f8d1-11ea-8102-d00fd07921ff.PNG)

Is this normal behavior or should I access it?

I am using docker-compose.yml to install the application with some modifications highlighted in bold

version: '3'
services:
  neo4j:
    image: neo4j:3.3.0
    container_name: neo4j_amundsen
    environment:
      - NEO4J_AUTH=neo4j/test
      - dbms.netty.ssl.provider=OPENSSL
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    ports:
      - 7474:7474
    ports:
      - 7474:7474
      - **7473:7473**
      - 7687:7687
    volumes: 
      - **./example/docker/neo4j/certificates:/ssl**
      - ./example/docker/neo4j/conf:/conf
      - ./example/docker/neo4j/plugins:/plugins
      - ./example/backup:/backup
      - neo4j_data:/neo4j/data
  elasticsearch:
    image: elasticsearch:6.7.0
    container_name: es_amundsen
    ports: 
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  amundsensearch:  
    image: amundsendev/amundsen-search:2.1.3
    container_name: amundsensearch
    ports:
      - 5001:5000
    depends_on:
      - elasticsearch
    networks:
      - amundsennet
    environment:
      - PROXY_ENDPOINT=es_amundsen
    command: gunicorn -w 2 --bind :5000 search_service.search_wsgi
  amundsenmetadata:
    image: amundsendev/amundsen-metadata:2.0.0
    container_name: amundsenmetadata
    depends_on:
      - neo4j
    ports:
      - 5002:5000
    environment:
      - PROXY_HOST=bolt://neo4j_amundsen
    command: gunicorn -w 2 --bind :5000 metadata_service.metadata_wsgi
  amundsenfrontend:
    image: amundsendev/amundsen-frontend:2.1.1       
    container_name: amundsenfrontend
    depends_on:
      - amundsenmetadata
      - amundsensearch
    ports:
      - **5003**:5000
    environment:
      - SEARCHSERVICE_BASE=http://amundsensearch:5000         
      - METADATASERVICE_BASE=http://amundsenmetadata:5000
      - FRONTEND_SVC_CONFIG_MODULE_CLASS=amundsen_application.config.TestConfig
    command: gunicorn -w 2 --bind :5000 amundsen_application.wsgi

networks:
  amundsennet:

volumes:
  es_data:
  neo4j_data:      
` 

Thanks

**Comment by feng-tao** [comment]
@GiovannaR does it issue get resolved?
