### ISSUE TITLE
Filter search request on 'cluster' field not works.

### ISSUE THREAD

**Issue by Wonong** [amundsen-io/amundsen#712]
## Expected Behavior
I ran amundsen and execute example data loader like this page(https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md#bootstrap-a-default-version-of-amundsen-using-docker)
After that, I send a request `POST  /search_table` to search service with body like below.
```
{
    "search_request": {
        "filters":{
            "cluster": ["gold"]
        }
    },
    "query_term": ""
}
```
Looking at `TABLE_MAPPING` constant of proxy in Amundsen searchservice, I expected documents with schema name 'gold' will be returned.

## Current Behavior
Current response is like below. It returned nothing
```
{
    "results": [],
    "total_results": 0
}
```

## Possible Solution
(https://github.com/amundsen-io/amundsendatabuilder/blob/master/databuilder/publisher/elasticsearch_constants.py#L13)
Above is Amundsen databuilder's elsaticsearch mapping codes.
In the codes above, `cluster` field has no multi filed type `raw`.
In my thought, It is the reason because Amundsen searchservice convert string `cluster` to `cluster.raw` in query when client request filter search on it.
So I updated mapping codes in Amundsen databuilder and rerun example_data_loader.
Then It works successfully.

So, my solution is to update `databuilder` and make `cluster` field has multi-field `raw`

## Steps to Reproduce
1. Run Amundsen using docker-compose
2. Run datbuilder's sample_data_loader
3. (Using curl or postman), Request `POST http://localhost:5001/search_table` with body like above.
4. Check response.

## Context
I found this issue when I creating a filter search and delete function on other fields of elasticsearch.
If cluster has `raw` field(keyword type), It is very useful to create filter search and delete functions.

**FYI**
I think elasticsearch index map in amundsencommon is same with databuilder's.
(common: https://github.com/amundsen-io/amundsencommon/blob/master/amundsen_common/models/index_map.py)

## Your Environment
* Amunsen version used: latest version master branch
* Data warehouse stores: Neo4j, Elasticsearch
* Deployment (k8s or native): native(docker-compose)
* Link to your fork or repository: https://github.com/Wonong/amundsen

**Comment by feng-tao** [comment]
thanks, eventually we need to use common (https://github.com/amundsen-io/amundsencommon/blob/master/amundsen_common/models/index_map.py) as deps in databuilder. Just haven't had time to clear it up..
The change makes sense. The UI currently doesn't have cluster in filtering as FYI.

**Comment by Wonong** [comment]
Thank you for your comment and PR approvement.
I had created cluster filtering amd use it in my own frontend.
If that's what you need, I will create a PR to make search to use common soon. :)
