### ISSUE TITLE
Cannot run front end locally

### ISSUE THREAD

**Issue by finkton1** [amundsen-io/amundsen#714]
Good Day,

I am trying to run Amundsen front end locally, I went through all the steps, here: [https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/installation.md](url)
And when I try to run application localhost:5000 I receive these types of errors

`{
    "msg": "Encountered exception: AUTH_USER_METHOD is not configured"
}`

I am running the metadata service on http://0.0.0.0:5002 and search service on http://0.0.0.0:5001

I also tried to just run them in docker local to no avail. 

Some more error messages from chrome console:

`GET http://localhost:5000/api/auth_user 500 (INTERNAL SERVER ERROR)
GET http://localhost:5000/api/metadata/v0/user/bookmark 500 (INTERNAL SERVER ERROR)
GET http://localhost:5000/api/metadata/v0/get_last_indexed 500 (INTERNAL SERVER ERROR)
GET http://localhost:5000/api/metadata/v0/popular_tables 500 (INTERNAL SERVER ERROR)
GET http://localhost:5000/api/metadata/v0/tags 500 (INTERNAL SERVER ERROR)`

Would anyone know what is going on?

I am running all of this off Windows 10

Any help is appreciated!

Thanks!

**Comment by pPanda-beta** [comment]
Hey @finkton1 
Try to use the docker-compose provided. 

Safe : 
https://github.com/amundsen-io/amundsen/blob/master/docker-amundsen.yml

Adventurous : 
https://github.com/amundsen-io/amundsen/blob/master/docker-amundsen-atlas.yml

Steps : 
just download the docker-compose file and run `docker-compose up -d; docker-compose logs -f`

**Comment by finkton1** [comment]
> Hey @finkton1
> Try to use the docker-compose provided.
> 
> Safe :
> https://github.com/amundsen-io/amundsen/blob/master/docker-amundsen.yml
> 
> Adventurous :
> https://github.com/amundsen-io/amundsen/blob/master/docker-amundsen-atlas.yml
> 
> Steps :
> just download the docker-compose file and run `docker-compose up -d; docker-compose logs -f`

Thanks!
However I am trying to run metadata and search service locally in their own separate environments.

I can run the health checks on both services and I receive a 200 so I know they are running.

**Comment by finkton1** [comment]
I also tried the setup documentation by using Ubuntu 20 in virtual machine with same results.
Used documentation same as before: [https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/installation.md](url)

**Comment by jornh** [comment]
> And when I try to run application localhost:5000 I receive these types of errors

> { "msg": "Encountered exception: AUTH_USER_METHOD is not configured" }

> I am running the metadata service on http://0.0.0.0:5002 and search service on http://0.0.0.0:5001

> I also tried to just run them in docker local to no avail.

This “error” (rather a warning) is expected for both of the two setups you tried if you didn’t configure authentication. 

In comparison the Quickstart setup @pPanda-beta mention above get around it by configuring a dummy auth method in the compose file.

**Comment by jornh** [comment]
Basically same thing as in the Docker compose file. Set the `FRONTEND_SVC_CONFIG_MODULE_CLASS` environment var to the Flask config class you want to use Including definition of auth (either the dummy one above or OIDC) 👈 This is essentially just following Flask conventions.

Yeah, I know documentation for your scenario is scattered across repos etc. and people want to run stuff in several different ways. So it’s not an easy job to cover all cases. Often you have to read code as well. That’s why I pointed to the Docker files because that are actually just succinct documentation of how to do it manually as well.

Contributions towards improving docs are always welcome though.

**Comment by jornh** [comment]
Hope the above brings you a step further
