### ISSUE TITLE
Filter by tag not working

### ISSUE THREAD

**Issue by liviasilvasantos** [amundsen-io/amundsen#735]
Since I've had a hard time with Atlas installation (the adventurous path ;-) ), I've started again with the safe neo4j and es. 

Followed the instalation steps, got containers up and running. Next, I ran example/scripts/sample_data_loader.py and I could see sample data in localhost:5000.

When I edit a table, adding a new tag, it seems to work. But if I click directly on the tag link (at table_detail page or at the initial page), I get 0 result. 

I've looked at neo4j browser, and the only difference between the new tag I created at frontend app and the tag created by the sample script, is it lacks two informations:

-publisher_last_updated_epoch_ms and published_tag

Can this be related to the tag search 'no result' error? 

Thanks!

**Comment by feng-tao** [comment]
currently if we add a tag, the ES index job needs to rerun again to populate the index.

**Comment by liviasilvasantos** [comment]
Thanks, @feng-tao . I ran the ES etl job again and the index is now updated.
