### ISSUE TITLE
Search Service is not working correctly

### ISSUE THREAD

**Issue by ben-j-herbertz** [amundsen-io/amundsen#738]
Amundsen has been installed locally based on the latest version 2.4 and built from source.
Atlas is used as backend and search engine.

Note: Atlas was installed and used before. I used the kickstart method to generate all types.

## Expected Behavior
The search should list all results

## Current Behavior

Error Message: `Page index out of bounds for available matches`

Response from `/api/search/v0/table`:

```
{
   "msg":"Success",
   "search_term":"test_serde",
   "status_code":200,
   "tables":{
      "page_index":0,
      "results":[
         {
            "badges":[
               
            ],
            "cluster":"hdptuc01",
            "database":"hive_table",
            "description":null,
            "key":"hive_table://hdptuc01.test_eh2heqc/test_serde",
            "last_updated_timestamp":null,
            "name":"test_serde",
            "schema":"test_eh2heqc",
            "schema_description":null,
            "type":"table"
         }
      ],
      "total_results":null
   }
}
```

## Possible Solution
/

## Steps to Reproduce
/

## Screenshots (if appropriate)
/

## Context
/
## Your Environment
versions:
- amundsen-search: 2.4.0
- amundsen-metadata: 2.5.5
- amundsen-frontend: 2.3.0
- amundsen-databuilder: 3.3.2

Data warehouse stores: hive metastore HDP 3.1.0.3.1.5 on mariadb
Deployment (k8s or native): native

**Comment by josn0w** [comment]
Link to slack discussion: https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1601290167028400

**Comment by lutzkuen** [comment]
I have the same issue, and noticed that the response json contains a results array but total_results is null. In the frontend there is a check to display nothing if the startIndex of the page is above the total_results. I worked around the issue by replacing in the amundsen frontend in file amundsen_application/api/search/v0.py  line 103 by:
tables['total_results'] = len(tables['results'])

now it shows the first 10 lines in the search results, i am not yet sure though how to get the page switch to work.

**Comment by mgorsk1** [comment]
what version of atlas are you using? this is common error for very old atlas being used.

**Comment by lutzkuen** [comment]
After a bit more digging around i noticed that our elasticsearch returns a dict for hits.total while the Elasticsearch proxy in the search library expects an int. I have created a PR with the changes that fixed it for us https://github.com/amundsen-io/amundsensearchlibrary/pull/191

**Comment by mgorsk1** [comment]
so is this related to Atlas or Es Search Proxy ?

**Comment by corridordigital** [comment]
Hi ! I'm getting this error now with the newest version, when using the advanced search.
