### ISSUE TITLE
Non Docker Installation & Atlas Configuration Documentation missing

### ISSUE THREAD

**Issue by ben-j-herbertz** [amundsen-io/amundsen#739]
I am missing a documentation for a non docker environment.

Currently i try to do the configuration native (built from source) and i am facing multiple issues.

Also i am missing a full documentation on how to use Apache Atlas as the metadata and search backend.

**Comment by jornh** [comment]
Maybe it not easy to find but there  **is** documentation available for a non-docker install. It’s just scattered across repos so you’ll have to go and read documentation for each service one by one. A starting point is the frontend install docs in https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/installation.md 

Regarding Atlas I’m sure docs could also be improved (I’m personally not using that) so can’t comment apart from giving a pointer to the faq followed by #troubleshooting on slack as a starting point.
