### ISSUE TITLE
Client certificates for Frontend to Metadata/Search requests (mutual TLS)

### ISSUE THREAD

**Issue by davcamer** [amundsen-io/amundsen#754]
## Expected Behavior or Use Case
Be able to configure client certificates that the Frontend service will use to communicate with the Metadata and Search services.

## Service or Ingestion ETL
The Frontend Python code.

### Environment Variables
This could be implemented as environment variables. The requests library can take a client certificate [either as a single  file or as a tuple of cert and key files](https://requests.readthedocs.io/en/master/user/advanced/#client-side-certificates). To cover all the options, the recognized environment variables could be, for example:

- `METADATA_CLIENT_CERT_FILE_PATH`
- `METADATA_CLIENT_KEY_FILE_PATH`
- `METADATA_CLIENT_COMBINED_FILE_PATH`
- `SEARCH_CLIENT_CERT_FILE_PATH`
- `SEARCH_CLIENT_KEY_FILE_PATH`
- `SEARCH_CLIENT_COMBINED_FILE_PATH`

In the environment I'm deploying Amundsen in to, we distribute keys and certs in separate files. The client certs identify the client uniquely, so Amundsen Frontend only needs a single cert, it doesn't vary for Search vs Metadata. So, for my environment I could achieve what I need with just two envvars:
- `CLIENT_CERT_FILE_PATH`
- `CLIENT_KEY_FILE_PATH`

Although, our internal PaaS dictates the name of these variables, so I'd need some shim to "rename" the environment variables to the name Amundsen expects.

### Expose `requests.Session()` in Config class
Earlier in my work to deploy Amundsen I needed to set up the Search to Elasticsearch connection to validate Elasticsearch's certificate against our internal Certificate Authority root cert. The Search library doesn't have configuration for a CA Root, but it allows a custom Elasticsearch instance to be supplied:
```
    PROXY_CLIENT_KEY = Elasticsearch(
        PROXY_ENDPOINT,
        http_auth=(PROXY_USER, PROXY_PASSWORD),
        ssl_context=create_default_context(cafile=SSL_ROOT_PATH),
    )
```
I'm not 100% sure this is the intended use for this config key, but it is how the code works.

mTLS configuration could be provided for Frontend's outgoing requests clients with code like:
```
class MyConfig(OidcConfig):
    FRONTEND_BASE = os.environ.get('FRONTEND_BASE')

    client_cert = os.environ.get('MY_PAAS_MTLS_CLIENT_CERT_FILE_PATH')
    client_key = os.environ.get('MY_PAAS_MTLS_CLIENT_KEY_FILE_PATH')
    session = requests.Session()
    session.cert = (client_cert, client_key)

    SEARCHSERVICE_BASE = os.environ.get('SEARCHSERVICE_BASE')
    SEARCHSERVICE_REQUESTS_SESSION = session

    METADATASERVICE_BASE = os.environ.get('METADATASERVICE_BASE')
    METADATASERVICE_REQUESTS_SESSION = session
```
This also creates a long-lived `requests.Session` object which allows for connection re-use between backend requests. That should offer a small performance benefit, more pronounced for environments with TLS enabled. 

## Context
We strive to use mTLS for all of our internal services. This allows us to secure the Search and Metadata APIs so that they are only accessible by Amundsen's Frontend and authorized staff members.

**Comment by davcamer** [comment]
I have implemented the "Expose in Config" approach for the moment, which can be seen on my personal fork here:
https://github.com/davcamer/amundsenfrontendlibrary/commit/7f2da8f0046f27a21a003e0564430b2da36faa84

**Comment by feng-tao** [comment]
cc @verdan curious on how iNG does.
At Lyft, every service communications is done through envoy (https://github.com/envoyproxy/envoy) which the service communication RBAC is very easy to setup with one line config.

**Comment by verdan** [comment]
Mostly it's just SSL (using ingress objects) afaik. 
We are currently playing around with a service mesh but nothing in production. For a few things, like superset, we have Envoy proxy in front of it.

**Comment by davcamer** [comment]
Service Mesh is on a backlog for one of our teams, but for now we are doing this sort of direct mTLS.

I realized I could still meet my goals, while using the Env Var approach that was favored in the Slack discussion thread, so I've done that in PR 757, linked above.

**Comment by davcamer** [comment]
This Slack thread has a little more context: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1602020359102800

**Comment by jornh** [comment]
With https://github.com/amundsen-io/amundsenfrontendlibrary/pull/757 merged is this issue resolved?

**Comment by feng-tao** [comment]
yeap
