### ISSUE TITLE
Inconsistency in case conversion when using Amundsen Databuilder

### ISSUE THREAD

**Issue by joshthoward** [amundsen-io/amundsen#758]
There is inconsistency when handling case conversion for model attributes in the Databuilder code. Some models convert to lower case while others don't. More details are below.

## Expected Behavior
Still TBD, but it would be my preference as a user for the extractor to handle case conversion rather than the model. 

## Current Behavior
The table below captures the several classes that do case conversion in various capacities:

- TableColumnStats – lower: table_name, schema, col_name
- TableMetadata - lower: nothing
- Watermark - lower: database, schema, table_name, cluster, part_name
- TableOwner - lower: database, schema, table_name, cluster, owners
- ColumnUsageModel - lower: nothing
- User - lower: nothing
- Application - lower: nothing
- TableSource - lower: database, schema, table_name, cluster
- TableLastUpdated - lower: nothing

The issue arises when classes like TableColumnStats lowercase `table_name` whereas TableMetadata doesn't, therefore causing broken links in the graph. 

## Possible Solution
Again TBD, but I would prefer for the extractor, not the model, to perform case conversion.

An alternative would be for the following attributes to be consistently lowercased across each model:
-  database
- schema
- table_name
- cluster
- col_name
- part_name
- owners

## Steps to Reproduce

1. Publish a TableColumnStats and TableMetadata model where the `table_name` has mixed casing. 

## Screenshots (if appropriate)
N/A

## Context

Inability to publish metadata models for data with uppercase characters. 

## Your Environment

* Amunsen version used: 2.0.0
* Data warehouse stores: Dremio / Hive (but would effect all)
* Deployment (k8s or native): k8s
* Link to your fork or repository: N/A

**Comment by joshthoward** [comment]
@feng-tao Just as an FYI. Copied this from Slack and added some more detail.

**Comment by bogo96** [comment]
related amundsen-io/amundsen#596

**Comment by joshthoward** [comment]
PR is raised to fix this issue [here](https://github.com/amundsen-io/amundsendatabuilder/pull/388).
