### ISSUE TITLE
Results from alpha testing at REA Group

### ISSUE THREAD

**Issue by sterlins** [amundsen-io/amundsen#759]
We're loving working with Amundsen so far, and our team thought we'd share our results from alpha testing so that other companies that are considering Amundsen might get a bit more info about how much customisation they'll need to do.  Our organisation uses BigQuery, and some of this feedback will be particularly relevant to others using that platform.

**Who we tested with**
Our alpha testing was done with 9 users across different lines of business and different roles (data analyst, data scientist, and data engineers). 

**What features we tested**
Our implementation of Amundsen was largely out of the box.  We've brought in the metadata for our BigQuery production projects (~30), which is ingested daily into Neo4j using an Airflow-based custom-built ETL tool.  We did not index dev or sandbox projects. One feature we added was a basic button to click through to see the table/view in the BigQuery UI. We had not implemented authorisation or authentication yet, so features like the preview button were not yet functional. We've also decided to use BigQuery as our source of truth, so we will not be using the edit descriptions/add tags features, but those have not yet been disabled.

**Key findings**

- The UI is great, quick, and easy to navigate. 
- Many users were unsure of how to use the advanced search, particularly since the search terms do not match up to BigQuery (e.g., what BigQuery refers to as a "dataset" is called a "schema" in Amundsen) and exact versus fuzzy match is not well-documented. 
- Search results aren’t intuitive, and it’s not clear why some tables/views appear higher in search results than others. It's also unclear which projects/tables are being indexed.  This has been raised in the ["Advanced Search is not intuitive" issue](https://github.com/amundsen-io/amundsen/issues/715).
- The option to click through to BigQuery for a table is very useful, but in testing none of the users realised it was a button without our telling them. The button just said "BigQuery" and was next to the greyed-out "Preview" button.
- Our testers would use the “frequent users” feature to ask other people about the table and to understand if it’s credible; however, including our service accounts caused confusion because of the way they are named.
- A few users noted that they could search for the same things in the BigQuery UI.  This is not true (for example, the BigQuery UI returns results only within the projects that you have pinned, doesn't search descriptions) and we have some education to do about why Amundsen is better. 
- Complete data dictionary information is going to be key. Many tables and columns still do not have descriptions, and users called out that Amundsen will be much better once this information is populated. 

**Improvements and customisations we'll be making based on this feedback**

**UI improvements**
*Advanced search page*

- Changing the advanced search terms to match those in BigQuery (e.g., "Dataset" -> "Table", "Schema" -> "Dataset").
- We'd like to add a filter for `project` ("Cluster").  This is a [feature](https://github.com/amundsen-io/amundsen/issues/712) that has been identified by other users.

*Table details page*

- Removing features that we are not planning on using, e.g., ability to edit descriptions & owners
- Make the button to click through to BigQuery look like a button! We've added the BQ logo to it and have used the wording "Explore in BigQuery", which our users like better.
- In the "Frequent Users", separate out system vs. end user credentials for clarity
- When a table is not partitioned, the default text is to say "data is available for all dates".  We'd like to update this to clarify that the table is not partitioned.
- For tables that do have a partition, in the "date range", we'd like to make it clear which field is partitioned.

**Additional metadata**

- We aren't currently using tags, and asked our alpha testers what they might like to see here.  I'd love to hear how other people using Amundsen use tags.
- We will play work to enforce completion of table/field definitions in our ETL service. 
- We are playing work to bring in additional metadata, such as table owners, link to the git repo, and the Airflow DAG.

**Comment by feng-tao** [comment]
Thanks for sharing the note! There is a UI config to disable description editing. @dikshathakur3119 could you share the config and doc?

**Comment by jornh** [comment]
@sterlins thank you for taking the time to share. Valuable for the community as a whole IMO.

I'll chime in on a few points. Take from it what you find useful ..

> * Search results aren’t intuitive, and it’s not clear why some tables/views appear higher in search results than others. It's also unclear which projects/tables are being indexed.  This has been raised in the ["Advanced Search is not intuitive" issue](https://github.com/amundsen-io/amundsen/issues/715).

The search ranking is based on some logarithmic weighing in `amundsen-search` on the number of frequent users. In addition `amundsen-metadata` has a filter limiting ranking to only count popularity on tables with > 10 users  (default). This is now configurable. Depending on your usage scenario, perhaps it's this setting that trips you up?

> * Our testers would use the “frequent users” feature to ask other people about the table and to understand if it’s credible; however, including our service accounts caused confusion because of the way they are named.

Depending on if you at all want to let those system accounts count towards popularity you could filter them out when ingesting to avoid the noise. This of course depends on what this system account activity really is about.

**Comment by sterlins** [comment]
> 
> 
> Thanks for sharing the note! There is a UI config to disable description editing. @dikshathakur3119 could you share the config and doc?

Thanks @feng-tao - yes, we've used this to update our UI since seeing the user feedback.

>The search ranking is based on some logarithmic weighing in amundsen-search on the number of frequent users. In >addition amundsen-metadata has a filter limiting ranking to only count popularity on tables with > 10 users (default). >This is now configurable. Depending on your usage scenario, perhaps it's this setting that trips you up?

Thanks @jornh  - I'm actually seeing the opposite: tables with lower numbers of users are appearing higher in search results, so I will do some digging into what's going on.  My hunch is that it might be because we have lots of tables that need descriptions added, and my understanding is that description matches to search terms there contribute to ranking (please let me know if I've got this wrong!).  
This might also be affected in part by the fact that we don't seem to be pulling in users for BQ views? I _think_ the [BQ extractor](https://github.com/amundsen-io/amundsendatabuilder/blob/master/databuilder/extractor/bigquery_usage_extractor.py#L67) is only returning frequent users for `referencedTables`, but we need to get `referencedViews` from the [audit logs](https://cloud.google.com/bigquery/docs/reference/auditlogs/rest/Shared.Types/AuditData#jobstatistics) as well.  We'll be doing a bit more investigation on this, and I'll raise an issue once I've got more information.

**Comment by feng-tao** [comment]
add a doc on search tutorial for FYI (https://github.com/amundsen-io/amundsen/pull/773/files)

**Comment by sterlins** [comment]
We're about 2 months into our beta launch, so I thought I'd update this with some additional feedback we've gotten:


> I've used it a few times. Very helpful! The most frequent users feature is interesting however it would be good to try and get more owners assigned to each table or at least someone you can contact to request access to the table (if applicable). In the table description could be handy to include refresh frequency and date of last refresh


These are features we hadn't included in beta and are working on adding now - it's always great to be able to respond to feature requests with "that will be ready next week"!

>Love the data catalogue!

❤️ I love it too!

> would be nice to have:
> 
> - data quality metrics in the catalogue
> - search using team name (i.e. easy search of datasets belonging to audience data science)
> - data dependencies of each dataset
> - other external links within dataset (e.g. to our github pages site)
> - a timeseries graph of data volume
> 
> also sometimes i get 'something went wrong, please refresh' errors not sure why
> 


In a recent [talk by Shopify](https://youtu.be/vt2gwHUUb_w?t=2404), they mentioned they have a search by data owner.  This is interesting and I could see a lot of use cases for us.  I'd be interested to hear if anyone else has tackled this; potentially using tags could be one way?

In terms of usage, we have about 50 data analysts/data scientists throughout the business and are hovering around ~20-30 weekly users so far.  I'm hoping that will increase a bit once we add in the metadata on owners, delivery SLAs, git repo, and Airflow DAG.

**Comment by sterlins** [comment]
Here is a list of most of the customisations we've made:

### BigQuery-specific

- Align advanced search filter names to be aligned with BigQuery structure (e.g., Cluster -> Project, Schema -> Dataset)
- Added "project" as an advanced search filter
- Remove "source" from advanced filter as we are bringing in BigQuery only
- Add button to "Explore data in BigQuery" 


### Usability

- Add "Please refresh" to error message instead of simply "Something went wrong"
- Change partition date info message from "data available for all dates" (when a table is not partitioned) to "Table is not partitioned"
- Removed favourite & popular tables for the moment, as we didn't have auth from home page & search pages
- Removed tagging searches as we don't have tags in BigQuery (yet!)
- Updated help text on advanced search to make it clear what wildcard search does (*)
- Remove ability to edit table/field descriptions and tags (BigQuery is the source of truth for these)


### Metadata

- Separate frequent users into frequent "human" users and frequent system credentials
- Added in which field is the partition field in table details page

**Comment by feng-tao** [comment]
thanks @sterlins for sharing!
