### ISSUE TITLE
Remove marshmallow-annotations dependency

### ISSUE THREAD

**Issue by feng-tao** [amundsen-io/amundsen#769]
## Expected Behavior
Remove marshmallow-annotations dependency as the package is no longer maintained (last update was in 2018) which fix the marshmallow dep to be < 3.0

## Possible Solution
Rewrite it with plain marshmallow API

## Context
When common is used as dep in databuilder, it requires databuilder to be marshmallow in < 3.0 version. This conflicts with internal etl dependency which requires marshmallow to be > 3.0 version. In the long run, we should remove any unmaintained dependency.

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by feng-tao** [comment]
cc @allisonsuarez

**Comment by allisonsuarez** [comment]
Updated in common
