### ISSUE TITLE
Issue with wrong redirect_uri for SSO

### ISSUE THREAD

**Issue by dalbaradoey** [amundsen-io/amundsen#776]
We were using amundsen frontend with flaskoidc with okta as auth layer wrapper.

This is our Architecture (Mounted on Azure):

Browser(Client) --(HTTPS)--> Azure AppGateway ----(HTTPS)--> Nginx Ingress Controller --(HTTP, port:5000)--> Amundsen-Frontend-Service

In our case is very similar to issue #594 because flask_oidc was detecting the wrong redirect_uri
(Identity Provider: Unknown Error Code: invalid_request
Description: The 'redirect_uri' parameter [http://subdomain.domain.com/oidc_callback] must be an absolute URI whitelisted in the client app settings: https://dev-xxxxxxxx-admin.okta.com/admin/app/oidc_client/instance/xxxxxxxxxxxxxxxxx#tab-general )

 
URL Whitelisted: https://subdomain.domain.com/oidc_callback

 

Also when we hardcode it (adding https) starting show an Internal Server Error 500 on the amundsen application.

 

## Expected Behavior
redirect uri comes correctly on "Location" header with "https" scheme

 

## Current Behavior
redirect_uri comes incorrectly on "Location" header with http. If we hardcoded it(force to use https), shows an Internal Server Error 500

 

## Possible Solution
N/A

 

## Steps to Reproduce
Deploy App on K8s and expose the service.

 

## Context
Unable to use SSO for Amundsen app

 

## Your Environment
* Amunsen version used: 

 

dockerimages :
amundsendev/amundsen-search:2.0.0
amundsendev/amundsen-metadata:2.0.0  
amundsendev/amundsen-frontend-oidc:2.2.0

 

Deployment: k8s behind Nginx ingress and AzureAppGw:

 

Browser(Client) --(HTTPS)--> Azure AppGateway ----(HTTPS)--> Nginx Ingress Controller --(HTTP, port:5000)--> Amundsen-Frontend-Service

**Comment by dalbaradoey** [comment]
Hi team, I close this issue, we found that flaskoidc has an error on the config file. Right now is working with Okta.

**Comment by alldoami** [comment]
@dalbaradoey How did you fix this? We're experiencing issues with creating a user profile with Okta through the `get_user_details` method which we passed in through the metadata config.
