### ISSUE TITLE
Bug Report: stat_val containing date (yyyy-mm-dd) Transforms to Integer

### ISSUE THREAD

**Issue by mersal** [amundsen-io/amundsen#778]
Using **TableColumnStats**, stat_val containing dates are displaying as integers, with the values being the subtraction calculation of the date pieces.

The output from my Athena query looks like this:
```
"db","cluster","schema","table_name","col_name","stat_name","start_epoch","end_epoch","stat_val"
"mydb","mycluster","myschema","mytable","column1","distinct values","1603238400","1603238400","437553"
"mydb","mycluster","myschema","mytable","column2","average","1603238400","1603238400","84712"
"mydb","mycluster","myschema","mytable","column3","max","1603238400","1603238400","2020-10-20"
"mydb","mycluster","myschema","mytable","column4","min","1603238400","1603238400","1945-06-30"
```

## Expected Behavior
Date values should render as strings, not integers.

## Current Behavior
The stats for column1 and column2 display fine on the front-end.
But the stats for the date columns (column3, column4) are displaying as integers, with the values being the subtraction calculation of the date pieces.

```
"2020-10-20" => 1990
"1945-06-30" = > 1909
```

Checked _neo4j_ for one of the values, and stat_val is showing as integer:
```
{
  "identity": 1833,
  "labels": [
    "Stat"
  ],
  "properties": {
"stat_name": "min",
"end_epoch": "1603238400",
"start_epoch": "1603238400",
"publisher_last_updated_epoch_ms": 1603401299050,
"stat_val": 1909,
"published_tag": "unique_tag",
"key": "<removed for privacy>/min/"
  }
}
```

## Context
So may be an issue with the data builder?
This is a blocker for our use as we need to display min/max of several dates in our datasets.

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/79398/96938199-a022c480-147e-11eb-8f36-a4223b952951.png)

## Your Environment
elasticsearch:6.7.0                   
neo4j:4.0                             
amundsendev/amundsen-search:2.1.3     
amundsendev/amundsen-metadata:2.5.4   
amundsendev/amundsen-frontend:2.1.1   
amazon/amazon-ecs-agent:latest

**Comment by feng-tao** [comment]
cc @ttannis @Golodhros @dikshathakur3119 @allisonsuarez

**Comment by ttannis** [comment]
Posting context in case someone gets to the fix before I can. We introduced automatic number formatting of stats, and did not consider that something other than numerical values would be sent as a stat: https://github.com/amundsen-io/amundsenfrontendlibrary/pull/723. cc @dikshathakur3119 

Instead of using `const numberVal = +stat_val`, we could explicitly check if `stat_val` is a number before formatting else render `stat_val` as is.

**Comment by mersal** [comment]
@ttannis FYI, the documentation here: https://github.com/amundsen-io/amundsenfrontendlibrary
includes a screenshot of stat values that are strings: https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/img/column_details.png
min: aardvark
max: zebra

**Comment by allisonsuarez** [comment]
Should be fixed with the PR mentioned above!
