### ISSUE TITLE
Superset Preview Client not working as expected - No params/headers passed

### ISSUE THREAD

**Issue by pioppob** [amundsen-io/amundsen#779]
Hello, 

Im currently trying to set up the preview feature. I'm running the frontend locally while running the rest of the microservices through docker compose.

My issue is that headers and parameters are not passing from function to function thus breaking the preview functionality (and probably many other things)

When making a POST request to /api/preview/v0, the request_json contains:
`{'database': 'postgres', 'schema': 'public', 'tableName': 'conversations'}`

The request_json is then passed as a params object to get_preview_data in the file /api/preview/v0.py
`response = PREVIEW_CLIENT_INSTANCE.get_preview_data(params=request.get_json())`

However, in get_preview_data(), the params object is empty despite being passed the json in v0.py
The empty params object is then passed to
`response = self.post_to_sql_json(params=params, headers=headers)`

which ultimately returns a 500 error due to the line:
`database_name = params.get('database')`

It doesn't make sense to me how the params object is not being passed, hopefully someone can give me some insight into this.

Screenshot of logs:

<img width="1107" alt="Screen Shot 2020-10-23 at 4 27 38 PM" src="https://user-images.githubusercontent.com/52827941/97029241-ada68000-154c-11eb-83fa-cf0fdee550a6.png">

Here is my entrypoint in setup.py:
```
entry_points="""
        [action_log.post_exec.plugin]
        logging_action_log=amundsen_application.log.action_log_callback:logging_action_log
    
        [preview_client]
        table_preview_client_class = amundsen_application.base.examples.example_superset_preview_client:SupersetPreviewClient
    """,
```

Any assistance would be appreciated.

**Comment by feng-tao** [comment]
have you checked with the superset slack / community on how to access the sql_json endpoint? And I think superset has a complicated security model which you may want to ask as well.

**Comment by pioppob** [comment]
@feng-tao it is my understanding that the issue is still in the amundsen application, the request has not yet reached superset.

**Comment by vikalpmullick** [comment]
@pioppob any success on this?

**Comment by telmofranciscmultivision** [comment]
any success on this?

**Comment by MarcoFranchin96** [comment]
I would like to ask you a question because I can't either configure the preview.

Have you modified something in the file "examples.example_superset_preview_client"?
After I run python3 setup.py with che cahnges in the entry point, and restart the frontend docker, nothing change in the datacatalog.

**Comment by HenrryVargas** [comment]
Hi 
Same issue https://github.com/amundsen-io/amundsen/issues/1195

**Comment by akumarseth** [comment]
This feature is still not working, Any input on this would be appreciated.
