### ISSUE TITLE
BigQuery Usage Collector does not extract usage for views

### ISSUE THREAD

**Issue by abhinay04** [amundsen-io/amundsen#789]
Currently, the BigQuery Usage Extractor in Amundsen Data Builder does not extract the usage logs for views. It just works for 
tables.

## Expected Behavior
Should extract information about views as well.

## Possible Solution
We are currently using the audit logs to get the data. If we see the response for the audit logs [here](https://cloud.google.com/logging/docs/reference/audit/bigquery/rest/Shared.Types/AuditData#JobStatistics), it also has gives back `referencedViews` and `totalViewsProcessed ` which can be used to grab this data.

**Comment by feng-tao** [comment]
@abhinay-kathuria-rmit let us know if you have the fix.

**Comment by abhinay04** [comment]
@feng-tao I have the fix! Will raise a PR for this tomorrow

**Comment by dorianj** [comment]
Please feel free to re-open if you end up fixing this!
