### ISSUE TITLE
Feature Proposal: Add dashboard connector for Metabase

### ISSUE THREAD

**Issue by namdnguyen** [amundsen-io/amundsen#791]
## Service or Ingestion ETL
Dashboard Connector

## Example Screenshots (if appropriate):

![Metabase](https://raw.githubusercontent.com/metabase/metabase/master/docs/metabase-product-screenshot.png)

## Context
[Metabase](https://github.com/metabase/metabase) is a really nice, open-source business intelligence tool that would be a great candidate for dashboard connector support from Amundsen.

**Comment by feng-tao** [comment]
@namdnguyen that's great! Amundsen has already had the dashboard support with example of Mode Analytics, Redash and Tableau.Would be great to have the metabase dashboard support!

**Comment by teoria** [comment]
hi @namdnguyen  @feng-tao  
i created metabase dashboards and users extractor  using metabasepy lib.
i needed create a wrapper of metabasepy to add the dashboard method
and added the metabase svg icon on amundsenfrontend 

[https://imgur.com/a/PADlJRi](https://imgur.com/a/PADlJRi)

i'll create table and query relationship 
and send a pr to community

**Comment by feng-tao** [comment]
@teoria that's great to hear! Looking forward to that!

**Comment by viniciusdsmello** [comment]
@teoria it's good to see you here! Looking forward to your contributions!

**Comment by namdnguyen** [comment]
There is active development by @teoria, so it shouldn't be stale.

**Comment by jensenity** [comment]
Hi @namdnguyen, is this still an active development?

**Comment by teoria** [comment]
![image](https://user-images.githubusercontent.com/3239299/124506909-02b8b800-dda3-11eb-89d2-882301eb2743.png)
@jensenity  i did the extractor for dashboards and users
added metabase icon 
i'll create the table -> dashboard relationship
and remove the hardcode to select the specific database that i use in my company.

next week i'll send PR with my extractors ( Metabase, GitLab and MongoDB )

**Comment by jensenity** [comment]
Cant wait for it! @teoria

**Comment by feng-tao** [comment]
that's cool @teoria !

**Comment by GuilhermeFernandes95** [comment]
Awesome initiative @teoria!

**Comment by Will-Angel** [comment]
This will be awesome to have! Thank you @teoria!

**Comment by nicosuave** [comment]
Looking forward to the Metabase extractor @teoria 💯

**Comment by maanwater** [comment]
@teoria: was your PR already merged? I am considering Amundsen and a Metabase integration would be very nice!

**Comment by brow1998** [comment]
@teoria any news regarding this feature?

**Comment by rloredo** [comment]
Any update about this?

**Comment by jiriklein** [comment]
Is this issue stale?

**Comment by Golodhros** [comment]
> Is this issue stale?

Is in the pool of improvements to be voted on.
