### ISSUE TITLE
databuilder 4.0.2 missing dependencies 

### ISSUE THREAD

**Issue by hhobson** [amundsen-io/amundsen#793]
Importing `neo4j_csv_publisher` raises `ModuleNotFoundError: No module named 'pandas'` exception. 

Look like PR [#382](https://github.com/amundsen-io/amundsendatabuilder/pull/382) has added `pandas` and `Jinja2` as dependencies for _databuilder/publisher/neo4j_csv_publisher.py_. These have been added to _requirements.txt_ but not _setup.py_

## Steps to Reproduce

1. `pip install amundsen-databuilder[snowflake]==4.0.2`
2. `python -c "from databuilder.extractor.snowflake_metadata_extractor import SnowflakeMetadataExtractor"

**Comment by feng-tao** [comment]
thanks for the report, I build a new version as well
