### ISSUE TITLE
Update Webpack to version 5

### ISSUE THREAD

**Issue by Golodhros** [amundsen-io/amundsen#794]
## Expected Behavior or Use Case
Use Webpack 5

## Possible Implementation
Check https://webpack.js.org/migrate/5/

## Context

Keep the project up to date

**Comment by dorianj** [comment]
I'm working on this -- there's some errors, but shouldn't be too bad to resolve. Should have PR out next week.

**Comment by Golodhros** [comment]
> I'm working on this -- there's some errors, but shouldn't be too bad to resolve. Should have PR out next week.

Oh, nice! Thanks a lot Dorian!

**Comment by dorianj** [comment]
implemented in https://github.com/amundsen-io/amundsenfrontendlibrary/pull/770

**Comment by dorianj** [comment]
This is resolved.
