### ISSUE TITLE
Watermark Model unnecessarily requires create_time

### ISSUE THREAD

**Issue by instazackwu** [amundsen-io/amundsen#804]
## Expected Behavior

create_time is an optional field

## Current Behavior

create_time is a required field in the Watermark model https://github.com/amundsen-io/amundsendatabuilder/blob/master/databuilder/models/watermark.py#L23

## Possible Solution

Make create_time not required in the watermark model on the backend, or in the watermark type on the frontend.

## Steps to Reproduce

1. Publish data to the model without create_time

## Context

I'm passing in Snowflake min/max ts data in the watermark model. There are no physical partitions in Snowflake, so `create_time` does not apply for our models

## Your Environment

* Amunsen version used: Databuilder 4.0.3
* Data warehouse stores: Snowflake
* Deployment (k8s or native): Docker

**Comment by dorianj** [comment]
@instazackwu would gladly take a PR to fix this, if you want!
