### ISSUE TITLE
Sqlite3 error when running sample_data_loader.py 

### ISSUE THREAD

**Issue by DataBrenes** [amundsen-io/amundsen#807]
Continue to receive this error when running the quickstart
```python example/scripts/sample_data_loader.py
exception
Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 79, in create_connection
    conn = sqlite3.connect(db_file)
sqlite3.OperationalError: unable to open database file
(amundsen_test) 
```

## Expected Behavior

Script to load the example data 
## Current Behavior

Fails trying to open a db_file
## Steps to Reproduce

1.  python3 -m venv venv
 2.source venv/bin/activate  
 3. pip3 install -r requirements.txt
 4. python3 setup.py install
 5. python3 example/scripts/sample_data_loader.py

## Context

I cannot evaluate Amundson for my organization

## Your Environment

Using Engine Docker Engine v19.03.12

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by jornh** [comment]
What's your OS and python version?

**Comment by DataBrenes** [comment]
Windows 10 Enterprise Version 1903 OS Build 18362.1082 
Python 3.8.6

Just tried on Windows 10 Pro Version 20H2 OS 19042.572 
Python 3.8.5 

And received same error as this: https://github.com/amundsen-io/amundsen/issues/803

**Comment by jornh** [comment]
To get past #803 do a git pull of databuilder - a fic just landed as per https://github.com/amundsen-io/amundsen/issues/803#issuecomment-725584896 

I bet the difference between the two Windows versions is your Pro version has a `/tmp` folder and the Enterprise doesn't - databuilder currently relies on that. You might work around it with creating such a folder but a better fix would be to use https://docs.python.org/3.8/library/tempfile.html#tempfile.gettempdir. I'd imagine a pull request would be welcome.

**Comment by DataBrenes** [comment]
@jornh Thank you so much!  I will give it a whirl.

**Comment by feng-tao** [comment]
I need to take a look but given the current csv approach, I am not sure if we need sqlite for sample loader any more.

**Comment by feng-tao** [comment]
https://github.com/amundsen-io/amundsendatabuilder/pull/413

**Comment by feng-tao** [comment]
please rebase with master which you won't need sqlite dependency any more.
