### ISSUE TITLE
Ability to import Glue table properties

### ISSUE THREAD

**Issue by bmasciarelli** [amundsen-io/amundsen#817]
## Expected Behavior or Use Case
I'd like to extract Glue's table properties

## Service or Ingestion ETL
GlueExtractor

## Possible Implementation
The search_tables method returns a Parameters dict. Mapping the concatenation of key:value to a tag could be an option. Another could be importing key's whose values were "true".

## Context
Glue's table properties are often used to tag datasets, it would be nice to bring them to Amundsen.

**Comment by feng-tao** [comment]
@bmasciarelli that's great, please contribute back once you figure out the solution!

**Comment by dorianj** [comment]
Please do upstream this if you find a fix :)
