### ISSUE TITLE
frontend: upgrade react-bootstrap from 0.x to 1.x

### ISSUE THREAD

**Issue by dorianj** [amundsen-io/amundsen#818]
###  Expected Behavior

While working on https://github.com/amundsen-io/amundsen/issues/794, I noticed that we're on an outdated version of react-bootstrap, and it's causing a variety of deprecation warnings during compilation. The new version is a breaking release with extensive backwards-incompatible changes. Because it's visual, there's a good chance that test coverage will not catch regressions, so complete manual testing with a valid dataset is suggested to ensure no breakages.

There is a guide at https://react-bootstrap.github.io/migrating/

**Comment by Golodhros** [comment]
Hi @dorianj,

Yeah, we are aware of this, but we decided to eventually move out of react-bootstrap overall.

We are preparing a component library for Amundsen and other products at Lyft, and we want to use that once we manage to open source it (hopefully soon!).

**Comment by dorianj** [comment]
oh, nice, that's even better
