### ISSUE TITLE
Installation Issue with Atlas Backend

### ISSUE THREAD

**Issue by vthorwat** [amundsen-io/amundsen#819]
Hello Team,

I am facing an issue while installing amundsen.

While running docker-compose as below having HDP-Atlas (Hortonworks) as backend

# docker-compose -f docker-amundsen-atlas.yml up

While configuring this we are getting below error:

"/

[root@bdpd amundsen]# docker-compose -f docker-amundsen-atlas.yml up
Creating network "amundsen_amundsennet" with the default driver
Pulling atlas (wbaa/rokku-dev-apache-atlas:0.1.5)...
0.1.5: Pulling from wbaa/rokku-dev-apache-atlas
524b0c1e57f8: Pull complete
7786e4eb3940: Pull complete
e776b5313e65: Pull complete
6a21787cee37: Pull complete
d84bf6ebb5b6: Pull complete
59a02d5727c6: Pull complete
3502444dd1e0: Pull complete
8dadc8731f35: Pull complete
8158e7c77990: Pull complete
8ca2c443493b: Pull complete
6fa7e90a21d3: Pull complete
9fbcb8eea822: Pull complete
6fbe8cb54ebf: Pull complete
Digest: sha256:d67ac867d299618daa8ddb9b2225f20dfc8806c96207f5d4a466fc98d9fc213c
Status: Downloaded newer image for wbaa/rokku-dev-apache-atlas:0.1.5
Building amundsensearch
**ERROR: Cannot locate specified Dockerfile: public.Dockerfile**
 
/"

We are currently blocked due to this..

Can you please guide us regarding this.

Thanks,
Vinod

**Comment by feng-tao** [comment]
cc @verdan  @mgorsk1

**Comment by jornh** [comment]
@vthorwat it's failing at:

https://github.com/amundsen-io/amundsen/blob/31195038d680224779d55b4e05a4102ec6a97cc8/docker-amundsen-atlas.yml#L15-L17

Did you do a *recursive* copy of repos as per:

https://github.com/amundsen-io/amundsen/blob/31195038d680224779d55b4e05a4102ec6a97cc8/docs/installation.md#L7-L10

**Comment by vthorwat** [comment]
Yes I have pulled all the directories mentioned in git.
