### ISSUE TITLE
Some table keys are missing from BQ metadata extractor

### ISSUE THREAD

**Issue by crazy-2020** [amundsen-io/amundsen#833]
Some tables key supposed to be gotten from BQ metadata extractor are missing. 

## Expected Behavior

Table keys gotten from BQ metadata extractor should cover all tables. 

## Current Behavior

```
table_prefix = table_id[:-BigQueryMetadataExtractor.DATE_LENGTH]
if table_prefix in self.grouped_tables:
    # If one table in the date range is processed, then ignore other ones
    # (it adds too much metadata)
    continue
table_id = table_prefix
self.grouped_tables.add(table_prefix)
```
In bigquery_metadata_extractor, there is a set 'grouped_tables' storing table_prefix of sharded tables to avoid duplicate metadata records, but it is possible the table prefixes would be same in different datasets. This ```if ```check may ignore some tables we should extract in other datasets. 

Actually, the table_keys gotten from bq_metadata_extractor would be different from bq_watermark_extractor due to this issue. 

## Possible Solution

In bigquery_metadata_extractor, it would be better to use the concatenation of dataset and table_prefix as the key of 'grouped_tables' instead of single table_prefix 

## Context
Given Dataset_A/table_11302020, Dataset_B/table_12032020 in BQ, we can only get one table key instead of two from current bigquery_metadata_extractor

## Your Environment

* Data warehouse stores: BigQuery

**Comment by feng-tao** [comment]
@crazy-2020 sounds good, let us know if you have a pr for that.

**Comment by crazy-2020** [comment]
Cool, the pr was just sent out

**Comment by feng-tao** [comment]
pr merged, thanks @crazy-2020 !
