### ISSUE TITLE
Feature Proposal: Database as a UI resource

### ISSUE THREAD

**Issue by nevi-me** [amundsen-io/amundsen#835]
## Expected Behavior or Use Case

The main entity type used in Amundsen is the `Dataset`, and we can enable dashboards and users.
Datasets can originate from various sources, and in Atlas this is commonly either `hive_db` or `rdbms_db`.

To facilitate better database discovery, we could have a `Database` entity type, which would include some metadata that provides the user with information like:

* What schemas or tables (datasets) are in the database. I assume this is already possible through clicking on the database name while on the dataset page, but it's just a generic link that takes me to the search page (http://amundsen/search, using Atlas backend).
* Description of the database
* Owners, we could get frequent users by aggregating on datasets, or omit them
* Additional custom metadata such as connection string (if populated in Atlas), type of database (MSSQL, Postgres, etc)

## Service or Ingestion ETL

I'm not sure of what it would be in the Neo4J backend, but in Atlas it is classified as a `Dataset`, which isn't ideal because it could have been easier if it were a `Database` instead.

## Possible Implementation

* Create a page for databases, with many page components of the dataset page being reusable
* Read database information from supported backends (I could work on Atlas backend so I get more familiar with Amundsen)
* Display info on database page

## Example Screenshots (if appropriate):

Don't have one as yet

## Context

If a user finds a dataset that has information that they would like to use, but that dataset resides in a database that they have not used before; it would be beneficial to surface some details about the database.

**Comment by jornh** [comment]
It maps well to the Neo4j backend data model - it already has a database node: https://github.com/amundsen-io/amundsen/blob/master/docs/architecture.md#metadata
