### ISSUE TITLE
ElasticSearch elasticsearch.exceptions.AuthorizationException

### ISSUE THREAD

**Issue by AustinBGibbons** [amundsen-io/amundsen#843]
## Expected Behavior
Hello again, I'm trying to setup Amundsen for the first time. I've been able to stand up the architecture. I'm trying to search over the test data, but it is not succeeding

## Current Behavior
The website gets a 500 when I search. The search service logs

```
elasticsearch.exceptions.AuthorizationException: TransportError(403, '{"message":"\'ZWxhc3RpYzplbGFzdGlj\' not a valid key=value pair (missing equal-sign) in Authorization header: \'Basic ZWxhc3RpYzplbGFzdGlj\'."}')
```

Which I think is because I setup OIDC via okta? I set this up because it seemed like the "bookmarks" thing would load indefinitely if there was no user authentication.

From what I can tell it is passing an authorization header, but my cluster doesn't have authorized users. I can `bash` into the container and run the query without passing authorization

```
curl https://<endpoint>.es.amazonaws.com:443/table_search_index/_search
{"took":17,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":87,"max_score":1.0,"hits":[{"_index":"table_378746f6-8012-4b19-8122-6b10d7a876f8","_type":"table","_id":"VPOsTnYBmg9jf7w4Wa-b","_score":1.0,"_source":{"badges":[],"cluster":"plaiddw","column_descriptions":[],"column_names":["id","item_id","account_id",
...
```

## Possible Solution
Is it possible to setup the search service to not pass authorization?

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/1144402/101840395-e00a3d80-3af8-11eb-905d-37c6139bc68a.png)

![image](https://user-images.githubusercontent.com/1144402/101840414-e993a580-3af8-11eb-8a91-a2b8cd7a2ff6.png)

**Comment by AustinBGibbons** [comment]
So I think that it's passed here

```
def get_access_headers(app: Flask) -> Optional[Dict]:
    """
    Function to retrieve and format the Authorization Headers
    that can be passed to various microservices who are expecting that.
    :param oidc: OIDC object having authorization information
    :return: A formatted dictionary containing access token
    as Authorization header.
    """
    try:
        access_token = app.oidc.get_access_token()
        return {'Authorization': 'Bearer {}'.format(access_token)}
    except Exception:
        return None
```

from the oidc frontend build. But I'm using AWS ES, which does not want this Authorization set. I'm (attempting to) use okta just so that the amundsen user is set (the bookmarks UI seemed to spin indefinitely otherwise)

**Comment by AustinBGibbons** [comment]
Okay, I get this even with ```oidcEnabled: false``` set

**Comment by feng-tao** [comment]
cc @verdan do you have any suggestions?

**Comment by feng-tao** [comment]
@AustinBGibbons is OIDC enabled across all services?

**Comment by AustinBGibbons** [comment]
@feng-tao no, originally only in frontend, but then I also tried adding it to metadata but I am still using ```image: amundsendev/amundsen-metadata```

**Comment by jornh** [comment]
@AustinBGibbons I think OIDC isn't related to the problem at hand. Here's why + a take on what you can do, first some of the facts you provided:

> Okay, I get this even with `oidcEnabled: false` set

> From what I can tell it is passing an authorization header, but my cluster doesn't have authorized users. I can bash into the container and run the query without passing authorization

> But I'm using AWS ES, which does not want this Authorization set.

It seems to be related to just the hop between `amundsen-search` and AWS ES, not OIDC. Currently the default Amundsen search container and the Helm chart is configured to use basic authentication towards ES:

https://github.com/amundsen-io/amundsensearchlibrary/blob/fc4503f92faece804c7ad49a0875a85d209cd75b/search_service/config.py#L51-L52

and 

https://github.com/amundsen-io/amundsensearchlibrary/blob/fc4503f92faece804c7ad49a0875a85d209cd75b/search_service/proxy/elasticsearch.py#L72-L74

But from this ☝️  last link you see there's a backdoor where you can provide your own initial ES object. So if you want/need to go with AWS ES - and not just the containerized one in the Helm chart this is where you'd either:

* Instantiate an ElasticSearch object with *NO* authentication
* Instantiate one with AWS authentication (see more below)

---
Googling for “python elasticsearch aws authentication” brought this up:

https://gist.github.com/simonw/f99c70588f4d7447a223#file-how-to-use-aws-elasticsearch-md

As you can see from that gist an extra library to convert to username/password from IAM credentials then appears to be needed in the search service.

**Comment by AustinBGibbons** [comment]
Setting

```
        - name: CREDENTIALS_PROXY_USER
          value: ''
        - name: CREDENTIALS_PROXY_PASSWORD
          value: ''
```

Worked for me, thank you!
