### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NiravLangaliya** [amundsen-io/amundsen#848]
Frontend UI would not able to show data for test_table1 after loading details via example data
http://localhost:5000/table_detail/gold/hive/test_schema/test_table1  

## Expected Behavior

Need to 

![image](https://user-images.githubusercontent.com/13895686/101990495-34fead00-3ccd-11eb-9078-48935a3d9599.png)

![image](https://user-images.githubusercontent.com/13895686/101990505-4051d880-3ccd-11eb-82ea-10ea6fdd6c9c.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/13895686/101990484-257f6400-3ccd-11eb-85b4-a72ac1ac08a3.png)

## Possible Solution

Modify code 
amundsen_application/api/utils/metadata_utils.py to add watermark_type string conversion to lower to make sure that it will equate to 'high_watermark' string

![image](https://user-images.githubusercontent.com/13895686/101990551-7beca280-3ccd-11eb-82dc-d4b5cfb0bc9b.png)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Amunsen version used:
* Data warehouse stores:
* Deployment (k8s or native):
* Link to your fork or repository:

**Comment by jornh** [comment]
Already fixed in https://github.com/amundsen-io/amundsendatabuilder/pull/403 - update your Databuilder
