### ISSUE TITLE
Feature Proposal: Ability to search based on table and column level badges

### ISSUE THREAD

**Issue by arjunprakash84** [amundsen-io/amundsen#855]
Enabling searching of tables by table and/or column level badges. 

## Expected Behavior or Use Case
User wants to look for all tables which have certain table and/or column level badges from the UI. 

Currently backend supports searching by table level badges, and I am not sure if search by column level badges is supported in backend. If a table level badge is clicked on UI, all tables with that table badge are displayed. But user can't specify badges (table or column level) in the advanced search form. 

## Service or Ingestion ETL
amundsenmetadatalibrary
amundsenfrontendlibrary

## Context
https://amundsenworkspace.slack.com/archives/CHQERT0D7/p1607966876006300?thread_ts=1606856618.396600&cid=CHQERT0D7

**Comment by feng-tao** [comment]
cc @allisonsuarez
