### ISSUE TITLE
Two questions about Helm deployment that aren’t clear in docs or values.yaml 

### ISSUE THREAD

**Issue by joehoeller** [amundsen-io/amundsen#856]
How does one open up nodePorts in values.yaml?

How would one adjust memory for elastic search env var called vm.max_map_count, or simply run this command on build in values.yaml:

`sysctl -w vm.max_map_count=262144`

Link to helm repo:
https://github.com/amundsen-io/amundsen/tree/master/amundsen-kube-helm

@ibnipun10 is it possible to add data: with vm.max_map_count to this file for elastic search? Helm File: https://github.com/amundsen-io/amundsen/blob/master/amundsen-kube-helm/templates/helm/templates/deployment-search.yaml

**Comment by mgorsk1** [comment]
you could implement something like this init cointainer https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/configmap-initcontainer.yaml but it requires root permissions in k8s cointainers which is not always the case

**Comment by jornh** [comment]
If you want nodePorts I think you can change `serviceType` https://github.com/amundsen-io/amundsen/blob/master/amundsen-kube-helm/templates/helm/values.yaml#L177

Haven’t personally tried only ClusterIP and LoadBalancer
