### ISSUE TITLE
Bug Report: Error in frontend OIDC after update deployment-frontend file

### ISSUE THREAD

**Issue by Wonong** [amundsen-io/amundsen#857]
I rebased my amundsen project recently.
After that, I upgraded helm chart and I got error in frontend.

## Expected Behavior

If I access my amundsen web, landing page is successfully loaded without login because there is a persistent cookie :)

## Current Behavior

It does not work. 
Amudnsen frontend pod prints error logs that It can not interpret token...

## Possible Solution

If I access amdunsen web on web browser's secret mode, It works.
If I access amundsen web after deleting browser cookie, It works.
So, I think there is a problem in OIDC token

## Steps to Reproduce

0. Configure OIDC on amundsen
1. Login amundsen which is released before october 2020
2. Upgrade amundsen to latest master
3. Deploy (upgraded) amundsen with helm chart
4. Access amundsen again

## Context

In my thought, There is a problem in name of environment variable(oidc secret key).
After revert code below, It works successfully.
https://github.com/amundsen-io/amundsen/blob/master/amundsen-kube-helm/templates/helm/templates/deployment-frontend.yaml#L80

https://github.com/verdan/flaskoidc/blob/master/flaskoidc/config.py#L15
https://github.com/verdan/flaskoidc#configurations
Looking at the code and doc above, I think the name of the environment variable should be `FLASK_OIDC_SECRET_KEY` like before, not `OIDC_SECRET_KEY`.

## Your Environment

* Amunsen version used: master
* Data warehouse stores: neo4j, ES
* Deployment (k8s or native): k8s
* Link to your fork or repository: None

Is there anyone who gets same error like me?...

**Comment by Wonong** [comment]
I think This PR(https://github.com/amundsen-io/amundsen/pull/777) updated code.

**Comment by feng-tao** [comment]
thanks @Wonong !
