### ISSUE TITLE
Loader file using DPAPIExtractor 

### ISSUE THREAD

**Issue by aabharaut** [amundsen-io/amundsen#859]
I am trying to extract the data from Exasol DWH using DPAPIExtractor, to load the data I have created or modified the loader file with connection, SQL stmt details. As requested by @Tao Feng I am sharing the loader file to understand what is happening or where I am wrong. As I am not aware of how to proceed with DBAPIextractor in the loader part. I tried to ran the loader script but received some error (attached screenshot) . It will be helpful if someone please provide feedback on it for improvement.

## Expected Behavior
should able to see the selected table and column value as per SQL query 

## Current Behavior
unknown errors
![amundsen_loaderoutput](https://user-images.githubusercontent.com/52012856/102425819-60a3cf00-400e-11eb-9f70-ae8a9bf33db4.PNG)

## Your Environment

* Amundsen version used: Apache license 2.0
* Data warehouse stores: Exasol Datawarehouse (On-premise)
* Deployment (k8s or native): followed installation guideline with Neo4j
[db_api_extractor.txt](https://github.com/amundsen-io/amundsen/files/5706380/db_api_extractor.txt)
[sample_dbapi_loader.txt](https://github.com/amundsen-io/amundsen/files/5706381/sample_dbapi_loader.txt)

**Comment by OElesin** [comment]
Hi @aabharaut ,

Great work with the [sample_dbapi_loader.txt](https://github.com/amundsen-io/amundsen/files/5706381/sample_dbapi_loader.txt). I am also interested in integration our Exasol DWH with Amundsen. 

I inspected your code, sample_dbapi_loader.txt, and discovered that you missed a `.` on line 85. I assume this made it impossible to read the object.

Please change: `'extractor.dbapi{}'.format(DBAPIExtractor.CONNECTION_CONFIG_KEY): DB_CONN_STRING,` to `'extractor.dbapi.{}'.format(DBAPIExtractor.CONNECTION_CONFIG_KEY): DB_CONN_STRING,`.

Hopefully, this should resolve the issue.

**Comment by feng-tao** [comment]
cool, feel free to reopen if the issue still exists after the suggestion. thanks @OElesin
