### ISSUE TITLE
[Feature Proposal] Make 'cluster' clickable to initiate a search, add cluster to Advanced Search

### ISSUE THREAD

**Issue by instazackwu** [amundsen-io/amundsen#860]
## Expected Behavior or Use Case

https://github.com/amundsen-io/amundsenfrontendlibrary/pull/766 recently made `database` and `schema` clickable. Since cluster is shown in the Table Detail view by default, also made cluster a clickable field, with a corresponding advanced search section.

## Service or Ingestion ETL

Frontend / Search Service

## Possible Implementation

Very similar to https://github.com/amundsen-io/amundsenfrontendlibrary/pull/766, add in clickable clusters. 

Will also have to add in cluster search and have that hit the search endpoint to search by cluster. 

## Context

At Instacart, we leverage the `cluster` datatype to store the Snowflake `database`. Adding in this feature will allow users to click through a cluster (db) to see other tables in that Snowflake database.

**Comment by feng-tao** [comment]
sgtm! The two issues are related:
1. Add cluster field to advanced search
2. Make search clickable in table page.

Let me know if you want to make the change!

**Comment by instazackwu** [comment]
Ah, I don't think I'll be able to look at this anytime soon, but happy to try to take a crack at this later in the new year if nobody else is able to take this sooner!
