### ISSUE TITLE
Advanced search column bug

### ISSUE THREAD

**Issue by bruno-nirello** [amundsen-io/amundsen#863]
On home page the search behavior is alright. However when looking for a column on advanced search it does not return Upper case columns.

## Expected Behavior
On advanced search column when searching for `revenue` or `revenue*`  it should return all tables with `Revenue`, `RevenueUSD`, etc.

## Current Behavior
Does not return any column at all. because our calculated columns have initial Uppercase.

## Possible Solution
Change the behavior of the advanced search API.

## Steps to Reproduce

1. On the frontend log, Home page search and advanced search use different API's.
Home page.
```
http://amundsen-search.cluster.local:5001 "GET /search?query_term=revenue&page_index=0 HTTP/1.1" 200 14598
```

Advanced search uses POST method without much information
```
http://amundsen-search.cluster.local:5001 "POST /search_table HTTP/1.1" 200 36
logging_action_log: ActionLogParams(command='_search_table', start_epoch_ms=1608577469559, end_epoch_ms=1608577469602, user='bruno.nirello@company.com', host_name='amundsen-frontend-7b4-qgp9q', pos_args_json='[]', keyword_args_json='{"filters": {"column": ["revenue"]}, "search_term": "", "page_index": 0, "search_type": "update_filter"}', output='{"search_term": "", "msg": "Success", "tables": {"page_index": 0, "results": [], "total_results": 0}, "status_code": 200}', error=None)
[21/Dec/2020 19:04:29] "POST /api/search/v0/table HTTP/1.1" 200
```

## Context
This issue prevent looking for particular metric in the company

## Your Environment
Deployed via helm using
```
  amundsen-frontend-oidc  imageTag: 3.1.0
  amundsen-search: imageTag: 2.4.1
  Neo4j: version: 3.3.0
  amundsen-metadata : imageTag: 3.0.0
```

**Comment by jornh** [comment]
Related: https://github.com/amundsen-io/amundsen/issues/283

**Comment by dorianj** [comment]
I think closing this in favor of the ticket Jorn mentioned is right? WDYT @bruno-nirello

**Comment by bruno-nirello** [comment]
Indeed @dorianj, what i did was reverting this PR https://github.com/amundsen-io/amundsenfrontendlibrary/pull/404,
because the API is not case-sensitive.
Also the ticket Jorn mentioned is a bit old and i want to bring the issue again.

**Comment by feng-tao** [comment]
@bruno-nirello you could use https://github.com/amundsen-io/amundsencommon/blob/master/amundsen_common/models/index_map.py#L13-L110 which will fix your issue. We are in the process of change databuilder to use common lib as well.
