### ISSUE TITLE
Feature Request: Incremental es index update support

### ISSUE THREAD

**Issue by lucafuji** [amundsen-io/amundsen#871]
Hi, I took a look at this example
https://github.com/amundsen-io/amundsendatabuilder/blob/master/example/dags/postgres_sample_dag.py
to ingest postgres schema into amundsen.

It seems when running create_es_publisher_sample_job, the whole search data is extracted from neo4j and ingested into es.

Are there anyway to only ingest the changed part? Otherwise if the data is huge it will take a long time.

No one reported this before
## Expected Behavior

Only changed search data should be uploaded to es.

## Current Behavior

Whole search data is uploaded to es.

## Possible Solution

Maybe add a where condition in the neo4j_search_extractor?
## Steps to Reproduce

1. Run docker-compose up -f docker-amundsen.yml
2. Run the dag in https://github.com/amundsen-io/amundsendatabuilder/blob/master/example/dags/postgres_sample_dag.py
3. Check /var/tmp/amundsen/search_data.json to see whether it contains all the data in neo4j

## Context

It might affect the performance of amundsen when loading all the data every time

## Your Environment

* Amunsen version used: latest master commit d3c5d663f3b2ffa77948e5903ecc7eab3ac1dc7c
* Data warehouse stores: postgres
* Deployment (k8s or native): native

**Comment by feng-tao** [comment]
currently the search indices (with ES as backend) is built by ingesting metadata from neo4j first. Agree that if it will be great to ingest delta. But I wonder how much data on your side given at Lyft production the index search task normally takes less than a few mins to run.

**Comment by feng-tao** [comment]
@lucafuji nice to see you here as we discussed before in airflow pr/issue !

**Comment by lucafuji** [comment]
@feng-tao 
Haha, same here. 
I think one single optimization we can make is add a where clause in the Neo4jSearchDataExtractor to filter by the cluster we just update. e.g
`
 MATCH (db:Database)<-[:CLUSTER_OF]-(cluster:Cluster)
        <-[:SCHEMA_OF]-(schema:Schema)<-[:TABLE_OF]-(table:Table)
        WHERE cluster.name = '{updated_cluster}'
        OPTIONAL MATCH (table)-[:DESCRIPTION]->(table_description:Description)
`

**Comment by feng-tao** [comment]
@lucafuji why the cluster name for delta? will you change the cluster name often for the same dataset? Also i need to take a look but currently the ES indices build is always to build a new one with uuid , delete old ones, and then assign the new one to the alias. Assume we consume delta from neo4j/ metadata source, we need to change to change the publisher support as well.

**Comment by lucafuji** [comment]
I see, thanks for the explanation.  Sounds like a brand new feature request. Just changed the title
