### ISSUE TITLE
Documentation is not up-to-date (lacking): Deployment of non-production Amundsen on AWS ECS using aws-cli

### ISSUE THREAD

**Issue by iamtodor** [amundsen-io/amundsen#875]
Hi guys
Step #3 from https://www.amundsen.io/amundsen/installation-aws-ecs/aws-ecs-deployment/ is not valid.

```
$ ecs-cli up --keypair JoaoCorreia --extra-user-data userData.sh --capability-iam --size 1 --instance-type t2.large --cluster-config amundsen --verbose --force --aws-profile $AWS_PROFILE
>>> FATA[0002] Error executing 'up': open userData.sh: no such file or directory
```
What to do with it?
I've seen some comment: in ~/<your-path-to-cloned-repo>/amundsenfrontendlibrary/docs/instalation-aws-ecs but there is no such dir instalation-aws-ecs

The same issue to step #4 from https://www.amundsen.io/amundsen/installation-aws-ecs/aws-ecs-deployment/
`ecs-cli compose --cluster-config amundsen --file docker-ecs-amundsen.yml up --create-log-groups`

No such file. I searched over two repos https://github.com/amundsen-io/amundsen and https://github.com/amundsen-io/amundsenfrontendlibrary

I haven't found such files. What am I missing?

**Comment by iamtodor** [comment]
While walking thought the issues I found a proper location of the needed files: https://github.com/amundsen-io/amundsen/tree/master/docs/installation-aws-ecs

**Comment by feng-tao** [comment]
pr is merged.
