### ISSUE TITLE
Requests dependency version collision in amundsendatabuilder module

### ISSUE THREAD

**Issue by iamtodor** [amundsen-io/amundsen#878]
I couldn't find this problem mentioned anywhere in the issue tracker, but if I missed it please feel free to close this/mark as duplicate and point me in the right direction 😄

Expected Behavior
While following the [installation guide](https://www.amundsen.io/amundsen/installation/) using dummy data, I expected the dependency installation process to complete successfully and correctly install all the required dependencies.

Current Behavior
ERROR: requests 2.23.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.2 which is incompatible.

Possible Solution
Either upgrade Amundsen to use pytest v4.6 or later, or use a different version of pytest-cov that does not require an incompatible version of pytest. I'm a newcomer to Amundsen, so I'm not sure which one of these would be better (if they would even work).

Steps to Reproduce
(steps copied from the installation guide)

1. Clone the repo: `git clone --recursive git@github.com:lyft/amundsen.git`
2. Run `docker-compose -f docker-amundsen.yml up` in the cloned directory
3. Create a Python 3.6+ virtual environment `python3 -m venv venv`
4. Activate a Python 3.6+ virtual environment `source venv/bin/activate`
4. Inside the amundsendatabuilder folder, run `pip3 install -r requirements.txt`
5. Observe this error message near the end of the process:
```
ERROR: requests 2.23.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.2 which is incompatible.
```

**Comment by dixonwhitmire** [comment]
I encountered the issue above and was able to resolve it by updating the requests version spec, within the amundsendatabuilder module to

```shell
requests>=2.23.0,<3.0
```

Although updating the version range to a minimum of 2.25 (current latest) may be preferred, since requests 2.25 supports a urllib3 [range](https://github.com/psf/requests/blob/master/setup.py#L47) between 1.21.1 to 1.26 inclusive.

```shell
requests=>2.25.,<3.0
```
I'm still working through the tutorial to ensure that I can complete the remainder of the setup.

**Comment by dixonwhitmire** [comment]
On an additional note, I encountered a "numpy" error once I had a valid virtual environment and running containers. To be fair this is really a corner case.

```
  RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
  RankWarning: Polyfit may be poorly conditioned
```
I am on OS X 11.1 (Big Sur). I resolved this issue by simply updating my version of pip per this [issue](https://github.com/numpy/numpy/issues/17784#issuecomment-735795584).

I can submit a separate PR for the Developer Setup to include this step
```
python3 -m venv venv
source venv/bin/activate
pip3 install --upgrade pip
<etc>
```
Offhand I don't see why updating the virtual environment's pip executable would be detrimental.

**Comment by dixonwhitmire** [comment]
And to follow-up, I am no longer able to duplicate this setup issue on my laptop which is running OS X 11.1 (Big Sur).

To ensure I had a clean slate I removed all cached pip libraries under $HOME/Library/Caches/pip (found using `pip3 cache dir`) and $TMPDIR/pip-*.

**Comment by feng-tao** [comment]
let me know if we could close this issue given it is not longer applicable.

**Comment by iamtodor** [comment]
@feng-tao @dixonwhitmire the command `pip3 install --upgrade pip` helps to avoid this issue. 
My suggestion is to add this step to the page https://github.com/amundsen-io/amundsen/blob/master/docs/installation.md
if you agree @feng-tao I can make a commit and PR.
What do you think?

**Comment by iamtodor** [comment]
@feng-tao Hey Tao. Here is the PR for this issue: https://github.com/amundsen-io/amundsen/pull/891
