### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Rohan1-23** [amundsen-io/amundsen#886]
Amundsen - Times out after around 20 mins of inactivity 

There should be a mechanism to ask user to reload the page. Once their access token get expired. So that, access token can be re-allotted.

 
All APIs stops working once times out. For instance, services like searching, tagging doesn't work.

**Comment by feng-tao** [comment]
do you use OIDC? do you put the session token into a persistent store instead of sqlite? Maybe good to have a bit more details on your deployment setup.

**Comment by feng-tao** [comment]
@Rohan1-23 feel free to reopen if you have more details.
