### ISSUE TITLE
Allow React app to develope with create-react-app

### ISSUE THREAD

**Issue by zaheeruddinfaiz** [amundsen-io/amundsen#892]
I am working on tweaking the front end UI. I use `npm run watch` to watch file changes and build. And use flask server to display the changed on browser. Since `webpack` builds with live reloading. That makes my development slow and time consuming. My question is how can I configure front end app to work with `create-react-app`.

So I can:

1. Develop/Test React app without having to launch Flask server
2. Leverage hot reloading for faster development

**Comment by dorianj** [comment]
Thanks for reporting! This is indeed very desired, it's being tracked here: https://github.com/amundsen-io/amundsen/issues/392 -- CRA shouldn't be necessary, we only need to enable the specific hot relaoad bits. There was a prior attempt at this that hit some roadblocks with the python server, I'm not sure if those are still in the way today.
