### ISSUE TITLE
Support multiple column-level badges when loading CSV

### ISSUE THREAD

**Issue by mparaz** [amundsen-io/amundsen#900]
## Expected Behavior or Use Case
Table columns currently support one badge only. I'd like them to support multiple badges.

## Service or Ingestion ETL
Databuilder

## Possible Implementation
In `./databuilder/extractor/csv_extractor.py`  line 195, change:

```
badges=[column_dict['badges']]
```

to load multiple again, like split on commas.

## Context
I would like to multiple badges on columns to display different column attributes, since my project is doing data lineage and access control at a column level.
I have implemented this in my project by making my own class based on this `CsvTableColumnExtractor`.

**Comment by sewardgw** [comment]
This issue can be closed per https://github.com/amundsen-io/amundsendatabuilder/pull/469
