### ISSUE TITLE
More support for get_user_details

### ISSUE THREAD

**Issue by alldoami** [amundsen-io/amundsen#908]
## Expected Behavior or Use Case
In the [docs](https://github.com/amundsen-io/amundsenmetadatalibrary/blob/master/docs/configurations.md#user_detail_method-optional), it suggests to give `USER_DETAIL_METHOD = get_user_details` within the `metadata_service` config. After defining the function given in the docs:
```
def get_user_details(user_id):
    user_info = {
        'email': 'email',
        'user_id': user_id,
        'first_name': 'Firstname',
        'last_name': 'Lastname',
        'full_name': 'Firstname Lastname',
    }
    return user_info
```
The only info attached to the user is the email and the users are created with names `Firstname Lastname`. We're able to properly authenticate the user based on their email with Okta, but we are unable to create the user with their proper names.

## Possible Implementation
In order for more info to be available for the function, the function header needs to change and accept other arguments like a json of the header. Something like:
```
def get_user_details(data):
    user_info = {
        'email': data['email'],
        'user_id': data['user_id'],
        'first_name': data['first_name'],
        'last_name': data['last_name'],
        'full_name': data['first_name']+" "+data['last_name'],
    }
    return user_info
```
where data is a json object with the request header info.

If this is implemented, then all of the function calls will need to be changed so that the correct info is passed along. We would need to fork the metadata submodule, build our own image and test our changes. After finishing testing, we'd push back upstream.

## Context
This is needed to properly create users with their correct names. 

I was following #852 but opened a new issue to provide more context and its current state.

**Comment by verdan** [comment]
@alldoami the function defined in the docs is for reference, as to how to use this method. 
The reason to introduce this method as a config variable is to give organisations a flexibility to get user details from their respective systems. 
If you are using OIDC, then you can already get the user details using the 'user_id' inside the function,  from flask oidc package. https://flask-oidc.readthedocs.io/en/latest/#flask_oidc.OpenIDConnect.user_getinfo

In my opinion, you don't need more info to pass to this function, and can get all the required details within this function. 

Also, please note that this function should enrich the User model properties defined in amundsencommon as much as possible. 


Let me know if I am missing something here.

**Comment by feng-tao** [comment]
@verdan does the user_info from OIDC have name info as well? I recall we just got email though, hence we don't enable user profile.

**Comment by alldoami** [comment]
I believe `user_id` is only email and nothing more, at least from what it looks like, it's just a string and not an object.

**Comment by verdan** [comment]
@alldoami user_id is indeed only a string, but based on that string you can get more information from a different system. How did you get the user data in the first place? you can get the same again inside this function. 

@feng-tao based on the implementation I assume you can request the fields from OIDC provider: https://github.com/puiterwijk/flask-oidc/blob/master/flask_oidc/__init__.py#L225 (I am not 100% sure though). 

But in any case, you'd be able to get the user information from oidc provider by using user info endpoint, and then simply cache this method so that it does not make queries everytime.

**Comment by alldoami** [comment]
> but based on that string you can get more information from a different system.

I don't believe this is true because you can't just grab secure information with just an email address. We would need to follow a protocol like this: https://www.oauth.com/oauth2-servers/signing-in-with-google/verifying-the-user-info/

> How did you get the user data in the first place?

The data we get is from the functions that call `get_user_details` which only pass in the email address found after authentication. So if we were to provide more information besides the email at that step, then we would be able to map more info to the user.

Let me know if you have more questions or if you think this is wrong.

**Comment by hanxlin** [comment]
@verdan
To add to what @alldoami said, I also don't think user_id alone gets us user details from an ID provider inside the get_user_details function.

Flask oidc package's user_getinfo method tries to get the user info either directly from the cached oidc id token, or use the cached access token to make a request to the ID provider's UserInfo endpoint. The problem I see here is that the oidc authentication happens in the frontend service, and so both the oidc id token and access token are cached there. The get_user_details method is called inside the metadata service, with no way of referencing the tokens.

I see frontend service's [default oidc_config](https://github.com/amundsen-io/amundsenfrontendlibrary/blob/b34151c3b989246513c1a0c0030d0193fefee962/amundsen_application/oidc_config.py#L41) is set to pass the **access token** along in the header of its requests to metadata service's api. The frontend calls metadata service's /user/ endpoint in login flow. And if I am not mistaken, that /user/ endpoint in turn [calls get_user_details](https://github.com/amundsen-io/amundsenmetadatalibrary/blob/01d0f38fbf8f284007bea7a47b438629b21899ef/metadata_service/api/user.py#L39). Maybe that can be a path to pass the oidc id token into the get_user_details function?

**Comment by verdan** [comment]
@alldoami @hanxlin when I said the different system, I meant that getting user information from different systems like LDAP, etc, and for this, you only need the user_id to make a query. 

I understand what you are trying to achieve here. My point is that both frontend and metadata are connected to the OIDC using the `flaskoidc` package, so both of them should have the information about the user. I never used Okta, so I could be wrong. Can you please try to implement your get_user_details method like this, and see if this gets you the details you are looking for via OIDC provider?

```
def get_user_detail(user_id):
    from flask import g
    # this could be anything, or completely optional. g.oidc_token_info should have the information from OIDC
    user_info = type('UserInfo', (object,), g.oidc_token_info) 
    # print(user_info)
```

**Comment by alldoami** [comment]
@verdan we tried these steps and are only able to get substantial user info from the frontend service and not the metadata service. The `g` object on the frontend side contains the right info, but not the `g` object on the metadata side.

**Comment by apalmercari** [comment]
@alldoami  have you enabled oidc in metadata service?

**Comment by verdan** [comment]
@alldoami @hanxlin I get it. I only worked for KeyCloak, and LDAP so was not aware of this issue. Just tried this using Google OIDC, and reproduced this issue. 
@hanxlin you are correct, in this case, you'll need the access_token to get the user information. 

I've just released a new version of `flaskoidc` to fix this. A couple of things:
- make sure to install `flaskoidc==0.2.1`
- Not sure about OKTA, but for Google, I needed to update OIDC Scope, and add a profile to it as well. i.e., add a new environment variable `OIDC_SCOPES="openid,email,profile"`
- and update your metadata `get_user_detail` function something like this. (Update the "fields_mapping" according to OKTA. This is for Google)
```python
    fields_mapping = {
        "display_name": "name",
        "full_name": "name",
        "first_name": "given_name",
        "last_name": "family_name",
        "profile_url": "profile",
        "user_id": "email",
        "email": "email",
        "is_active": "email_verified"
    }

    user_data = dict()

    if current_app.oidc.FLASKOIDC_ACCESS_TOKEN:
        user_data = current_app.oidc.user_getinfo(fields_mapping.values(), current_app.oidc.FLASKOIDC_ACCESS_TOKEN)

    user_data = user_data or g.oidc_token_info
    user_dict = {}

    for key, value in fields_mapping.items():
        user_dict[key] = user_data.get(value)

    return user_dict
```

**Comment by verdan** [comment]
> @alldoami have you enabled oidc in metadata service?

Yes, this is also important to enable flaskoidc support in metadata and search services.

**Comment by apalmercari** [comment]
@verdan I was able to get g.oidc_token_info from google oidc in metadata service using flaskoidc==0.1.1

**Comment by apalmercari** [comment]
Ahh okay for extra information.Got it

**Comment by alldoami** [comment]
@verdan where does one find the `FLASKOIDC_ACCESS_TOKEN`?

**Comment by mgorsk1** [comment]
from what I gather `FLASKOIDC_ACCESS_TOKEN` is a JWT Token - it's automatically generated by your OIDC token provider. It's generated after you login to Amundsen and it's valid for a certain period of time (you don't generate it yourself at any point).

curious @verdan - why we are not retrieving it from headers but use this `oidc.FLASKOIDC_ACCESS_TOKEN` ?

Seeing how many questions for OIDC there are I think it would make sense to hav  generic `get_user_details` function for OIDC, which would populate UserModel from JWT claims. It obviously wouldn't cover all the fields but it would cover the most substantial ones.

**Comment by alldoami** [comment]
The only parameter that's passed into the `get_user_details` is the acquired email address so that's why we couldn't do my possible implementation. @mgorsk1

**Comment by alldoami** [comment]
@verdan where should the `flaskoidc` be installed? we tried building our own metadata image by including the `pip3 install flaskoidc==0.2.1` in the Dockerfile, but the `public.Dockerfile` might be broken...

**Comment by apalmercari** [comment]
There are multiple oidc image you can use one of these 
https://hub.docker.com/u/amundsendev

**Comment by alldoami** [comment]
@apalmercari but those don't have updated `flaskoidc` requirements.

**Comment by apalmercari** [comment]
May be you can use this for customization https://github.com/stemma-ai/amundsen-custom

**Comment by verdan** [comment]
@alldoami I am not sure about the Amundsen OIDC image as I never used one. Always had to customize the Amundsen installation. I'd open a PR to update the flaskoidc version here: https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/setup.py#L42 , and I think this will solve the oidc images. 

This is where flaskoidc gets installed via Dockerfile: https://github.com/amundsen-io/amundsenfrontendlibrary/blob/072d5319f2fd85b8731e4d36ca1d4571c9cee030/public.Dockerfile#L26, so most probably you add your `pip3 install flaskoidc==0.2.1` line after this, and you will have the required version.

**Comment by verdan** [comment]
@mgorsk1 this `oidc.FLASKOIDC_ACCESS_TOKEN` is actually retrieving the token from the headers and store this in this variable. Reason for using this variable instead of heders is to keep the splitting/formatting logic of headers in just one place i.e., flaskoidc, and always pass the validated token.

**Comment by mgorsk1** [comment]
Ok, I understand. I wonder though whether it's not too much of an dependency between flaskoidc and Amundsen. There is a possibility to have user auth using OIDC with Amundsen without relying on flaskoidc (for example using oauth2 proxy) and then passing headers (which should have valid token anwyas - I don't think that scenario where frontend passes invalid token to metadata is likely to the point we need such workarounds) go get_user_auth is much more flexible.
