### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by Rohan1-23** [amundsen-io/amundsen#909]
Can curated data  (add tags, owners manually directly in the interface) in the amundsen be indexed in a real time? 

Hi,
I tried adding tags in the total details page of our dataset. However, searching is not working by using those additional tags as a metadata unless I publish the updated metadata to elasticsearch by using extractors and publisher. Isn't there any automated way for this? 

Thanks, Nice work!

**Comment by feng-tao** [comment]
@Rohan1-23 if you pull the master branch, it should support realtime tag search.

**Comment by feng-tao** [comment]
Feel to reopen the issue if that's not the case.

**Comment by Rohan1-23** [comment]
@feng-tao Thanks, Can you point me to the code which does ingestion to elastic search on adding new tags or owners?

**Comment by feng-tao** [comment]
https://github.com/amundsen-io/amundsenfrontendlibrary/pull/883 and https://github.com/amundsen-io/amundsensearchlibrary/pull/172 

I don't think you could search owner

**Comment by Rohan1-23** [comment]
Agreed, Does amundsensearchlibrary also need to update for this functionality to work?

Thanks in advance!

**Comment by feng-tao** [comment]
yes
