### ISSUE TITLE
Programmatic descriptions overlap other table metadata on Safari

### ISSUE THREAD

**Issue by ponizvezdochka** [amundsen-io/amundsen#912]
Hello!
I'm having trouble with displaying programmatic descriptions on Table Detail pages in Safari browser: programmatic description block lay on other descriptions (Frequent users, Data range, Tags).
Other browsers (Chrome, Opera, Mozilla) display well. Please fix.
<img width="1413" alt="Снимок экрана 2021-02-12 в 14 44 31" src="https://user-images.githubusercontent.com/10932513/107765445-e8723500-6d42-11eb-8a19-2e00b167afde.png">

* Amunsen version used: 3
* Safari version: 14.0.2 (15610.3.7.1.10, 15610)

**Comment by dorianj** [comment]
I've repro'd this in latest version of Amundsen front-end

**Comment by dorianj** [comment]
This is fixed, thanks @ponizvezdochka for reporting!

**Comment by ponizvezdochka** [comment]
Thank you @dorianj !
