### ISSUE TITLE
Only one entry type

### ISSUE THREAD

**Issue by kirill3000** [amundsen-io/amundsen#917]
Hello!
1 sudo docker-compose  -f /doc/amundsen/docker-amundsen-atlas.yml up
2 http://localhost:21000
3 Only hdfs_path
![image](https://user-images.githubusercontent.com/22203338/107984224-86caf880-6fd8-11eb-9c56-0d4a3afc831d.png)

p.s. API creates correct

**Comment by dorianj** [comment]
Can you specify what you're expecting to see?

**Comment by kirik10** [comment]
For example:  Entities table
![image](https://user-images.githubusercontent.com/5138783/108036854-d39ae780-7049-11eb-82a3-49566f6436aa.png)

**Comment by dorianj** [comment]
We need more information to help you: what are you experiencing inside Amundsen, and what do you expect to see?

**Comment by kirik10** [comment]
lts try )
for hdfs_path i can create step 1 and 2
1
![image](https://user-images.githubusercontent.com/5138783/108111601-f35ff900-70a5-11eb-88bd-3f7b58f47eec.png)
2
![image](https://user-images.githubusercontent.com/5138783/108112549-500fe380-70a7-11eb-9825-2f8898333274.png)

but for Table i can't do step 2

**Comment by dorianj** [comment]
It looks like your problem is entirely within Atlas, not Amundsen. Can you please reach out to the Atlas community?
