### ISSUE TITLE
Create a relationship between 2 entities

### ISSUE THREAD

**Issue by kirik10** [amundsen-io/amundsen#918]
----------------------
curl -i -X POST  -H 'Content-Type: application/json' -H 'Accept: application/json' -u x:x 'http://localhost:21000/api/atlas/v2/relationship' -d '
{
**"typeName" : "Referenceable",**
 "end1" :    {
 "guid" : "ee5d6b7d-464f-4e60-b79a-ca3e4e28fb2e",
  "typeName": "Column"
 
 },
  "end2" : {
  "guid" : "f52df0fe-d5e0-44d9-bb82-d9121c412e7c",
   "typeName": "Column"
  }
}
'

-------------------

From other dicussions, I don't know the typeName needs. Looking at the docs, not really clear on what exactly I can enter as a valid AtlasRelationshipDef. The logic almost seems circular wherein I need to reference an existing 'object' to create an atlas relationship.

I highly suspect I'm am misinterpreting something here, but not sure how to proceed. Can anyone let me know what a valid AtlasRelationshipDef is or any docs on where I can get more clarity on what exactly I need to be entering as one in the relationship contruction API request I'm trying to do?

Thank you

**Comment by feng-tao** [comment]
maybe post the question to Apache Atlas community? cc @mgorsk1

**Comment by dorianj** [comment]
Closing -- please follow-up with the Atlas community.
