### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Rohan1-23** [amundsen-io/amundsen#919]
Updating tags is not working
 
Hi,
When I m creating tags in the interface, it's sending post request to "https://amundsen.resilience-datafabric-dev.sbp.eyclienthub.com/api/metadata/v0/update_table_tags". It's returning the response with 500 status code (msg : "Encountered exception: list index out of range"). It's publishing the data to the neo4j but not on elastic search. I believe that there is some issue with recently introduced function i.e. update_search_tags.

https://github.com/amundsenio/amundsenfrontendlibrary/blob/master/amundsen_application/api/metadata/v0.py

**Comment by feng-tao** [comment]
Are you in the latest master?

**Comment by Rohan1-23** [comment]
yes

**Comment by Rohan1-23** [comment]
It's occurring because the variable raw_data_map doesn't have any result. I am not sure what's going wrong but it's not to fetch data from search service. However, I can still search those tables from amundsen frontend.

Is amundsendev/amundsen-search:latest updated?

P.S. -I m using the latest docker image of amundsendev/amundsen-search in our infrastructure.
