### ISSUE TITLE
Use yield instead of return for all node/relation iterators in databuilder models

### ISSUE THREAD

**Issue by crazy-2020** [amundsen-io/amundsen#924]
There are some models supporting returned list as the node/relation iterator and I am gonna refactor the code to make sure all models support node/relationship work with yield. 

## Expected Behavior or Use Case
Some existing models, like TableMetadata or DashBoard related models, have already supported generators using yield. The expected behaviors is same as them, namely, `create_nodes()` or `create_relation()` will yield element instead of returning a node/relation list.

## Service or Ingestion ETL

Databuilder models

## Possible Implementation
 The potential change will be implemented in the same way as Dashboard models did. 
e.g., for node in Application.py
`create_nodes()` -> `_create_node_iterator()` 

`self._node_iter = iter(self.create_nodes())` -> `self._node_iter = self._create_node_iterator()`

in `_create_node_iterator()`, we will yield node instead of returning a node list

## Context
Actually, I am going to add a new [Serializable](https://github.com/amundsen-io/rfcs/blob/master/rfcs/000-abstract-serializable-for-relational-db.md) which will support a new iterator(record_iterator) for mysql support. In order to make future mysql related data loader only call record_iterator and won't execute any function related to node/graph. We need to refactor the iterators in some models to make sure node/relation iterators yield element only when invoked.

**Comment by feng-tao** [comment]
change is merged
