### ISSUE TITLE
[Feast Extractor] Feast client needs a valid Serving URL, instead default localhost

### ISSUE THREAD

**Issue by amommendes** [amundsen-io/amundsen#930]
Feast extractor is failing when the Feast Serving Service is not the default `localhost:6566`. It is because the Feast client tests the connection with Serving URL when starting, even if we'll not use the Online service.

## Expected Behavior
- Use the Feast extractor even when Feast is running in another host than `localhost`

## Current Behavior
- Running the Feast Extractor with a Feast not running in the `localhost` causes the following error:
```python
[2021-02-24 22:59:34,163] {job.py:59} INFO - Launching a job
[2021-02-24 22:59:34,165] {task.py:53} INFO - Running a task
[2021-02-24 22:59:44,191] {file_system_neo4j_csv_loader.py:88} INFO - Deleting directory /var/tmp/amundsen/table_metadata/relationships/
[2021-02-24 22:59:44,192] {file_system_neo4j_csv_loader.py:88} INFO - Deleting directory /var/tmp/amundsen/table_metadata/nodes/
[2021-02-24 22:59:44,192] {taskinstance.py:1455} ERROR - Connection timed out while attempting to connect to localhost:6566
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/feast/grpc/grpc.py", line 48, in create_grpc_channel
    grpc.channel_ready_future(channel).result(timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/grpc/_utilities.py", line 140, in result
    self._block(timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/grpc/_utilities.py", line 86, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError
```

## Possible Solution
- Add `serving_url` parameter to the client creation, for example:
 ```python
class FeastExtractor(Extractor):
    """
    Extracts feature tables from Feast Core service. Since Feast is
    a metadata store (and not the database itself), it maps the
    following atributes:
     * a database is name of feast project
     * table name is a name of the feature table
     * columns are features stored in the feature table
    """

    FEAST_SERVICE_CONFIG_KEY = "instance_name"
    FEAST_ENDPOINT_CONFIG_KEY = "endpoint"
    FEAST_SERVING_ENDPOINT_CONFIG_KEY="serving_endpoint"
    DESCRIBE_FEATURE_TABLES = "describe_feature_tables"
    DEFAULT_CONFIG = ConfigFactory.from_dict(
        {FEAST_SERVICE_CONFIG_KEY: "main", DESCRIBE_FEATURE_TABLES: True}
    )

    def init(self, conf: ConfigTree) -> None:
        conf = conf.with_fallback(FeastExtractor.DEFAULT_CONFIG)
        self._feast_service = conf.get_string(FeastExtractor.FEAST_SERVICE_CONFIG_KEY)
        self._describe_feature_tables = conf.get_bool(
            FeastExtractor.DESCRIBE_FEATURE_TABLES
        )
        self._client = Client(
            core_url=conf.get_string(FeastExtractor.FEAST_ENDPOINT_CONFIG_KEY),
            serving_url=conf.get_string(FeastExtractor.FEAST_SERVING_ENDPOINT_CONFIG_KEY),
        )
        self._extract_iter: Union[None, Iterator] = None
```

- Or receive a dictionary with Feast client options, as exemplified in the [Feast notebook example](https://github.com/feast-dev/feast/blob/master/examples/minimal/minimal_ride_hailing.ipynb)

## Steps to Reproduce

1. Run Feast Extractor Sample with a Feast Client running in a host other than `localhost`

## Your Environment

* Amunsen version used: amundsen-databuilder = "^4.1.0"
* Feast: feast==0.9.2

**Comment by feng-tao** [comment]
cool, could you create a pr to fix that? thanks

**Comment by dorianj** [comment]
@amommendes hey, would still love this contribution if you're able to subit as a PR!

**Comment by amommendes** [comment]
hey @dorianj, now I´m able to submit this PR.. However, it is possible that is already out of date, Feast changed a lot from 0.9 to 0.10

**Comment by feng-tao** [comment]
thanks @amommendes could you file another issue about feast extractor upgrade?

**Comment by amommendes** [comment]
> thanks @amommendes could you file another issue about feast extractor upgrade?  

Sure @feng-tao, I'll write a new issue about it

**Comment by amommendes** [comment]
@feng-tao, new issue opened: #1337
