### ISSUE TITLE
Amundsen gremlin breaks Amundsen Metadata installation

### ISSUE THREAD

**Issue by mgorsk1** [amundsen-io/amundsen#937]
While deploying Amundsen with AtlasProxy it fails to start - the stacktrace pasted below suggests amundsen gremlin modules run functions outside main context (so they are executed even if module is not used).

## Expected Behavior

Amundsen metadata starts w/o issues.

## Current Behavior

Amundsen metadata fails to start.

## Possible Solution

1. Do not execute methods if not in main:

https://github.com/amundsen-io/amundsengremlin/blob/9ae5a5bfd5bcb1705eceecdb1bd606ec13d037c4/amundsen_gremlin/test_and_development_shard.py#L74

### Workaround

1. Always set USER env variable which will make function trigger but not fail.

## Steps to Reproduce

1. Checkout latest master
2. Unset USER env variable (it can be missing if running in docker container)
3. Build and run metadata service using docker

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/5680655/109619237-d2cd7f80-7b38-11eb-8050-f3d7d84c6167.png)

## Context

It breaks my deployment.

## Your Environment

* Amunsen version used: latest master
* Deployment (k8s or native): k8s, atlas

**Comment by mgorsk1** [comment]
cc @feng-tao @AndrewCiambrone

**Comment by verdan** [comment]
Not just the Atlas, but the overall amundsenmetadatalibrary. 
Think it's time to divide the config in separate files, as not everyone would want to install `amundsen_gremlin` all the time.

**Comment by mgorsk1** [comment]
indeed overall, updated the subject to be even more dramatic !

**Comment by verdan** [comment]
> indeed overall, updated the subject to be even more dramatic !
> 
> in general refactor would be useful, however to unblock amundsenmetadata something simpler will do.

Indeed,  ot auggesting to do the refactor roght away to fix this. But more in general.

**Comment by feng-tao** [comment]
make sense, we could do sth similar in databuilder to put additional packages into setup.py extra. Let me know if you have a pr to do so.

**Comment by AndrewCiambrone** [comment]
I am honestly okay with removing it from the amundsengremlin repo. It was causing me issues as well. I think if we want a quick fix could be to set: https://github.com/amundsen-io/amundsenmetadatalibrary/blob/master/metadata_service/config.py#L122
to be 'True'

**Comment by mgorsk1** [comment]
I think the execution of the method at fault is caused by import itself so resolution should be either moving gremlin imports to gremlinconfig class or removing function call in gremlin module (which would be a good idea to cleanup anyway)

**Comment by feng-tao** [comment]
> I think the execution of the method at fault is caused by import itself so resolution should be either moving gremlin imports to gremlinconfig class or removing function call in gremlin module (which would be a good idea to cleanup anyway)

which function call? but either way, if we could get it fix soon, that will be great.

**Comment by mgorsk1** [comment]
https://github.com/amundsen-io/amundsengremlin/blob/9ae5a5bfd5bcb1705eceecdb1bd606ec13d037c4/amundsen_gremlin/test_and_development_shard.py#L74 this one

**Comment by AndrewCiambrone** [comment]
Are we Good to close this?

**Comment by feng-tao** [comment]
yeap
