### ISSUE TITLE
Installation Datasets : Field May not be null

### ISSUE THREAD

**Issue by mclose90** [amundsen-io/amundsen#939]
I was following the installation instructions and everything seemed to be working until I get to step Verify Setup part 2.
When I navigate to http://localhost:5000/table_detail/gold/hive/test_schema/test_table1. I get something went wrong.

In the browser logs and docker logs I see.

{"msg":"Encountered exception: {'columns': {0: {'col_type': ['Field may not be null.'], 'stats': {0: {'stat_type': ['Field may not be null.']}, 1: {'stat_type': ['Field may not be null.']}, 2: {'stat_type': ['Field may not be null.']}, 3: {'stat_type': ['Field may not be null.']}, 4: {'stat_type': ['Field may not be null.']}}}, 1: {'col_type': ['Field may not be null.']}, 2: {'col_type': ['Field may not be null.']}, 3: {'col_type': ['Field may not be null.']}, 4: {'col_type': ['Field may not be null.'], 'stats': {0: {'stat_type': ['Field may not be null.']}, 1: {'stat_type': ['Field may not be null.']}, 2: {'stat_type': ['Field may not be null.']}}}}}","status_code":500,"tableData":{}}

## Expected Behavior

Table information to be displayed 

## Current Behavior

"Something went wrong"
Docker logs show Field may not be null

## Steps to Reproduce

1.) I used a fresh linux mint Ubuntu focal based installation.
2.) Installed all need docker components
3.) follow the installation.md line for line w/ Neo4j
4.) Go all the way to Verify setup step 2

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/41022806/109713497-4b4f3300-7b6f-11eb-857b-1928948c893e.png)

## Context

This issue has affected me by not being able to verify setup. 

## Your Environment

OS: Linux Mint 20.1 x86_64 
Host: VirtualBox 1.2 
Kernel: 5.4.0-66-generic

* Amunsen version used: commit 8836cd90b338f0672753a2efb846d24dd8929a38

**Comment by aselelliott** [comment]
I am facing the same issue. 
OS: Linux 3.10.0 x86_64

Also not being to reach neo4j UI on localhost:7474
![image](https://user-images.githubusercontent.com/80000497/109854289-7ba0db00-7c1c-11eb-8870-678e7fab4b97.png)

**Comment by Coqueiro** [comment]
Facing the same issue with the basic installation

**Comment by Coqueiro** [comment]
I tried this version of the databuilder: [3e28137](https://github.com/amundsen-io/amundsendatabuilder/tree/3e281373bfa8989c7a489dcf5b8c67a9f1ac38f1)
And it worked.

**Comment by feng-tao** [comment]
cc @allisonsuarez hey Allison, do you know if it is related to recent change to mashmallow lib?

**Comment by feng-tao** [comment]
@mclose90 @aselelliott could you verify with this commit (https://github.com/amundsen-io/amundsen/commit/6445175e790e13ec8b1eef3f053c5d7a0cfed548) and see if the issue persists? I am trying to see if it is due to recent clean up in metadata/databuilder naming.

**Comment by mclose90** [comment]
Using commit 6445175 I still get the same error on the UI "Something went wrong" but in the docker logs I get a different error output now. 

![image](https://user-images.githubusercontent.com/41022806/110120532-2cc58380-7d8b-11eb-971b-378c61af272e.png)

**Comment by feng-tao** [comment]
@mclose90 thanks for getting back. @allisonsuarez it seems to be the same issue with https://github.com/amundsen-io/amundsenmetadatalibrary/pull/262/files that after bumping the common lib version, we need to fix https://github.com/amundsen-io/amundsenfrontendlibrary/blob/4f20cc9f93c0529671007cfb6747d071ee711ffb/amundsen_application/api/utils/metadata_utils.py#L110

**Comment by HenrryVargas** [comment]
I have had this error, is solved changing the image version in the chart.

The problem was that de data builder works with a version schema different to  the Docker metadata imagen.
