### ISSUE TITLE
Feature request - Add business terms

### ISSUE THREAD

**Issue by swatro** [amundsen-io/amundsen#94]
Definition of a business term: A business term is a domain concept. These terms map to column(s) in table(s). They also have their own description, owners, and tag associated with them. 

Business term features: 
As a user, I can search for business term. 
As a user, I can add a description to a business term.
As a user, I can add an owner to a business term. 
As a user, I can add a tag to a business term
As a user, I can link a column to a business term. 
As a user, I can link a business term to a column.

**Comment by jornh** [comment]
@swatro great foundation you put there. A few observations/questions.

1:1 vs 1:N vs N:M links?
* Can a you own several terms? Can a term have several users? 
* Similarly with tags
* I notice terms are only related to columns, not tables. Oversight or deliberate choice?

If a tag could (optionally) also have a description, owners - and be linked to columns as well as tables, then terms and tags would effectively be the same entity AFAICT. (But I recognize the desire from @kmurra possibly @bolkedebruin to have an API similar to the one in Atlas just for the sake of back-end parity)

Should there be UI to bulk-apply terms, or even automation, to apply a term to the same column based on e.g. data lineage? (can always be a stretch goal, but I guess it doesn't hurt to a least give it a consideration already as I think I might greatly affect how you would think about UX)

**Comment by swatro** [comment]
@jornh Great questions. Here are my thoughts:

1. I see the users to terms relationship as a many-to-many. A user can own many terms and a term can have many owners. 
2. I also see terms to tags as a many-to-many relationship. 
3. I don't think business terms have to relate to a column. For my use case business terms mostly relate to columns, but I think this could be generic enough for business terms to relate to tables or columns. I'm open to either approach. 

I do agree that if the functionality of tags could be expended that many of these features could be covered with tags. I do think that is one potential solution to business terms. 

As for loading business terms, I was thinking automation to do a bulk load of terms and relationships would be a place to start. Then adding the UI features. I'm open to other approaches too.
