### ISSUE TITLE
Loaded Neo4j column data not visible in Amundsen UI 

### ISSUE THREAD

**Issue by tallurig** [amundsen-io/amundsen#956]
## Expected Behavior
CSV data loaded using the CSV connector into Neo4j. After that search index recreated. Data should be visible in frontend UI.

## Current Behavior
Loaded CSV data not visible in Frontend UI

## Steps to Reproduce
1. Check out the new code and do the setup based on Neo4j as per installation steps
2. make changes in sample CSV data files, keep only data source, schema, table and column details
3.Load the data into Neo4j using sample data loader
4.After successful load, data can be found in Neo4j but in Amundsen UI, only table details visible. When click on table name to view column details getting "Something went wrong" message.

## Screenshots (if appropriate)
To view column details getting error message "Something went wrong"

## Context
End user unable to view column details

## Your Environment
Basic setup as per instructions in documentation, no other data only modified sample data.

**Comment by dorianj** [comment]
Looks similar as https://github.com/amundsen-io/amundsen/issues/955

can you share what data changes you made, and what errors you're getting?

**Comment by feng-tao** [comment]
@allisonsuarez @dkunitsk I thought this is not an issue with the latest version. I think we may want to specify it in the FAQ/installation doc.

**Comment by tallurig** [comment]
@dorianj I am able to successfully load the sample_data as per instructions provided amundsendatabuilder/Example/sample_data_loader.py.
After that removed all content from files in example/sample_data, added content only to 
sample_source.csv
sample_table.csv
sample_col.csv

Then the data loaded into Neo4j, In Amundsen UI data not visible.

**Comment by tallurig** [comment]
Due to below error message got the issue "elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'cluster_block_exception', 'blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')"

**Solution:** Run the following commands
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_cluster/settings -d '{ "transient": { "cluster.routing.allocation.disk.threshold_enabled": false } }'
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'

**Comment by akiratwang** [comment]
@tallurig I somehow started to get this error recently (randomly happened) - cheers for the solution, it worked!
