### ISSUE TITLE
public.Docker NPM error

### ISSUE THREAD

**Issue by f1gjam** [amundsen-io/amundsen#961]
When building the public.Dockerfile you get the following error/warning

npm: not found ERROR:root:npm must be available amundsen docker image

I reverted to python-3.7 none slim image and used curl to install npm

I am not sure if I am making a mistake or if this is something that can be ignored.

**Comment by feng-tao** [comment]
which docker file? If it is FE, I think it should install npm by default through https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/public.Dockerfile#L1

**Comment by f1gjam** [comment]
That’s the one,

However it doesn’t install NPM after it starts uses the python image.

Regards,

Kashif

**Comment by dorianj** [comment]
Can you repro this in the monorepo? I haven't seen this lately
