### ISSUE TITLE
Click on Table in UI gives error Something went wrong because table has no columns

### ISSUE THREAD

**Issue by paularmand** [amundsen-io/amundsen#963]
Loaded table data in via sample_data_loader.py for datasets, but used an empty csv file for the column information (just headers, no rows). Data was loaded into neo4j as expected.

## Expected Behavior
Amundsen UI gives an overview of the tables via search. When a table is clicked on, I expected a overview of the table with maybe a warning that no columns could be found, but also other info is displayed

## Current Behavior
"Something went wrong" is displayed in the UI.

## Possible Solution
I see 2 possible solutions:
###The first one: 
in metadata_service/proxy/neo4j_proxy.py on [L126](https://github.com/amundsen-io/amundsenmetadatalibrary/blob/a765424aa13c71afdb04f7457f30d8a8977974a2/metadata_service/proxy/neo4j_proxy.py#L126)
in def _exec_col_query(self, table_uri: str) the query could be changed from:
 ```
MATCH (db:Database)-[:CLUSTER]->(clstr:Cluster)-[:SCHEMA]->(schema:Schema)
-[:TABLE]->(tbl:Table {key: $tbl_key})-[:COLUMN]->(col:Column)
OPTIONAL MATCH (tbl)-[:DESCRIPTION]->(tbl_dscrpt:Description)
OPTIONAL MATCH (col:Column)-[:DESCRIPTION]->(col_dscrpt:Description)
OPTIONAL MATCH (col:Column)-[:STAT]->(stat:Stat)
OPTIONAL MATCH (col:Column)-[:HAS_BADGE]->(badge:Badge)
RETURN db, clstr, schema, tbl, tbl_dscrpt, col, col_dscrpt, collect(distinct stat) as col_stats,
collect(distinct badge) as col_badges
ORDER BY col.sort_order;""")
```
to
 ```
MATCH (db:Database)-[:CLUSTER]->(clstr:Cluster)-[:SCHEMA]->(schema:Schema)
-[:TABLE]->(tbl:Table {key: $tbl_key})
OPTIONAL MATCH (tbl)-[:COLUMN]->(col: Column)
OPTIONAL MATCH (tbl)-[:DESCRIPTION]->(tbl_dscrpt:Description)
OPTIONAL MATCH (col:Column)-[:DESCRIPTION]->(col_dscrpt:Description)
OPTIONAL MATCH (col:Column)-[:STAT]->(stat:Stat)
OPTIONAL MATCH (col:Column)-[:HAS_BADGE]->(badge:Badge)
RETURN db, clstr, schema, tbl, tbl_dscrpt, col, col_dscrpt, collect(distinct stat) as col_stats,
collect(distinct badge) as col_badges
ORDER BY col.sort_order;""")
```
###The second one:
Another perhaps better solution is to not throw the exception (table not found) on [L170](https://github.com/amundsen-io/amundsenmetadatalibrary/blob/a765424aa13c71afdb04f7457f30d8a8977974a2/metadata_service/proxy/neo4j_proxy.py#L170), but to throw a columns not found exception, and catch this exception on [L100](https://github.com/amundsen-io/amundsenmetadatalibrary/blob/a765424aa13c71afdb04f7457f30d8a8977974a2/metadata_service/proxy/neo4j_proxy.py#L98) and just proceed with cols = []

This would return the table even if no cols can be found.

## Steps to Reproduce

1. store the [sample_dataset.txt](https://github.com/amundsen-io/amundsen/files/6163426/sample_dataset.txt) file in attachment as ./example/sample_data/sample_dataset.csv 
2. store the [empty_cols.txt](https://github.com/amundsen-io/amundsen/files/6163425/empty_cols.txt) file (empty with only header row) as ./example/sample_data/empty_cols.csv
3. upload the data to neo4j via the command in the sample_data_loader: `run_table_column_job('./example/sample_data/sample_dataset.csv', './example/sample_data/empty_cols.csv')`
4. upload the data so elasticsearch via the command in the sample_data_loader:
```
    job_es_table = create_es_publisher_sample_job(
        elasticsearch_index_alias='table_search_index',
        elasticsearch_doc_type_key='table',
        entity_type='table',
        model_name='databuilder.models.table_elasticsearch_document.TableESDocument')
    job_es_table.launch()
```
5. search for the table in amundsen frontend UI and then click on the table to go to the details page

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/379288/111612566-dff79900-87dd-11eb-8296-64f91a78d99b.png)

## Context
The problem is that while rolling out Amundsen, we do this in phases. First we try to get all tables in, then dashboards, then jobs, and only then we want to go further into the details of the tables. Currently, our internal users (data analysts and scientists) are left with the impression that there is a bug in the system. It is unclear why this happens, and no information is displayed. It would be beneficial to see at least the information that we have on the table even when there is no column info present. 

## Your Environment

* Amunsen version used: helm chart amundsen-2.1.0 
* Data warehouse stores: custom purview extraction via intermediary csv files 
* Deployment (k8s or native): k8s via helm
* Link to your fork or repository: no fork yet

**Comment by paularmand** [comment]
It is unclear whether this is a duplicate of #955 and #956 cause there is not enough details on the setup and data entered into neo4j and elastic in those issues. Maybe resolving this issue will result in resolving the others too.

**Comment by paularmand** [comment]
@feng-tao I noticed that you commented on #955 and #956 that these would be fixed in the latest release. Can you point me to the branch you are referring to, or do you mean the latest code in master? If the latter is the case, then I would assume the bug is still there.

**Comment by feng-tao** [comment]
I don't think it is related, any reason you have a table with empty columns?

**Comment by paularmand** [comment]
Yes, we use custom extractors from different sources such as glue catalog, purview and google catalog (reason: different countries and different organizational units with different tech stacks). We extract that data to csv files on a data lake (single source of truth), and then we upload the data to Amundsen (in neo4j and from there to elastic). We envisage different phases cause it is hard to write the custom extractors:
+ first extract all datasets and write a file like sample_dataset.csv (to be translated to tables in amundsen)
+ second extract all dashboards
+ 3th dashboard_table links
+ jobs 
Then we still need to do the following, but prio will be given by the user feedback (of data scientists and analysts)
+ owners
+ descriptions
+ columns
+ terms
+ PII info
+ usage info
+ ...

I hope the above gives some idea of the context and why we wanted the table without columns.

**Comment by markgrover** [comment]
Hey @paularmand yeah, I think the assumption of the product is that tables will have at least one column.

We can update the product, but I haven't heard of anyone else with such a use-case so I am not sure if this broadly applies for the maintainers (like Tao, I and others) to invest our energy in. If you were to put up a patch, we'd be happy to review.

Another alternative, I'd encourage you to explore would be to merge the table and columns ingest together. I don't think it's incrementally a lot of work to do both, so, here's a concrete alternate suggestion of phases:

```
first extract all datasets + columns and write a file like sample_dataset.csv (to be translated to tables in amundsen)
second extract all dashboards
3th dashboard_table links
jobs
Then we still need to do the following, but prio will be given by the user feedback (of data scientists and analysts)
owners
descriptions
terms
PII info
usage info
...
```

In my experience, simply showing the name of the table without showing what columns are inside wasn't very meaningful to users (data scientists/analysts), so that'd be my recommendation here.

Let us know what you think, thanks!
