### ISSUE TITLE
Athena Sample Data Loader throwing an error for sqlalchemy

### ISSUE THREAD

**Issue by akshay07jan** [amundsen-io/amundsen#964]
## Expected Behavior
Tables to be populated on UI.

## Current Behavior
Deployed or bootstrapped Amundsen on EC2. Created python code rather than DAG to pull tables from Athena and publish them to ES. Published some of the tables but from the last couple of days not able to publish more tables due to error thrown around sqlalchemy engine creation.

Error:
    self.description = None
sqlalchemy.exc.StatementError: (builtins.AttributeError) can't set attribute

Config is exactly same as provided in a script.
job_config = ConfigFactory.from_dict({
        f'extractor.athena_metadata.{AthenaMetadataExtractor.WHERE_CLAUSE_SUFFIX_KEY}': where_clause_suffix,
        f'extractor.athena_metadata.extractor.sqlalchemy.{SQLAlchemyExtractor.CONN_STRING}': connection_string(),
        f'extractor.athena_metadata.{AthenaMetadataExtractor.CATALOG_KEY}': "'AwsDataCatalog'",
        f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.NODE_DIR_PATH}': node_files_folder,
        f'loader.filesystem_csv_neo4j.{FsNeo4jCSVLoader.RELATION_DIR_PATH}': relationship_files_folder,
        f'publisher.neo4j.{neo4j_csv_publisher.NODE_FILES_DIR}': node_files_folder,
        f'publisher.neo4j.{neo4j_csv_publisher.RELATION_FILES_DIR}': relationship_files_folder,
        f'publisher.neo4j.{neo4j_csv_publisher.NEO4J_END_POINT_KEY}': neo4j_endpoint,
        f'publisher.neo4j.{neo4j_csv_publisher.NEO4J_USER}': neo4j_user,
        f'publisher.neo4j.{neo4j_csv_publisher.NEO4J_PASSWORD}': neo4j_password,
        f'publisher.neo4j.{neo4j_csv_publisher.JOB_PUBLISH_TAG}': 'unique_tag',  # should use unique tag here like {ds}
    })

Passed string interpreted by engine:
Engine(awsathena+rest://***:***@athena.us-west-2.amazonaws.com:443/?s3_staging_dir=%27s3%3A%2F%2Faws-athena-query-results-xxx-us-west-2%2F%27)

Noticed that the connection string is passed correctly but the engine is interpreting it differently.

## Steps to Reproduce
Bootstrapped on EC2 using docker-amundsen.yml.
Run sample_athena_dag but without airflow modules.

## Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/12534249/111714108-3250ae00-880e-11eb-9ac0-b97d3c6d3b36.png)

## Context
Need to present it to product managers for planning.

Image used : amundsendev/amundsen-metadata:3.3.0

**Comment by M0kY** [comment]
We faced the same issue but on metadata and search services. We traced the root cause being the recent release of **SQLAlchemy 1.4.0**. In our case it happened becasue we enabled authentication and **flaskoidc** depends on **flask_sqlalchemy**, which in turn depends on **sqlalchemy >=1.2.0**. Since the release of **SQLAlchemy 1.4.0** this started being an issue.
The simplest fix was adding **SQLAlchemy==1.3.23** to our requirements.txt

**Comment by verdan** [comment]
@M0kY I just released a new version of `flaskoidc`. You don't need to change the version of `SQLAlchemy` manually anymore. https://pypi.org/project/flaskoidc/
