### ISSUE TITLE
Storybook is broken

### ISSUE THREAD

**Issue by Golodhros** [amundsen-io/amundsen#973]
After updating to Webpack 5, Storybook got broken as it wasn't supporting it yet.

## Expected Behavior
Storybook should be running in the local dev environment

## Possible Solution
They just released experimental support of Webpack 5 (https://storybook.js.org/blog/storybook-for-webpack-5/). There is a Github issue tracking all this (https://github.com/storybookjs/storybook/issues/9216#issuecomment-799582351).

I started the work in https://github.com/amundsen-io/amundsenfrontendlibrary/tree/WAITING-storybook-webpack-5-issue-fix, happy if anybody can pick it up and take it through the finish line.

## Steps to Reproduce

1. Run `npm start storybook`
2. See the build breaking

**Comment by dorianj** [comment]
I worked on this for a while and just couldn't get it working, either... I eventually got stuck on an issue where core-js modules wouldn't load:
```ModuleNotFoundError: Module not found: Error: Can't resolve '../../core-js/object/keys' in '/Users/dorian/dev/amundsen/frontend/amundsen_application/static/node_modules/@babel/runtime-corejs2/helpers/esm'
Did you mean 'keys.js'?
BREAKING CHANGE: The request '../../core-js/object/keys' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
```


I wonder if there's anything in our normal build configuration that could be simplified/removed, which would then make this easier?
