### ISSUE TITLE
Build setup.py frontendamundsen

### ISSUE THREAD

**Issue by telmofranciscmultivision** [amundsen-io/amundsen#985]
Hi,

I'm trying to create amundsen integration with superset but when starting to build setup.py (https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/examples/superset_preview_client.md)

But i have this error at the end of the script:

`Downloading https://files.pythonhosted.org/packages/00/be/c3769a5d6a179c42eba04186dc7efeb165edf92f7b1582ccfe81cb17d7f9/typed-ast-1.2.0.tar.gz#sha256=b4726339a4c180a8b6ad9d8b50d2b6dc247e1b79b38fe2290549c98e82e4fd15
Best match: typed-ast 1.2.0
Processing typed-ast-1.2.0.tar.gz
Writing /tmp/easy_install-_kupxu1a/typed-ast-1.2.0/setup.cfg
Running typed-ast-1.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_kupxu1a/typed-ast-1.2.0/egg-dist-tmp-1n8dvw2n
ast27/Parser/acceler.c:13:10: fatal error: pgenheaders.h: No such file or directory
   13 | #include "pgenheaders.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by telmofranciscmultivision** [comment]
some more info:

`xhr.js:177 POST http://localhost:5000/api/preview/v0/ 500 (INTERNAL SERVER ERROR)'
`

**Comment by dorianj** [comment]
What version of Python are you using. IIRC, using too new a version can cause this compile error. The other error looks unrelated

**Comment by telmofranciscmultivision** [comment]
Hi,
Python version is 3.0.
Now I'm getting  this error building setup.py:

![image](https://user-images.githubusercontent.com/80980005/113735951-9f13e580-96f4-11eb-95c8-641c99158fbb.png)

**Comment by dorianj** [comment]
try 3.8

**Comment by telmofranciscmultivision** [comment]
I've tried with Python 3.8.5, and with the same error

**Comment by telmofranciscmultivision** [comment]
I think that is because python3 cannot install typed_ast 1.2.0 (that is requesit for mypy 0.660 - that is requesit for amundsen 3.6) :S How do i solve this?

**Comment by telmofranciscmultivision** [comment]
Installed python 3.7, it worked !
