### ISSUE TITLE
Cannot integrate with superset 

### ISSUE THREAD

**Issue by telmofranciscmultivision** [amundsen-io/amundsen#986]
I've followed all steps on this tutorial:
https://www.amundsen.io/amundsen/tutorials/data-preview-with-superset/

But I cannot preview data:
Request:
`{database: "mysql", schema: "movies_db", tableName: "persons", cluster: "def"}`

Response:
{"msg":"Encountered error: Preview client request failed with code HTTPStatus.INTERNAL_SERVER_ERROR","previewData":{"error_text":""}}

**Comment by MarcoFranchin96** [comment]
I would like to ask you a question because I can't either configure the preview.

Have you modified something in the file "examples.example_superset_preview_client"?
After I run python3 setup.py with che cahnges in the entry point, and restart the frontend docker, nothing change in the datacatalog.

**Comment by telmofranciscmultivision** [comment]
Hmm, I cant remember very well, but try to use python3.7, and after every change on preview, you need to run setup.py for amundsen frontend.
