### ISSUE TITLE
Support for authentication using Google IAP

### ISSUE THREAD

**Issue by crooy** [amundsen-io/amundsen#999]
# Authentication support for IAP on GKE

Google IAP is an authentication proxy, which can be deployed easily in front of any K8s service. It passes a JWT to the proxied service, so it should be possible to have Flask use this to authenticate. 

## Context

I am using your helm chart to deploy Amundsen, but 
now i get the error `"msg":"Encountered exception: AUTH_USER_METHOD is not configured"}`.
Now this is where the docs become a bit vague IMHO, but I figure i need to add some authentication logic. 

Our infrastructure runs on Google Cloud, where we have this great feature to get [IAP](https://cloud.google.com/iap/docs/signed-headers-howto)  with a couple lines of yaml on our service +ingress. 

## Howto
I am capable of finishing any code, but i havent used Flask yet so any help you can give me to get started is welcome!

I gather from this [Q&A thread](https://stackoverflow.com/questions/61449100/how-get-jwt-token-from-iap-in-flask#61568854) it shouldnt be hard to get working.

**Comment by crooy** [comment]
Also this project might have what is needed in this PR: https://github.com/google/timesketch/commit/c9b514c5cb593f65567beeb349ea72efc03e4eb6

**Comment by apalmercari** [comment]
it's really good to heave feature
